### ISSUE TITLE
make: *** [Makefile:136: all] Error 2

### ISSUE THREAD

**Issue by nekobi** [darlinghq/darling#1004]
Hi ! dear Administrators of the darling project , I'm sorry if bothering you , I got some problem while trying to build the instructions , and I don't know how to fix it , I notice that in the README.md says the default prefix location won't work if you have an encrypted home directory , I am new in here and I actual did encrypt my disk , I do full encryption of my disk not only home directory but I'm not sure if I do encrypted the home directory also , what should I do , could there's some way to fix the problem , thanks for your notice.
**Build Log**
```
File 'src/libsystem/libSystem.B.dylib' was considered already.
   Finished prerequisites of target file 'src/external/libressl-2.5.5/libcrypto.41.dylib'.
  Must remake target 'src/external/libressl-2.5.5/libcrypto.41.dylib'.
Need a job token; we don't have children
Putting child 0x55c220d80f40 (src/external/libressl-2.5.5/libcrypto.41.dylib) PID 27298 on the chain.
  Recipe of 'src/external/libressl-2.5.5/libcrypto.41.dylib' is being run.
 Finished prerequisites of target file 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build'.
The prerequisites of 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build' are being made.
Live child 0x55c220d80f40 (src/external/libressl-2.5.5/libcrypto.41.dylib) PID 27298 
[ 46%] Linking C shared library libcrypto.41.dylib
Reaping winning child 0x55c220d80f40 PID 27298 
Live child 0x55c220d80f40 (src/external/libressl-2.5.5/libcrypto.41.dylib) PID 27299 
Reaping winning child 0x55c220d80f40 PID 27299 
Removing child 0x55c220d80f40 PID 27299 from chain.
Considering target file 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build'.
 File 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build' does not exist.
  Considering target file 'src/external/libressl-2.5.5/libcrypto.41.dylib'.
  File 'src/external/libressl-2.5.5/libcrypto.41.dylib' was considered already.
 Finished prerequisites of target file 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build'.
Must remake target 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build'.
Successfully remade target file 'src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/build'.
Reaping winning child 0x560cc683f180 PID 10914 
Live child 0x560cc683f180 (src/external/libressl-2.5.5/CMakeFiles/crypto41.dir/all) PID 27320 
[ 46%] Built target crypto41
Reaping winning child 0x560cc683f180 PID 27320 
Removing child 0x560cc683f180 PID 27320 from chain.
Reaping losing child 0x55734d692700 PID 1977 
make: *** [Makefile:136: all] Error 2
Removing child 0x55734d692700 PID 1977 from chain.

```

**System Information**
Arch Linux x86_64
5.11.16-artix1-1 
CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.100GHz
GPU: AMD ATI 03:00.0 Lucienne
What system are you building with?
Linux
| Software | Version |
5.11.16-artix1-1
| Clang | 12.0.1 |
| CMake | 3.21.1 |
| Linux Kernel | 5.11.6 |
| Darling | Git Commit Hash |

**Comment by HinTak** [comment]
Building on an external usb drive, and setting DPREFIX to some other place that ~/.darling that is not encrypted should be fine. Note however #848 !

Disclaimer: just another user (and not a happy one).

**Comment by nekobi** [comment]
When I tried a second round I got these messages
```
ld: warning: ignoring file CMakeFiles/crypto42_64.dir/crypto/asn1/a_time_tm.c.o, building for macOS-i386 but attempting to link with file built for macOS-x86_64

```

**Comment by nekobi** [comment]
Hi everyone , I'm now sure that I do a full disk encryption but I didn't encrypt my home directory , does that also effect the darling install process , and how can I fix those error messages , thanks for the reply

**Comment by nekobi** [comment]
![Screenshot from 2021-08-03 23-39-29](https://user-images.githubusercontent.com/88288367/128044772-f4d37fd4-dbd0-4a51-9005-c24a766ab5b0.png)

**Comment by LubosD** [comment]
You need to find the first error message, not the last one. Disregard any warnings.

**Comment by nekobi** [comment]
![Screenshot from 2021-08-03 23-44-13](https://user-images.githubusercontent.com/88288367/128045550-fd355023-3633-40ed-9907-a15f496a7231.png)

**Comment by nekobi** [comment]
[CMakeError.log](https://github.com/darlinghq/darling/files/6925603/CMakeError.log)
[CMakeOutput.log](https://github.com/darlinghq/darling/files/6925615/CMakeOutput.log)

**Comment by nekobi** [comment]
> You need to find the first error message, not the last one. Disregard any warnings.

Hi !

I'm sorry about that I forgot to tell something may cause errors is that I using bedrock Linux , the error log seems says that clang version did not match and the required version was 12.0.1 , and the reason I using bedrock Linux is because I install gnome shell before I trying to install darling dependencies so I got the error is that gcc and sysprof are in conflict , so I using bedrock Linux to install another arch Linux to provides the darling dependencies , em .. so . in this case , what should I do , how can I solve this problem with the operating system I using right now , should I try to edit the MakeFile , but the biggest problem with editing MakeFile is that there are 23346 lines codes and I don't know which part should I edit , I want to install darling shell because I want to use xcode on my Linux machine , as always thanks for the notice

**Comment by HinTak** [comment]
FWIW, if you just want the capability for building mac os x software on Linux, https://github.com/tpoechtrager/osxcross would be a lot easier and quicker to use.

**Comment by rdrpenguin04** [comment]
The original issue here has been solved; if anyone has additional problems, separate issues should be opened. Could OP or a maintainer close this please?
