### ISSUE TITLE
Some questions about it

### ISSUE THREAD

**Issue by Stevemoretz** [darlinghq/darling#1008]
Currently I'm using a hackintosh in the next 5 years probably apple stops supporting intel macs, which probably kills hackintoshing, would you suppose by then we can get a basic iOS simulator running on linux by this tool?
It could be really useful that's the only reason I'm using mac os.

**Comment by rdrpenguin04** [comment]
If you'll be able to run it on Darling, you'll be able to run it (probably better) on a Hackintosh, at least for the forseeable future. Darling targeting ARM has been brought up more than a few times; you can see more about it on the Discord.

**Comment by Stevemoretz** [comment]
> If you'll be able to run it on Darling, you'll be able to run it (probably better) on a Hackintosh, at least for the forseeable future. Darling targeting ARM has been brought up more than a few times; you can see more about it on the Discord.

I didn't quite get what you meant, you mean it's even less likely to happen than having a Hackintosh which works on arm?

**Comment by SomeDevHere** [comment]
Darling itself does not translate x86 to arm. Instead it would require the system to be arm. There

**Comment by Stevemoretz** [comment]
Thanks for the info.
