### ISSUE TITLE
Failed build: ../src/external/objc4/runtime/objc-runtime.mm:124:2: error: mismatch in debug-ness macros

### ISSUE THREAD

**Issue by JCWasmx86** [darlinghq/darling#1017]
**Build Log**
What is the build error? - `../src/external/objc4/runtime/objc-runtime.mm:124:2: error: mismatch in debug-ness macros`
```
See file
[build.log](https://github.com/darlinghq/darling/files/7046512/build.log)

```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | Fedora 12.0.1-1.fc34  |
| CMake | 3.20.5 |
| Linux Kernel | 5.13.9-200.fc34.x86_64 |
| Darling | 9393db2c6ed530acaa2a4a933c391f1363fea1e8 |

cmake commands:

```
cmake -DCMAKE_BUILD_TYPE=Release -DFULL_BUILD=ON -DADDITIONAL_PACKAGES=ON -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/darling ..
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFULL_BUILD=ON -DADDITIONAL_PACKAGES=ON -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/darling ..
```
Both fail with the same error. It doesn't matter, whether I use ninja or make

**Comment by LubosD** [comment]
Then don't pass `CMAKE_BUILD_TYPE=Release` to the build...

**Comment by JCWasmx86** [comment]
Removing CMAKE_BUILD_TYPE solved it

**Comment by TheBrokenRail** [comment]
IMO Darling should be able to build in `Release` mode for any potential size or performance benefits.

**Comment by LubosD** [comment]
> IMO Darling should be able to build in `Release` mode for any potential size or performance benefits.

It's quite problematic, we'd have to implement various CFLAGS filters in different packages. We know that certain optimizations cause linker errors in libc and weird crashes in objc :-(
