### ISSUE TITLE
Uninstall darling-mach

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1021]
Uninstalling kernel modules is not covered by [Build instructions](https://docs.darlinghq.org/build-instructions.html). What's the proper way to do it? Also a request to improve documentation.

**Comment by bugaevc** [comment]
I suppose we could add a `lkm_uninstall` target to just `rm` all the instances of `darling-mach.ko`?

**Comment by bugaevc** [comment]
No, loading the module before installing is definitely not required, unloading it before deleting the module file should not be required either. It's not different from any other module in this regard.

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
