### ISSUE TITLE
sudo make lkm_install SSL error

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1024]
Latest git source code, OS Ubuntu 21.04:
````
ubuntu@ubuntu:/darling/build$ sudo make lkm_install
Scanning dependencies of target lkm_install
Installing the Linux kernel module
make[4]: Entering directory '/darling/src/external/lkm'
Running kernel version is 5.11.0-31-generic
make -C /lib/modules/5.11.0-31-generic/build M=/darling/src/external/lkm modules_install
make[5]: Entering directory '/usr/src/linux-headers-5.11.0-31-generic'
  INSTALL /darling/src/external/lkm/darling-mach.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.11.0-31-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[5]: Leaving directory '/usr/src/linux-headers-5.11.0-31-generic'
make[4]: Leaving directory '/darling/src/external/lkm'
Built target lkm_install
````
What does that mean? How do I fix this?

**Comment by HinTak** [comment]
Read the "Secure Boot" section of the build-instruction, especially regarding "generate a key and self-sign the kernel module".

**Comment by superbonaci** [comment]
I'm using a virtual machine as you recommended, so no idea if it will work.

**Comment by HinTak** [comment]
Not me recommending, just another user. Regardless of vm or not, Ubuntu kernels and kernel modules are signed by ubuntu folks, so you need to match them if you use a ubuntu kernel...

**Comment by superbonaci** [comment]
But should this work anyway, or must I sign it?

**Comment by HinTak** [comment]
"make module_install" obeys whatever your kernel's configuration does. So if Ubuntu's kernel modules are all signed, it tries to get you to match it and sign too.

If you don't actually use secure boot, or you disable secure boot, or you run inside a VM where secure boot is irrelevant, you can manually install any kernel modules by copying them by hands into /lib/modules/<kernel-version>/extra/ (or /update/) , runs "depmod -a" to get the kernel to rescan those directories, and just reboot.

"make module_install" is equivalent to optionally signing (depending on kernel build config), copying, then depmod. If you are sure you don't need signing for any of the reasons stated above, you can by-pass that step.

You can run "make -n ..." to get "make ..." to tell you what it is supposed to do, without actually doing it. You manually skip the steps which you don't like, or steps which don't apply to you, one by one.

**Comment by superbonaci** [comment]
Built kernel module and installed with:
````
sudo cp ./darling/src/external/lkm/darling-mach.ko /lib/modules/5.11.0-31-generic/extra/
sudo modprobe darling-mach
````
for some reason the module was already there but loaded...
