### ISSUE TITLE
EFI variables are not supported on this system

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1025]
Following build instruction to build for Ubuntu which is inside a vm:
````
sudo mokutil --import MOK.der
EFI variables are not supported on this system
````

**Comment by wjk** [comment]
If you’re using a VM, then Secure Boot is almost certainly disabled. Are you seeing an error when loading darling_mach.so? These instructions are only required when Secure Boot is blocking the darling_mach kernel module from loading.

**Comment by superbonaci** [comment]
Yes I'm using a vm and following the steps to sign the module (Build Instructions/Secure Boot). I can generate key but not enroll it. The module loads fine anyway.

**Comment by superbonaci** [comment]
The point is, is this supposed to happen on a vm without Secure Boot, or mokutil should work anyway and there's something wrong with my system?

**Comment by wjk** [comment]
If you are not using Secure Boot, then manipulation of the relevant EFI variables is expected to fail. Again, if the module loads fine, there is no need to generate or enroll any keys.

**Comment by superbonaci** [comment]
Thanks.
