### ISSUE TITLE
uname kernel version

### ISSUE THREAD

**Issue by neon12345** [darlinghq/darling#103]
The kernel version is derived from the real kernel. This is not expected by programs that try to extract the current Mac OS X version.

Darwin version to OS X release:
15.x.x  OS X 10.11.x El Capitan
14.x.x  OS X 10.10.x Yosemite
13.x.x  OS X 10.9.x Mavericks
12.x.x  OS X 10.8.x Mountain Lion
11.x.x  OS X 10.7.x Lion
10.x.x  OS X 10.6.x Snow Leopard
 9.x.x  OS X 10.5.x Leopard
 8.x.x  OS X 10.4.x Tiger
 7.x.x  OS X 10.3.x Panther
 6.x.x  OS X 10.2.x Jaguar
 5.x    OS X 10.1.x Puma

There is also another tool for this:
sw_vers 
ERROR @MachOObject.cpp:772 in void *Darling::MachOObject::performBind(MachO::Bind *):Creating a fake implementation for _kCFSystemVersionBuildVersionKey
ERROR @MachOObject.cpp:772 in void *Darling::MachOObject::performBind(MachO::Bind *):Creating a fake implementation for _kCFSystemVersionProductNameKey
ERROR @MachOObject.cpp:772 in void *Darling::MachOObject::performBind(MachO::Bind *):Creating a fake implementation for _kCFSystemVersionProductVersionKey

**Comment by LubosD** [comment]
Acknowledged. I will for sure correct the uname case (there is already /etc/darling/version.conf to be used for this purpose).

If the .plist loading code in gnustep-corebase is good enough, I'll finally implement the functions relevant to sw_vers in src/CFF/CFUtilities.c.

**Comment by LubosD** [comment]
sw_vers now works (libsystem branch):

````
 $ ~/Projects/darling-root/bin/dyld /tmp/sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.8
BuildVersion:   Darling
````
