### ISSUE TITLE
Package 'libavresample-dev' has no installation candidate

### ISSUE THREAD

**Issue by machinexa2** [darlinghq/darling#1038]
[ 43%] Linking C shared library libavcodec.dylib
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
ld: warning: static initializer found in 'CMakeFiles/avcodec.dir/avcodec.c.o'. Use -no_inits to
make this an error.  Use -no_warn_inits to suppress warning
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
ld: warning: static initializer found in 'CMakeFiles/avcodec.dir/avcodec.c.o'. Use -no_inits to
make this an error.  Use -no_warn_inits to suppress warning
[ 43%] Built target avcodec
[ 43%] Generating avresample.c
Cannot load libavresample.so: libavresample.so: cannot open shared object file: No such file or
directory
make[2]: *** [src/CoreAudio/CMakeFiles/avresample.dir/build.make:81: src/CoreAudio/avresample.c] Error 1
make[2]: *** Deleting file 'src/CoreAudio/avresample.c'
make[1]: *** [CMakeFiles/Makefile2:25515: src/CoreAudio/CMakeFiles/avresample.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

Can I make darling compilable without this library as I cant install it. 
root@kali-linux:~# uname -a
Linux kali-linux 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux
I am using almost latest version of darling

**Comment by machinexa2** [comment]
root@kali-linux:~# sudo apt install cmake bison flex xz-utils libfuse-dev libudev-dev pkg-config
mesa-dev libtiff5-dev libfreetype6-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-de
e-dev libdbus-1-dev libxkbfile-dev libssl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libavresample-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libavresample-dev' has no installation candidate

**Comment by machinexa2** [comment]
Is it possible that you guys update the code so that some newer library replace this libavreplace library

**Comment by machinexa2** [comment]
Or is it possible to provide a flag/change make file to not compile audio? Please Help :pray:

**Comment by machinexa2** [comment]
Raised https://bugs.kali.org/view.php?id=7335 for now

**Comment by machinexa2** [comment]
```
This package is no longer present in testing. It' still present as cruft in unstable but it will disappear soon.

See the Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971318 that planned its removal. That package has been deprecated in favor of libswresample-dev. 
```

**Comment by machinexa2** [comment]
So, update code to use libswresample-dev instead of libavresample-dev

**Comment by ontologiae** [comment]
I have the same problem

**Comment by AldairSoraka** [comment]
i have the files

**Comment by ontologiae** [comment]
> i have the package for arch https://builds.garudalinux.org/repos/chaotic-aur/x86_64/libavresample-4.3.1-1-x86_64.pkg.tar.zst use tar xf on the file, and make sure to put the files in their folders and give them permissions. WARNING: DO NOT COPY THIS ON "/"COULD OVERWRITE EVERYTHING

Thanks a lot, I carefully copy the file into /usr/lib and /usr/include
It pass the compiling spot with libavresample !

**Comment by superbonaci** [comment]
@ontologiae did you already end up the compiling? How did it go?

**Comment by ontologiae** [comment]
@superbonaci Yes, 20mn after it ends up.
I tried some hacks to make iTerm2 and Macvims working, especially copy the /System/Library of my mac bit it didn't worked 😉

**Comment by superbonaci** [comment]
@ontologiae could you share a bash script to extract the zst file and get libavresample ready? I don't know how to operate with it.

**Comment by ontologiae** [comment]
@superbonaci In my .bashhistory I have : 
wget https://builds.garudalinux.org/repos/chaotic-aur/x86_64/libavresample-4.3.1-1-x86_64.pkg.tar.zst
zstd -d libavresample-4.3.1-1-x86_64.pkg.tar.zst
tar xvf libavresample-4.3.1-1-x86_64.pkg.tar
sudo cp -rv usr/lib/* /usr/lib/
sudo cp -rv usr/include/libavresample /usr/include/

**Comment by superbonaci** [comment]
> 
> 
> @superbonaci In my .bashhistory I have :
> 
> ```
> wget https://builds.garudalinux.org/repos/chaotic-aur/x86_64/libavresample-4.3.1-1-x86_64.pkg.tar.zst
> zstd -d libavresample-4.3.1-1-x86_64.pkg.tar.zst
> tar xvf libavresample-4.3.1-1-x86_64.pkg.tar
> sudo cp -rv usr/lib/* /usr/lib/
> sudo cp -rv usr/include/libavresample /usr/include/
> ```

Fantastic, that's what I was looking for. Working now.

**Comment by facekapow** [comment]
This should now be fixed as we have switch to libswresample; see my comment [here](https://github.com/darlinghq/darling/issues/1075#issuecomment-1021200152).
