### ISSUE TITLE
Add libedit

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#104]
Add Apple libedit to build (needed for swift compiler).

**Comment by neon12345** [comment]
you can also add libcache along with a lot of others ^^

**Comment by LubosD** [comment]
It appears that libcache is not open source, so it will nees to be reimplemented. Where is it used?

**Comment by neon12345** [comment]
Probably in the native libedit so not a real problem. I wonder if it shouldn't be possible to load the native libs.

**Comment by LubosD** [comment]
It is possible for sure... but copying libs from OS X is not the way I want to go. At least not officially.
