### ISSUE TITLE
/Applications folder missing

### ISSUE THREAD

**Issue by superbonaci** [darlinghq/darling#1043]
`/Applications` folder doesn't exist after fresh darling install.

**Comment by bugaevc** [comment]
It does — are you sure? What are the symptoms?

**Comment by superbonaci** [comment]
What is — ? The symptoms are I wanted to extract Xcode.app to /Applications but such folder didn't exist, had to create it.

**Comment by TheAwesome98-Real** [comment]
are you in `/` (in darling) or `~/.darling` (on linux)?

**Comment by superbonaci** [comment]
Seems like it's fixed. I delere current `~/.darling` folder, then run `darling shell` and it's populated, so the issue is not happening anymore.
