### ISSUE TITLE
Homebrew not displaying any output

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [darlinghq/darling#1045]
**Expected Result**
What did you expect to happen?
homebrew to print something with brew -v
**Actual Result**
What did happen?
it just did nothing

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?
install xcode command line tools and then install homebrew and run brew -v
| Linux Kernel | 5.14 |
output:
`Darling [/Volumes/SystemRoot/home/etaash]$ brew -v
Darling [/Volumes/SystemRoot/home/etaash]$`

**Comment by facekapow** [comment]
This should be fixed in the latest commit to master.

**Comment by Etaash-mathamsetty** [comment]
> This should be fixed in the latest commit to master.

the latest commit dosen't compile lol
