### ISSUE TITLE
`brew install dotnet` crashes.

### ISSUE THREAD

**Issue by trungnt2910** [darlinghq/darling#1052]
**Expected Result**
Brew should fetch and install the dotnet core sdk.

**Actual Result**
Brew crashed without logging anything.

**Steps To Reproduce**
Install homebrew, with the workaround mentioned in #1006, with `Command line tools for Xcode 12`.
Run `brew install dotnet` and then run `echo $?`. The shell should print 141.
Run `brew --version` and then run `echo $?`. The shell should also print 141.

**System Information**
Ubuntu 20.04.3 LTS (GNU/Linux 5.10.60.1-microsoft-standard-WSL2+ x86_64)

| Software | Version |
| Ubuntu | 20.04. |
| Linux Kernel | 5.10.60.1-microsoft-standard-WSL2+ |
| Darling | master @ 9393db2c6 |

**Comment by trungnt2910** [comment]
This is due to an error in Darling's `bash`:
Brew runs some commands that uses process substitution, something that looks like:
```
cat <(echo foo)
```

**Comment by facekapow** [comment]
Using `git bisect`, I've identified 3761b3d7f1148e1a12cf41ea291504d2bb0fe6bb as the commit that introduced the bug. I'll work on a fix later today.
