### ISSUE TITLE
"sudo" in Darling does not actually give root when genuinely needed

### ISSUE THREAD

**Issue by Wind-Explorer** [darlinghq/darling#1073]
**Expected Result**
What did you expect to happen?
Installing packages or executing install scripts (like Midnight Commander `mc` or Homebrew `brew` in "what to try" section under Darling Docs) copies content to root directory `/` with real root privileges and things works

**Actual Result**
What did happen?
command `sudo` is for show and the package fails to create a folder called `mc` under `/usr/local/etc/` due to insufficient permissions

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?
quite literally just follow what the instruction for installing mc.pkg says under "what to try" section

**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| Arch Linux  | x86_64 |
| Linux Kernel | 5.15.6 |
| Darling | Git Commit Hash |

**Disclaimer:** I know how under Darling Docs it says giving programs "fake" root privileges is a "f e a t u r e" but I just want to know how to actually give one "real" root privileges

**Comment by Etaash-mathamsetty** [comment]
try using su

**Comment by acheong08** [comment]
It depends on whether you are trying to access the emulated root or real root. If it's the latter, you can use `sudo darling shell` to run darling with root access to the real root.
