### ISSUE TITLE
make fails : no such file or directory libavrsample.so

### ISSUE THREAD

**Issue by giorgos-athanassopoulos** [darlinghq/darling#1075]
**Build Log**
```
Cannot load libavresample.so: libavresample.so: cannot open shared object file: No such file or directory
make[2]: *** [src/CoreAudio/CMakeFiles/avresample.dir/build.make:74: src/CoreAudio/avresample.c] Error 1
make[2]: *** Deleting file 'src/CoreAudio/avresample.c'
make[1]: *** [CMakeFiles/Makefile2:23234: src/CoreAudio/CMakeFiles/avresample.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**System Information**
| Software | Version |
| --- | --- |
| Clang | 13.0.0 |
| CMake | 3.22.1 |
| Linux Kernel | 5.10.84-1-lts |
| Darling | Git Commit Hash |
```
This is what i did:
$ git clone darling_repo.git
$ cd darling
$ mkdir build
$ cd build
$ cmake
$ make
**This is where the error pops out from(make)**
Please tell me to include any further information for debugging, as im new to github issues, thnx for the help in advance :)
```

**Comment by augustobmoura** [comment]
Same error

**Comment by augustobmoura** [comment]
Having the same issue, this error breaks parallel compilation

**Comment by augustobmoura** [comment]
Ok, my problem is that I didn't installed `libavresample`, I use manjaro so I just copied and pasted the pacman command on the docs and missed the note about `libavresample`.

Because `libavresample` is only available on AUR and not on the manjaro repos, I actually needed to also run `pamac build libavresample`

**Comment by facekapow** [comment]
This should be fixed in the latest commit; we now use libswresample (which is present in most distro's software repos) instead of libavresample. If you want to update an existing clone, make sure to follow https://docs.darlinghq.org/build-instructions.html#updating-sources.
