### ISSUE TITLE
Copy paste bug(same if/else if) in SCNetworkInterface.c

### ISSUE THREAD

**Issue by qarmin** [darlinghq/darling#1081]
https://github.com/darlinghq/darling/blob/1c3749bf8ae40fd2de217e7f2d9e20bf20e0815c/src/configd/SystemConfiguration.fproj/SCNetworkInterface.c#L1125-L1131

**Comment by LubosD** [comment]
Yes, but we don't fix bugs in Apple's upstream sources.
