### ISSUE TITLE
LKM build failed. duct_kern_task.c:266:53 

### ISSUE THREAD

**Issue by Xinmudotmoe** [darlinghq/darling#1084]
**Build Log**
What is the build error?
```
/usr/src/darling/src/external/lkm/osfmk/duct/duct_kern_task.c:266:53: error: 'struct task_struct' has no member named 'se'
  266 |                         times->sum_exec_runtime += t->se.sum_exec_runtime;
      |                                                     ^~

```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 13.0.0 |
| gcc | 11.2.0 |
| CMake | 3.21.4 |
| Linux Kernel | 5.15.13 |
| Darling | 97fc8eeaa45cfb6d67c45d59a4fa1520c9add50e |

I found a similar function in linux-kernel. I compared the different parts.

```c
// in kernel-5.15.13/kernel/sched/cputime.c:327
void thread_group_cputime(struct task_struct *tsk, struct task_cputime *times)
{
//...
			times->sum_exec_runtime += read_sum_exec_runtime(t);
//...
}
// in kernel-5.15.13/kernel/sched/cputime.c:270
#ifdef CONFIG_64BIT
static inline u64 read_sum_exec_runtime(struct task_struct *t)
{
	return tsk_seruntime(t);
}
#else
// ...
#endif
```

Change to the following code to build successfully under this version. I think this may not apply to other versions of the kernel.

```patch
Index: osfmk/duct/duct_kern_task.c
@@ -263,7 +263,7 @@
                         stime = t->stime;
                         times->utime += utime;
                         times->stime += stime;
-                        times->sum_exec_runtime += t->se.sum_exec_runtime;
+                        times->sum_exec_runtime += tsk_seruntime(t);
                 }
                 /* If lockless access failed, take the lock. */
                 nextseq = 1;

```

**Comment by facekapow** [comment]
That function isn't present in the mainline kernel; are you using a different kernel, perhaps?

**Comment by Xinmudotmoe** [comment]
I think I found the reason, I turned on "**alternative CPU scheduler**". The build cannot be completed when **SCHED_ALT** is enabled.

 If other users also have this feature turned on, the build may not be successful as well.

**Comment by Etaash-mathamsetty** [comment]
> I think I found the reason, I turned on "**alternative CPU scheduler**". The build cannot be completed when **SCHED_ALT** is enabled.
> 
> If other users also have this feature turned on, the build may not be successful as well.

this is true, I had a similar issue using the liquorix kernel

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
