### ISSUE TITLE
Unable to compile LKM on Linux 5.15/5.16 

### ISSUE THREAD

**Issue by Doregon** [darlinghq/darling#1089]
**Expected Result**
Compiling works fine

**Actual Result**
Fails with `fatal error: stdatomic.h: No such file or directory`. headers are installed so, removed? Changing things to use a local copy results in build failing with `error: ‘struct mm_struct’ has no member named ‘core_state’`

**Steps To Reproduce**
1. Attempt to build the latest commit on 5.15/5.16.

**``dmesg`` Output**
N/A

**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| OS | Manjaro Linux 21.2.1 Qonos |
| Linux Kernel | 5.15.12-1 or 5.16rc6.211220.ga7904a5-1 |
| Darling | 97fc8ee |

**Comment by acheong08** [comment]
Same issue here
`uname -a`
`Linux Insignificant 5.16.2-t2 #1 SMP PREEMPT Fri Jan 21 05:07:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
result:
`fatal error: stdatomic.h: No such file or directory`

**Comment by acheong08** [comment]
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdatomic.h exists

**Comment by facekapow** [comment]
This should be fixed with the latest commit; if you want to update an existing clone, make sure to follow https://docs.darlinghq.org/build-instructions.html#updating-sources to update the LKM submodule.

Please re-open if the issue persists.

**Comment by arifer612** [comment]
I can verify that LKM compiles on e3bbaa11e84d99e461e1665327b5f63d59538351 for 5.16.2-zen kernel. No problems so far after rebooting into my system!

**Comment by acheong08** [comment]
Hello. That specific issue of stdatomic.h missing has been fixed. However, another error happens when compiling `make lkm`.

```
./include/uapi/linux/fcntl.h:99: note: this is the location of the previous definition
   99 | #define AT_EACCESS  0x200 /* Test access permitted for
      | 
cc1: some warnings being treated as errors
```
