### ISSUE TITLE
Will Apple's built in apps become supported? (iMessage, Safari, etc)

### ISSUE THREAD

**Issue by acheong08** [darlinghq/darling#1095]
**Library**
`/System/Library/Frameworks/BusinessChat.framework/Versions/A/BusinessChat`
Couldn't find information about whether it is open source online though there seems to be some python implementations of it.

**Test Application**
Apple's `Messages.app` airdropped from an Apple computer.
**Steps To Reproduce**
1. `darling shell ./Messages.app/Content/MacOS/Messages`

**System Information**
OS: Ubuntu 20.04.3 LTS x86_64 
Host: MacBookPro15,2 1.0 
Kernel: 5.16.2-t2 
CPU: Intel i5-8279U (8) @ 4.100GHz 
GPU: Intel Iris Plus Graphics 655 
Memory: 2619MiB / 7801MiB 

| Software | Version |
| --- | --- |
| Darling | 597325bc702e7b0893ade8272000a4086b23f121 |

**Comment by facekapow** [comment]
I won't say it's impossible, but it is certainly more unlikely than most other apps. Apple's own apps frequently depend on internal APIs and frameworks, sometimes even the hardware (as is the case of iMessage). It might be possible, but Darling is a long ways away from being able to run them.
