### ISSUE TITLE
Skype for Mac

### ISSUE THREAD

**Issue by Hanterdeep** [darlinghq/darling#110]
When I try to start Skype for Mac I get 
"dyld: Cannot execute binary file: dyld: Library not loaded: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth".

**Comment by LubosD** [comment]
No chance of Skype running any time soon.

**Comment by Hanterdeep** [comment]
Ok... So still no alternative for Skype for Linux...

**Comment by msva** [comment]
@Hanterdeep depends on what do you want about it.

**Comment by Hanterdeep** [comment]
Videoconference
