### ISSUE TITLE
System seems to kernel panic about a minute after running a Darling program

### ISSUE THREAD

**Issue by TheAwesome98-Real** [darlinghq/darling#1102]
**Expected Result**
What did you expect to happen?

Nothing to happen, and the system to continue fine

**Actual Result**
What did happen?

The kernel seems to panic. The OS never exits graphical, but X freezes and audio loops.

**Steps To Reproduce**
1. Open a Terminal window
2. run something like `darling shell`
3. do some things like `ls` or `echo`
4. `exit` the shell
5. do something, like use Firefox or Nautilus
6. watch the system crash

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
[nothing: i think this is because i have to shutdown and reboot. where can i find "old" dmesgs?]
```

**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| Distro | Ubuntu 20.04.3 LTS |
| Linux Kernel | 5.13.0-28-generic |
| Darling | 597325bc |

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.

**Comment by TheAwesome98-Real** [comment]
nice, going to upgrade now
