### ISSUE TITLE
Darling-DKMS has replaced normal DKMS.

### ISSUE THREAD

**Issue by Baby-Gaston** [darlinghq/darling#1106]
I tried to install Darling on Ubuntu 21.04, it failed, and got me stuck in Darling-DKMS, I have tried restarting and I am still stuck.
Any ideas?

**Comment by CuriousTommy** [comment]
Hello @Baby-Gaston, can you provided more details on what you tried to do to install Darling? Did you try to build from source or did you try to use a prebuilt version? What error message showed when you try to install Darling?

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
