### ISSUE TITLE
Xcode 13.2.1 requires AssertionServices.framework

### ISSUE THREAD

**Issue by zachwolfe** [darlinghq/darling#1107]
**Framework**
/System/Library/PrivateFrameworks/AssertionServices.framework

**Test Application**
Xcode 13.2.1, possibly earlier versions as well.

**Steps To Reproduce**
1. Extract Xcode_13.2.1.xip to /Applications/Xcode.app
2. Run `xcode-select --switch /Applications/Xcode.app`
3. Run `clang` or any other tool that relies on the IDEFoundation framework.
- Produces approximately the following output (I forgot to copy the actual output before adding stubs):
```
Error loading required libraries. If there is an ongoing installation please wait for it to complete. Otherwise reinstall. 
(dlopen(@rpath/libxcodebuildLoader.dylib, 1): Library not loaded: /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
  Reason: image not found)
```

**System Information**
WSL2, with my own build of Darling.

| Software | Version |
| --- | --- |
| Darling | 597325bc702e7b0893ade8272000a4086b23f121 |

As alluded to above, I have already generated stubs by following the docs, which fixed this issue (now I fail on #1007). Shall I open a PR?

**Comment by facekapow** [comment]
Absolutely; if you have stubs already generated, definitely go ahead and open a PR for them.

**Comment by slonopotamus** [comment]
So, is it fixed by https://github.com/darlinghq/darling/pull/1108?

**Comment by zachwolfe** [comment]
@slonopotamus IIRC yes, this specific issue should be fixed now. I would imagine Xcode still fails to launch for other reasons, though. But I haven’t tried Darling in a while.
