### ISSUE TITLE
Implement CoreAudio base framework

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#112]
And migrate existing AudioUnit implementation to use CA instead of ALSA/PA.

Example apps using CA directly:
- https://github.com/allenporter/thebends/tree/master/ycoreaudio
- https://chromium.googlesource.com/chromium/src/media/+/master/audio/mac/audio_manager_mac.cc

**Comment by bugaevc** [comment]
Both links return 404 for me.

**Comment by ahyattdev** [comment]
@LubosD @bugaevc links broken for me too.

**Comment by Vantrix-Bitm** [comment]
What's the status on this? I see there's some code and commented includes in `CMakeLists`. Is this something I can potentially fiddle around with to get compiling?

**Comment by squarebracket** [comment]
What's the status on this? I see there's some code in `src` and commented includes in `CMakeLists`. Is this something I can potentially fiddle around with and get compiling?

**Comment by LubosD** [comment]
There is some code, which is sufficient to run `mpg123`. But I need to adapt it to the new build (where we produce everything as Mach-O).

It has two problems:
* The internal API used in AudioUnit is not compatible with 3rd party plugins, which is a shame.
* Integration with ALSA/PA is done in an AudioUnit unit, but it should be done in CoreAudio instead. CA itself is not thoroughly documented, because it's a low-level API not intended for ordinary apps.

**Comment by johnothwolo** [comment]
Replacement for the first https://web.archive.org/web/20100830145959/http://thebends.googlecode.com/svn/trunk/ycoreaudio/sample.cpp

**Comment by LubosD** [comment]
Thanks, now I managed to find an even better link: https://github.com/allenporter/thebends/tree/master/ycoreaudio

**Comment by LubosD** [comment]
The most basic stuff is done, sufficient for `sox`.
