### ISSUE TITLE
Custom kernel not supported

### ISSUE THREAD

**Issue by acheong08** [darlinghq/darling#1159]
**Expected Result**
Build properly

**Actual Result**
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Steps To Reproduce**
1. Install deb package from releases

**System Information**
OS: Ubuntu 21.10 x86_64 
Host: MacBookPro15,2 1.0 
Kernel: 5.17.1-t2 
Uptime: 1 hour, 14 mins 
Packages: 3519 (dpkg), 41 (brew), 3 (flatpak), 15 (snap) 
Shell: zsh 5.8 
Resolution: 2560x1600 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: WhiteSur-dark 
Theme: WhiteSur-dark [GTK2/3] 
Icons: WhiteSur-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-8279U (8) @ 4.100GHz 
GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] 
Memory: 3379MiB / 7801MiB 

| Software | Version |
| --- | --- |
| Linux Kernel | 5.17.1-t2 |
| Darling | 597325bc702e7b0893ade8272000a4086b23f121 |

Custom kernel being used for hardware

**Comment by Etaash-mathamsetty** [comment]
> **Expected Result** Build properly
> 
> **Actual Result** E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
> **Steps To Reproduce**
> 
> 1. Install deb package from releases
> 
> **System Information** OS: Ubuntu 21.10 x86_64 Host: MacBookPro15,2 1.0 Kernel: 5.17.1-t2 Uptime: 1 hour, 14 mins Packages: 3519 (dpkg), 41 (brew), 3 (flatpak), 15 (snap) Shell: zsh 5.8 Resolution: 2560x1600 DE: GNOME 40.5 WM: Mutter WM Theme: WhiteSur-dark Theme: WhiteSur-dark [GTK2/3] Icons: WhiteSur-dark [GTK2/3] Terminal: gnome-terminal CPU: Intel i5-8279U (8) @ 4.100GHz GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] Memory: 3379MiB / 7801MiB
> 
> Software	Version
> Linux Kernel	5.17.1-t2
> Darling	[597325b](https://github.com/darlinghq/darling/commit/597325bc702e7b0893ade8272000a4086b23f121)
> Custom kernel being used for hardware

try compiling from source, it is failing building the lkm kernel module, by building from source, you could see where the issue is

**Comment by acheong08** [comment]
Building from source gives
`ERROR: modpost: "do_exit" [/tmp/darling/src/external/lkm/darling-mach.ko] undefined!`

**Comment by Etaash-mathamsetty** [comment]
> modpost: "do_exit"

could you give more of the log?

**Comment by acheong08** [comment]
```
Running kernel version is 5.17.1-t2
Invoked by kernel build system, building for 5.17.1-t2
  MODPOST /home/acheong/dependencies/darling/src/external/lkm/Module.symvers
ERROR: modpost: "do_exit" [/home/acheong/dependencies/darling/src/external/lkm/darling-mach.ko] undefined!
make[6]: *** [scripts/Makefile.modpost:134: /home/acheong/dependencies/darling/src/external/lkm/Module.symvers] Error 1
make[6]: *** Deleting file '/home/acheong/dependencies/darling/src/external/lkm/Module.symvers'
make[5]: *** [Makefile:1746: modules] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-5.17.1-t2'
make[4]: *** [Makefile:618: default] Error 2
make[4]: Leaving directory '/home/acheong/dependencies/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:77: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:61691: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:61698: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:20177: lkm] Error 2
```

**Comment by Etaash-mathamsetty** [comment]
> ```
> Running kernel version is 5.17.1-t2
> Invoked by kernel build system, building for 5.17.1-t2
>   MODPOST /home/acheong/dependencies/darling/src/external/lkm/Module.symvers
> ERROR: modpost: "do_exit" [/home/acheong/dependencies/darling/src/external/lkm/darling-mach.ko] undefined!
> make[6]: *** [scripts/Makefile.modpost:134: /home/acheong/dependencies/darling/src/external/lkm/Module.symvers] Error 1
> make[6]: *** Deleting file '/home/acheong/dependencies/darling/src/external/lkm/Module.symvers'
> make[5]: *** [Makefile:1746: modules] Error 2
> make[5]: Leaving directory '/usr/src/linux-headers-5.17.1-t2'
> make[4]: *** [Makefile:618: default] Error 2
> make[4]: Leaving directory '/home/acheong/dependencies/darling/src/external/lkm'
> make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:77: src/external/lkm/CMakeFiles/lkm] Error 2
> make[2]: *** [CMakeFiles/Makefile2:61691: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:61698: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
> make: *** [Makefile:20177: lkm] Error 2
> ```

these errors are really weird, just use the darlingserver branch for now. (lkm is gonna die anyway)

**Comment by LubosD** [comment]
Nothing weird here, newer kernels don't export do_exit() any more.

**Comment by Etaash-mathamsetty** [comment]
> Nothing weird here, newer kernels don't export do_exit() any more.

oh it's been a while since I have compiled darling lol

**Comment by acheong08** [comment]
> > ```
> > Running kernel version is 5.17.1-t2
> > Invoked by kernel build system, building for 5.17.1-t2
> >   MODPOST /home/acheong/dependencies/darling/src/external/lkm/Module.symvers
> > ERROR: modpost: "do_exit" [/home/acheong/dependencies/darling/src/external/lkm/darling-mach.ko] undefined!
> > make[6]: *** [scripts/Makefile.modpost:134: /home/acheong/dependencies/darling/src/external/lkm/Module.symvers] Error 1
> > make[6]: *** Deleting file '/home/acheong/dependencies/darling/src/external/lkm/Module.symvers'
> > make[5]: *** [Makefile:1746: modules] Error 2
> > make[5]: Leaving directory '/usr/src/linux-headers-5.17.1-t2'
> > make[4]: *** [Makefile:618: default] Error 2
> > make[4]: Leaving directory '/home/acheong/dependencies/darling/src/external/lkm'
> > make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:77: src/external/lkm/CMakeFiles/lkm] Error 2
> > make[2]: *** [CMakeFiles/Makefile2:61691: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
> > make[1]: *** [CMakeFiles/Makefile2:61698: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
> > make: *** [Makefile:20177: lkm] Error 2
> > ```
> 
> these errors are really weird, just use the darlingserver branch for now. (the kernel module is gonna die anyway)

How do I compile from darlingserver branch? I did `git checkout darlingserver` and followed the normal build instructions but it still relies on lkm.

**Comment by facekapow** [comment]
You also have to do `git submodule update --init --recursive`.

**Comment by acheong08** [comment]
I did do that. It appears that the darlingserver branch isn't functional yet.

**Comment by CuriousTommy** [comment]
It shouldn't though 

> I did do that. It appears that the darlingserver branch isn't functional yet.

It working fine for others. Are you trying to do a `make lkm`? You only need to do a `make` and `make install`

**Comment by Etaash-mathamsetty** [comment]
> I did do that. It appears that the darlingserver branch isn't functional yet.

just in case, run `make clean`, before starting to compile again

**Comment by acheong08** [comment]
```
[ 32%] Linking CXX static library libWTF.a
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(CrossThreadCopier.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(HashTable.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(PlatformRegisters.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(PtrTag.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(SizeLimits.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(StackStats.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(WTFAssertions.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(WebCoreThread.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(DeprecatedSymbolsUsedBySafari.mm.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: x86_64 file: libWTF.a(CollatorDefault.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(CrossThreadCopier.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(HashTable.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(PlatformRegisters.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(PtrTag.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(SizeLimits.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(StackStats.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(WTFAssertions.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(WebCoreThread.cpp.o) has no symbols
/home/acheong/dependencies/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib: for architecture: i386 file: libWTF.a(CollatorDefault.cpp.o) has no symbols
[ 32%] Built target WTF
make: *** [Makefile:136: all] Error 2
```

**Comment by CuriousTommy** [comment]
I don't see the error message... Are you building the project with multithreading? 

Trying continuing the build with single threading and post the full log in a txt file.

**Comment by acheong08** [comment]
Building with single thread gives:
```
[  0%] Linking CXX static library libdarlingserver_duct_tape.a
[  0%] Built target darlingserver_duct_tape
[  0%] Building CXX object src/external/darlingserver/CMakeFiles/darlingserver.dir/src/darlingserver.cpp.o
/home/acheong/dependencies/darling/src/external/darlingserver/src/darlingserver.cpp:40:10: fatal error: 'sys/capability.h' file not found
#include <sys/capability.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/external/darlingserver/CMakeFiles/darlingserver.dir/build.make:76: src/external/darlingserver/CMakeFiles/darlingserver.dir/src/darlingserver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:13810: src/external/darlingserver/CMakeFiles/darlingserver.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by facekapow** [comment]
Oh, right; you need to install `libcap-dev` for the darlingserver branch.

**Comment by acheong08** [comment]
Fixed thanks!
