### ISSUE TITLE
installer --pkg failure: Floating point exception: 8

### ISSUE THREAD

**Issue by acheong08** [darlinghq/darling#1167]
```
installer: Package name is Go
installer: Installing at base path /
installer: Installing selected choice Go
installer: Installing package org.golang.go version go1.18.1 (446098 KB)
Removing previous installation
installer: Extracting files
Fixing permissions
Floating point exception: 8 (core dumped)
```

**System Information**
OS: Ubuntu 22.04 LTS x86_64 
Host: MacBookPro15,2 1.0 
Kernel: 5.17.4-t2 
CPU: Intel i5-8279U (8) @ 4.100GHz 
GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] 
Memory: 3942MiB / 7801MiB

| Software | Version |
| --- | --- |
| Linux Kernel | 5.17.4-t2 |
| Darling | cef3a6a06 |
(Using darlingserver branch)

**Comment by Hareis** [comment]
yes, i have some problem
