### ISSUE TITLE
LKM install trouble

### ISSUE THREAD

**Issue by Skiexx** [darlinghq/darling#1170]
I want make file on ubuntu 20.04, but while make i get an error.

make log
[log.txt](https://github.com/darlinghq/darling/files/8643850/log.txt)

**Steps To Reproduce**
1. Clone git repo
2. make and setup darling
3. make kernel module

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
nothing
```

**System Information**
OS: Ubuntu 20.04.4 LTS x86_64
kernel: 5.13.0-40-generic
CPU: AMD Ryzen 5 PRO 4650G with Radeon Graphics (12) @ 3.700GHz  
GPU: AMD ATI 06:00.0 Renoir 

| Software | Version |
| --- | --- |
| Linux Kernel | 5.13.0-40-generic |
| Darling | [26e55e1](https://github.com/darlinghq/darling/commit/26e55e11175da4846511764e650062fb29f3e3f7) |

**Comment by ShadowOfPripyat** [comment]
I have exactly the same issue on same kernel and OS. I tried to build the Darling LKM but it says 
**`modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.13.0-40-generic`** 
`Failed to load the kernel module`

**Comment by LubosD** [comment]
> I have exactly the same issue on same kernel and OS. I tried to build the Darling LKM but it says **`modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.13.0-40-generic`** `Failed to load the kernel module` After trying a lot of times and following carefully the build instructions

Then you obviously didn't compile **and** install the LKM for your currently running kernel. I don't think there's any other possibility.

**Comment by ShadowOfPripyat** [comment]
Yes i'm that dumb that i can't even do it with a fukin *.deb package Lmao
Tell me what i have to do to don't get errors on compiling

**Comment by facekapow** [comment]
Closing as we no longer use a kernel module.
