### ISSUE TITLE
Unable to run PowerPC Applications

### ISSUE THREAD

**Issue by iamhumanipromise** [darlinghq/darling#1172]
Given GNUStep’s Cocoa compatibility, it seems like legacy PowerPC mac apps would be a great place to start “playing around”! 

However - it seems that PowerPC emulation is not built in. 

Is there a way to implement this? QEMU? Box86 but in reverse?

——

Additionally, on OpenPOWER devices and legacy PowerPC devices running Linux, having access to legacy Mac apps would be the other use case

**Comment by CuriousTommy** [comment]
There is already an opened about supporting PowerPC apps (https://github.com/darlinghq/darling/issues/252)

**Comment by CuriousTommy** [comment]
I'm going to close this issue. Feel free to comment on the other issue.
