### ISSUE TITLE
404 on darlinghq pages

### ISSUE THREAD

**Issue by stuaxo** [darlinghq/darling#118]
Happens on all pages on the top tabs

**Comment by LubosD** [comment]
Can you provide example of such a URL?

**Comment by stuaxo** [comment]
Sure:

https://www.darlinghq.org/introduction

https://www.darlinghq.org/project-status

https://www.darlinghq.org/source-code

https://www.darlinghq.org/faq

https://www.darlinghq.org/developer-zone

https://www.darlinghq.org/contact

Screenshot:

http://imgur.com/a/nPngm

**Comment by LubosD** [comment]
D'oh, HTTPS is broken :-) Thanks for the heads up!

**Comment by X0rg** [comment]
@stuaxo: try in HTTP. http://www.darlinghq.org ;)

**Comment by LubosD** [comment]
Fixed
