### ISSUE TITLE
LKM won't build against Fedora Kernel 5.18.5

### ISSUE THREAD

**Issue by thatsysadmin** [darlinghq/darling#1185]
**Expected Result**
`darling-mach` kernel module would build successfully.

**Actual Result**
Running `make lkm -j32` to build the ```darling-mach``` errors out with exit code 2.

**Steps To Reproduce**
1. Clone Darling Repo
2. ```mkdir build; cd build```
3. ```cmake .. -DTARGET_i386=OFF```
4. ```make -j32```
5. ```sudo make install```
6. ```make lkm -j32```
7. Observe error.

**Output of ``make lkm``
[output_redacted.txt](https://github.com/darlinghq/darling/files/8932747/output_redacted.txt)

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
(Outputs nothing with an exit code of 1)

**System Information**
What system are you using?
Fedora Linux 36 with Kernel 5.18.5 updated as of June 17
Intel Xeon E5-2640v3

| Software | Version |
| --- | --- |
| Linux Kernel | 5.18.5 |
| Darling | 26e55e11175da4846511764e650062fb29f3e3f7 |

**Comment by Etaash-mathamsetty** [comment]
use the darlingserver branch

**Comment by thatsysadmin** [comment]
@Etaash-mathamsetty 
Will try when I have a chance. Thanks!

**Comment by facekapow** [comment]
Darling no longer uses a kernel module, so I'll go ahead and close this.
