### ISSUE TITLE
Download a deb for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by rusimody** [darlinghq/darling#1187]
Would like to try darling on Ubuntu 22.04 LTS.
I see on the [releases](https://github.com/darlinghq/darling/releases) page that
- Deb packages for Ubuntu are only available to 20.04 LTS (Focal-Fossa)
- Anyway releases are considered obsolete and github actions are recommended

But I am unable to figure out how to get a suitable deb from actions -- assuming its possible

**Comment by acheong08** [comment]
The deb packages for Ubuntu 20.04 also work on 22.04

**Comment by rusimody** [comment]
> The deb packages for Ubuntu 20.04 also work on 22.04

Thanks much
` darling shell` Seems to work!

Is it possible to run a C compiler? gcc or clang either is ok

Or is that asking too much

[Ive a reasonably basic C program that I would like to compile for mac]

**Comment by facekapow** [comment]
You should be able to use either, but clang is easier to install (just do `xcode-select --install`).

**Comment by acheong08** [comment]
> You should be able to use either, but clang is easier to install (just do `xcode-select --install`).

that installs both 🖒

**Comment by lnee94** [comment]
i working on geting a 22.04 debbuild

**Comment by facekapow** [comment]
Closing this as the original issue seems to be resolved.

**Comment by kupiqu** [comment]
> The deb packages for Ubuntu 20.04 also work on 22.04

For me, when I try to install it in 22.04, it requires uninstalling a bunch of system packages
