### ISSUE TITLE
(Self-Built) LLDB Unable To Find __kCFBooleanTrue Symbol

### ISSUE THREAD

**Issue by CuriousTommy** [darlinghq/darling#1191]
This is a strange issue... because [`__kCFBooleanTrue` already exists in CoreFoundation](https://github.com/darlinghq/darling-corefoundation/blob/master/CFNumber.c#L53). This was tested with a self-built version of lldb.

```
$ ./lldb
dyld: dyld cache load error: shared cache file open() failed
dyld: Symbol not found: ___kCFBooleanTrue
  Referenced from: /Volumes/SystemRoot/home/user/Downloads/lldb-install/bin/../lib/liblldb.15.0.0git.dylib (which was built for Mac OS X 12.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

abort_with_payload: reason: dyld cache load error: shared cache file open() failed
Symbol not found: ___kCFBooleanTrue
  Referenced from: /Volumes/SystemRoot/home/user/Downloads/lldb-install/bin/../lib/liblldb.15.0.0git.dylib (which was built for Mac OS X 12.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
; code: 4
Abort trap: 6 (core dumped)
```

**How To Reproduce**

See "How to reproduce" section in https://github.com/darlinghq/darling/issues/1188.

Notes
* This was built on `update_sources_11.5` (6bc3222b9fc8eb53ff9380dc9a9216c884e340a2) with the `libcxx`/`libcxxabi` branch set to `update_sources_11.5` .
* I checked the `nm` output for CoreFoundation between macOS and Darling. Haven't look into the meaning of the differences yet.
```
#macOS
00007ff842e7e430 S ___kCFBooleanTrue
#Darling
001d7648 d ___kCFBooleanTrue
```

**Comment by facekapow** [comment]
Looks like something Apple updated in the newer CoreFoundation. `S` from `nm` means that the symbol is exported/visible (and it's uninitialized), `d` means it's unexported/invisible (and it's initialized). Should be a simple fix: just remove the `static` qualifiers from `__kCFBooleanFalse` and `__kCFBooleanTrue`.
