### ISSUE TITLE
Cmake build error

### ISSUE THREAD

**Issue by maxqxam** [darlinghq/darling#1192]
**Build Log**
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'fuse'
--   Found fuse, version 2.9.9
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavformat'
--   No package 'libavformat' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
CMake Error at cmake/FindFFmpeg.cmake:86 (message):
  Could not find libavcodec or libavformat or libavutil
Call Stack (most recent call first):
  src/CoreAudio/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/yolo/Darling/darling/build/CMakeFiles/CMakeOutput.log".
See also "/home/yolo/Darling/darling/build/CMakeFiles/CMakeError.log".

```

[CMakeError.log](https://github.com/darlinghq/darling/files/9189054/CMakeError.log)
[CMakeOutput.log](https://github.com/darlinghq/darling/files/9189055/CMakeOutput.log)

**System Information**
```
OS: Kali GNU/Linux Rolling x86_64 
Kernel: 5.16.0-kali7-amd64
CPU: 11th Gen Intel i7-11700 (16) @ 4.800GHz
GPU: Intel RocketLake-S GT1 [UHD Graphics 750]
Memory: 6545MiB / 15768MiB
```

| Software | Version |
| --- | --- |
| Clang | Debian clang version 13.0.1-6 |
| CMake | cmake version 3.23.2|
| Linux Kernel |  5.16.0-kali7-amd64 |
| Darling | latest version|

I used [this](https://www.maketecheasier.com/run-mac-apps-on-linux/) tutorial to install darling

**Comment by mrolappe** [comment]
As the error message tells you, you need the `libav` dependency. See also the [official build instructions](https://docs.darlinghq.org/build-instructions.html) for other required depencies.

**Comment by facekapow** [comment]
As @mrolappe said, follow the official build instructions. Since Kali is based on Debian, you should be able to install the Debian dependencies.
