### ISSUE TITLE
Missing Photos.framework

### ISSUE THREAD

**Issue by bpint** [darlinghq/darling#1198]
**Framework**
Photos.framework missing

**Test Application**
Thunder Download from https://dl.xunlei.com

**Steps To Reproduce**
1. Build darling from source
2. Run thunder from command line

```
Darling [~]$ /Applications/Thunder.app/Contents/MacOS/thunder
dyld: dyld cache load error: shared cache file open() failed
dyld: Library not loaded: /System/Library/Frameworks/Photos.framework/Versions/A/Photos
  Referenced from: /Applications/Thunder.app/Contents/MacOS/Thunder
  Reason: image not found
abort_with_payload: reason: dyld cache load error: shared cache file open() failed
Library not loaded: /System/Library/Frameworks/Photos.framework/Versions/A/Photos
  Referenced from: /Applications/Thunder.app/Contents/MacOS/Thunder
  Reason: image not found; code: 1
Abort trap: 6 (core dumped)
```

**System Information**
Ubuntu 22.04

| Software | Version |
| --- | --- |
| Darling | [e385bb9](https://github.com/darlinghq/darling/commit/e385bb9d9898987119c6514d01d403204e00704d) |

**Comment by mrolappe** [comment]
See PR #1199

**Comment by facekapow** [comment]
Closing this since we now have a stub for `Photos.framework`.
