### ISSUE TITLE
[Question][Not Issue] XCode command

### ISSUE THREAD

**Issue by jhay06** [darlinghq/darling#1201]
hi , this is not an issue , this is just a question.
would like to ask since darling can't run xcode GUI but can run a command xcodebuild ,
would like to know if there's any way i can create a free ios provisioning profile certificate by just using a terminal .

in xcode this will auto generated once we create an ios app , but how can i do it without GUI , by just terminal? 

Thanks

**Comment by facekapow** [comment]
Closing this in favor of your newer issue (which also includes this question): #1228.
