### ISSUE TITLE
Does darling support nvidia graphic cards?

### ISSUE THREAD

**Issue by James4Ever0** [darlinghq/darling#1203]
macOS needs to install nvidia card drivers if it is on a hackintosh, and there are many hacks around this after both nvidia and Apple officially dropped support for nvidia drivers since macOS Mojave. darling is a translation layer by its nature, and i have installed nvidia drivers on linux. so i'm wondering if darling could run frameworks like CoreML, CreateML with GPU support?

**Comment by James4Ever0** [comment]
can darling run nvcc and cuda?

**Comment by James4Ever0** [comment]
curious if darling can really do that, which will definitely bridge a huge gap for creating CoreML supported platforms, without the need to install and run macOS on top of linux or inside some emulation layers

**Comment by CuriousTommy** [comment]
>  I'm wondering if darling could run frameworks like CoreML, CreateML with GPU support?

In theory, it should be possible, but just like with our other frameworks, it will need to be re-implemented from scratch.

> can darling run nvcc and cuda?

If the API is the same as on Linux, in theory it should be possible. With that being said, we normally don't implement 3rd party macOS API.

**Comment by facekapow** [comment]
Closing this since the original question has been answered.
