### ISSUE TITLE
Sugestion: Add clang, cmake to enable a basic toolchain on Darling

### ISSUE THREAD

**Issue by Arucard1983** [darlinghq/darling#122]
Since clang or gcc works on recent versions of Darling, but was bundled on real Mac OS X installations by the restricted XCode (licenses issues), unless I grab from here... legally
http://llvm.org/releases/download.html
And waste several minutes to find and set the correct directories for compilers, and header files once I untar the package.
 Once fixed the PATH issues, it compiles without problems.

This project is already building several native Mach-O command line tools like python, curl and even compiler-rt. 
My suggestion is to add the following component for Darling...
- Create a darling-cmake and darling-clang (And symlinks to make and gcc for compatibility).
  With this small improvement, Darling gains a basic toolchain for cross-compiling, specially on my recent work of a Software in C++ that make stoichiometric analysis based on Gamma Ray Spectroscopy, using wxWidgets to build Linux and Windows versions without changing a line of code.
- Since some colleges use Mac, and I program in Linux, and cross-compile for Windows, one of long term possibilities is also to cross-compile for Mac OS X. And Darling could make ease in this task.

**Comment by LubosD** [comment]
Hi, yes, the Xcode license agreement only allows you to run their tools under Darling as long as you have Darling installed in a Linux VM on a Mac machine :-)

I shared your idea of providing developer tools directly in Darling. While I may do something in this direction in future, it is difficult to build anything for OS X without the Mac SDK. Don't forget that for building you need a) header files b) real Mach-O files to link against. Getting both right is a lot of work.

This is why, at least for now, I'll focus on getting the solution that uses the Xcode toolchain fully working. That currently means working `xcodebuild` and also JRE to enable running CI build agents (Jenkins, TeamCity...).

BTW: I haven't yet checked if cmake runs under Darling, but you can get a package from rudix.org.

**Comment by LubosD** [comment]
Update: CMake unfortunately uses the Security framework, among other things to create SSL connections. I don't even know what for. Darling isn't yet building Security.framework (and the SSL stuff is not open sourced AFAIK).

**Comment by Arucard1983** [comment]
An alternative is to build a real gcc and GNU make from source using the xcode tools, or the clang package mentioned above, in a surreal bootstrapping process. (DarlingTricks, the cousin of WineTricks may born in this way.)
 Some native cross-compilers for Linux exists, but requires the Xcode package to extract the major libraries to build the cross-toolchain. 
 Basically the main problem comes from Apple itself, by packaging the core libraries in a restricting license, avoiding the distribution by third-party sources. Otherwise, a OS X clone of MinGW was already here.

 Even so, the main target of Darling should to run the Mac OS X software that was already compiled from the official Apple XCode, and leave this issue to a long term objective, since the OSX-Cross, which is the standard cross-compiler for Linux, still requires XCode.
 https://github.com/tpoechtrager/osxcross

**Comment by LubosD** [comment]
Yep. Looking at osxcross, I think Darling is already easier to use and performing better, but there is still a lot left to desire.

**Comment by Arucard1983** [comment]
Using the rudix repository as you mentioned it, cmake fails due to the lack of Security Framework, but the GNU make appears to work. (However using make without a working compiler is not so desirable).
 Too bad that rudix don't include the gcc compiler, which at last could enable a basic compiler toolchain, even with only the open-sourced components of Mac OS X.
 However a bootstrap gcc compiler for Mac OS X (version 4.2) can be installed from here, since it was a PKG file.
 https://github.com/kennethreitz/osx-gcc-installer
 The installation gives some issues, but installs a lot of libraries that appears to be the open-sourced components of Mac OS X, and in a long term could be used to build newer versions of gcc or clang using the Darling libraries to replace the proprietary components of Mac OS X. 

This version of gcc appears to work in this stage (except linking, but your project had a fork of ld64 linker, but don't appears on /bin directory list), even Darling warns that compiler was not linked with libSystem. But it works, somehow.

**Comment by Arucard1983** [comment]
When I make a clean install of a new DPREFIX, and update the new patches, ld from the bootstrap gcc package that I was mentioned in previous commentary, now appears on /usr/bin, and the linkage fails due to ld error:

Beware! This executable does not link against libSystem. It is very likely a copy-protected executable which makes direct system calls.
Darling currently cannot support that.
# But the hello.o binary are created without problems...
ld: library not found for -lSystem
collect2: ld returned 1 exit status
# And fails here.

At last it's a good progress!

**Comment by LubosD** [comment]
The recommendation remains to be "install Apple's SDK". Providing all the header files etc. ourselves is too much work and an alternative solution is very simple.

That being said, ld shouldn't really complain about -lSystem not being found, when using Darling from the using-machos-experiment branch.
