### ISSUE TITLE
curl hangs due to DNS resolution

### ISSUE THREAD

**Issue by thecodrr** [darlinghq/darling#1220]
**Expected Result**
`curl https://google.com/` should output valid HTML. `curl 1.1.1.1` works as expected though so I am pretty sure it's a DNS resolution issue. The thing is I can't even edit `/etc/resolve.conf` (I get permission denied error).

**Actual Result**
`curl https://google.com/` hangs.

**Steps To Reproduce**
1. `darling shell`
2. `curl https://google.com/`

**System Information**

| Software | Version |
| --- | --- |
| Linux Kernel | 5.15.0-41-generic |
| Darling | b75c25e2c192d005dec3f0613acc33b500d08172 |

**Comment by thecodrr** [comment]
Running darling as root allowed me to edit `/etc/resolve.conf`. As soon as I put the host system's `resolve.conf` curl started to work. Which is great but I still haven't found a way to edit `/etc/resolve.conf` as `sudo nano /etc/resolve.conf`

**Comment by CKegel** [comment]
I also had this issue, and your solution worked

**Comment by ZeppLu** [comment]
`sudo` is unnecessary, you can edit the file in Linux host directly:
```shell
mkdir -p ~/.darling/private/etc
cp /etc/resolve.conf ~/.darling/private/etc/  # or you may try `ln -s`
darling shutdown
darling shell
```

Ideally, darling should take care of resolve.conf when creating prefix.

BTW, I also noticed that `~/.darling` prefix misses some directories (including `Library` and `private/tmp`) on my machine for unprivileged users, haven't figured out why.

**Comment by facekapow** [comment]
See #981 for the proposed solution to this (we should just use the host's resolver). For now though, as @ZeppLu discovered, you can edit `${DPREFIX}/private/etc/resolv.conf` (where `${DPREFIX}` is usually `~/.darling`) outside of Darling to set your desired settings.
