### ISSUE TITLE
Add Disable GUI ?

### ISSUE THREAD

**Issue by tnagorran** [darlinghq/darling#1225]
darling must be built with all graphical dependencies like :
- pulseaudio
- x11 
- png-tiff-gif 
- freetype
- opengl
- xml

It is not possible to compile darling without graphic interface and so without this library
it would be nice to add a --without-x / --without-pulseaudio (like wine)
or simply a -DCMAKE_DISABLE_GUI=ON
for those who use darling on servers and do not need all these dependencies graphic or executes only client applications (like wine build with --without-x or the wineconsole executable)

**Comment by CKegel** [comment]
I believe this issue has now been addressed, and can be closed. See [this section](https://docs.darlinghq.org/build-instructions.html#building-only-certain-components) of the documentation for more details.
