### ISSUE TITLE
[Question] : Darling in other partition?

### ISSUE THREAD

**Issue by jhay06** [darlinghq/darling#1230]
Hi , 
  can we install darling system in external partition ? is this posible 

my main partition is has  10G  available , but the other partition has 100GB+ available space.

i would like to install the systems of darling on my other partition.

Thanks

**Comment by HinTak** [comment]
The answer is yes. Works on usb drives. Search for USB drive on the issue list :-(.

**Comment by jhay06** [comment]
Thanks :)

**Comment by jhay06** [comment]
i tried the DPREFIX but when darling initialize , it fails with this error 
Cannot mount overlay: Invalid argument
Cannot open mnt namespace file: No such file or directory

**Comment by jhay06** [comment]
> I think you already have your answer. While usb / external drive works, they must be formatted with ext4 or one of the file systems which support symlinks, permission bits, and mounted with execution allowed.
> 
> ===
> 
> write(2, "Sorry, the /usr/bin/darling' bi"..., 77Sorry, the /usr/bin/darling' binary is not setuid root, which is mandatory.
> 
> ) = 77
> 
> write(2, "Darling needs this in order to c"..., 86Darling needs this in order to create mount and PID namespaces and to perform mounts.
> 
> ) = 86
> 
> ===

i tried to format my usb drive to ext4  to check if this work before going to real partition .   

but still doesn't work 

strace darling shell

execve("/usr/bin/darling", ["darling", "shell"], 0x7ffc8e051d58 /* 50 vars */) = 0

access("/etc/suid-debug", F_OK)         = 0

brk(NULL)                               = 0x5589c0c40000

arch_prctl(0x3001 /* ARCH_??? */, 0x7ffde9c0c810) = -1 EINVAL (Invalid argument)

fcntl(0, F_GETFD)                       = 0

fcntl(1, F_GETFD)                       = 0

fcntl(2, F_GETFD)                       = 0

access("/etc/suid-debug", F_OK)         = 0

mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc584259000

access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3

newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=87931, ...}, AT_EMPTY_PATH) = 0

mmap(NULL, 87931, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fc584243000

close(3)                                = 0

openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3

read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832

newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=14432, ...}, AT_EMPTY_PATH) = 0

mmap(NULL, 16424, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58423e000

mmap(0x7fc58423f000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7fc58423f000

mmap(0x7fc584240000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fc584240000

mmap(0x7fc584241000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fc584241000

close(3)                                = 0

openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3

read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832

pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784

pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48

pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0i8\235HZ\227\223\333\350s\360\352,\223\340."..., 68, 896) = 68

newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0

pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784

mmap(NULL, 2260560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc584016000

mmap(0x7fc58403e000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7fc58403e000

mmap(0x7fc5841d3000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7fc5841d3000

mmap(0x7fc58422b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7fc58422b000

mmap(0x7fc584231000, 52816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fc584231000

close(3)                                = 0

mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc584013000

arch_prctl(ARCH_SET_FS, 0x7fc584013740) = 0

set_tid_address(0x7fc584013a10)         = 31585

set_robust_list(0x7fc584013a20, 24)     = 0

rseq(0x7fc5840140e0, 0x20, 0, 0x53053053) = 0

mprotect(0x7fc58422b000, 16384, PROT_READ) = 0

mprotect(0x7fc584241000, 4096, PROT_READ) = 0

mprotect(0x5589c0384000, 4096, PROT_READ) = 0

mprotect(0x7fc584293000, 8192, PROT_READ) = 0

prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0

munmap(0x7fc584243000, 87931)           = 0

geteuid()                               = 1000

readlink("/proc/self/exe", "/usr/bin/darling", 4095) = 16

write(2, "Sorry, the `/usr/bin/darling' bi"..., 77Sorry, the `/usr/bin/darling' binary is not setuid root, which is mandatory.

) = 77

write(2, "Darling needs this in order to c"..., 86Darling needs this in order to create mount and PID namespaces and to perform mounts.

) = 86

exit_group(1)                           = ?

+++ exited with 1 +++



darling shell

Error connecting to shellspawn in the container (/media/jhay/8a24f7fb-e599-453f-b939-075fda7d871d/.darling/var/run/shellspawn.sock): No such file or directory

**Comment by HinTak** [comment]
The execution allowed flag is a mount option. Default off for removable drives, so you need to put it in explicitly. There is a separate suid allowed option flag too, again default off.

**Comment by jhay06** [comment]
> The execution allowed flag is a mount option. Default off for removable drives, so you need to put it in explicitly. There is a separate suid allowed option flag too, again default off.

what do you mean ? sorry im not familiar on that option

**Comment by HinTak** [comment]
Read "man mount". Look for "nosuid", "noexec" in particular.

**Comment by jhay06** [comment]
i tried both mount -o rw,nosuid,noexec /dev/sdb1 /media/usbdrive 
and mount -o rw,exec,suid /dev/sdb1 /media/usbdrive

both gives me the same output above
