### ISSUE TITLE
[RFC] 9p file server

### ISSUE THREAD

**Issue by markusbkk** [darlinghq/darling#1235]
I don't know how well this fits your vision but both [Microsoft WSL2](https://devblogs.microsoft.com/commandline/a-deep-dive-into-how-wsl-allows-windows-to-access-linux-files/) and [Google Crostini](https://chromeos.dev/en/linux/linux-on-chromeos-glossary) utilize [9p](https://en.wikipedia.org/wiki/9P_(protocol)) to share files between the host and the VM.

IMHO, running a Plan 9 file server would make communication between the host and Darling more streamlined.
That being said, I have only been using Darling for 5 hours so I've yet to take a deep dive into that part of its architecture.

**Comment by TheBrokenRail** [comment]
Is this really necessary though when Darling can just access the host's filesystem by itself? (And vice versa by the host accessing the `.darling` folder.)

**Comment by markusbkk** [comment]
> My understanding is that both WSL2 and Crostini are using virtual machines to run Linux. Using a file server, like Plan 9, would make sense in that scenario (since there isn't an alternative that would be practical).
> 
> However, Darling is just a "normal" Linux app. I don't see how using Plan 9 would streamline or even secure a Linux app. If security is your concern, we're better off working on implementing Flatpak support for Darling.

Well yea. Flatpak would help isolating resources. However, then you'd definitely need a mechanism to share the host file system efficiently and securely (Portals? 9p? Something else?)

Just to re-iterate. I'm not saying implementing a a file server will magically make Darling more secure. I'm saying this could be part of the strategy, in addition to isolating the host file system from Darling.

**Comment by markusbkk** [comment]
> My point is that I don't see how using a file server would help with security or how it would help with streamline Darling. It just seems like unnecessary work in my opinion.

It really depends on the sort of resource restrictions you want to enforce further down the line. When I filed the issue, I was thinking we could achieve similar isolation to WSL2 or Crostini. I didn't necessarily have Flatpak in mind either, as there are many other ways to isolate Darling's VFS from the host.

**Comment by facekapow** [comment]
Thanks for the suggestion, but I'm closing this since it there's really no need for something like a 9p server in Darling. If it's FS isolation you want, Darling is now able to run easily inside privileged Docker containers and there are plans to enable it to run in Flatpaks and unprivileged Docker containers by getting rid of our SUID permissions.

Then again, there's nothing stopping you from creating said server for Darling (e.g. see how darling-dmg mounts DMGs within Darling).
