### ISSUE TITLE
'thread' file not found

### ISSUE THREAD

**Issue by luimen6** [darlinghq/darling#1239]
**Build Log**
What is the build error?
```
[ -3%] Building C object src/bsdln/CMakeFiles/bsdln.dir/ln.c.o
[ -3%] Linking C executable bsdln
[ -3%] Built target bsdln
[ -3%] Building CXX object src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin19-ld.dir/ld/InputFiles.cpp.o
darling/src/external/cctools-port/cctools/ld64/src/ld/InputFiles.cpp:34:10: fatal error: 'thread' file not found
#include <thread> // for std::thread
         ^~~~~~~~
1 error generated.
make[2]: *** [src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin19-ld.dir/build.make:76: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin19-ld.dir/ld/InputFiles.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:13700: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin19-ld.dir/all] Error 2
make: *** [Makefile:136: all] Fehler 2
```

**System Information**
What system are you building with?

Ubuntu 22.04
5.15.0-53-generic

**Comment by Phantasimay** [comment]
i build on kali-rolling release. it's find with command:
cmake -GNinja -Bbuild -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -DADDITIONAL_PACKAGES=ON -DJSC_UNIFIED_BUILD=ON

on darling tree folder.

**Comment by facekapow** [comment]
This should be fixed with the updated dependencies for Ubuntu 22.04: some dependencies changed from Ubuntu 20.04 to 22.04 and it seems `libstdc++` is no longer installed automatically by our other dependencies. Installing `libstdc++-12-dev` should fix this.

Feel free to reopen this if it still doesn't work after installing that package.
