### ISSUE TITLE
[QUESTION]: Current Darling 

### ISSUE THREAD

**Issue by jhay06** [darlinghq/darling#1244]
Hi , i'm sorry for this question . but i have to ask this.

I just want to ask , What apps works or what can i do on the current darling version.

as i am also a programmer so what i know are apps for dev like Xcode , Visual studio for Mac , QT for Mac

but it seems that those apps won't run on the current darling version, i tested it on both stable version and the 11.5 source but no luck .

so i'm a bit confused right now. what can i do on the current darling version ? 
also if there's a thing like wine app Database for darling is a great help.

the only thing that i tested to run is the midnight commander. 

Thanks
Regards,

**Comment by CuriousTommy** [comment]
I recommend looking at the following pages to get an idea of the types of application that would/would not work on Darling
* [Known working software](https://docs.darlinghq.org/known-working-software.html)
* [Known partially working software](https://docs.darlinghq.org/known-partial-software.html)
* [Known non-functional software](https://docs.darlinghq.org/known-nonfunctional-software.html)

> also if there's a thing like wine app Database for darling is a great help.

We don't currently have one. I know that LubosD was working on one, but I'm not sure if he still is.

> as i am also a programmer so what i know are apps for dev like Xcode , Visual studio for Mac , QT for Mac

GUI support is still at the early stages, it unlikely that the majority of GUI apps will work. You may have better luck with CLI apps, but even then not all apps will work.

**Comment by jhay06** [comment]
hi @CuriousTommy , thanks for the response will look on the link .

btw, xcode build cli  is not working on both stable and 11.5 source darling .  

thanks
