### ISSUE TITLE
Warnings on startup under Fedora 36 running on Distrobox

### ISSUE THREAD

**Issue by aral** [darlinghq/darling#1248]
Just wanted to share my experience in building and running Darling under Distrobox running Fedora 36 (on a Fedora Silverblue 37 host system).

The build went well (I finally got my money’s worth from my 16 cores). Lots of warnings but no errors. (And I’d substituted ffmpeg-free-devel for ffmpeg-devel as a dependency so I was worried that would mess things up but it apparently didn’t.)

When I ran `darling shell` for the first time, this is the output I got:

```
Setting up a new Darling prefix at /var/home/aral/.darling
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
Bootstrapping the container with launchd...
libEGL warning: MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)


The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Darling [/Volumes/SystemRoot/var/home/aral/sandbox/darling/build]$
```

So it seems to be working but there were some errors/warnings.

Hope this helps and thanks for making and sharing this.

**Comment by firashacker** [comment]
this is not an issue with darling, you just didnt export your environmental variables in distrobox-enter command , you can report this on distrobox repo.

**Comment by facekapow** [comment]
Closing this since it's technically not an issue. It seems the container didn't have `xdg-user-dir` nor any graphics drivers installed, so that's why you got those warnings.
