### ISSUE TITLE
dyld cache load error: shared cache file open() failed

### ISSUE THREAD

**Issue by Slackadays** [darlinghq/darling#1258]
**Expected Result**
When running `clipboard`, the help message is displayed or clipboard contents shown.

**Actual Result**
I get the following errors:
```
dyld: dyld cache load error: shared cache file open() failed
dyld: Symbol not found: __ZTINSt3__14__fs10filesystem16filesystem_errorE
  Referenced from: /Volumes/SystemRoot/home/jackson/Downloads/bin/clipboard (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Volumes/SystemRoot/home/jackson/Downloads/bin/clipboard
abort_with_payload: reason: dyld cache load error: shared cache file open() failed
Symbol not found: __ZTINSt3__14__fs10filesystem16filesystem_errorE
  Referenced from: /Volumes/SystemRoot/home/jackson/Downloads/bin/clipboard (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib
 in /Volumes/SystemRoot/home/jackson/Downloads/bin/clipboard; code: 4
```

**Steps To Reproduce**
1. Install Darling using the `.deb` from the latest release
2. Download `clipboard` from GitHub Actions (https://github.com/Slackadays/Clipboard/actions/runs/3977264606)
3. Run `darling shell ./clipboard` or `darling shell ./clipboard -h`
4. Get the above error

**System Information**
I'm using Pop!_OS 22.04 with an x86 processor.

| Software | Version |
| --- | --- |
| Linux Kernel | 6.0.2 |
| Darling | b75c25e2c192d005dec3f0613acc33b500d08172 |

**Comment by facekapow** [comment]
This is essentially the same as #1216; closing in favor of that (older) issue.
