### ISSUE TITLE
Java 17 crashes

### ISSUE THREAD

**Issue by axelfontaine** [darlinghq/darling#1289]
**Expected Result**
`java -version` displays the installed Java version

**Actual Result**
```
Darling [~]$ java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fef0357689d, pid=2528, tid=9475
#
# JRE version:  (17.0.6+10) (build )
# Java VM: OpenJDK 64-Bit Server VM (17.0.6+10-jvmci-22.3-b13, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libobjc.A.dylib+0x3989d]
[error occurred during error reporting (printing problematic frame), id 0xb, SIGSEGV (0xb) at pc=0x00007fef046eae3b]

# Core dump will be written. Default location: /cores/core.2528 (max size 18014398509481983 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007fef03a22f19]
```

**Steps To Reproduce**
Follow the install instructions at https://www.graalvm.org/latest/docs/getting-started/macos/ . Step 1 to 4 work. Step 5 triggers the crash.

**System Information**
WSL2 + Ubuntu 22.10

| Software | Version |
| --- | --- |
| Linux Kernel | `5.15.79.1-microsoft-standard-WSL2` |
| Darling | `5900547626878bdfd2f3b731d66041905d8c88d0` |

**Comment by facekapow** [comment]
Confirmed that I can reproduce this even with the newer version.

**Comment by facekapow** [comment]
This should now be fixed with the latest commit on the master branch (darlinghq/darling-corefoundation@aa4fa49413d6ec41d71e9a6f36ee3f9b8509b491). However, note that compiling with `native-image` crashes.

**Comment by axelfontaine** [comment]
Is there any issue tracking the crash with native-image? (which was my original goal when I created this issue)

**Comment by facekapow** [comment]
No, none yet; feel free to create one for that.
