### ISSUE TITLE
Build troubles

### ISSUE THREAD

**Issue by X0rg** [darlinghq/darling#129]
Since I've updated my system (log: [Arch_update.txt](https://github.com/darlinghq/darling/files/149339/Arch_update.txt)), I can't build Darling (but it was working before update).
Maybe it's due to a change in Glibc 2.23...

The first issue is with 32-bit build:
```
[ 50%] Linking C shared library libsystem.so
clang-3.7: warning: argument unused during compilation: '-nostdinc'
/usr/lib32/libc.so.6:(*IND*+0x0): multiple definition of `scalbln'
/usr/lib32/libc.so.6:(*IND*+0x0): multiple definition of `scalblnf'
/usr/lib32/libc.so.6:(*IND*+0x0): multiple definition of `scalblnl'
[ 51%] Built target stdcxx
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
src/libsystem/CMakeFiles/system.dir/build.make:165: recipe for target 'src/libsystem/libsystem.so' failed
make[2]: *** [src/libsystem/libsystem.so] Error 1
CMakeFiles/Makefile2:4182: recipe for target 'src/libsystem/CMakeFiles/system.dir/all' failed
make[1]: *** [src/libsystem/CMakeFiles/system.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

When I skip the 32-bit build, I have an other issue with 64-bit install:
```
-- Installing: /home/xorg/darling-git/pkg/darling-git/usr/libexec/darling/bin/id
CMake Error at src/external/shell_cmds/cmake_install.cmake:436 (file):
  file INSTALL cannot find
  "/home/xorg/darling-git/src/darling/build/x86-64/src/external/shell_cmds/symlinks/groups".
Call Stack (most recent call first):
  src/cmake_install.cmake:98 (include)
  cmake_install.cmake:44 (include)
  


Makefile:137: recipe for target 'install' failed
make: *** [install] Error 1
```

I don't know what is causing these bugs. :s

**Comment by LubosD** [comment]
Symlinks: I'll try reverting a change I made not long ago. CMake really doesn't play nice with symlinks. (See https://github.com/darlinghq/darling/commit/745793eeea4bb0cc0f2ea302d8a8636b3800ee13#diff-1c7a00134324ff9c8a4dc229b74b2031).

As for the other problem, I'll setup a Docker image and try it out.

**Comment by LubosD** [comment]
I have reproduced the issue in Docker Arch image.

**Comment by LubosD** [comment]
The problem is caused by the `-Wl,--unresolved-symbols=report-all` linker flag. I'd think that this is a bug in the linker (but the flag was only needed for debugging, so I'll get rid of it).

**Comment by X0rg** [comment]
I can confirm it's fixed. Thanks for your fix.
