### ISSUE TITLE
Hopefully, no longer an issue with the attached patch.

### ISSUE THREAD

**Issue by x3x7** [darlinghq/darling#1308]
Building the darling project was a bit of an adventure. I have followed the steps from the build instructions but still got build failures due to treatment of warnings as errors in the corecrypto submodule (located at ./src/external/corecrypto).

The required updates are in the text file attached.
  
[corecrypto.txt](https://github.com/darlinghq/darling/files/10716347/corecrypto.txt)

**Comment by x3x7** [comment]
Hmm, looking again through the patch file there is an error for the bit below:

```
@@ -218,11 +218,11 @@ int ccrsa_export_pub(const ccrsa_pub_ctx_t key, size_t out_len, uint8_t *out)
 }
 
 cc_size ccder_decode_rsa_pub_x509_n(const uint8_t *der, const uint8_t *der_end) {
-	const uint8_t* body_end = NULL;
-	const uint8_t* body = ccder_decode_sequence_tl(&body_end, der, der_end);
+	//const uint8_t* body_end = NULL;
+	//const uint8_t* body = ccder_decode_sequence_tl(&body_end, der, der_end);
 
 	size_t mod_length = 0;
-	const uint8_t* mod_body = ccder_decode_tl(CCDER_INTEGER, &mod_length, body, body_end);
+	//const uint8_t* mod_body = ccder_decode_tl(CCDER_INTEGER, &mod_length, body, body_end);
 
 	return ccn_nof_size(mod_length);
 };
```
This should be removed  and the remaining ones double-checked if considered for merging. It seems that unused variables are no longer a show-stopper as it was with my earlier builds (the setting of compiler flags is another build adventure).

**Comment by CuriousTommy** [comment]
> It seems that unused variables are no longer a show-stopper as it was with my earlier builds (the setting of compiler flags is another build adventure).

What distro are you using? I haven't run into this issue on Fedora 37.

**Comment by x3x7** [comment]
I am also using Fedora but it is closer to Fedora 38/rawhide. I tried to do a custom spec file and had quite a hard time finding the proper setup (It was unexpected to see that setting the CC and CXX flags in environment variables or on cmake command line is breaking the build).

**Comment by facekapow** [comment]
This should be fixed now after the updates for Clang 16 compatibility.
