### ISSUE TITLE
CMake Error: Could NOT find Setcap (missing: SETCAP_EXECUTABLE)

### ISSUE THREAD

**Issue by Ultra980** [darlinghq/darling#1311]
Hello,
I tried installing darling in a ubuntu 20.04 distrobox, but when I run `cmake ..` I get an error:
```
CMake Warning at cmake/dsym.cmake:40 (message):
  Cannot find llvm-dsymutil, will not produce debug information
Call Stack (most recent call first):
  CMakeLists.txt:113 (FindDsymutil)


CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Setcap (missing: SETCAP_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSetcap.cmake:8 (find_package_handle_standard_args)
  CMakeLists.txt:114 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ultra/git/darling/build/CMakeFiles/CMakeOutput.log".
See also "/home/ultra/git/darling/build/CMakeFiles/CMakeError.log".
```
There's no mention of this in the CMakeOutput and CMakeError files. I followed the instructions [here](https://docs.darlinghq.org/build-instructions.html). Why does it fail?

**Comment by LubosD** [comment]
It's literally saying that you lack the setcap executable, so install it.

**Comment by Ultra980** [comment]
`sudo apt install setcap` failed. However I managed to install the `deb` in releases.

**Comment by Ultra980** [comment]
`apt search setcap` also didn't find anything.

**Comment by LubosD** [comment]
I don't want to be mean, but I suspect that if you can't find the right package to install, then Darling won't be much use for you anyway in its current stage.
https://packages.ubuntu.com/search?searchon=contents&keywords=setcap&mode=exactfilename&suite=kinetic&arch=any

**Comment by Ultra980** [comment]
I found [this stackoverflow answer](https://unix.stackexchange.com/questions/189237/how-to-install-linux-capabilities-like-setcap-and-getcap) by searching. I'm not really familiar with ubuntu, so I didn't know how to find a package by the binary on it. Thanks for the help, anyways!
