### ISSUE TITLE
Clang cannot be loaded by darling (version from 02-mach-2016)

### ISSUE THREAD

**Issue by crazyblu** [darlinghq/darling#132]
I give last version and build it for x86_64 (host system Debian 8 kernel 3.16.0-4).
I am download Xcode.7.2.1.dmg and unpack it ( uncompress by '7z', mount hfsplus image and copy Xcode.app to ~/.darling/Applications

I attempt translate 'helloworld' example and found error message
"dyld: Cannot execute binary file: Symbol not found: _environ"

SDKROOT set is correct.

**Comment by LubosD** [comment]
I really need to add a test runner into CI, this is a regression. Sorry for that.

**Comment by D3nshi** [comment]
Hey friend, 

It's just amazing what some  people  can create, I love it, look  at  that <http://add.myhealthtool.com/lnqdcz>

Good wishes, phil

**Comment by D3nshi** [comment]
Hello, 

I've got an announcement for you, you may be interested, you can find more information  here <http://grab.jenniferbethmulligan.com/lnfdxwak>

Looking forward, phil
