### ISSUE TITLE
DMG cannot be copy by darling (version from 02-mach-2016)

### ISSUE THREAD

**Issue by crazyblu** [darlinghq/darling#133]
I give last version and build it for x86_64 (host system Debian 8 kernel 3.16.0-4).
I am download Xcode.7.2.1.dmg and attempt to mount it by 'hdiutil'

Short (small) files (text files for example) successfully copy and show. When I start recursive copy
"cp -r /Volumes/Xcode_7.2.1/Xcode.app /Applications" 
(as example at http://www.darlinghq.org/introduction )
many error message in form "bad file handle" was been received and copy fail finish with "segmentation fault" error.

**Comment by LubosD** [comment]
I'll download the new Xcode dmg and try extraction myself.

**Comment by LubosD** [comment]
The bad file handle errors as misleading - they happen because prior to printing the message to the console, it tries to talk to syslog - which is not provided by Darling yet. These errors can be ignored.

I will focus on the crash.

**Comment by LubosD** [comment]
This is the problematic directory: /Volumes/Xcode_7.2.1/Xcode.app//Contents/Developer/Documentation/DocSets/com.apple.adc.documentation.OSX.docset/Contents/Resources/Tokens/C/data/-

Unfortunately, it makes crash gdb as well. Fun times.

**Comment by LubosD** [comment]
I've figured out the problem and it's interesting it hasn't appeared until now. Darling doesn't support `VM_MAKE_TAG(VM_MEMORY_REALLOC)` in `vm_allocate()`. The requirements of this allocation flag are so specific, they cannot be implemented from userspace (Linux mmap is too simple), so this needs additional implementation in Darling's kernel module.

**Comment by D3nshi** [comment]
Hello,

I've just found some new methods to solve the problem you're facing, read more here <http://wevicopi.petitionman.com/thirty.php?vjj>

Good wishes, phil@hoefer-elze.de

**Comment by D3nshi** [comment]
Hey,

My friends just have been talking about that stuff all day long, you may like it too. More info here  <http://tufafowu.nj-heating-cooling.com/lnxfna>

Sincerely yours, phil@hoefer-elze.de
