### ISSUE TITLE
mac 12 dyld chained fixups framework miss

### ISSUE THREAD

**Issue by lilili87222** [darlinghq/darling#1330]
```
 Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT
	/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit: stat() failed with errno=22
	/System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit: malformed mach-o image: dyld chained fixups info underruns __LINKEDIT
abort_with_payload: reason: dyld cache load error: shared cache file open() failed
Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit
```

**Framework**
CryptoKit.framework

**Test Application**
any app compile for mac 12  used this framework

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?

**System Information**
ubuntu 20

| Software | Version |
| --- | --- |
darling_0.1.20220929.focal_amd64.deb | 3373f6147fda4b83d5aefc4281678112a74bdc34 |

**Comment by CuriousTommy** [comment]
@lilili87222 I see that you are using the [Update Source 11.5 Public Test](https://github.com/darlinghq/darling/releases/tag/v0.1.20220929_update_sources_11_5). Do you run into this issue on the `master` branch?

**Comment by CuriousTommy** [comment]
I'm looking at the source code, and I don't see any reference to `CryptoKit`. I don't even even see `CryptoKit.framework` in `/System/Library/Frameworks/`.

In Darling, can you do a `cd /System/Library/Frameworks/` and `ls` for me and paste the output here? I want to see if the `CryptoKit.framework` exist there.

**Comment by CuriousTommy** [comment]
Hey @lilili87222, we don't support using Apple's official proprietary system frameworks in Darling.

**Comment by lilili87222** [comment]
I copy   /System/Library/Frameworks/CryptoKit.framework from mac 12.  because my tool required this lib .

**Comment by lilili87222** [comment]
Many frameworks are miss . TextureIO ,which is required by xcode command not work either.

**Comment by CuriousTommy** [comment]
> Many frameworks are miss . TextureIO ,which is required by xcode command not work either.

If a framework is missing in Darling, [a stub should be created for those missing frameworks](https://docs.darlinghq.org/contributing/generating-stubs.html).
