### ISSUE TITLE
Brew doesnt work properly on update_sources_11.5_alpharelease2

### ISSUE THREAD

**Issue by Radiicall** [darlinghq/darling#1334]
**Expected Result**
Successful installation of neofetch and exa from brew.

**Actual Result**
Brew fails with this error on neofetch `Error: macOS '10.16' is invalid` 
and this error on exa `Error: pandoc: unknown or unsupported macOS version: :dunno`.

**Steps To Reproduce**
1. Install brew
2. try to install neofetch from brew
3. `Error: macOS '10.16' is invalid`
4. try to install exa
5. `Error: pandoc: unknown or unsupported macOS version: :dunno`

| Software | Version |
| --- | --- |
| Linux Kernel | 6.1.14-200.fc37.x86_64 |
| Darling | update_sources_11.5_alpharelease2 @ 15e5b8024 |

**Comment by CuriousTommy** [comment]
Thank you for the bug report! I was able to get fix the issue and get `neofetch` and `exa` installed. Once I get the other issues fixed, I'll release another alpha for testing.

**Comment by Radiicall** [comment]
Nice!
