### ISSUE TITLE
installing kernel module fails

### ISSUE THREAD

**Issue by Elronnd** [darlinghq/darling#134]
(Ubuntu 14.04 LTS)

Darling itself build and installed fine, and the kernel module compiles fine, but when I try to install it, I get:

    $ sudo make install
    make -C /lib/modules/3.19.0-51-generic/build M=/home/elronnd/darling/src/lkm modules_install
    make[1]: Entering directory `/usr/src/linux-headers-3.19.0-51-generic'
      INSTALL /home/elronnd/darling/src/lkm/darling-mach.ko
    Can't read private key
      DEPMOD  3.19.0-51-generic
    make[1]: Leaving directory `/usr/src/linux-headers-3.19.0-51-generic'

**Comment by LubosD** [comment]
This is just a warning. You should be able to load the module just fine.

**Comment by Elronnd** [comment]
But if I then do `modprobe darling-mach`, it complains that it can't find it.  However, the module still seems to have been installed in `/lib/modules/3.19.0-51-generic/extra/darling-mach.ko`.  Maybe I need to let modprobe know it has to look there?

**Comment by LubosD** [comment]
This is normally done by `depmod`. But you should always be able to `insmod` the module with an absolute path.

**Comment by Elronnd** [comment]
That worked.  But now, it's looking for stuff in `/libexec` which doesn't exist on ubuntu -- but `/usr/local/libexec` contains a `darling/` dir, but just that, so I moved `/usr/local/libexec` into /, but there's a host of other problems.  It complains about a missing `/bin/darling`, lack of `realpath`, and then segfaults.

**Comment by LubosD** [comment]
I'm sorry you're having this experience. Unfortunately, every Linux distribution seems to have a ton of quirks. I regularly test Darling on Debian and I hoped things would be similar enough on Ubuntu.

Until I figure this out, I suggest re-running cmake with `-DCMAKE_INSTALL_PREFIX=/usr/local`, followed by make and make install.

**Comment by Elronnd** [comment]
It's giving me a weird error now

    $ darling shell
    /usr/local/bin/darling: 36: [: Illegal number: 
    terminate called after throwing an instance of 'std::regex_error'
      what():  regex_error
    zsh: abort (core dumped)  darling shell

And it looks like the line that's being complained about is

            if [ "$updatets" != "disable" -a "$updatets" -lt $selfmtime ]; then

**Comment by LubosD** [comment]
I will probably force Bash for this script.

As for the second error, it turns out that std::regex is completely broken on Ubuntu LTS's toolchain. Fantastic distribution. Please do as described here: http://askubuntu.com/a/456849 (NO need to do the symlink thing described in comments).

**Comment by LubosD** [comment]
After doing that update, you need to rebuild Darling (so that new libstdc++ is picked up).

I have updated the build instructions to describe getting a newer libstdc++. I could now, however, reproduce the initial problem with CMAKE_INSTALL_PREFIX. `darling-config.h` contains

````
#define LIBEXEC_PATH "/usr/local/libexec/darling"
````

which is OK.

**Comment by Elronnd** [comment]
with the new libstdc++, it fails to compile

    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/cstddef:51:11: error: 
          no member named 'max_align_t' in the global namespace
      using ::max_align_t;
            ~~^

**Comment by Shridha12** [comment]
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.3.0-29-generic
Failed to load the kernel module

**Comment by Shridha12** [comment]
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.3.0-29-generic
Failed to load the kernel module

what can i do for this error?
will any answer?

**Comment by ahyattdev** [comment]
@Shridha12 see if your latest installed kernel is the same was your currently running kernel. This happens when you upgrade your kernel and don't reboot. Please reboot and try again.

**Comment by Shridha12** [comment]
Thank You but it solved i trys to copy and paste the download-mack.ko file to lib/modules

**Comment by HinTak** [comment]
Copying kernel modules across kernel versions is bad. I'm general, kernel modules are built against specific kernel versions... If you run a different kernel after reboot, you should do `make lkm && make lkm_install` again.
