### ISSUE TITLE
Clarify limitation of Darling's thread implementation

### ISSUE THREAD

**Issue by dingari** [darlinghq/darling#1362]
I'm running into a bug when running my application under Darling and it's proving very difficult to track down. 

I'm confused about the phrasing in the [Thread Implementation](https://docs.darlinghq.org/internals/threading/thread-implementation.html) section of the documentation, especially this paragraph:

> However, there is a huge catch. Darling could set up threads on its own and everything would be working fine, but only unless no calls to native Linux libraries (e.g. PulseAudio) would be made. The problem would become obvious as soon as a Linux library makes any thread-related operations on its own - they would crash immediately. This includes many pthread_* calls, but thread-local storage access as well.

My application is written in Rust, and utilises a [Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html), which for macOS targets seems to use `pthread_*` calls to manage the locks. Is this an error-prone approach?

I've run into issues before when my macOS application spawns threads, so I've deliberately been avoiding that. However I'm using a shared Linux library that starts and manages a PulseAudio thread. I was under the assumption that this would be ok since I'm not spawning threads in my app.

Could you clarify in more detail what the documentation is stating? Is there a way to work around it allowing PulseAudio to run alongside my applications main thread safely?

**Comment by bugaevc** [comment]
Hi,

this section is about Darling implementation internals, it describes why we haven't taken an alternative (simpler) approach of implementing threads on our own, and instead are coordinating threading with the host's libc (i.e. glibc).

This should all be of no concern to you as a macOS software developer, you are free to use threads and mutexes (and Rust), and of course Darling supports that. A huge lot of software uses threads, especially on Darwin where libdispatch is spawning threads behind your back. So no, please feel free to spawn threads, and if that runs into issues on Darling, report them to us and let's investigate and fix them together.

> However I'm using a shared Linux library that starts and manages a PulseAudio thread.

What do you mean you're using a shared Linux library -- from your macOS app? How?

**Comment by bugaevc** [comment]
I... uh, don't even know where to start. Accessing ELFs and `wrap_elf` is super cool, but it's very Darling-internal, private and unsupported. You're very much not supposed to use it in an external app. If you need a specific scenario how this could break, here's one: we may change the ABI of `_elfcalls`; we will of course recompile all of our own code that uses it, but your dylib bundled with your app won't get the new version.

And of course this would not work on Apple's macOS at all.

What are you [really trying to do](https://xyproblem.info/)?

**Comment by dingari** [comment]
Thanks for clarifying.

> What are you [really trying to do](https://xyproblem.info/)?

Basically, I need access to the native audio device through a process running under Darling. When I started out on this project,  this route seemed easiest since CoreAudio isn't (or at least wasn't at the time) implemented fully in Darling.

I'm open to any suggestions on how this could be achieved in a more official/sane way :)

**Comment by bugaevc** [comment]
...but to answer your initial question, your (Darwin) code spawning threads is always fine, and these threads can be used with both host and Darwin code. But if a Linux library spawns a thread itself, as you're saying, and then your code runs in that thread (perhaps as a callback), then you're in trouble. Don't do that.

(There _may be_ some private functions in Darwin's libpthread that you may be able to call to trick libpthread into believing your Linux thread is a legitimate Darwin one... such as maybe `pthread_create_from_mach_thread()`...)

> Basically, I need access to the native audio device through a process running under Darling. When I started out on this project, this route seemed easiest since CoreAudio isn't (or at least wasn't at the time) implemented fully in Darling.
>
> I'm open to any suggestions on how this could be achieved in a more official/sane way :)

The sane way is of course implementing the missing parts of Core Audio on top of PulseAudio, and that would be a part of Darling, so for that you are allowed to use `_elfcalls` / `wrap_elf`. So you get both to play with the shiny toy and to do things the right way 🙂

Now, you sound (pun not intended!) like you know way more about audio than I do, so you likely know better which parts of CA are missing and how they map to PA.

**Comment by dingari** [comment]
Thanks for the clarification. I'll take a look and see if I can get the CoreAudio implementation to a state where I can use it :)

**Comment by LubosD** [comment]
Just to give you more historical background, I started implementing things incorrectly by implementing native audio in an Audio Unit - instead of implementing it in CoreAudio and then writing an Audio Unit on top of CA.

I didn't have the know-how back then and Apple's documentation isn't always too clear about such details.
