### ISSUE TITLE
Ubuntu having issues CMaking :(

### ISSUE THREAD

**Issue by Zendeuo** [darlinghq/darling#1372]
**Build Log**
What is the build error?
Can't find directories, or some CMake commands (Also attached the CMakeOutput.log & CMakeError.log)

Put the build log here!
overworked@deuob:~/darling/build$ sudo cmake ..
Including component: stock
Including component: cli
Including component: python
Including component: ruby
Including component: perl
Including component: dev_gui_common
Including component: dev_gui_frameworks_common
Including component: dev_gui_stubs_common
Including component: gui_frameworks
Including component: gui_stubs
Including component: system
Including component: core
Including component: gui
Including component: iokitd
Python 2 not available; bytecode compilation is disabled
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
Did not find required libraries (Vulkan and LLVM); building without Metal support
CMake Warning at cmake/dsym.cmake:48 (message):
  Cannot find llvm-dsymutil, will not produce debug information
Call Stack (most recent call first):
  CMakeLists.txt:162 (FindDsymutil)

-- Compiler include path detected as /usr/lib/llvm-15/lib/clang/15.0.7/include/
CMake Error at src/CMakeLists.txt:67 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/ld64/src"
  which is not an existing directory.

CMake Error at src/CMakeLists.txt:68 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/ar" which is
  not an existing directory.

CMake Error at src/CMakeLists.txt:70 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/misc" which is
  not an existing directory.

CMake Error at src/CMakeLists.txt:80 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/darlingserver

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:85 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bootstrap_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:136 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libkqueue

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:141 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libplatform

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:142 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libpthread

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:143 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libtrace

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:144 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libc

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:150 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libstdcxx

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:160 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/dyld

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:161 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libxpc

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:163 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/copyfile

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:164 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/Libinfo

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:165 (add_subdirectory):
  add_subdirectory given source "external/compiler-rt/lib/builtins" which is
  not an existing directory.

CMake Error at src/CMakeLists.txt:166 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libnotify

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:168 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/syslog

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:169 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libclosure

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:170 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/keymgr

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:171 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libunwind

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:172 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libmalloc

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:173 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/coretls

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:175 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/removefile

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:178 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/corecrypto

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:179 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/commoncrypto

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:182 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/configd

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:183 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libsystem

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:184 (add_subdirectory):
  add_subdirectory given source "external/objc4/runtime" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:185 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/corefoundation

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:186 (add_subdirectory):
  add_subdirectory given source "external/icu/icuSources" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:187 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/csu

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:188 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libresolv

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:189 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/usertemplate

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:190 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bsm

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:191 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/zlib

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:197 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libedit

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:198 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/ncurses

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:210 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libiconv

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:211 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bzip2

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:212 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libressl-2.8.3

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:213 (add_subdirectory):
  add_subdirectory given source "external/libarchive/libarchive" which is not
  an existing directory.

CMake Error at src/CMakeLists.txt:214 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/liblzma

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:215 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/OpenDirectory

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:216 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/openssl_certificates

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:217 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bash

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:218 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/zsh

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:219 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/tcsh

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:220 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/files

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:221 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/crontabs

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:222 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/swift

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:228 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/darling-dmg

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:229 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libutil

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:231 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libxslt

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:232 (add_subdirectory):
  add_subdirectory given source "external/openssl/src" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:233 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/nghttp2

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:234 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/passwordserver_sasl

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:235 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/curl

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:236 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/OpenLDAP

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:237 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/pcre

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:238 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libtelnet

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:239 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/remote_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:240 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/IOKitTools

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:241 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/apr

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:243 (add_subdirectory):
  add_subdirectory given source "external/file/file" which is not an existing
  directory.

CMake Error at src/CMakeLists.txt:244 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/shell_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:245 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/file_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:246 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/text_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:247 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/adv_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:248 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/network_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:249 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/system_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:250 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/mail_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:251 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/doc_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:252 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/basic_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:253 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/misc_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:254 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/patch_cmds

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:255 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/less

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:256 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/grep

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:257 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/awk

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:258 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/groff

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:259 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/nano

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:260 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/man

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:261 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bc

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:262 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/zip

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:263 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/installer

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:264 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/bind9

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:265 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/netcat

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:266 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/gpatch

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:267 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/gnudiff

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:268 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/openssh

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:269 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/top

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:270 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/screen

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:272 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/rsync

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:273 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/DSTools

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:277 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/lzfse

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:283 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libressl-2.2.9

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:284 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libressl-2.5.5

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:285 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libressl-2.6.5

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:290 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libffi

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:301 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libxml2

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:302 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/foundation

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:303 (add_subdirectory):
  add_subdirectory given source "external/cfnetwork/src" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:304 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/sqlite

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:305 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/openpam

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:306 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/energytrace

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:307 (add_subdirectory):
  add_subdirectory given source "external/lkm/libkern/kxld" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:308 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/IOKitUser

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:309 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/xar

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:311 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/DirectoryService

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:315 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/Heimdal

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:319 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/fmdb

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:320 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/libnetwork

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:322 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/MITKerberosShim

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:327 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/iokitd

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:334 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/openjdk

  does not contain a CMakeLists.txt file.

CMake Error at src/CMakeLists.txt:346 (add_subdirectory):
  The source directory

    /home/overworked/darling/src/external/cocotron

  does not contain a CMakeLists.txt file.

CMake Error at src/CoreAudio/CMakeLists.txt:4 (remove_sdk_framework):
  Unknown CMake command "remove_sdk_framework".

-- Configuring incomplete, errors occurred!
See also "/home/overworked/darling/build/CMakeFiles/CMakeOutput.log".
See also "/home/overworked/darling/build/CMakeFiles/CMakeError.log".

**System Information**
What system are you building with?
[CMakeOutput.log](https://github.com/darlinghq/darling/files/11501907/CMakeOutput.log)
[CMakeError.log](https://github.com/darlinghq/darling/files/11501911/CMakeError.log)

| Software | Version |
| --- | --- |
| Clang | 15.0.7 |
| CMake | 3.25.1 |
| Linux Kernel | 5.10.178 |
| Darling | Git Commit Hash |

**Comment by facekapow** [comment]
Did you [clone recursively](https://docs.darlinghq.org/build-instructions.html#fetch-the-sources)? (i.e. `git clone --recursive`). If not, then you can fix it by cloning the submodules with `git submodule update --init --recursive`.

**Comment by Zendeuo** [comment]
Lemme quickly rm -rf the folder and retry that I'll get back to you, tysm for you extremely quick response!

**Comment by Zendeuo** [comment]
Cool just redid the entire thing and now I'm only getting 2 errors & 1 warn:

**Warn:**
CMake Warning at cmake/dsym.cmake:48 (message):
  Cannot find llvm-dsymutil, will not produce debug information
Call Stack (most recent call first):
  CMakeLists.txt:162 (FindDsymutil)

**Error 1:**
CMake Error at /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:894 (message):
  None of the required 'openssl' found
Call Stack (most recent call first):
  src/external/openssl_certificates/CMakeLists.txt:11 (pkg_search_module)

**Error 2:**
Make Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindGIF.cmake:109 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/external/cocotron/Onyx2D/CMakeLists.txt:21 (find_package)

**Comment by facekapow** [comment]
Sounds like you don’t have OpenSSL and libGIF installed. Did you install the dependencies for your system according to the [docs](https://docs.darlinghq.org/build-instructions.html#dependencies)?

**Comment by Zendeuo** [comment]
I did, turns out it failed to find Python 2 so I guess it stopped the whole thing? So I just had to install python-is-python-3 instead as an alternative, I hope this works, I also removed the Python 2 from the ending of the install script and ran that and that installation worked, the build files have been successfully written so now I'm in hopes that the whole thing works!

**Comment by Zendeuo** [comment]
Cool I just started the Make command and everything seems to be rolling smoothly, I'll update you if I get any errors from here on out, If not I'll post a final message on how it went and hopefully have fun!

**Comment by Zendeuo** [comment]
Cool it works perfectly, runs as well, Thank you so much for your support! :3
