### ISSUE TITLE
Discord & Website

### ISSUE THREAD

**Issue by JonTAllen** [darlinghq/darling#1378]
Your Discord Server link is expired and your website doesn't show any quarterly progress beyond Q2 2019. Is this project still active? I came across your project via a recommendation on Reddit by a separate user wanting to try and have the MacOS versions of Serif Affinity software run natively on Linux. 

I tried to join your discord server via your "HQ" website and the discord service replied back as "invalid link". I am unable to join your discord server because of that fact. So I had to create this Github account to let you know about it. Most people won't go to this length to let project owners like you about these two issues.

Can you please provide an active discord server link I can join through?

**Comment by CuriousTommy** [comment]
> Your Discord Server link is expired

Weird... when I click on the link, I see the "Accept Invite" option.

> your website doesn't show any quarterly progress beyond Q2 2019.

We are currently in the process of moving away from our old blog to our new blog. We plan on making an announcement about the recent changes once our new blog is ready.

> I came across your project via a recommendation on Reddit by a separate user wanting to try and have the MacOS versions of Serif Affinity software run natively on Linux.

While Darling can run basic GUI application (such as a simple hello world), more advance applications are unlikely to work. I recommend reading the following documents to get a good idea of what Darling can/can not run:
* https://docs.darlinghq.org/known-working-software.html
* https://docs.darlinghq.org/known-partial-software.html
* https://docs.darlinghq.org/known-nonfunctional-software.html

> Can you please provide an active discord server link I can join through?

For now, try this link:
https://discord.gg/2xFCNNkTgY

**Comment by JonTAllen** [comment]
So you're saying this project is far from capable of running complex UI applications in the foreseeable future? One of the people on reddit who shared your project was wondering if it would someday be possible to run the Serif Affinity Software (Affinity Photo, Affinity Designer, Affinity Publisher) on linux via this project of yours.

**Comment by CuriousTommy** [comment]
> So you're saying this project is far from capable of running complex UI applications in the foreseeable future?
Yes

**Comment by bugaevc** [comment]
The Discord link on the frontpage works for me too, must be something wrong on your end.
