### ISSUE TITLE
Building i386 on debian

### ISSUE THREAD

**Issue by fzg** [darlinghq/darling#138]
While following the [build instructions](http://www.darlinghq.org/build-instructions) to build the i386 runtime (on up-to-date Debian experimental):

```
[ 15%] Building CXX object src/util/CMakeFiles/darling-util.dir/debug.o
In file included from /home/fzn/git/darling/src/util/debug.cpp:1:
In file included from /home/fzn/git/darling/src/util/debug.h:5:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.3.1/../../../../include/c++/5.3.1/cstdio:41:10: fatal error: 'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
1 error generated.

```

-> _apt-get install gcc-5-multilib g++-5-multilib_ fixed it (you might consider amending the webpage)

**Comment by LubosD** [comment]
Well, the webpage only deals with Debian Stable. Obviously, anyone who uses something else has to figure out the right packages himself...

**Comment by ahyattdev** [comment]
None of us are on Debian experimental, so we can't figure out what is needed. Please report back if you are on that distro and figure out the necessary packages.

**Comment by stek29** [comment]
[First page in Google](http://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit).
