### ISSUE TITLE
i dont know how to use dprefix

### ISSUE THREAD

**Issue by C3OK** [darlinghq/darling#1385]
hello. i have another question about how dprefix works it says.. "Note that in order to change the prefix location with DPREFIX, you should export this variable in the current shell before running Darling." but i dont know how to export it or where to export it

**Comment by bugaevc** [comment]
It's an environment variable, like `PATH`. The syntax depends on your shell, in Bash it's

```
$ export DPREFIX=/path/to/dprefix
```

in Fish it's

```
$ set -x DPREFIX /path/to/dprefix
```
according to [their docs](https://fishshell.com/docs/current/faq.html#how-do-i-set-or-clear-an-environment-variable).

P.S. Please consider [joining our Discord](https://discord.gg/XRD3mQA) and asking this kind of questions there, we specifically have a `#support` channel for that. GitHub issues are primarily for tracking Darling issues.

**Comment by facekapow** [comment]
Closing this since the original question has been answered and there's been no response.
