### ISSUE TITLE
Error connecting to shellspawn in the container (foo/var/run/shellspawn.sock): No such file or directory

### ISSUE THREAD

**Issue by C3OK** [darlinghq/darling#1386]
help! darling was working a while back but i did 

declare -x DPREFIX="foo darling shell"

but now i get this error

Error connecting to shellspawn in the container (foo/var/run/shellspawn.sock): No such file or directory

**Comment by facekapow** [comment]
The correct way to use `DPREFIX` is to specify just the path you want for the prefix (e.g. if you want it to be in `/foo/bar`, you set it with `declare -x DPREFIX="/foo/bar"` or, equivalently, `export DPREFIX="/foo/bar"`). After doing that, you can just run the Darling command as normal: `darling shell`.

**Comment by facekapow** [comment]
Closing this for the same reason as #1385 (the original question has been answered and there's been no response).
