### ISSUE TITLE
Python ctypes error

### ISSUE THREAD

**Issue by jrhoades** [darlinghq/darling#139]
I'm trying to use a Mac Python app that uses the module ctypes, I can see that cytpes was successfully compiled during the Darling setup, but when either using my app or just running python & "import cytpes", I get the following error:

```
Darling [/system-root/root]# python
Python 2.7.10 (default, Mar 22 2016, 13:43:37)
[GCC 4.2.1 Compatible Debian Clang 3.5.0 (tags/RELEASE_350/final)] on unknown
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 453, in <module>
    pythonapi = PyDLL(None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen() error
>>>
```

Running Debian 8.3 and I've tried compiling from scratch a couple of times.  Importing cytpes on the underlying Debian Python works fine as does on OS X.  All the other Python modules I've tried are imported without issue.  Happy to help if you could point me in the right direction.

**Comment by jrhoades** [comment]
So further investigations show, that the python module is fine.  The issues is that it's looking for libSystem.dylib in /usr/lib  - it gives Python access to the standard C library.
I imagine if I copied /usr/lib to where Darling is running it would work, but I guess this would probably be the non open source part of OS X?

**Comment by LubosD** [comment]
Darling provides its own libSystem. It appears that there is still something fishy around Darling's Python build. I'll look into it.

**Comment by LubosD** [comment]
Sorry for the delay, I've been busy doing home improvements (automation).

The Python code tries to dlopen(NULL) and this scenario is currently only supported for Mach-O main executables:
````
    if (!filename)
        return MachOMgr::instance()->mainModule();
````

I'll fix the code to support ELF as well.
