### ISSUE TITLE
how to install darling on debian 12

### ISSUE THREAD

**Issue by alavaelian** [darlinghq/darling#1391]
**Library**
python 2 

**Test Application**
darling

**Steps To Reproduce**
debian 12 deprecated the support for python2

**System Information**
debian 12 bookworm
the gide says that i need python 2 but it seems that i can not install it so my was wondering how to install it on debian 12

**Comment by facekapow** [comment]
See #1410; we no longer need Python 2, so that shouldn't be an issue anymore. I haven't tested it myself, but Darling *should* build on Debian 12.

**Comment by p0358** [comment]
As a follow-up to issue #1410, I've mitigated the `python2` dependency issue and ended up with this at the very end:
```
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVAudioAmplitudeSampleExtractionHelper.m.o
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVWaveformGenerator.m.o
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVTrimTracksView.m.o
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVVolumeButton.m.o
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVVolumeButtonContentView.m.o
[100%] Building C object src/frameworks/AVKit/CMakeFiles/AVKit.dir/src/AVVolumeImageValueTransformer.m.o
[100%] Linking C shared library AVKit
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
ld: warning: static initializer found in 'CMakeFiles/AVKit.dir/src/AVKit.m.o'. Use -no_inits to make this an error.  Use -no_warn_inits to suppress warning
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
ld: warning: static initializer found in 'CMakeFiles/AVKit.dir/src/AVKit.m.o'. Use -no_inits to make this an error.  Use -no_warn_inits to suppress warning
make[4]: Leaving directory '/app2/darling/debbuild'
[100%] Built target AVKit
make[3]: Leaving directory '/app2/darling/debbuild'
make[2]: *** [Makefile:136: all] Error 2
make[2]: Leaving directory '/app2/darling/debbuild'
make[1]: *** [debian/rules:57: override_dh_auto_build] Error 2
make[1]: Leaving directory '/app2/darling'
make: *** [debian/rules:50: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b -d failed
```

**Comment by p0358** [comment]
@facekapow sorry for ping, but just in case it was to be missed, I think the issue needs to be reopened :/

I would suggest considering having a CI build for latest Debian too so this could be avoided in the future after that's fixed (I see many projects on GitHub compiling for all possible targets), perhaps with some build cache so the rebuild doesn't always take that much CI minutes

**Comment by p0358** [comment]
Actually gonna upload the whole log since I think the actual error is concealed somewhere above:
[darling_build_log.txt](https://github.com/darlinghq/darling/files/12707561/darling_build_log.txt)
