### ISSUE TITLE
uname returns the "host" uname info

### ISSUE THREAD

**Issue by tgc-dk** [darlinghq/darling#140]
According to https://www.darlinghq.org/project-status using uname in the darwin shell should return info mimic'ing a Darwin system, but it returns the info of the "host" linux system.

**Comment by LubosD** [comment]
Cannot reproduce:

````
lubos@8-0-27-99-d5-df ~ $ export DPREFIX=/tmp/darling
lubos@8-0-27-99-d5-df ~ $ darling shell
Setting up prefix at /tmp/darling

Getting latest version of org.darlinghq.pkg.OpenSSLCertificates...
Downloading org.darlinghq.pkg.OpenSSLCertificates (version 1)...
installer: Installing package org.darlinghq.pkg.OpenSSLCertificates version 1 (405 KB)
installer: Extracting files
installer: Installation complete
Prefix is ready.
Darling [~]$ uname -a
Darwin 8-0-27-99-d5-df 12.0.0 Darwin Kernel Version 12.0.0 x86_64
````

**Comment by tgc-dk** [comment]
Hmm, interesting... I'm running on a ArchLinux VM, building darling using this PKGBUILD (build script): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=darling-git
It could be an issue due to different systems...
This is what is see:
```
$ darling shell
Darling [~]$ uname -a
Linux osboxes 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64
Darling [~]$ sw_vers 
Darling [~]$ 
```

**Comment by LubosD** [comment]
This happens when the installation is incomplete, meaning that there is for example no /etc/darling/version.conf *inside* the prefix.

**Comment by LubosD** [comment]
(Meaning the pkgbuild must be broken somehow.)

**Comment by tgc-dk** [comment]
The prefix-setup does indeed fail. Didn't notice because it didn't emit an error. It just exits while getting the OpenSSL certificates. This is what I get when setting up a new prefix:
```
[osboxes@osboxes ~]$ DPREFIX=/tmp/darling darling shell
Setting up prefix at /tmp/darling

Getting latest version of org.darlinghq.pkg.OpenSSLCertificates...
[osboxes@osboxes ~]$
```

**Comment by LubosD** [comment]
Oh, it is for sure not correct that the certificates setup fails and no error is printed, but the actual setup of the most important stuff is done right before that. FYI, the script uses wget to fetch  `http://packages.darlinghq.org/org.darlinghq.pkg.OpenSSLCertificates/latest.txt`.

Could you check that the pkgbuild has installed something like `/usr/libexec/darling/etc/darling/version.conf` (the real path on your system may vary)?

**Comment by tgc-dk** [comment]
The install does include a `/usr/libexec/darling/etc/darling/version.conf`and in the prefix it is installed in `/etc/darling/version.conf`. So the file exists, but for some reason it is not read.
Installing wget made the certificate installation work. I'll make sure to get it added to the PKGBUILD.

**Comment by LubosD** [comment]
D'oh, there was really a mistake I didn't notice up until now. Too many things to think about :-(

I don't, however, see any bug relating to `sw_vers`. It seems to be read from the right location:

````
lubos@8-0-27-99-d5-df ~ $ strace darling shell sw_vers 2>&1 | grep Core
lstat("/home/lubos/.darling//System/Library/CoreServices", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/lubos/.darling//System/Library/CoreServices/SystemVersion.plist", {st_mode=S_IFREG|0644, st_size=479, ...}) = 0
open("/home/lubos/.darling//System/Library/CoreServices/SystemVersion.plist", O_RDONLY) = 5
````

**Comment by X0rg** [comment]
@tgc-dk: Since 63c6f36, does it work without wget installed?
Tell me if PKGBUILD needs to be modified.

**Comment by LubosD** [comment]
@X0rg wget is still needed.

**Comment by X0rg** [comment]
Ok, I have added wget in PKGBUILD.

**Comment by tgc-dk** [comment]
@LubosD: The commit fixed uname - thanks!
The problem with `sw_vers` seems to be that `SystemVersion.plist` is installed into `/usr/share/darling/`, not into `<prefix>/System/Library/CoreServices/`.
Looking at `src/CoreServices/CMakeLists.txt` that actually looks correct...?

**Comment by LubosD** [comment]
No, it's not :-( I need to clean up my local installation.

**Comment by tgc-dk** [comment]
`sw_vers` works now - thanks for fixing!
