### ISSUE TITLE
Issue compiling for Ubuntu, unrecognized command-line option -fblocks

### ISSUE THREAD

**Issue by MTollens** [darlinghq/darling#1407]
**Build Log**
**build error**
```
/darling/build$ sudo make install
Consolidate compiler generated dependencies of target bsdln
[  0%] Built target bsdln
[  0%] Building CXX object src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin20-ld.dir/ld/InputFiles.cpp.o
c++: error: unrecognized command-line option ‘-fblocks’
make[2]: *** [src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin20-ld.dir/build.make:76: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin20-ld.dir/ld/InputFiles.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:13650: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin20-ld.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**build log**
[CMakeOutput.log](https://github.com/darlinghq/darling/files/12141260/CMakeOutput.log)
[CMakeError.log](https://github.com/darlinghq/darling/files/12141261/CMakeError.log)

**System Information**
Ubuntu 22.04.2 LTS x86_64 
| Software | Version |
| --- | --- |
| Clang | 14.0.0-1ubuntu1 |
| CMake | 3.22.1 |
| Linux Kernel | 5.19.0-46-generic  |
| Darling | b2847095e3afb483ad2abd219d20e5ceea871348|

**Comment by CuriousTommy** [comment]
@MTollens Can you delete your current build and checkout `ubuntu_hotfix` (`git checkout ubuntu_hotfix`)? Let me know if this fixes your issue.

**Comment by MTollens** [comment]
that seems to have worked, thank you.

**Comment by CuriousTommy** [comment]
Thanks! I'll merge those changes into `master` soon.
