### ISSUE TITLE
AuthKit.framework missing

### ISSUE THREAD

**Issue by mdolezel** [darlinghq/darling#141]
When i try to execute ld from Xcode_7.2 i get following error.

`dyld: Cannot execute binary file: dyld: Library not loaded: /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit as a dependency of /home/mdolezel/.darling/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
`
What is AuthKit.framework supposed to be?

**Comment by LubosD** [comment]
That's Apple's private framework handling authentication with Apple ID. I've never seen `ld` require this dependency - what exactly are you running?

**Comment by mehmooda** [comment]
Same issue running Xcode 7.3.1

`Darling [~]$ /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
dyld: Cannot execute binary file: dyld: Library not loaded: /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit as a dependency of /home/asad/.darling/Volumes/Xcode_7.3.1/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation`

**Comment by LubosD** [comment]
xcrun is not supported

**Comment by ahyattdev** [comment]
I will work on a stub generator that uses dumped Objective-C classes

**Comment by ahyattdev** [comment]
`AuthKit` now has stubs
