### ISSUE TITLE
conflicting types for '_Block_object_assign'

### ISSUE THREAD

**Issue by mimoccc** [darlinghq/darling#1415]
**Build Log**
```
[ 19%] Building C object src/external/dyld/CMakeFiles/system_loader.dir/src/glue.c.o
/home/mimo/Plocha/Mudita/darling/src/external/dyld/src/glue.c:1130:6: error: conflicting types for '_Block_object_assign'
void _Block_object_assign()
     ^
/home/mimo/Plocha/Mudita/darling/src/external/dyld/src/glue.c:1130:6: note: '_Block_object_assign' is a builtin with type 'void (void *, const void *, const int)'
1 error generated.
make[2]: *** [src/external/dyld/CMakeFiles/system_loader.dir/build.make:257: src/external/dyld/CMakeFiles/system_loader.dir/src/glue.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:17788: src/external/dyld/CMakeFiles/system_loader.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**System Information**
 
| Software | Version |
| Ubuntu | 23.04 |
| Clang | 13.0.0 |
| CMake | 3.25.1 |
| Linux Kernel | 6.2.0-1010-lowlatency |
| Darling | Git Commit Hash |

**Comment by mimoccc** [comment]
Can You please prepare package for Ubuntu 23.04? 
I am not into c, c++ and can not compile your project :)
Thank You.

**Comment by facekapow** [comment]
This *should* be fixed on the master branch now, but it's strange you ran into this at all; no other systems have had this problem and I was unable to reproduce this myself.

Feel free to reopen this if it turns out it's still broken.
