### ISSUE TITLE
how to fix 'unknow type name: fuse_XXXXX' issue

### ISSUE THREAD

**Issue by qokelate** [darlinghq/darling#142]
```
In file included from /home/darling/src/external/darling-dmg/src/main-fuse.cpp:1:
/home/darling/src/external/darling-dmg/src/main-fuse.h:11:47: error: unknown type name 'size_t'
int hfs_readlink(const char\* path, char\* buf, size_t size);
                                              ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:13:43: error: unknown type name 'size_t'
int hfs_read(const char\* path, char\* buf, size_t bytes, off_t offset, struct fuse_file_info\* info);
                                          ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:13:57: error: unknown type name 'off_t'
int hfs_read(const char\* path, char\* buf, size_t bytes, off_t offset, struct fuse_file_info\* info);
                                                        ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:15:46: error: unknown type name 'fuse_fill_dir_t'; did you mean 'fuse_file_info'?
int hfs_readdir(const char\* path, void\* buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info\* info);
                                             ^~~~~~~~~~~~~~~
                                             fuse_file_info
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: 'fuse_file_info' declared here
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:15:70: error: unknown type name 'off_t'
int hfs_readdir(const char\* path, void\* buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info\* info);
                                                                     ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:16:67: error: unknown type name 'size_t'
int hfs_getxattr(const char\* path, const char\* name, char\* value, size_t vlen);
                                                                  ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:17:51: error: unknown type name 'size_t'
int hfs_listxattr(const char\* path, char\* buffer, size_t size);
                                                  ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:30:26: error: variable has incomplete type 'struct fuse_operations'
                struct fuse_operations ops;
                                       ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:30:10: note: forward declaration of 'fuse_operations'
                struct fuse_operations ops;
                       ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:31:27: error: use of undeclared identifier 'FUSE_ARGS_INIT'
                struct fuse_args args = FUSE_ARGS_INIT(0, NULL);
                                        ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:31:20: error: variable has incomplete type 'struct fuse_args'
                struct fuse_args args = FUSE_ARGS_INIT(0, NULL);
                                 ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:31:10: note: forward declaration of 'fuse_args'
                struct fuse_args args = FUSE_ARGS_INIT(0, NULL);
                       ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:214:7: error: member access into incomplete type 'struct fuse_file_info'
                info->fh = uint64_t(fh);
                    ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:222:12: error: member access into incomplete type 'struct fuse_file_info'
                if (!info->fh)
                         ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:225:67: error: member access into incomplete type 'struct fuse_file_info'
                std::shared_ptr<Reader>& file = _(std::shared_ptr<Reader>_) info->fh;
                                                                                ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:236:66: error: member access into incomplete type 'struct fuse_file_info'
                std::shared_ptr<Reader>\* file = (std::shared_ptr<Reader>_) info->fh;
                                                                               ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char_ path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:238:7: error: member access into incomplete type 'struct fuse_file_info'
                info->fh = 0;
                    ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:244:46: error: unknown type name 'fuse_fill_dir_t'; did you mean 'fuse_file_info'?
int hfs_readdir(const char\* path, void\* buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info\* info)
                                             ^~~~~~~~~~~~~~~
                                             fuse_file_info
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: 'fuse_file_info' declared here
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
/home/darling/src/external/darling-dmg/src/main-fuse.cpp:244:62: error: variable has incomplete type 'fuse_file_info'
int hfs_readdir(const char\* path, void\* buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info\* info)
                                                             ^
/home/darling/src/external/darling-dmg/src/main-fuse.h:12:39: note: forward declaration of 'fuse_file_info'
int hfs_open(const char\* path, struct fuse_file_info\* info);
                                      ^
17 errors generated.
make[2]: **\* [src/external/darling-dmg/CMakeFiles/darling-dmg.dir/src/main-fuse.cpp.o] Error 1
make[1]: **\* [src/external/darling-dmg/CMakeFiles/darling-dmg.dir/all] Error 2
make: **\* [all] Error 2

```

**Comment by qokelate** [comment]
os: elementary os / x86_64

**Comment by qokelate** [comment]
os: elementary os / x86_64

**Comment by qokelate** [comment]
i purge fuse and reinstall libfuse-dev, now:

libdmg.so: undefined reference to `icu_53::UnicodeString::doEquals(icu_53::UnicodeString const&, int) const'
libdmg.so: undefined reference to `icu_53::UnicodeString::operator=(icu_53::UnicodeString const&)'
libdmg.so: undefined reference to `icu_53::ByteSink::~ByteSink()'
libdmg.so: undefined reference to `icu_53::UnicodeString::toUTF8(icu_53::ByteSink&) const'
libdmg.so: undefined reference to `icu_53::UnicodeString::extract(char*, int, UConverter*, UErrorCode&) const'
libdmg.so: undefined reference to `vtable for icu_53::ByteSink'
libdmg.so: undefined reference to `icu_53::ByteSink::Flush()'
libdmg.so: undefined reference to `icu_53::UnicodeString::~UnicodeString()'
libdmg.so: undefined reference to `typeinfo for icu_53::ByteSink'
libdmg.so: undefined reference to `icu_53::UnicodeString::doCompare(int, int, unsigned short const*, int, int) const'
libdmg.so: undefined reference to `vtable for icu_53::Replaceable'
libdmg.so: undefined reference to `ucnv_close_53'
libdmg.so: undefined reference to `icu_53::ByteSink::GetAppendBuffer(int, int, char*, int, int*)'
libdmg.so: undefined reference to `vtable for icu_53::UnicodeString'
libdmg.so: undefined reference to `icu_53::UnicodeString::UnicodeString(char const*, int, char const*)'
libdmg.so: undefined reference to `icu_53::UnicodeString::UnicodeString(char const*, int, UConverter*, UErrorCode&)'
libdmg.so: undefined reference to `icu_53::UMemory::operator delete(void*)'
libdmg.so: undefined reference to `icu_53::UnicodeString::fromUTF8(icu_53::StringPiece const&)'
libdmg.so: undefined reference to `icu_53::UnicodeString::doCaseCompare(int, int, unsigned short const*, int, int, unsigned int) const'
libdmg.so: undefined reference to `ucnv_open_53'
libdmg.so: undefined reference to `vtable for icu_53::UObject'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/external/darling-dmg/darling-dmg] Error 1
make[1]: *** [src/external/darling-dmg/CMakeFiles/darling-dmg.dir/all] Error 2
make: *** [all] Error 2

**Comment by qokelate** [comment]
i use old version to resolved it, 
svn export http://source.icu-project.org/repos/icu/icu/tags/release-53-1/ 
but new problems:

CMake Error at src/external/bzip2/cmake_install.cmake:56 (FILE):
  file INSTALL cannot find "/home/darling/src/external/bzip2/bzcat".
Call Stack (most recent call first):
  src/cmake_install.cmake:70 (INCLUDE)
  cmake_install.cmake:44 (INCLUDE)


make: *** [install] Error 1

**Comment by qokelate** [comment]
i copied /bin/bzcat to bzip2/ and reinstall, 
it say not found /bin/darling, so i copy /usr/local/darling to /bin/
but problems:
i fall apart, ooh, ooh

/usr/local/bin/darling: 25: /usr/local/bin/darling: realpath: not found
stat: cannot stat ‘/bin/darling’: No such file or directory
Cannot open /dev/mach, running 'darling load'.
Loading module... /usr/local/bin/darling: 126: [: 1000: unexpected operator
-p: not found
sudo is /usr/bin/sudo
sudo: a password is required
[sudo] password for sma11case: 
modprobe: FATAL: Module darling-mach not found.
Fail.
/usr/local/bin/darling: 126: [: 1000: unexpected operator
-p: not found
sudo is a tracked alias for /usr/bin/sudo
Matching Defaults entries for sma11case on unknow:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin

User sma11case may run the following commands on unknow:
    (ALL : ALL) ALL
chmod: cannot access ‘/dev/mach’: No such file or directory

**Comment by qokelate** [comment]
i change dash to default bash, sudo dpkg-reconfigure dash  -->NO 
and is last problems?  there ' s no help for it

Cannot open /dev/mach, running 'darling load'.
Loading module... modprobe: FATAL: Module darling-mach not found.
Fail.
chmod: cannot access ‘/dev/mach’: No such file or directory

**Comment by LubosD** [comment]
The last error means you did not install the kernel module.

**Comment by qokelate** [comment]
@LubosD thanks! How to fix it?

**Comment by LubosD** [comment]
Follow the build instructions, there it is described.

**Comment by qokelate** [comment]
I executed commands:

```
# Now we go into src/lkm to build the kernel module
cd ../../src/lkm
make
make install
```

And file was generated at `/lib/modules/3.16.0-71-generic/extra/darling-mach.ko`
but can not run darling too.

```
➜ /tmp >sudo darling shell
Cannot open /dev/mach, running 'darling load'.
Loading module... modprobe: FATAL: Module darling-mach not found.
Fail.
chmod: cannot access ‘/dev/mach’: No such file or directory
➜ /tmp >sudo darling load
Loading module... modprobe: FATAL: Module darling-mach not found.
Fail.
chmod: cannot access ‘/dev/mach’: No such file or directory
➜ /tmp >

```

system info:
```
➜ /tmp >uname -a
Linux unknow 3.16.0-71-generic #92~14.04.1-Ubuntu SMP Thu May 12 23:31:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by LubosD** [comment]
Typically you have to run `depmod` to update the module db.

Please take no offence, but I'm not sure if you're the right person to be trying Darling at this stage, because the skillset needed may be high.

**Comment by qokelate** [comment]
@LubosD Thanks you very much, i just want to try and i think i need learn english at first :(

`insmod '/lib/modules/3.16.0-71-generic/extra/darling-mach.ko'`

```
➜ /tmp >sudo darling shell
Setting up prefix at /home/sma11case/.darling

Getting latest version of org.darlinghq.pkg.OpenSSLCertificates...
Downloading org.darlinghq.pkg.OpenSSLCertificates (version 1)...
/usr/local/bin/darling: line 113: /usr/local/libexec/darling/usr/bin/installer: No such file or directory

```

```
➜ /tmp >sudo darling shell
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

```

**Comment by LubosD** [comment]
This means you have very old GCC (namely its C++ runtime) installed on your system. Also your Darling installation appears to be incomplete.

**Comment by ahyattdev** [comment]
I'm going to go ahead and close this issue. The problem has been identified.
