### ISSUE TITLE
zbsm.zip found as virus

### ISSUE THREAD

**Issue by TimYao18** [darlinghq/darling#1420]
I pulled the project and tried to build it, but before that, the antivirus agent says it found a virus as below screenshot.
I'm unsure if this project is exclusively intended for pure Linux systems, given that I run it using the Windows Subsystem for Linux. If this isn't an issue, please go ahead and close this issue.

**Build Log**
What is the build error?
<img width="331" alt="image" src="https://github.com/darlinghq/darling/assets/15173100/dac95bad-21c6-421a-9751-261a35d5130f">

**System Information**
What system are you building with?

Windows 11 subsystem for Ubuntu 22.04

| Software | Version |
| --- | --- |
| Clang | 10.0.0-4ubuntu1 |
| CMake | 3.27.2 |
| Linux Kernel | 5.15.90.4-microsoft-standard-WSL2 |
| Darling | c9522cc1a43941b4eaea1a0aec3e2b162890fc75 |

**Comment by CuriousTommy** [comment]
Looks like this file comes from the `libarchive` repo. Seem to be part of a test case that test malicious zip files (`test_zip_bomb_small`). So it makes sense why your anti-virus would flag this file.

I would just ignore the file. You can also delete the file if you prefer, but that might cause issue when you try to update the `libarchive` repo.

I'm going to close this issue. Feel free to reopen if you have any questions about this issue.
