### ISSUE TITLE
src/lkm make install error

### ISSUE THREAD

**Issue by jvblue** [darlinghq/darling#143]
Hello, 
i have been successful up to the following steps (and have tried on 3 different builds, so now I am guessing it is user error).
# Now we go into src/lkm to build the kernel module
cd ../../src/lkm
make
make install

When I run the make install i get the following error. 
`make -C /lib/modules/4.2.0-16-generic/build M=/home/jblue/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.2.0-16-generic'
  INSTALL /home/jblue/darling/src/lkm/darling-mach.ko
Can't read private key
  DEPMOD  4.2.0-16-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-16-generic'
`
need help trying to get to next step, but updating keys or headers is not working. 
Thank you

**Comment by LubosD** [comment]
Sorry, this is a Ubuntu-specific problem, I cannot provide support for that. Search for the solution via Google or Ubuntu Forums.
