### ISSUE TITLE
Failed to build Darling from aur/darling-git

### ISSUE THREAD

**Issue by Integral-Tech** [darlinghq/darling#1434]
**Build Log**
What is the build error?
```
Updating recursive submodules
Submodule 'pam_modules' (/build/darling-git/src/darling-pam_modules.git) registered for path 'darling/submodules/pam_modules'
fatal: repository '/build/darling-git/src/darling-pam_modules.git' does not exist
fatal: clone of '/build/darling-git/src/darling-pam_modules.git' into submodule path '/build/darling-git/src/darling/src/external/openpam/darling/submodules/pam_modules' failed
Failed to clone 'darling/submodules/pam_modules'. Retry scheduled
fatal: repository '/build/darling-git/src/darling-pam_modules.git' does not exist
fatal: clone of '/build/darling-git/src/darling-pam_modules.git' into submodule path '/build/darling-git/src/darling/src/external/openpam/darling/submodules/pam_modules' failed
Failed to clone 'darling/submodules/pam_modules' a second time, aborting
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**System Information**
What system are you building with?
Arch Linux, rolling

| Software | Version |
| --- | --- |
| Clang | 16.0.6 |
| CMake | 3.27.7 |
| Linux Kernel | 6.5.6 |
| Darling | efc8aac1d1ad652c8724334311120e7ab101a556 |

**Comment by facekapow** [comment]
Sorry, this is something I broke when I last updated the `PKGBUILD`; Tommy moved the nested submodules in some of our top-level submodules (openpam and IOKitUser) and I thought he'd also changed their submodule names. I'm working on an update for the `PKGBUILD` right now that will also split it into multiple component packages like our Debian and RPM packages; I'll include a fix for this in there.

**Comment by facekapow** [comment]
This should be fixed now.
