### ISSUE TITLE
How can I load specific libraries within darling?

### ISSUE THREAD

**Issue by IgorGee** [darlinghq/darling#144]
So sorry if this is out of scope, but I've been googling this issue for the past hour.

I'm trying to run a script that was extracted from XCode, copySceneKitAssets, whose binaries I obtained from [this](https://github.com/frederik-jacques/DynamicColladaSceneKitPrototype) repository.

However, when I try to run the script, I encounter the following issue:

dyld: Cannot execute binary file: dyld: Library not loaded: @rpath/SceneKit.framework/Versions/A/SceneKit as a dependency of /home/ubuntu/DynamicColladaSceneKitPrototype/_collada_exporter/copySceneKitAssets

I'd greatly appreciate any guidance on this issue.

**Comment by zavorka** [comment]
1. An executable binary is not a script – script is a file readable in a text editor (not necessarily executable).
2. You can use either `install_name_tool -change` to replace the _@rpath_ (relative path) for an absolute path to the SceneKit library, or `install_name_tool -add_rpath` to specify the basedir which should the linker append _@rpath_ to. 

`man install_name_path` can help you with usage, minimal theoretical background explained in this [http://stackoverflow.com/a/9263735/3763673](answer).

**Comment by IgorGee** [comment]
Hey, thanks for the reply!

How would one go about getting "install_name_tool" installed into darling? At the moment, I do not have any of the following tools installed within darling:
- brew
- man
- install_name_tool

**Comment by zavorka** [comment]
install_name_tool is a part of [Command Line Tools for Xcode](http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_OS_X_10.11_for_Xcode_7.3/Command_Line_Tools_OS_X_10.11_for_Xcode_7.3.dmg).

**Comment by ahyattdev** [comment]
@IgorGee Darling now has `man`. 

We are currently working on `ruby`. 

The main this missing to support Homebrew after `ruby` is done is `git`, as it uses it to keep track of the various "taps".  

Of course after we get these, Homebrew will be broken as it pokes around the system expecting all the Xcode stuff to be there (such as it trying to install the command line tools). Maybe we can patch Homebrew to not run those checks on Darling.

**Comment by stek29** [comment]
@IgorGee @zavorka install_name_tool was added to darling.

Also, doesn't darling support DYLD_INJECT_LIBRARIES?..

**Comment by andyneff** [comment]
Has anyone gotten this to work?

(I'm using darling sha 1d7fff2, but am not attached to that version ;)

**Comment by stek29** [comment]
@andyneff I think I've managed to install it, but haven't tried anything after that
