### ISSUE TITLE
PyObjC request

### ISSUE THREAD

**Issue by jrhoades** [darlinghq/darling#145]
It is possible to get PyObjC installed in Darling?  No idea what this entails, but would be amazing if possible!

**Comment by stuaxo** [comment]
First thing would be getting to the point where python launches, then it may be possible to test from there.

**Comment by jrhoades** [comment]
Stuaxo - Python launches fine for me, can do most things -  LubosD  fixed an issue stopping it form accessing the standard C library and that part now works fine.  Just can't use the Python Objective C bridge

**Comment by stuaxo** [comment]
Interesting, probably worth pasting the error here..    I don't know much about ObjectiveC, but certainly quite a lot about python, no idea if it'll be helpful.

**Comment by LubosD** [comment]
Darling doesn't currently build PyObjC, but I'll take a look. I'm a little concerned that it may use internal libobjc APIs (not available in libobjc that Darling uses), but we'll see.

**Comment by bugaevc** [comment]
This may be easier now with obc4.

**Comment by bugaevc** [comment]
So currently I'm getting this when trying to `import objc`:
```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objc/_objc.cpython-37m-darwin.so, 2): Symbol not found: _LACopyACMContext
  Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Expected in: flat namespace
 in /System/Library/Frameworks/Security.framework/Versions/A/Security
```

cc @ahyattdev

**Comment by facekapow** [comment]
See #742.
