### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by MathyV** [darlinghq/darling#146]
I'm trying out Darling but running into issues with resolving hostnames. When I try to use for example curl I get this:

```
Darling [~]$ curl https://www.google.be
Reaping thread 0x7fd5e4b5f700; Free stack at 0x7fd5e4ae1000, 528384 bytes
curl: (6) Could not resolve host: www.google.be
```

If I try to fetch using an IP-address it works, but of course without DNS it's impossible to get things done.

I first noticed that inside the shell I was unable to read /etc/resolv.conf because on my system I use NetworkManager and /etc/resolv.conf is actually a symlink to /var/run/NetworkManager/resolv.conf. Of course this link does not resolve inside the shell so I changed the symlink to ../var/run/NetworkManager/resolv.conf after which I was able to cat the file from inside the shell.

This might be a first issue to fix as this setup is not uncommon on a lot of systems that are using NetworkManager. It might also go further than DNS as other things might also be symlinked using absolute paths instead of relative.

This fix however did not solve my issues. Next thing I tried was to remove the link and put in place an actual file as I thought the link might still be interfering. This did not change the result. I am still unable to resolve hosts.

Things about my setup: I use a non-default DPREFIX and I did not install to the default location but rather to a location inside the build directory using 

```
cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../Toolchain-x86_64.cmake -DCMAKE_INSTALL_PREFIX=../install-64/
```

Next step is to try and attach a gdb (tips on how to do this are welcome) to find out where my issue is but I thought I'd come check here first in case I am missing something obvious :-)

**Comment by LubosD** [comment]
Hi, when you run `ls -l /etc/resolv.conf` and `cat /etc/resolv.conf` in darling shell, what do you get?

**Comment by MathyV** [comment]
```
Darling [~]$ ls -l /etc/resolv.conf
lrwxrwxrwx  1 mathy  mathy  30 Jun 14 22:09 /etc/resolv.conf -> ../system-root/etc/resolv.conf
Darling [~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search home.mvision.be
nameserver 10.0.1.110
nameserver 10.0.1.254
```

As I said, when I just copy the file and not use a link the result is the same.

**Comment by Elronnd** [comment]
FWIW I have the same issue.

    Darling [~]$ ls -l /etc/resolv.conf
    -rw-r--r--  1 elronnd  elronnd  19 Oct  4 03:57 /etc/resolv.conf
    Darling [~]$ cat /etc/resolv.conf
    nameserver 8.8.8.8
    Darling [~]$ curl http://google.com/
    Reaping thread 0x7f28bd8dc700; Free stack at 0x7f28bd85e000, 528384 bytes
    curl: (6) Could not resolve host: google.com
    Darling [~]$ curl 194.122.81.18
    <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
    <TITLE>301 Moved</TITLE></HEAD><BODY>
    <H1>301 Moved</H1>
    The document has moved
    <A HREF="http://www.google.com/">here</A>.
    </BODY></HTML>
    Darling [~]$

**Comment by LubosD** [comment]
Really strange:

```
Darling [~]$ curl www.google.com
Reaping thread 0x7fe25f444700; Free stack at 0x7fe25f3c6000, 528384 bytes
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.cz/?gfe_rd=cr&amp;ei=fTD1V8GtNaOt8wfm2ZO4DA">here</A>.
</BODY></HTML>
Darling [~]$ cat /etc/resolv.conf 
search home.dolezel.info
nameserver 10.10.10.3
nameserver fd00:1::1
```

**Comment by LubosD** [comment]
Ah, it seems it has trouble talking to some name servers. If I switch to 8.8.8.8, I also see the problem.
