### ISSUE TITLE
fail when compile 

### ISSUE THREAD

**Issue by ibnuul** [darlinghq/darling#147]
i had error when compile it, see log here, and how to fix 

cacing@Error-PC:~/darling/src/lkm$ sudo make install
make -C /lib/modules/4.4.0-21-generic/build M=/home/cacing/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-21-generic'
  INSTALL /home/cacing/darling/src/lkm/darling-mach.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-21-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-21-generic'

**Comment by LubosD** [comment]
Sorry, this error is outside Darling and pertains to some kernel build system changes applied by your distribution. Please seek help in your diatro's forums or mailing list.
