### ISSUE TITLE
404 when going to build instructions page

### ISSUE THREAD

**Issue by luveti** [darlinghq/darling#151]
I was looking for the instructions on how to build this and found [this link]( http://www.darlinghq.org/build-instructions) on [this page](http://www.darlinghq.org/source-code/) but it appears to be dead. Can you guys look into this? :)

**Comment by LubosD** [comment]
Thanks for the heads up, it probably got lost when the website was moved from WordPress to Hugo last week.

**Comment by LubosD** [comment]
Fixed.
