### ISSUE TITLE
Module signature verification issues on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by luveti** [darlinghq/darling#152]
When running `sudo make install` in the `darling/src/lkm` directory I get the following error:

```sh
make -C /lib/modules/4.4.0-34-generic/build M=/home/cam/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-34-generic'
  INSTALL /home/cam/darling/src/lkm/darling-mach.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-34-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-34-generic'
```

I looked into this, and according to [this](https://github.com/free5lot/hid-apple-patched/issues/23) issue that another project was having, Ubuntu now uses Linux signed kernel modules. I'm assuming you guys already know about this though! :) As you're building darling on 16.04 on your [teamcity ci](https://teamcity.dolezel.info/viewType.html?buildTypeId=Darling_UbuntuLtsX8664).

Could you point me in the right direction as to how to get this working? I'm going to continue fiddling around with it, and see about making a pull request documentation wise if I figure something out :)

**Comment by luveti** [comment]
It looks like some sort of combination of calling `sudo update-initramfs -u -k all` and using `insmod` instead of `modprobe` when loading the module did the trick. I'll have to verify this tomorrow by doing a fresh install. In case anyone else has this same issue, here is the command I replaced the `modprobe darling-mach` call with:

`sudo insmod /lib/modules/4.4.0-34-generic/extra/darling-mach.ko`

**Comment by LubosD** [comment]
Darling is being built in 16.04, but not the kernel module, because the 16.04 is just a Docker container running on Gentoo :-)

But what you're showing is not a build failure; it just means the module couldn't be signed. It is up to the user how he deals with loading unsigned modules or signing them somehow, as there is no single good way (e.g. I'd feel bad if I started suggesting to disable validation completely).

**Comment by luveti** [comment]
Ahh.. thanks for the heads up! It looks like you actually mention this on the website on the build instructions page. I'll look into just disabling it!

**Comment by HefnySco** [comment]
I guess you can use this:
[https://help.ubuntu.com/community/DKMS](https://help.ubuntu.com/community/DKMS)
