### ISSUE TITLE
aarch64 Darling make error

### ISSUE THREAD

**Issue by kiki9402** [darlinghq/darling#1520]
This error occurred while making make. Is there any solution?

Error code:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/src/coredump/main.cpp:15:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/mach-o/loader.h:35:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/mach/machine.h:68:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/mach/boolean.h:73:
/home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/mach/machine/boolean.h:37:2: error: architecture not supported
#error architecture not supported
 ^
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/src/coredump/main.cpp:15:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/mach-o/loader.h:48:
In file included from /home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/architecture/byte_order.h:38:
/home/pi/Desktop/python_app/darling/src/hosttools/../startup/mldr/include/libkern/OSByteOrder.h:57:10: fatal error: 'libkern/machine/OSByteOrder.h' file not found
#include <libkern/machine/OSByteOrder.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [src/hosttools/CMakeFiles/darling-coredump.dir/build.make:76: src/hosttools/CMakeFiles/darling-coredump.dir/src/coredump/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:14009: src/hosttools/CMakeFiles/darling-coredump.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

pls help
| raspberrypi | arrch64 |

**Comment by CuriousTommy** [comment]
Please don't try to build Darling on ARM64. I'm currently working on adding support for ARM64, but it is still very broken and will take a while to fix.
