### ISSUE TITLE
Intalling Kernel Modules

### ISSUE THREAD

**Issue by mikevelasquez02** [darlinghq/darling#153]
I compiled the version for x86_64, but when I get to the step of installing the kernel modules by using the command "make install" in the folder src/lkm I get the following output with errors:

make -C /lib/modules/4.4.0-34-generic/build M=/home/xxxx/Desktop/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-34-generic'
  INSTALL /home/xxxx/Desktop/darling/src/lkm/darling-mach.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-34-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-34-generic'

and when I tried the command "modprobe darling-mach" i get:

modprobe: FATAL: Module darling-mach not found in directory /lib/modules/4.4.0-34-generic

Could you help me on this

**Comment by LubosD** [comment]
The instructions on the web mention this specifically.

**Comment by DeadNumbers** [comment]
Do you have solution?

**Comment by ahyattdev** [comment]
@LubosD are you referring to the dependencies for listed for Ubuntu 16.04?

I have them (`cmake clang bison flex xz-utils libfuse-dev libxml2-dev libicu-dev libssl-dev libbz2-dev zlib1g-dev libudev-dev linux-headers-generic`) installed and I get this same error. 

A workaround for this issue is manually inserting the kernel module with `insmod src/lkm/darling-mach.ko`.

**Comment by LubosD** [comment]
@ahyattdev No, I mean this: https://www.darlinghq.org/build-instructions/

> Important note for Ubuntu: Recent Ubuntu releases use kernel module signing. It is up to you to find and apply a workaround for loading a module that you have built by e.g. disabling signature verification or by signing the module somehow.
