### ISSUE TITLE
/dev/mach

### ISSUE THREAD

**Issue by rafg3xg** [darlinghq/darling#154]
Hi,

After, download, compile and install darling, `darling shell ` fails:

Cannot open /dev/mach, running 'darling load'.
Loading module... Done.
chmod: cannot access ‘/dev/mach’: No such file or directory

So, when is created the "/dev/mach" file/folder, is a file or is a folder in linux?

I'm trying to run Darling in Opensuse 42.1 Leap

**Comment by LubosD** [comment]
Have you installed the kernel module?

**Comment by rafg3xg** [comment]
Yes, I did. For `make` this the output:

make[1]: Entering directory '/usr/src/linux-4.1.27-27-obj/x86_64/default'
  CC [M]  /home/devone/install/darling/src/lkm/traps.o
/home/devone/install/darling/src/lkm/traps.c: In function ‘mach_msg_overwrite_trap’:
/home/devone/install/darling/src/lkm/traps.c:509:3: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
   debug_msg("!!! Cannot copy %d bytes from %p\n",
   ^
  CC [M]  /home/devone/install/darling/src/lkm/ipc_space.o
  CC [M]  /home/devone/install/darling/src/lkm/ipc_port.o
  CC [M]  /home/devone/install/darling/src/lkm/ipc_right.o
  CC [M]  /home/devone/install/darling/src/lkm/ipc_server.o
  CC [M]  /home/devone/install/darling/src/lkm/darling_task.o
  CC [M]  /home/devone/install/darling/src/lkm/ipc_msg.o
  CC [M]  /home/devone/install/darling/src/lkm/servers/mach_host.o
  CC [M]  /home/devone/install/darling/src/lkm/servers/clock.o
In file included from /home/devone/install/darling/src/lkm/../../platform-include/mach/mach_types.h:78:0,
                 from /home/devone/install/darling/src/lkm/servers/clock.c:21:
/home/devone/install/darling/src/lkm/../../kernel-include/sys/cdefs.h:141:0: warning: "__unused" redefined
 #define __unused __attribute__((unused))
 ^
In file included from /home/devone/install/darling/src/lkm/servers/clock.c:20:0:
/home/devone/install/darling/src/lkm/servers/../mig_includes_pre.h:29:0: note: this is the location of the previous definition
 # define __unused
 ^
  CC [M]  /home/devone/install/darling/src/lkm/servers/task.o
  CC [M]  /home/devone/install/darling/src/lkm/primitives/semaphore.o
/home/devone/install/darling/src/lkm/primitives/semaphore.c: In function ‘mach_semaphore_timedwait’:
/home/devone/install/darling/src/lkm/primitives/semaphore.c:254:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  debug_msg("down_timeout(jiffies=%d, pid=%d)\n", jiffies, current->pid);
  ^
  CC [M]  /home/devone/install/darling/src/lkm/mig/clockServer.o
In file included from /home/devone/install/darling/src/lkm/mig/clockServer.c:12:0:
/home/devone/install/darling/src/lkm/mig/clockServer.h:29:2: warning: ‘weak_import’ attribute directive ignored [-Wattributes]
  extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
  ^
  CC [M]  /home/devone/install/darling/src/lkm/mig/mach_hostServer.o
In file included from /home/devone/install/darling/src/lkm/mig/mach_hostServer.c:12:0:
/home/devone/install/darling/src/lkm/mig/mach_hostServer.h:29:2: warning: ‘weak_import’ attribute directive ignored [-Wattributes]
  extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
  ^
  CC [M]  /home/devone/install/darling/src/lkm/mig/taskServer.o
In file included from /home/devone/install/darling/src/lkm/mig/taskServer.c:12:0:
/home/devone/install/darling/src/lkm/mig/taskServer.h:29:2: warning: ‘weak_import’ attribute directive ignored [-Wattributes]
  extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
  ^
  CC [M]  /home/devone/install/darling/src/lkm/mig/thread_actServer.o
In file included from /home/devone/install/darling/src/lkm/mig/thread_actServer.c:12:0:
/home/devone/install/darling/src/lkm/mig/thread_actServer.h:29:2: warning: ‘weak_import’ attribute directive ignored [-Wattributes]
  extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
  ^
  CC [M]  /home/devone/install/darling/src/lkm/servers/thread_act.o
  CC [M]  /home/devone/install/darling/src/lkm/mig/duct.o
  CC [M]  /home/devone/install/darling/src/lkm/proc_entry.o
  CC [M]  /home/devone/install/darling/src/lkm/bsd_ioctl.o
In file included from /usr/src/linux-4.1.27-27/include/linux/list.h:8:0,
                 from /usr/src/linux-4.1.27-27/include/linux/preempt.h:10,
                 from /usr/src/linux-4.1.27-27/include/linux/spinlock.h:50,
                 from /usr/src/linux-4.1.27-27/include/linux/mmzone.h:7,
                 from /usr/src/linux-4.1.27-27/include/linux/gfp.h:5,
                 from /usr/src/linux-4.1.27-27/include/linux/slab.h:14,
                 from /home/devone/install/darling/src/lkm/debug.h:23,
                 from /home/devone/install/darling/src/lkm/bsd_ioctl.c:21:
/usr/src/linux-4.1.27-27/include/linux/kernel.h:30:0: warning: "SIZE_MAX" redefined
 #define SIZE_MAX (~(size_t)0)
 ^
In file included from /home/devone/install/darling/src/lkm/api.h:22:0,
                 from /home/devone/install/darling/src/lkm/bsd_ioctl.h:22,
                 from /home/devone/install/darling/src/lkm/bsd_ioctl.c:20:
/home/devone/install/darling/src/lkm/../libc/include/stdint.h:208:0: note: this is the location of the previous definition
 #define SIZE_MAX   UINT64_MAX
 ^
  CC [M]  /home/devone/install/darling/src/lkm/psynch/psynch_mutex.o
  CC [M]  /home/devone/install/darling/src/lkm/psynch/pthread_kill.o
  CC [M]  /home/devone/install/darling/src/lkm/psynch/psynch_cv.o
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:47:1: warning: declaration does not declare anything
 };
 ^
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:47:1: warning: no semicolon at end of struct or union
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c: In function ‘psynch_cvwait_trap’:
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:64:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 2 has type ‘uint64_t’ [-Wformat=]
  debug_msg("psynch_cvwait(): cv=%p, mutex=%p\n",
  ^
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:64:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 3 has type ‘uint64_t’ [-Wformat=]
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c: In function ‘psynch_cvbroad_trap’:
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:110:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 2 has type ‘uint64_t’ [-Wformat=]
  debug_msg("psynch_cvbroad_trap(): cv=%p\n", args.cv);
  ^
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c: In function ‘psynch_cvsignal_trap’:
/home/devone/install/darling/src/lkm/psynch/psynch_cv.c:149:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 2 has type ‘uint64_t’ [-Wformat=]
  debug_msg("psynch_cvsignal_trap(): cv=%p\n", args.cv);
  ^
  LD [M]  /home/devone/install/darling/src/lkm/darling-mach.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/devone/install/darling/src/lkm/darling-mach.mod.o
  LD [M]  /home/devone/install/darling/src/lkm/darling-mach.ko
make[1]: Leaving directory '/usr/src/linux-4.1.27-27-obj/x86_64/default

**Comment by rafg3xg** [comment]
And this the output for `make install`:

make -C /lib/modules/4.1.27-27-default/build M=/home/devone/install/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-4.1.27-27-obj/x86_64/default'
  INSTALL /home/devone/install/darling/src/lkm/darling-mach.ko
  DEPMOD  4.1.27-27-default
make[1]: Leaving directory '/usr/src/linux-4.1.27-27-obj/x86_64/default'

**Comment by Elronnd** [comment]
Did you `modprobe darling-mach` after installing it?

**Comment by fervi** [comment]
On Debian (i don't know why) i must "initialize" darling-mach by something like this|
insmod /lib/modules/4.5.0-2-amd64/extra/darling-mach.ko

Because modprobe darling-mach doesn't work for me

**Comment by LubosD** [comment]
@fervi Try running `depmod` to update the module db.

**Comment by fervi** [comment]
@LubosD Now works :) Thanks
