### ISSUE TITLE
Build issue on Arch Linux x86_64

### ISSUE THREAD

**Issue by LeRieur** [darlinghq/darling#157]
It doesn't seem to be related to the packaging: https://aur.archlinux.org/packages/darling-git https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=darling-git

Here's the output of makepkg:
https://0bin.net/paste/2Xv8WyeK8VkIcwoN#228SBG-bwAb+1F93Qm4qN43c1CZhL5P8ZvB59kkK4Qj

**Comment by LubosD** [comment]
You lack /usr/bin/arch, which could cause some problems. The final crash, however, is yet another compiler incompatibility. I'll take a look at it.

**Comment by LubosD** [comment]
Umm, checking it again, it looks more like a bug either in your version of LLVM or Binutils. Downgrading binutils could help. See https://groups.google.com/forum/#!topic/llvm-dev/vgVAb2B9DVg

**Comment by LeRieur** [comment]
Downgrading binutils to 2.26.1 fixed it. Thanks.

/usr/bin/arch is not part of util-linux since 2.23. Even without it, it seems to build fine.

**Comment by Maxqia** [comment]
:P I tried to get /usr/bin/arch included in Arch Linux, didn't go so well

**Comment by tpimh** [comment]
I finally managed to compile it on Arch Linux.

I used the following workarounds:

1. Creating executable `/usr/bin/arch` with the following content:

    #!/bin/sh
    echo x86_64
2. Downgrading binutils as mentioned above
3. `sed -i 's/-Werror//' src/external/libkqueue/CMakeLists.txt` (build breaks because of expansion-to-defined warning)
4. `cd src/libunwind; curl -qsL http://github.com/JuliaLang/libosxunwind/pull/7.patch | patch -p1` (build breaks because of use of COMPILE_TIME_ASSERT)

**Comment by LubosD** [comment]
I'll see what I can do about the `/usr/bin/arch` usage, but I'm surprised Arch Linux doesn't have it - Debian (Testing) does, ~amd64 Gentoo too...

**Comment by Scimmia22** [comment]
/usr/bin/arch is not enabled by default by coreutils upstream. Assuming it's present on all Linux systems is a bad idea.

**Comment by Maxqia** [comment]
Reopened issue here : https://bugs.archlinux.org/task/49890 ...

**Comment by tpimh** [comment]
Maybe `uname -p` is an option?

**Comment by LubosD** [comment]
@tpimh I'd day `uname -m` could work. I'll try to replace it.

**Comment by Maxqia** [comment]
Yeah, looking at the code for coreutils, that should be it.

**Comment by stek29** [comment]
@LubosD `/usr/bin/uname` doesn't exist on Debian, but it still builds without any errors somehow *
```
$ ls /usr/bin/uname
ls: cannot access /usr/bin/uname: No such file or directory
$ which uname
/bin/uname
```

**Comment by tpimh** [comment]
Do you still have to downgrade binutils to build it on ArchLinux? If yes, I request reopening. Or is this behavior fixed in newer versions of binutils?

**Comment by LubosD** [comment]
Yes, this problem should be fixed in the next binutils release. See https://sourceware.org/bugzilla/show_bug.cgi?id=20648

**Comment by tpimh** [comment]
Okay, thank you. So we will just wait for next binutils release to land in Arch Linux.
