### ISSUE TITLE
python reports sys.platform as "unknown"

### ISSUE THREAD

**Issue by Elronnd** [darlinghq/darling#158]
Sample output:

    Darling [/usr/bin]$ ./python2.7
    Python 2.7.10 (default, Oct  3 2016, 20:42:44) 
    [GCC 4.2.1 Compatible Clang 3.8.1 (tags/RELEASE_381/final)] on unknown
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.name
    'posix'
    >>> 

Oughtn't it to report "darwin"?

**Comment by PwnicornDev** [comment]
No. This is on OS 10.7.5:
```
$ python2.7
Python 2.7.1 (r271:86832, Jun 16 2011, 16:59:05) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.name
'posix'
>>> 
```

**Comment by Elronnd** [comment]
Ohh, okay.  `sys.platform` reports 'unknown', though, which seems to be an issue.

**Comment by LubosD** [comment]
Thank you guys for your analysis.
