### ISSUE TITLE
No way to uninstall a package that doesn't work

### ISSUE THREAD

**Issue by Elronnd** [darlinghq/darling#159]
I installed a couple of pkgs that turned out to segfault when I tried to use them.  That's fine, and I understand.  However, when I tried to uninstall them, they errored, I'm guessing because they were run as part of a pre-uninstall script.  For example:

    Darling [~/Downloads]$ uninstaller org.rudix.pkg.zsh
    Segmentation fault: 11
    Darling [~/Downloads]$ 

Any way to fix this?

**Comment by LubosD** [comment]
I can confirm both a problem with zsh and with uninstalling it. Thanks for your report.

**Comment by Elronnd** [comment]
It's not just with zsh, it's with a bunch of packages.  Zsh was just one of them.

**Comment by LubosD** [comment]
I've fixed the uninstaller's crash - hopefully. It seems it worked for many other packages by mere luck. You may need to force updating your prefix by running `touch $(which darling)`. The next step is to fix zsh itself.

**Comment by LubosD** [comment]
The next problem is unimplemented syscall 111 (sigsuspend), should be quite easy to fix.

**Comment by LubosD** [comment]
zsh works (or at least seems to). Thanks again for your report.
