### ISSUE TITLE
hdiutil complains about missing libraries

### ISSUE THREAD

**Issue by Elronnd** [darlinghq/darling#160]
When I run `hdiutil`, it tells me that it can't find libdmg.so.  I see a libdmg.so in /darling-prefix/lib/, though, so I'm not sure what the issue is.  I tried setting LD_LIBRARY_PATH to /darling-prefix/lib, but that accomplished nothing.

**Comment by LubosD** [comment]
This change should fix it I hope.

**Comment by Elronnd** [comment]
It **runs** now, but it doesn't work:

    Darling [~/Downloads]$ hdiutil attach Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg                                                                
    Cannot access Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg
    Darling [~/Downloads]$ ls Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg             
    Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg
    Darling [~/Downloads]$

**Comment by LubosD** [comment]
Good catch, it doesn't accept relative paths. Try using an absolute path until I fix the bug.
