### ISSUE TITLE
building kernel module failed

### ISSUE THREAD

**Issue by 0x5e** [darlinghq/darling#163]
Hello, I'm trying to build darling on docker with `debian:latest` image, installed dependencies as http://www.darlinghq.org/build-instructions/ said, failed when build the kernel module.

```
root@b0bdedabf6b5:/darling/src/lkm# make
make -C /lib/modules/4.4.20-moby/build M=/darling/src/lkm modules
make[1]: *** /lib/modules/4.4.20-moby/build: No such file or directory.  Stop.
Makefile:34: recipe for target 'default' failed
make: *** [default] Error 2
root@b0bdedabf6b5:/darling/src/lkm# uname -r
4.4.20-moby
root@b0bdedabf6b5:/darling/src/lkm# ls /lib/modules/
3.16.0-4-amd64
root@b0bdedabf6b5:/darling/src/lkm#
```

There is no `/lib/modules/4.4.20-moby` directory, only `/lib/modules/3.16.0-4-amd64` exist.

**Comment by Elronnd** [comment]
Can you try a `apt-get update && apt-get upgrade`, as root?

**Comment by LubosD** [comment]
The kernel module has to be built and loaded outside of Docker, because dockerized systems don't have their own kernel. They're basically just a chroot on steroids. The container itself then has to be run with `--privileged`.

**Comment by LubosD** [comment]
So if you're building Darling in Docker to avoid possible instabilities of Darling's kernel module, then your only choice is a VM.

**Comment by 0x5e** [comment]
okay, thanks
