### ISSUE TITLE
Implement CFNotificationCenter

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#165]
Implement CFNotificationCenter, needed for building Security.framework.

**Comment by 0x5e** [comment]
If Security.framework works, maybe codesign/security/actool can be used to re-sign iOS application?

**Comment by LubosD** [comment]
Precisely. The problem is, for Security.framework to build, we need to reimplement CoreCrypto. Which isn't hard, it's just a lot of work.

**Comment by leofantast** [comment]
must be wonderful work if supporting codesign：）

**Comment by LubosD** [comment]
Fixed, we use Apple's CF now.
