### ISSUE TITLE
Compilation of helloworld.c fails

### ISSUE THREAD

**Issue by luigiScarso** [darlinghq/darling#170]
I cannot compile helloworld.c as explained in 
https://www.darlinghq.org/introduction/

Darling [~]# /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang helloworld.c -o helloworld
error: unable to execute command: posix_spawn failed: No such file or directory
# uname -a

Linux xxx 4.4.0-41-generic #61-Ubuntu SMP Tue Sep 27 17:27:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# lsmod|grep darl

darling_mach           81920  1
# ls -al /dev/mach

crw-rw-rw- 1 root root 10, 50 Oct 11 13:52 /dev/mach

**Comment by LubosD** [comment]
Try adding a `-v` argument, clang will then print what it's trying to spawn.

**Comment by luigiScarso** [comment]
Darling [/tmp]# clang -v   -c helloworld.c -o helloworld
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin12.0.0
Thread model: posix
 "" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name helloworld.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 253.9 -v -dwarf-column-info -coverage-file /tmp/helloworld -resource-dir ../lib/clang/7.0.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fdebug-compilation-dir /tmp -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o helloworld -x c helloworld.c
error: unable to execute command: posix_spawn failed: No such file or directory

**Comment by luigiScarso** [comment]
Fixed. It was only a problem of a symbolic link wrongly resolved:
under Linux I have mounted xcode in /data/darling/mnt, 
under Darling I have to make a symlink under / , ie
Darling [~]# cd /
Darling [~]# ln -s system-root/data 

I have seen the missed symlink running 
Darling [~]# /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c99 -E helloworld.c

I think it's my personal setup, not a Darling error.
