### ISSUE TITLE
Sandboxed home dir?

### ISSUE THREAD

**Issue by fervi** [darlinghq/darling#171]
Well, I wanted to install Perl on Darling (can you add it? :P). I found on some installer, fired him, and although did not work correctly, wrote their things for example: .bashrc

I wonder if the user's home directory should not be separated?

**Comment by LubosD** [comment]
It may be a good idea, but on the other hand, this is quite easy to do by hand. Just export a different HOME environment variable.

**Comment by kamillys** [comment]
Just leaving a note about https://github.com/darlinghq/darling/pull/185
I've added option to rebuild your Darling home (darling clean-home) and you can set DARLING_SANDBOXED_HOME to 1 in env so this will create "sandboxed environment".

You still have access to your real home in /system-root/home/USER if you need copy files.

**Comment by bugaevc** [comment]
We now have a separate home dir for the container. You can access the Linux home directory at its full path (`/Volumes/SystemRoot/home/$USER`) or using the `~/LinuxHome` symlink we provide.
