### ISSUE TITLE
tar and installer are broken due to [de]compression issues

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#175]
**When trying to install the CLT**
```

installer: Package name is SU_TITLE
installer: Installing selected choice SU_TITLE
installer: Installing package com.apple.pkg.CLTools_Executables version 8.1.0.0.1.1476494586 (463786 KB)
installer: Extracting files
lzma decompression error
```

**When trying to decompress that same file manually**

```
$ tar xf /Volumes/Command_Line_Tools_macOS_10.12_for_Xcode_8.1/Command\ Line\ Tools\ \(macOS\ Sierra\ version\ 10.12\).pkg 
/usr/local/bin/dyld64: symbol lookup error: /usr/local/lib//darling/libarchive.so: undefined symbol: inflateInit_
```

**When trying to create an archive from any file with tar**

```
$ tar -c emptyfile 
Segmentation fault: 11 (core dumped)
```

**Comment by LubosD** [comment]
Thanks a lot for your reports. Using LZMA compressing in PKGs is relatively new, so it hasn't been tested yet. I have fixed LZMA support and can successfully install the pkg and compile a test program with it:

```
export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/
/Library/Developer/CommandLineTools/usr/bin/clang /tmp/helloworld.c -o /tmp/helloworld
```

FYI - pkg files cannot be extracted with tar. I have fixed tar's missing references to compression libraries. I have also fixed the crash - bsdtar passes a NULL path to lstat() and the prefix handling didn't bail out in this case.

**Comment by ahyattdev** [comment]
Awesome fixes, thanks!

```
installer: Package name is SU_TITLE
installer: Installing selected choice SU_TITLE
installer: Installing package com.apple.pkg.CLTools_Executables version 8.1.0.0.1.1476494586 (463786 KB)
installer: Extracting files
**Cannot run script: No such file or directory**
installer: Installing package com.apple.pkg.DevSDK_OSX1012 version 8.1.0.0.1.1476494586 (258930 KB)
installer: Extracting files
installer: Installation complete
```

Is this error significant?

Also, how does macOS handle directing /usr/bin/clang to the CommandLineTools one?

Is there any better solution than adding `/Library/Developer/CommandLineTools/usr/bin` to `PATH`?
