### ISSUE TITLE
Kernel module incompatible with CONFIG_PREEMPT_RT patch set

### ISSUE THREAD

**Issue by J5lx** [darlinghq/darling#179]
The title says it all. When building the module for a kernel patched with the [CONFIG_PREEMPT_RT patch set](https://wiki.linuxfoundation.org/realtime), the build fails. The build log can be found at <https://gist.github.com/J5lx/68c196b73920a90a38e9cc01c9acc2ec>. I see that the realtime patch set isn't entirely "official" right now, but nonetheless I'd appreciate it if there was support for it in the kernel module of Darling.

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
