### ISSUE TITLE
Cannot compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by PaulBGD** [darlinghq/darling#180]
I've followed the instructions, installed all the dependencies, and cannot seem to build for x86-64. Here's the log:

```
paul@paulpc:~/Documents/Coding$ cd darling
paul@paulpc:~/Documents/Coding/darling$ mkdir -p build/x86-64
paul@paulpc:~/Documents/Coding/darling$ cd build/x86-64
paul@paulpc:~/Documents/Coding/darling/build/x86-64$ cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../Toolchain-x86_64.cmake
-- The C compiler identification is Clang 3.8.0
CMake Error at /usr/share/cmake-3.5/Modules/CMakeFindBinUtils.cmake:74 (message):
  Could not find install_name_tool, please check your installation.
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineCCompiler.cmake:174 (include)
  CMakeLists.txt:1 (project)
```

Then CMakeOutput.log:

```
The target system is: Linux -  - x86-64
The host system is: Linux - 4.4.0-45-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/clang 
Build flags: 
Id flags: 

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is Clang, found in "/home/paul/Documents/Coding/darling/build/x86-64/CMakeFiles/3.5.1/CompilerIdC/a.out"
```

**Comment by GlenDC** [comment]
This problem seems to originate from one of @LubosD's latest commits: c40ea91056f777efaff3bebe510461d9d808dc89

For now you could get past this issue (in case you are working on something else), by removing the lines that that commit have added to the toolchain cmake files.

**Comment by GlenDC** [comment]
I also don't seem to find any documentation about `CMAKE_PLATFORM_HAS_INSTALLNAME`. I do see one forum topic about a ugly hack to make ninja work with cmake, using this environment variable: https://cmake.org/Bug/view.php?id=13934

**Comment by LubosD** [comment]
Sorry fellas, commit reverted. I'll try putting an if() around this hack.
