### ISSUE TITLE
[ruby] use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#183]
Can anyone help solve this compilation error with Ruby?

The submodule commit reference in this repo is not the one with the issue, as building Ruby is commented out in that. Make sure you have the latest version of darlinghq/ruby in order to get this error. 

```
[ 81%] Building C object src/external/ruby/CMakeFiles/libruby.dir/time.o
/home/andrewhyatt/git/darling/src/external/ruby/time.c:1999:23: error: use of undeclared identifier 'CLOCK_REALTIME'
    if (clock_gettime(CLOCK_REALTIME, &ts) == -1) {
                      ^
1 error generated.
```

**Comment by LubosD** [comment]
OS X lacks some common APIs, such as clock_gettime. I didn't try my change out, but hope this helps: https://github.com/darlinghq/darling-ruby/commit/37ad02dc031e0c7d7f38bd5b9df4b5bda44bfd3e
