### ISSUE TITLE
DebugSymbols.framework is not installed

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#184]
The commit that adds `DebugSymbols`: 136c34d

How do all the folders in `/System/Library/Frameworks` get there?

How can we add `/System/Library/PrivateFrameworks`?

How can we get `DebugSymbols` to install as a framework to `/System/Library/PrivateFrameworks`?

**Comment by LubosD** [comment]
The folders in `/System/Library/Frameworks` get there by being installed into `/usr/local/libexec/darling` (varies by installation prefix). There might be a problem with PrivateFrameworks, I'm not sure libdyld will recognize what you add into dylib.conf for this location. Patching libdyld should be easy though.
