### ISSUE TITLE
miniruby built by darling-ruby crashes: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#190]
The syslog is flooded with hundreds of messages from `darling-mach` during a second. 

https://gist.github.com/ahyattdev/e29274cfb41a02cc58ba856685a97a21

Is this a known issue due to something being unimplemented (many of the messages involve IPC), or is this a new issue?

If this is a known issue, then count Ruby in as one of the things being held back by it.

Steps to reproduce:

1. Be have the latest commits from `darling-ruby`
2. Build `darling`
3. With the working directory as the build folder, run `darling src/external/ruby/miniruby`

**Comment by LubosD** [comment]
The output in dmesg is normal. The kernel module is highly experimental, hence it prints out lots of debug info.

**Comment by LubosD** [comment]
I'm building it now and there's a little problem: the dependency on dtrace. Linux distros don't usually have dtrace (among others Debian and Gentoo), hence I typically just create fake probes by #define-ing them away.

**Comment by LubosD** [comment]
And this is the reason for the SIGSEGV:

```
$ readelf -d ./src/external/ruby/miniruby

Dynamic section at offset 0x2fa1e8 contains 42 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsystem.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libobjc.so.4.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdyld.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++abi.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libkeymgr.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_info.so]
 0x0000000000000001 (NEEDED)             Shared library: [libresolv-darwin.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_notify.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdispatch.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_malloc.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblaunch.so]
 0x0000000000000001 (NEEDED)             Shared library: [libremovefile.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_copyfile.so]
 0x0000000000000001 (NEEDED)             Shared library: [libunwind.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_coreservices.so]
 0x0000000000000001 (NEEDED)             Shared library: [libCommonCrypto.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_c.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_m.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_kernel.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsystem_duct.so]
```

Darling executables may never ever directly link Linux system libraries such as libpthread.so. This is because you're building against OS X headers. In this case, Linux libpthread's sigaction() smashes the stack in ruby_signal().

I've comitted a fix into the darling-ruby repository. In this case, libsystem provides all you need (pthread and dl* stuff).

**Comment by ahyattdev** [comment]
Fixed, thank you
