### ISSUE TITLE
[groff] undefined symbol: __dso_handle

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#195]
The following error occurs when trying to run `troff` or `pic`, both C++ programs. 

`dyld: Cannot execute binary file: Failed to load native library: troff: undefined symbol: __dso_handle`

This is strange, because the symbol is present in `libstdcxx.so` and `troff` links to it. 

```
$ readelf -s /usr/local/lib/darling/libstdcxx.so | grep __dso_handle
        1218: 0000000000303538     8 OBJECT  LOCAL  DEFAULT   17 __dso_handle
```

It appears that is is linked to `libstdcxx.so`. How everything is not found is not the error, because all the other darling binaries say the same thing. 

```
$ ldd build/x86_64/src/external/groff/troff 
	linux-vdso.so.1 =>  (0x00007ffd81b58000)
	libsystem.so => not found
	libstdcxx.so => not found
	libdyld.so => not found
	libkeymgr.so => not found
	libsystem_info.so => not found
	libresolv-darwin.so => not found
	libsystem_notify.so => not found
	libsystem_quarantine.so => not found
	libdispatch.so.0 => not found
	libsystem_malloc.so => not found
	libobjc.so.4.6 => not found
	liblaunch.so => not found
	libremovefile.so => not found
	libsystem_copyfile.so => not found
	libsystem_coreservices.so => not found
	libCommonCrypto.so => not found
	libc++abi.so.1 => not found
	libunwind.so => not found
	libsystem_c.so => not found
	libsystem_kernel.so => not found
	libsystem_duct.so => not found
	libsystem_m.so => not found
```

**Comment by LubosD** [comment]
You need to include dso_handle.c into your binary, just search the project source tree. The thing is this symbol should be present in all objects, normally this is included in the part of the runtime that gets statically included into every C++ app. In Darling, this has to be done manually.

**Comment by ahyattdev** [comment]
This worked! Thanks.
