### ISSUE TITLE
New Darling prefix design

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#197]
* Replace `darling` script with a C binary
  * Detects if the prefix is already "booted" and if not, initiates boot.
* Make OpenSSL certificates part of Darling (instead of installed package).
* Build prefixes on overlayfs rather than on copying files.
* Implement `prelaunchd` as the init process for prefixes. `prelaunchd` creates a mount and pid namespace (consider setting up a UID namespace - do we need that?).
  * When we have working launchd, prelaunchd will exec() launchd after its work is done. Until that is done, prelaunchd will end in a loop reaping child processes.
* Abandon `dylib.conf`.
  * Use symlinks? Or generate dummy Mach-O files that just link e.g. `@darling/libFoundation.so`?

**Comment by ahyattdev** [comment]
I agree that the `darling` shell script needs to be replaced. It is taking on more than what was originally intended. 

Not having to copy files in `/usr/local/libexec/darling` to `~/.darling` because of an overlay would be great. It would solve changes to the `libexec` files not being synced to the prefix. 

Would using symlinks instead of `dylib.conf` work since the prefix is `chroot`ed?

Broad question, but why not generate real Mach-Os?

**Comment by LubosD** [comment]
> Would using symlinks instead of dylib.conf work since the prefix is chrooted?

It would work, because VirtualPrefix.cpp in libdyld has special handling for symlinks. But generating semi-real Mach-O files (referring internally to an ELF file with actual implementation) somehow feels better.

> Broad question, but why not generate real Mach-Os?

Using Mach-O for Darling's libraries and executables would eliminate many hacks, but there is a catch. We sometimes need to link our frameworks against system Linux libraries. Currently, this is the case only for AudioUnit I think, but in future this will also apply to CoreGraphics, AppKit etc.

In these cases, [Apple's ld](https://opensource.apple.com/source/ld64/) (which we would need to build) would need to somehow link to ELF files. Either we could add a simple ELF parser into ld64 or feed it dummy Mach-Os containing the symbols from the real ELF file.

It is probably viable (and likely even preferable in long term), but for now I took the easy way out by not building Mach-Os.

**Comment by ahyattdev** [comment]
Having dummy Mach-Os but real symbols in them would allow us to use Linux libraries and also allow a compiler running in the prefix to link to the Mach-Os. This solution allows using Darling for development without the macOS SDK.

**Comment by X0rg** [comment]
About `darling` script rewriting in C, should we try to load `darling-mach` kernel module from binary itself?
If yes, should we do that by `system()` calls, or by using `init_module()`?

**Comment by LubosD** [comment]
I think I will have a first experimental version of the new `darling` binary in a few days. The `darling` binary will need CAP_SYS_ADMIN capability to "boot" a prefix.

In order to load modules, it would also need CAP_SYS_MODULE. A lot better than using `sudo`, because none of my systems has `sudo` ;-) We should probably also install an udev rule to `chgrp darling /dev/mach` and recommend users to create such a group.

**Comment by bugaevc** [comment]
> Having dummy Mach-Os but real symbols in them would allow us to use Linux libraries and also allow a compiler running in the prefix to link to the Mach-Os. This solution allows using Darling for development without the macOS SDK.

This sounds absolutely great!

> Implement prelaunchd as the init process for prefixes. prelaunchd creates a mount and pid namespace (consider setting up a UID namespace - do we need that?).

If we're using mount namespaces, do we really need the hackish fakechroot/VirtualPrefix implementation inside the syscall emulation? The kernel is much better at doing this -- why not just mount `$DPREFIX` to `/` and the real root to `/system-root` (nosuid)?

Next, instead of setting up a new namespace every time, `darling` is called, it should check for an existing one and join it if possible.

**Comment by LubosD** [comment]
@bugaevc 

> If we're using mount namespaces, do we really need the hackish fakechroot/VirtualPrefix implementation in syscall emulation? The kernel is much better at doing this -- why not just mount $DPREFIX to / and the real root to /system-root (nosuid)?

This would be fantastic, but there is a small problem. Darling itself (e.g. dyld) and all of its dependencies (e.g. native libc) must exist and be loadable inside the chroot. Before you say "we can avoid these native dependencies", you need to realize they are eventually needed e.g. for ALSA or X11 access.

The simplest solution I can think of right now is to interpret `/etc/ld.so.conf` from the main system and generate it inside our chroot with `/system-root` with `/system-root` prepended.

> Next, instead of setting up a new namespace every time darling is called, it should check for an existing one and join it if possible.

Yes, this is indeed the idea.

**Comment by bugaevc** [comment]
@LubosD 
> This would be fantastic, but there is a small problem. Darling itself (e.g. dyld) and all of its dependencies (e.g. native libc) must exist and be loadable inside the chroot. Before you say "we can avoid these native dependencies", you need to realize they are eventually needed e.g. for ALSA or X11 access.

I know that, and, in fact, I have a working prototype in [my no-virtual-prefix branch](https://github.com/bugaevc/darling/tree/no-virtual-prefix) (not ready yet!, expect rebases) -- basically, I pass `LD_LIBRARY_PATH` and symlink `/lib` & `/lib64`.

> The simplest solution I can think of right now is to interpret /etc/ld.so.conf from the main system and generate it inside our chroot with /system-root with /system-root prepended.

That's exactly what I've been thinking of.

> Yes, this is indeed the idea.

Yeah, I missed that part initially when reading the code -- but since then it's been implemented by me and merged by you :wink:

**Comment by LubosD** [comment]
Another thing to do: when setting up the prefix, either `cat /etc/resolv.conf` or just set 8.8.8.8/8.8.4.4 in it (like Docker). The current symlinking doesn't work on systems where `/etc/resolv.conf` is already a symlink.

**Comment by bugaevc** [comment]
> Another thing to do: when setting up the prefix, either cat /etc/resolv.conf or just set 8.8.8.8/8.8.4.4 in it (like Docker). The current symlinking doesn't work on systems where /etc/resolv.conf is already a symlink.

(I'm developing Darling on a VM with Linux Mint Serena installed). I found that putting in 8.8.8.8 makes it work (on vanilla old executable) even though `/etc/resolv.conf` remains a symlink.

```
Darling [~]$ ls -l /etc/resolv.conf 
lrwxrwxrwx  1 sergey  sergey  30  2 Jan 10:04 /etc/resolv.conf -> ../system-root/etc/resolv.conf
Darling [~]$ ls -l /system-root/etc/resolv.conf 
lrwxrwxrwx  1 root  root  29  4 Dec 21:41 /system-root/etc/resolv.conf -> ../run/resolvconf/resolv.conf
Darling [~]$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
#nameserver 127.0.1.1
nameserver 8.8.8.8
search RTRouter
Darling [~]$ curl example.com
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
...
```

**Comment by LubosD** [comment]
FYI I've created a branch for experimenting with Mach-Os used for Darling libs:
https://github.com/darlinghq/darling/tree/using-machos-experiment
For now, it just builds Apple's linker and nothing more.

**Comment by bugaevc** [comment]
If I want to make a feature/design proposal, should I open an issue like this one?

**Comment by bugaevc** [comment]
> experimenting with Mach-Os used for Darling libs

What about building Darling executables as Mach-Os? If everything (except `darling` and `dyld*`) is built as Mach-O, we can use `binfmt_misc` and get rid of `fakeArgv0`, bang and `sys_execve` complications.

**Comment by LubosD** [comment]
I think we're done :-)

**Comment by bugaevc** [comment]
Yay! 😄
