### ISSUE TITLE
Prevent the linker from picking up linux libraries when building ssh

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#202]
```
libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fc9e4ab5000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fc9e489a000)
libz.so => /usr/lib/x86_64-linux-gnu/libz.so (0x00007fc9e467f000)
```

This ends up finding the native libraries
`target_link_libraries(ssh crypto z resolv)`

[Link to where this is done](https://github.com/darlinghq/darling-openssh/blob/4fccc184d708d9f74688abcda950218b1121efc3/CMakeLists.txt#L240)

**Comment by LubosD** [comment]
You need to use names of libraries as specified in respective CMakeLists.txt of the libraries you want to link:
- resolv -> resolv-darwin (if it really needs the resolver APIs e.g. for resolving SRV records)
- crypto -> crypto098
- z - this one should work as is

Whenever CMake sees a known library name in target_link_libraries(), it'll substitute it with path to the locally built library and add an implicit build dependency.

**Comment by ahyattdev** [comment]
Thanks. 

After linking to those libraries, it works!

I was able to SSH into a machine on my LAN from Darling.

**Comment by LubosD** [comment]
Great job!
