### ISSUE TITLE
Build polluted by __DARWIN_NO_LONG_LONG macro

### ISSUE THREAD

**Issue by X0rg** [darlinghq/darling#204]
I have enormously warnings when building Darling:
```
darling/src/libc/include/stdlib.h:172:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if !__DARWIN_NO_LONG_LONG
     ^
darling/platform-include/sys/cdefs.h:630:32: note: expanded from macro '__DARWIN_NO_LONG_LONG'
#define __DARWIN_NO_LONG_LONG   (defined(__STRICT_ANSI__) \
                                 ^
In file included from XXX:
darling/src/libc/include/stdlib.h:172:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
darling/platform-include/sys/cdefs.h:632:9: note: expanded from macro '__DARWIN_NO_LONG_LONG'
                                && !defined(__GNUG__))
```
Build on Arch Linux x86_64:
- Linux 4.4.34 (LTS)
- binutils 2.26.1
- clang 3.9.0
- gcc 6.2.1

I don't see this behavior on TC Build.
Is this warning normal?

**Comment by LubosD** [comment]
We should wait until this gets fixed by Apple. macOS 10.12 still contains the same problematic macro.

The warning was added into clang just recently.

**Comment by LubosD** [comment]
We can of course add `-Wno-expansion-to-defined` into global CFLAGS.

**Comment by X0rg** [comment]
Or I can do a patch.
```
#define	__DARWIN_NO_LONG_LONG	(defined(__STRICT_ANSI__) \
				&& (__STDC_VERSION__-0 < 199901L) \
				&& !defined(__GNUG__))
```
Using something like that solve this issue:
```
#if defined(__STRICT_ANSI__) && (__STDC_VERSION__-0 < 199901L) && !defined(__GNUG__)
#define __DARWIN_NO_LONG_LONG 1
#endif
```
There is WIP in my local tree to fix some warnings.

**Comment by LubosD** [comment]
It is preferable to hide warning rather than fix them. This is because the header files will need to be overwritten with new versions from Apple over time.
