### ISSUE TITLE
CFBase.h fatal error: MacTypes.h file not found

### ISSUE THREAD

**Issue by rbarros** [darlinghq/darling#213]
darling/build/x86-64/src/external/corefoundation/Headers/CoreFoundation/CFBase.h:52:10: fatal error:  'MacTypes.h' file not found
#include <MacTypes.h>

**Comment by ahyattdev** [comment]
This is likely my fault, I have been upgrading CF headers in order to get Security.framework to build recently (more of it, at least). 

What target is being built while this error occurs?

Chances are, the target does not have `${CMAKE_SOURCE_DIR}/platform-include` included.

**Comment by ahyattdev** [comment]
I just ran through a complete build and didn't get this issue. Pull the latest commits and do a fresh build. `CFBase.h` is a generated file.
