### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by yangchuans** [darlinghq/darling#216]
when i am run make ...........at master branch.................

```
[ 71%] Generating id.h
/bin/sh: 1: ruby: not found
src/external/ruby/CMakeFiles/ruby-genfiles.dir/build.make:64: recipe for target 'src/external/ruby/id.h' failed
make[2]: *** [src/external/ruby/id.h] Error 127
CMakeFiles/Makefile2:15467: recipe for target 'src/external/ruby/CMakeFiles/ruby-genfiles.dir/all' failed
make[1]: *** [src/external/ruby/CMakeFiles/ruby-genfiles.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
How to solve it?

**Comment by LubosD** [comment]
Install Ruby.

**Comment by yangchuans** [comment]
Thank you！
But when i am go into src/lkm to build the kernel module。。。。
```
yangchuan@yangchuan:~/soft/darling/src/lkm$ make install
make -C /lib/modules/4.4.0-57-generic/build M=/home/yangchuan/soft/darling/src/lkm modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-57-generic'
  INSTALL /home/yangchuan/soft/darling/src/lkm/darling-mach.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-57-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-57-generic'
```
Can you help me？

**Comment by LubosD** [comment]
See https://www.darlinghq.org/build-instructions/

"Important note for Ubuntu: Recent Ubuntu releases use kernel module 
signing. It is up to you to find and apply a workaround for loading a 
module that you have built by e.g. disabling signature verification or 
by signing the module somehow."

**Comment by ahyattdev** [comment]
I just revamped dkms.sh with 07cf79

See the [second paragraph of this linked section](https://github.com/darlinghq/darling#building-and-loading-the-kernel-module-x86-64-and-i386). 

dmks.sh is sufficient for building the kernel module on Ubuntu now.
