### ISSUE TITLE
No more TC Build since 1 month

### ISSUE THREAD

**Issue by X0rg** [darlinghq/darling#224]
Hello,

I don't known if it's a normal behavior, but the [last build](https://teamcity.dolezel.info/project.html?projectId=Darling) on TC was 27 days ago.
I'm unable to build Darling from scratch due to numerous errors. I think the build is broken.

**Comment by bugaevc** [comment]
Builds just fine for me. Please provide some details about your system and the errors you're getting.

**Comment by X0rg** [comment]
I try to build Darling on Arch x86_64 (GCC 6.2.1, Clang 3.9.1, binutils 2.26.1).
One example of error:
```
/tmp/makepkg/darling-git/src/darling/src/external/security/OSX/libsecurity_apple_csp/lib/MD2Object.cpp:57:22: error: return type of out-of-line definition of 'MD2Object::digestSizeInBytes' differs from
      that in the declaration
CSSM_SIZE MD2Object::digestSizeInBytes() const
~~~~~~~~~            ^
/tmp/makepkg/darling-git/src/darling/src/external/security/OSX/libsecurity_apple_csp/lib/MD2Object.h:41:17: note: previous declaration is here
        virtual size_t digestSizeInBytes() const;
                ~~~~~~ ^
1 error generated.
make[2]: *** [src/external/security/OSX/libsecurity_apple_csp/CMakeFiles/security_apple_csp.dir/build.make:807: src/external/security/OSX/libsecurity_apple_csp/CMakeFiles/security_apple_csp.dir/lib/MD2Object.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:16127: src/external/security/OSX/libsecurity_apple_csp/CMakeFiles/security_apple_csp.dir/all] Error 2
```
There are errors when building Ruby, too.

I was asking for TC build to avoid to annoy you with Arch specific build errors.

**Comment by LubosD** [comment]
Every time I update Docker, I have to restart all the agents and I typically forget... but anyway, the local build works fine to me.

My guess is maybe your submodules didn't get updated?

```
git submodule init
git submodule update
```

**Comment by bugaevc** [comment]
> I was asking for TC build to avoid to annoy you with Arch specific build errors.

I believe the intention is for Darling to successfully build on all major Linux distros (definitely including Arch, as build instructions for Arch are in the readme).

**Comment by LubosD** [comment]
There are some i386 build problems (fixing them now) and some complaints from `awk` when installing:
```
-- Up-to-date: /usr/local/libexec/darling/etc/ld.so.conf.d
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
awk: line 1: regular expression compile failed (bad class -- [], [^] or [)
^[^
awk: line 1: syntax error at or near ]
```

**Comment by X0rg** [comment]
Thank you LubosD. As you can see ATM, build is broken.

I misspoke: I want to proove that build is broken, not only on Arch.

**Comment by LubosD** [comment]
@X0rg But only if you build the audio stuff (fixing that now).

**Comment by bugaevc** [comment]
> some complaints from awk when installing

That is my code in [setup-ld-so](https://github.com/darlinghq/darling/blob/master/src/setup-ld-so.sh) failing, reporting an incorrect regexp, as you can see -- but it should not be run at all when building for i386 (`DARLING_NO_EXECUTABLES`).

**Comment by LubosD** [comment]
All builds are now stable.

**Comment by X0rg** [comment]
I can confirm it builds, thanks!

**Comment by bugaevc** [comment]
> That is my code in setup-ld-so failing

Fixed in https://github.com/darlinghq/darling/commit/dce27e3d6017e4a5bf5865616142ab230e6082f0
