### ISSUE TITLE
(Internal) branch renaming: darling -> master, master -> apple

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#225]
Some Git repositories have the "darling" as the main branch and the upstream code is in the "master" branch. This is confusing (my bad).

Branch names in submodules should correspond to the main repository, original upstream code can be in an "apple" branch (optional).

**Comment by bugaevc** [comment]
If the upstream is not always Apple, maybe name the branch just "upstream"?

**Comment by LubosD** [comment]
OK.

**Comment by LubosD** [comment]
Should be done, at least for the repositories we actually use at the moment.

**Comment by bugaevc** [comment]
But you haven't updated [.gitmodules](https://github.com/darlinghq/darling/blob/master/.gitmodules), why is that?

**Comment by LubosD** [comment]
Ah, right. Somehow I though the branch specification is only used when the submodule is added and only commit numbers refer to the submodule afterwards.

**Comment by ahyattdev** [comment]
Many repos have `darling`, `master`, and `upstream` branches. Apparently I "created" the `darling` branch on them, according to GitHub. See the GitHub activity list for this group.

**Comment by bugaevc** [comment]
You probably still have "darling" branch checked out on external repos, and that's why git creates the remote "darling" branch when you push. This can be fixed with e.g.:
```bash
cd src/external
for repo in *; do
    cd $repo
    git checkout master
    git merge darling
    git push
    git branch -d darling
    cd ..
done
```
Then remove extra branches from the GH interface.
