### ISSUE TITLE
Python: os.getcwd() fails

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#228]
To reproduce:

```
Darling [~]$ python -c "import os; os.getcwd()"                                                 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 13] Permission denied
```

`getcwd()` is actually defined in the `posix` module (on POSIX systems) and re-exported by `os`.

[Here's](https://github.com/darlinghq/darling-python/blob/master/2.7/Python-2.7.10/Modules/posixmodule.c#L2148) the definition in `posixmodule.c`, it wraps `getcwd` function defined [here](https://github.com/darlinghq/darling-python/blob/master/2.7/Python-2.7.10/Python/getcwd.c#L27), which wraps `getwd` defined seemingly [here](https://github.com/darlinghq/darling/blob/master/src/libc/compat-43/FreeBSD/getwd.c), which wraps `getcwd` defined [here](https://github.com/darlinghq/darling/blob/master/src/libc/gen/FreeBSD/getcwd.c), which calls `__getcwd` via one more wrapper.

`__getcwd()` uses `open(".")` and then `fcntl(fd, F_GETPATH, b)`, which gets translated into `readlink("/proc/self/{fd}")` by the syscall emulation layer. This is known to work (e.g. `pwd` command uses this if `PWD` environment variable isn't set).

In case of Python's `getcwd()`, `strace` shows the following (immediately following the previous command, if any, and right before outputting the error):

```
pipe([5, 6])                            = 0
fcntl(5, F_GETFL)                       = 0 (flags O_RDONLY)
pipe2([7, 8], O_CLOEXEC)                = 0
clone(child_stack=0, flags=SIGCHLD)     = 76
close(8)                                = 0
read(7, /Volumes/SystemRoot/usr/bin/strace: Process 76 attached
 <unfinished ...>
[pid    76] close(4)                    = 0
[pid    76] open("/dev/mach", O_RDWR)   = 4
[pid    76] ioctl(4, _IOC(0, 0x10, 0x00, 0x00), 0) = 1
[pid    76] close(7)                    = 0
[pid    76] close(5)                    = 0
[pid    76] dup2(6, 1)                  = 1
[pid    76] write(8, "\1\0\0\0", 4)     = 4
[pid    75] <... read resumed> "\1\0\0\0", 4) = 4
[pid    75] close(7)                    = 0
[pid    75] close(6)                    = 0
[pid    75] fstat(5, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid    75] read(5,  <unfinished ...>
[pid    76] exit_group(127)             = ?
[pid    75] <... read resumed> "", 4096) = 0
```

This doesn't look like trying to get CWD at all.

**Comment by bugaevc** [comment]
No! It's using the "Version for really old UNIX systems -- use pipe from pwd", which tries to `popen` `/bin/pwd` -- and fails to.

**Comment by bugaevc** [comment]
This is a bug in Darling's [`posix_spawn`](https://github.com/darlinghq/darling/blob/master/src/kernel/emulation/linux/process/posix_spawn.c):

```C

switch (act->psfaa_type)
{
    case PSFA_CLOSE:
        ret = sys_close(act->psfaa_filedes);
        if (ret != 0)
            goto fail;
        break;
    case PSFA_DUP2:
        ret = sys_dup2(act->psfaa_filedes, act->psfaa_openargs.psfao_oflag);
        if (ret != 0)
            goto fail;
        break;
```

Unlike for `close()`, a non-zero return code from `dup2()` doesn't mean an error occurred, because `dup2` returns the new `fd`.

**Comment by LubosD** [comment]
And I'll fix the Python build to define `HAVE_GETWD`.

**Comment by LubosD** [comment]
Wrong - it is defined, but libc's getcwd is overridden by the poor man's implementation inside Python.

**Comment by bugaevc** [comment]
How does it work on macOS?

**Comment by LubosD** [comment]
On macOS getcwd.c is not in the Python build, so it just uses getcwd from libc...
