### ISSUE TITLE
Add clock_gettime APIs

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#230]
macOS 10.12 finally adds clock_gettime APIs. Add them.

* Update time.h in libc (re-apply f7eca1050c4e97c12d5e2d5e947d701859f32ac1).
* Add gen/clock_gettime.c. This needs some [extra functions](https://opensource.apple.com/source/xnu/xnu-3789.1.32/libsyscall/wrappers/mach_continuous_time.c) in kernel/libsyscall, which depend on commpage features -> rewrite these funcs to make Linux syscalls?

**Comment by facekapow** [comment]
We do have this now.
