### ISSUE TITLE
CMAKE_LIBRARY_ARCHITECTURE is empty

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#231]
I may be misunderstanding everything big time, but it seems to me that:

* On Debian-based x64 systems, Darling libs are supposed to go under `/usr/local/lib/x86_64-linux-gnu/darling`
* In `Toolchain-x86_64.cmake`, `CMAKE_INSTALL_LIBDIR` is set to `"lib/${CMAKE_LIBRARY_ARCHITECTURE}"`
* In `darling-config.h.in`, `LIB_PATH` is `#define`d to be `"${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/darling"`, i.e. `/usr/local/lib/x86_64-linux-gnu/darling`
* We pass `SYSTEM_ROOT LIB_PATH`, i.e. `/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling` to the container in `$LD_LIBRARY_PATH`.

However, from what I see in practice, libs end up in `/usr/local/lib/darling` and `$LD_LIBRARY_PATH` gets set to `/Volumes/SystemRoot/usr/local/lib//darling` (notice the double slash; confirmed by @ahyattdev in #223).

**This works fine for x86_64, but the libs get overwritten if you try to compile for i386, because it uses the same path.** Basically, i386 build is broken (builds, but doesn't work), at least for me.

The reason for this seems to be that `CMAKE_LIBRARY_ARCHITECTURE` is sometimes not set/empty, as mentioned elsewhere on the internet (ex. TimothyGu/libilbc#10, [this one about Fedora](https://lists.freedesktop.org/archives/beignet/2015-March/005366.html)). Thus we get `/usr/local/lib//darling`.

I'm not proficient enough in CMake to suggest a solution (maybe just hardcode `x86_64-linux-gnu`/`i386-linux-gnu` instead of `CMAKE_LIBRARY_ARCHITECTURE`?).

Also, we should pass both `/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling` and `/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling` in `$LD_LIBRARY_PATH` -- how do we do this without hardcoding i386 (we only build it for x64)?

**Comment by LubosD** [comment]
> how do we do this without hardcoding i386 (we only build it for x64)?

Having both in doesn't do any harm...

This should all become a non-issue after the dylib work is done, although there we'll have another problem with i386: fat Mach-Os. Both 64 and 32bit builds should be done in one step in this case, which is hard on Debian where somepackage-dev:amd64 conflicts with somepackage-dev:i386 for dependant libraries.

**Comment by bugaevc** [comment]
>Having both in doesn't do any harm...

Of course. What I mean is that we only build `darling.c` on x64, and I currently use `setenv("LD_LIBRARY_PATH", SYSTEM_ROOT LIB_PATH, 1)` -- to pass both, I'd need to hardcode it like this:

`setenv("LD_LIBRARY_PATH", SYSTEM_ROOT LIB_PATH ":" SYSTEM_ROOT INSTALL_PREFIX "/lib/i386-linux-gnu/darling", 1)`.

> This should all become a non-issue after the dylib work is done

Yes*, but let's do something about it in the meantime :) E.g. hardcode arch in `Toolchain-*.cmake`

\* Is the plan to put libs into their proper place under `/usr/local/libexec/darling/`, or what?

**Comment by LubosD** [comment]
> Is the plan to put libs into their proper place under /usr/local/libexec/darling/, or what?

Yes, basically, at the end we should have a complete macOS "sysroot" under that directory.

**Comment by bugaevc** [comment]
Great, I like it. Should we also move everything else to there, e.g. `/usr/local/share/darling` stuff?

**Comment by LubosD** [comment]
> Should we also move everything else to there, e.g. /usr/local/share/darling stuff?

Absolutely.

**Comment by bugaevc** [comment]
> Both 64 and 32bit builds should be done in one step in this case, which is hard on Debian where somepackage-dev:amd64 conflicts with somepackage-dev:i386 for dependant libraries.

Aren't `dev` packages just the headers/source? If so, why do they have arch-specific versions?

Side questions: is macOS/Darwin self-hosting? Should Darling be? How do they build fat binaries on macOS?

**Comment by LubosD** [comment]
> Aren't dev packages just the headers/source? If so, why do they have arch-specific versions?

Yep, but on Debian they also made the choice that -dev packages include a symlink to the library version you should link to. In other words, the main package installs libsomelibrary.so.56.1, but only the -dev package provides libsomelibrary.so symlink, without which you/the linker doesn't know what to link against. See [here](https://packages.debian.org/jessie/amd64/libavcodec-dev/filelist) for an example, the do the same for libpulse as well.

Stupid? Yes, IMO.

I've been playing with some "cool" ideas such as hosting 32bit Mach-O-anything in 64bit Linux processes, which is not as impossible as it may seem:

1. mmap() has MMAP_32BIT, which would make sure that nothing in the "macOS realm" would end up being mapped above the 32-bit memory space.
2. Transition between 32/64 call ABIs between Mach-O and ELF could be handled in the respective proxy libraries.

> Side questions: is macOS/Darwin self-hosting?

Certainly.

> Should Darling be?

I don't think it has to.

> How do they build fat binaries on macOS?

This is directly handled by `clang` - you pass `-arch i386` and `-arch x86-64` and the compilation is done twice internally. I will definitely attempt to make this work.
