### ISSUE TITLE
Cannot open darling shell since new design

### ISSUE THREAD

**Issue by X0rg** [darlinghq/darling#237]
Unfortunately, I can't try the new darling binary: the libc is not found.

```
$ darling shell
Setting up a new Darling prefix at ~/.darling
/Volumes/SystemRoot/usr/local/bin/dyld: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
```
But I can run Bash by using `dyld`:
```
$ dyld64 /usr/local/libexec/darling/bin/bash 
Darling [~]$ uname -a
Linux Arch64-VM 4.4.39-1-lts #1 SMP Thu Dec 15 21:10:18 CET 2016 x86_64 GNU/Linux
```
This is the created prefix:
```
$ tree .darling .darling.workdir 
.darling
├── Applications
├── private
│   └── var
│       └── db
├── usr
│   └── local
│       └── share
└── Volumes
.darling.workdir
└── work [error opening dir]

9 directories, 0 files
```
`darling_mach` is loaded, permissions on /dev/mach are 666.

Is it related to `LD_LIBRARY_PATH`?

**Comment by bugaevc** [comment]
> Is it related to LD_LIBRARY_PATH?

No. `LD_LIBRARY_PATH` is for Darling libs (in `/usr/local/lib`), like `libdyld` and `libsystem`. `libc.so.6` is a native library located somewhere like `/usr/lib64/libc.so.6` -- visible at `/Volumes/SystemRoot/usr/lib64/libc.so.6` inside the container. We use paths from host's `/etc/ld.so.conf.d` (prepending `/Volumes/SystemRoot`) to look up native libraries. That folder doesn't necessarily include `/usr/lib64` proper, but `/lib64` is a built-in search path in `ld-linux`, and we symlink `/lib64 -> /Volumes/SystemRoot/lib64`, so it should work.

Is this related to the unusual layout on Arch that you've mentioned?

**Comment by bugaevc** [comment]
> This is the created prefix

The created prefix is just several empty dirs to allow the user to write there. We use overlayfs now, all the real files are in `/usr/local/libexec/darling`.

You may want to try to spawn busybox shell inside the container to examine the fs layout (see #223).

**Comment by bugaevc** [comment]
> Is this related to the unusual layout on Arch that you've mentioned?

I mean, it should all work in case of Arch too. `libc` is at `/usr/lib/libc.so.6`, `/lib -> usr/lib`, and we do `/lib -> /Volumes/SystemRoot/lib`

**Comment by X0rg** [comment]
> You may want to try to spawn busybox shell inside the container to examine the fs layout (see #223).

Like that?
```
pidChild = spawnChild(pidInit, SYSTEM_ROOT DYLD_PATH,
				(const char *[3]) {SYSTEM_ROOT DYLD_PATH, "/Volumes/SystemRoot/bin/busybox", (const char *[2]) {"sh", NULL} });
```
It's worst:
```
$ darling shell
Cannot exec the target program: Bad address
```

**Comment by bugaevc** [comment]
> Like that?

Well, not like _that_, obviously. I'm surprised it even compiles ;)

`pidChild = spawnChild(pidInit, "/Volumes/SystemRoot/bin/busybox", (const char *[2]) {"sh", NULL}`

**Comment by X0rg** [comment]
Ha, sorry. This is the tree (with locale directory truncated):
```
SYSTEM_ROOT:  /Volumes/SystemRoot
LIB_PATH:  ???
LD_LIBRARY_PATH: /Volumes/SystemRoot/usr/local/lib/darling:/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling
```
The
```
/usr
|-- bin
|-- include
|   `-- lzma
|-- lib
|   `-- groff
|       |-- groffer
|       `-- site-tmac
|-- libexec
|-- local
|   `-- share
|       `-- darling -> /Volumes/SystemRoot/usr/local/share/darling
|-- sbin
`-- share
    |-- doc
    |   |-- groff
    |   |   `-- 1.19.2
    |   |       |-- examples
    |   |       |   `-- mom
    |   |       |-- html
    |   |       |   `-- mom
    |   |       `-- pdf
    |   `-- xz
    |       |-- examples
    |       `-- examples_old
    |-- file
    |   `-- magic
    |-- groff
    |   |-- 1.19.2
    |   |   |-- font
    |   |   |   |-- devascii
    |   |   |   |-- devdvi
    |   |   |   |   `-- generate
    |   |   |   |-- devhtml
    |   |   |   |-- devlatin1
    |   |   |   |-- devlbp
    |   |   |   |-- devlj4
    |   |   |   |   `-- generate
    |   |   |   |-- devps
    |   |   |   |   `-- generate
    |   |   |   `-- devutf8
    |   |   `-- tmac
    |   |       |-- mdoc
    |   |       `-- mm
    |   |-- site-font
    |   `-- site-tmac
    |-- info
    |-- locale
    |   |-- UTF-8
    |       `-- LC_MESSAGES
    `-- man
        |-- man1
        |-- man2
        |-- man3
        |-- man5
        |-- man6
        |-- man7
        `-- man8

495 directories
```
A library directory seems missing...

**Comment by bugaevc** [comment]
I only see `/usr` in your tree, no `/lib` or `/Volumes` or whatever.

For the record, we symlink `/lib -> /Voluems/SystemRoot/lib` [here](https://github.com/darlinghq/darling/blob/master/CMakeLists.txt#L100).

**Comment by X0rg** [comment]
Yes, it was only on /usr. :x
This is full tree (`/Volumes/SystemRoot` excluded): https://gist.githubusercontent.com/X0rg/c921bb4aaba68051798e962a5499f54a/raw/ec873b7d56becc76577cb0f9664a8c639c01229b/gistfile1.txt
So /lib and /lib64 both link to Arch /usr/lib.

**Comment by bugaevc** [comment]
Okay, so I installed Arch and looked into it (corrected build instructions, btw https://github.com/darlinghq/darling/commit/8ba9573d605caaf18f20930c021b05637efb779d). `ld-linux` on   Arch doesn't even try to look under `/lib` (it's too usr-merge-avare, I'd say). The quick fix for now is to add it to `LD_LIBRARY_PATH`.

This won't work in the long term because we want `dyld` (or `mldr`) to be setuid/setcap. We won't need `LD_LIBRARY_PATH` for the Darling own libraries soon with @LubosD's Mach-O work, but it won't help us with `/lib` on Arch.

But we can use `DT_RUNPATH` to build the path into Darling binaries (will it work for dependencies of their dependencies though?)

**Comment by bugaevc** [comment]
Alternatively, we can just `echo /Volumes/SystemRoot/usr/lib > ./etc/ld.so.conf.d/arch-libs.conf` in `setup-ld-so.sh` on Arch.

**Comment by X0rg** [comment]
It works out-the-box now, thanks you.

**Comment by X0rg** [comment]
> corrected build instructions, btw 8ba9573

That's because you forgot to install [base-devel](https://www.archlinux.org/groups/x86_64/base-devel/) group. In fact, on Arch, when you need to build something, you need to install base-devel packages, so on this line, make, flex and bison are redundant.

In fact, I don't manually build darling, I maintain the [darling-git](https://aur.archlinux.org/packages/darling-git/) package on AUR.

**Comment by bugaevc** [comment]
> That's because you forgot to install base-devel group. In fact, on Arch, when you need to build something, you need to install base-devel packages, so on this line, make, flex and bison are redundant.

Should I change it to
`sudo pacman -S base-devel cmake clang icu fuse linux-headers`?

> In fact, I don't manually build darling, I maintain the darling-git package on AUR.

Awesome, but I, naturally, have to build it manually in order to test changes before they get into `master` ;)

Why does it depend on `python`, `ruby`, `libunwind`, `git`, and everything else not in the list above?

> Due to Arch doesn't use /usr/libexec, I have modified this path. The new prefix path is /usr/share/darling/prefix (/usr/libexec/darling previously).
Tell me if you are occurring troubles (tested on my comptuer, seems not).

`darling/libexec` is pretty much hardcoded now, do you replace `libexec/darling` everywhere in the source code or what?

**Comment by X0rg** [comment]
> Should I change it to
> `sudo pacman -S base-devel cmake clang icu fuse linux-headers?`

It can be done like that. I think base-devel on Arch is like build-essential on Debian: an implicit dependency. It doesn't matter.

> Why does it depend on `python`, `ruby`, `libunwind`, `git`, and everything else not in the list above?

`git` is a make dependency: obviously we need it to clone the repo. Others were added due to `namcap` complainations. If you think it's a false positive and they are not required to run darling properly, I can remove these dependencies.

> `darling/libexec` is pretty much hardcoded now, do you replace `libexec/darling` everywhere in the source code or what?

This is not longer the case since it breaks the new Darling binary. That's what I got:
```
$ darling shell
Setting up a new Darling prefix at ~/.darling
Cannot exec the target program: No such file or directory
```
Actually, it uses /usr/libexec. I'm not interested to investigate (it was replaced everywhere). Following lines were used to perform that:
```
find . -name CMakeLists.txt -exec sed -i 's|libexec/darling|${CMAKE_INSTALL_PREFIX}/share/darling/prefix|g' {} \;
find . -exec sed -i 's|${CMAKE_INSTALL_PREFIX}/libexec/darling|${CMAKE_INSTALL_PREFIX}/share/darling/prefix|g' {} \;
```
