### ISSUE TITLE
Common team communication channel

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#241]
I'm looking for something where we can leave messages to one another about what we're about to do, how something's progressing or to simply discuss stuff.

IRC is not a good choice IMO, because one can't read messages he's missed while he was offline.

What would be convenient for you? Jabber conference? Hangouts/Skype?

**Comment by bugaevc** [comment]
Hope I'm invited :blush:

I mostly use Telegram (it's awesome!), but Hangouts/Skype/Slack is okay. (Or maybe start a mailing list?)

**Comment by LubosD** [comment]
You for sure are invited. There is a mailing list (Google Group), but that's not good for real-time communication.
Let's see what @ahyattdev says.

**Comment by ahyattdev** [comment]
IRC would be fine if we each had a ZNC running all the time, but thats not possible for everyone. 

Discord could work for this. 

I have never used them, but have heard good things about Slack and Telegram. I'm willing to use whatever platform works for you guys.

**Comment by LubosD** [comment]
I'm just trying out Slack and it looks nice, I've sent out invitations.

**Comment by Tatsh** [comment]
Can I get an invite? I'd like to get into contributing and I would like to know where one can start.

**Comment by stek29** [comment]
@Tatsh I'm pretty sure you'd be invited if you start contributing, not the opposite.

**Comment by bugaevc** [comment]
@Tatsh: I suggest you use our IRC channel (see https://darlinghq.org/contact)
