### ISSUE TITLE
undefined symbol error when building i386 variant of darling on ArchLinux

### ISSUE THREAD

**Issue by maz-1** [darlinghq/darling#246]
I have downgraded binutils to 2.26 and use PKGBUILD from https://aur.archlinux.org/packages/darling-git/, and get following error message:
https://gist.github.com/maz-1/89b100c33520755605439ba9ad3f23b1

I modified the PKGBUILD to build x86-64 part first, and the x86-64 part builds just OK, this error only happens on i386 build of darling

**Comment by bugaevc** [comment]
Yes, one of my recent fixes broke the i386 build. Expect this to be fixed soon.

**Comment by LubosD** [comment]
This will also go away with the Mach-O migration. These aliases are only needed because `size_t` on Linux is `unsigned int`, whereas `unsigned long` on macOS. Same size, different name mangling.

**Comment by bugaevc** [comment]
Oh, awesome, then I'm not going to bother to do a pull request and try to understand & explain why the change breaks it and why the fix is the right one.

> If it compiles, it is good; if it boots up, it is perfect. -- Linus Torvalds
