### ISSUE TITLE
hdiutil : error while loading shared libraries: libdmg.so

### ISSUE THREAD

**Issue by Aqib** [darlinghq/darling#247]
Followed all the instructions as per the readme. Now I am trying to set up xcode using darling shell but I am getting this error :

> $ hdiutil attach /home/local/NEXTEDUCATION/mdaqib/mobiport/xcode/xcode_5.0.2.dmg 
> hdiutil: error while loading shared libraries: libdmg.so: cannot open shared object file: No such file or directory

**Comment by bugaevc** [comment]
Yes, hdiutil doesn't work as is since #222 I'm working on getting it to work again; meanwhile, you should be able to run it like `DPREFIX=/ PATH=/Volumes/SystemRoot/bin /usr/bin/hdiutil attach whatever`.

**Comment by Aqib** [comment]
Thanks, will try that.

**Comment by bugaevc** [comment]
What distro are you on?

**Comment by Aqib** [comment]
Linux version 4.4.0-59-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

**Comment by bugaevc** [comment]
> Yes, hdiutil doesn't work as is since #222. I'm working on getting it to work again; meanwhile, you should be able to run it like DPREFIX=/ PATH=/Volumes/SystemRoot/bin /usr/bin/hdiutil attach whatever.

:white_check_mark: fixed, now it should work out of the box once again

> Linux version 4.4.0-59-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

Do you have `/etc/ld.so.conf.d/libc.conf` file containing "`/usr/local/lib`"?

**Comment by Aqib** [comment]
Yes I do

**Comment by bugaevc** [comment]
Check that:
* `/usr/local/lib/libdmg.so` exists
* `/usr/local/libexec/darling/etc/ld.so.conf.d/libc.conf` contains `/Volumes/SystemRoot/usr/local/lib`
* `strings /usr/local/libexec/darling/etc/ld.so.cache | grep libdmg` outputs:
```
libdmg.so
/Volumes/SystemRoot/usr/local/lib/libdmg.so
```

If all of that is true, please get (and show me) an `strace` log -- e.g. by running `/Volumes/SystemRoot/usr/bin/strace hdiutil attach /home/local/NEXTEDUCATION/mdaqib/mobiport/xcode/xcode_5.0.2.dmg`

**Comment by Aqib** [comment]
Thanks a lot.

> strings /usr/local/libexec/darling/etc/ld.so.cache | grep libdmg outputs:
libdmg.so
/Volumes/SystemRoot/usr/local/lib/libdmg.so

This one failes. I am not getting any output whatsoever on running that.

**Comment by bugaevc** [comment]
This probably means that the file was not properly set up during the Darling installation. Try reinstalling Darling (e.g. `sudo rm -rf /usr/local/libexec/darling`, `sudo make install`)

**Comment by Aqib** [comment]
Okay, will try doing that and get back in case of problems. Thanks.

**Comment by Aqib** [comment]
Reinstalled darling and was able to get the proper output in the last case this time. However I am still getting that same error from hdiutil, posting the strace log here:

> execve("/usr/bin/hdiutil", ["hdiutil", "attach", "/home/local/NEXTEDUCATION/mdaqib"...], [/* 64 vars */]) = 0
brk(NULL)                               = 0x2180000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcf316d8000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/usr/local/lib/tls/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/tls/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/tls/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/tls", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib", 0x7fff476050a0)  = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/tls/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/tls/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/tls/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/tls", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/tls/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/tls/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/tls/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/tls", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/lib/tls/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/tls/x86_64", 0x7fff476050a0) = -1 ENOENT (No such file or directory)
open("/lib/tls/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/tls", 0x7fff476050a0)        = -1 ENOENT (No such file or directory)
open("/lib/x86_64/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64", 0x7fff476050a0)     = -1 ENOENT (No such file or directory)
open("/lib/libfuse.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=176437, ...}) = 0
mmap(NULL, 176437, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fcf316ac000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/lib/x86_64-linux-gnu/libfuse.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260o\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=243832, ...}) = 0
mmap(NULL, 2339104, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fcf31279000
mprotect(0x7fcf312a3000, 2093056, PROT_NONE) = 0
mmap(0x7fcf314a2000, 77824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7fcf314a2000
close(3)                                = 0
open("/Volumes/SystemRoot/usr/local/lib/x86_64-linux-gnu/darling/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/Volumes/SystemRoot/usr/local/lib/i386-linux-gnu/darling/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/tls/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/tls/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/tls/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/tls", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
open("/usr/lib/x86_64-linux-gnu/tls/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/tls/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/tls/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/tls", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/lib/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls", 0x7fff47605070)    = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7fff47605070) = -1 ENOENT (No such file or directory)
open("/usr/lib/libdmg.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
writev(2, [{"hdiutil", 7}, {": ", 2}, {"error while loading shared libra"..., 36}, {": ", 2}, {"libdmg.so", 9}, {": ", 2}, {"cannot open shared object file", 30}, {": ", 2}, {"No such file or directory", 25}, {"\n", 1}], 10hdiutil: error while loading shared libraries: libdmg.so: cannot open shared object file: No such file or directory
) = 116
exit_group(127)                         = ?
+++ exited with 127 +++

**Comment by bugaevc** [comment]
You've likely reinstalled Darling without shutting down the container first. Please always make sure to run `darling shutdown` before modifying the Darling installation.

**Comment by bugaevc** [comment]
...and if you're lucky, you can get it to work now by just restarting the container:
```
host$ darling shutdown
host$ darling shell
Darling [~]$ hdiutil attach whatever.dmg
```

**Comment by frank-trampe** [comment]
@Aqib, did you run ldconfig after adding the /etc/ld.so.conf.d entry?

**Comment by Aqib** [comment]
@bugaevc 
Thanks a lot, it ran fine just by restarting.

@frank-trampe 
Yes, I did

**Comment by bugaevc** [comment]
Just to clarify why this is needed: we build Darling containers/prefixes on [overlayfs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt), which doesn't support modifying the underlying filesystems (both `DPREFIX` and `/usr/local/libexec/darling/` subtrees) while mounted:

```
Offline changes, when the overlay is not mounted, are allowed to either the upper or the lower trees.

Changes to the underlying filesystems while part of a mounted overlay filesystem are not allowed.  If the underlying filesystem is changed, the behavior of the overlay is undefined, though it will not result in a crash or deadlock.
```

In practice this usually means that if you forget to stop the container before making changes, either new or old version may be visible from inside the container.

**Comment by Elronnd** [comment]
I'm also experiencing this issue.  I've tried running ldconfig (in linux), and darling shutdown then darling shell, but nothing works.  I'm on arch linux.

**Comment by bugaevc** [comment]
You're not supposed to run ldconfig manually or add any files or symlinks or whatever people try to do when Darling is not working.

Assuming your installation is corrupted, stop the container, remove libexec/darling, reinstall Darling, then launch the shell.
