### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by c0mpute** [darlinghq/darling#255]
Hi,

I can't seem to be able to compile this. Compilation fails for file `src/kernel/libsyscall/CMakeFiles/libsyscall.dir/custom/errno.o`, after calling the first `make` (right after `cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../Toolchain-x86_64.cmake`):

```
[  5%] Building C object src/kernel/libsyscall/CMakeFiles/libsyscall.dir/custom/errno.o
/tmp/errno-516328.s: Assembler messages:
/tmp/errno-516328.s:630: Error: inconsistent uses of .cfi_sections
clang-3.9: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/kernel/libsyscall/CMakeFiles/libsyscall.dir/build.make:1611: src/kernel/libsyscall/CMakeFiles/libsyscall.dir/custom/errno.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:530: src/kernel/libsyscall/CMakeFiles/libsyscall.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

I have all dependencies installed and followed all the steps.

System: Antergos Linux (Arch Linux) kernel 4.9.11.

**Comment by LubosD** [comment]
Hi, this is due to a broken version of binutils. This problem has been reported many times here, but GitHub's search doesn't work well. You must either downgrade or wait for an update.
