### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by xBartu** [darlinghq/darling#256]
Hi folks,

Recently I tried to install darling on manjaro from source. I strictly followed the guide. Wen I try to the command *make install*, I got the following-up error.

`Install the project...
-- Install configuration: ""
-- Installing: /usr/local/libexec/darling/private
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot make directory "/usr/local/libexec/darling/private": No
  such file or directory

make: *** [Makefile:84: install] Error 1
`

I am pretty new on building the modules from source.

**Comment by xBartu** [comment]
I used super admin for comamnd make install and it solved.

**Comment by bugaevc** [comment]
Of course, you need to perform installation as root.

**Comment by xBartu** [comment]
I can consider myself as newbie. Thanks for @bugaevc  the answer.
