### ISSUE TITLE
Implement stub generator

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#263]
Implement a native tool that produces stub files for any passed Mach-O dynamic library / framework.

* Detect global variables
* Detect global constants
* Detect functions
* Detect Objective-C classes and generate `- (void)forwardInvocation:(NSInvocation *)anInvocation` for them.

Related to #141.

**Comment by ahyattdev** [comment]
What is the best way to go about this? Parse nm output?

**Comment by LubosD** [comment]
Since this tool will not be executed during build, but rather manually by the developer, then yes, we can parse `nm` output and run the tool on real macOS (for example).

**Comment by LubosD** [comment]
`nm` output:

```
0000000000000fa8 S _stubConst
0000000000000fa0 T _stubFunc
0000000000001000 D _stubVar
```

The names are self-descriptive.

**Comment by ahyattdev** [comment]
Are you sure lower case symbols are always to be ignored? I ran `nm` on AuthKit and all the Objective-C methods are marked with `t`. Maybe that is just for Objective-C.

**Comment by jevinskie** [comment]
@ahyattdev I would think you could place all the defined symbols in the stub, hidden or not. Just use `__attribute__((visibility("{default,hidden}"))`, no?

@LubosD What exactly do you want the generated stubs to look like? I'm interesting in giving this a go - MachO is "fun". 😛

**Comment by ahyattdev** [comment]
We have an stub generator for Objective-C classes [here](https://github.com/darlinghq/darling/blob/master/tools/stub-gen-objc). 

This is what they look like:

`AKDevice.h`
```
@interface AKDevice : NSObject

@end
```

`AKDevice.m`
```
@implementation AKDevice

- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector {
    return [NSMethodSignature signatureWithObjCTypes: "v@:"];
}

- (void)forwardInvocation:(NSInvocation *)anInvocation {
    NSLog(@"Stub called: %@ in %@", NSStringFromSelector([anInvocation selector]), [self class]);
}

@end
```

Only stubs for the classes are necessary for Objective-C methods because of `methodSignatureForSelector:` and `forwardInvocation:`.

**Comment by ahyattdev** [comment]
We have a generator for functions and classes now, but constants have to be added manually. They tend to be fewer so creating them manually is easier than making a stub generator that can perform static analysis and guess the correct type and value for each.
