### ISSUE TITLE
Implement xcode-select

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#264]
Re-implement `xcode-select`, which is a standard part of macOS for setting the XCode installation path if the default is not OK.

**Comment by stek29** [comment]
Hm, Apple's `xcode-select` relies on `usr/lib/libxcrun.dylib`, so if `xcrun` binary doesn't exist developer path isn't necessary invalid.

**Comment by LubosD** [comment]
Our implementation closely follows the closed source original.

**Comment by stek29** [comment]
@LubosD Yes, you're right, I just messed up my installation :D
