### ISSUE TITLE
HDIUtil Fuse

### ISSUE THREAD

**Issue by DuIslingr** [darlinghq/darling#266]
Upon trying to mount a dmg it says everything is ok and it munted but at the end it says this

```bash
Darling [~]$ hdiutil attach Downloads/Command_Line_Tools_macOS_10.12_for_Xcode>
/Volumes/Command_Line_Tools_macOS_10.12_for_Xcode_8.3
Skipping partition of type Primary GPT Header
Skipping partition of type Primary GPT Table
Skipping partition of type Apple_Free
Using partition #3 of type Apple_HFS
Everything looks OK, disk mounted
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
```
Not sure how to resolve this. Checked other issues and can't seem to find a related issue on it.

I tried specifying a mount point but that doesnt seem to work as it just spits out the supported commands

**Comment by LubosD** [comment]
What do you get if you `ls /Volumes/Command_Line_Tools_macOS_10.12_for_Xcode_8.3`?

BTW I strongly recommend you to install XCode instead of these tools. XCode contains the whole SDK, which is what you need on Darling?

**Comment by DuIslingr** [comment]
Well the thing is since we cant run xcode anyways we don't really need to waste time downloading 4gb just for it. We only really need it for the sdks which we can grab elsewhere. Plus then you dont have to spend time making Environment variables to run clang and stuff if it can be called directly since they get stored in user/bin and stuff.

And ls reports the directory does not exist.

**Comment by ahyattdev** [comment]
This works now
