### ISSUE TITLE
hashbang handling broken

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#267]
To reproduce, download and run [this bash script](https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev). 

[This is what the `strace` output looks like](https://gist.github.com/ahyattdev/f86690af8e889d39860216778942dd4a), but it does this for every library repeatedly. There are also [long blocks of `clock_gettime` calls](https://gist.github.com/ahyattdev/a8beeb4ab1c980c4e1316e0102147814). 

It maxes out one CPU core on my machine just by doing this.

**Comment by LubosD** [comment]
Hashbang handling is broken:
```
[pid  7581] execve("/bin/mldr", ["/bin/mldr", "/usr/bin/env", "/tmp/screenfetch.sh"], [/* 55 vars */]) = 0
```
