### ISSUE TITLE
/bin/arch reports a different result from macOS's version

### ISSUE THREAD

**Issue by yan12125** [darlinghq/darling#277]
On a macOS Sierra VM,
```
$ /usr/bin/arch
i386

$ file /usr/bin/arch    
/usr/bin/arch: Mach-O universal binary with 2 architectures: [x86_64: Mach-O 64-bit executable x86_64] [i386: Mach-O executable i386]
/usr/bin/arch (for architecture x86_64):        Mach-O 64-bit executable x86_64
/usr/bin/arch (for architecture i386):  Mach-O executable i386
```

On the other hand, the darling version gives a different answer:
```
$ darling /usr/local/libexec/darling/usr/bin/arch
x86_64
```

The difference confuses CPython's configure script, which [expects "i386" even on 64-bit systems](https://github.com/python/cpython/blob/master/configure.ac#L2339). That line has been in CPython for more than 7 years ([the relevant commit in CPython's SVN repo](http://svn.python.org/view/python/trunk/configure.in?r1=74672&r2=74671&pathrev=74672)), so I guess /usr/bin/arch has been printing such an interesting response across different OS X versions.

Darling's answer is more sensible :D

**Comment by bugaevc** [comment]
Unrelated, but Darling binaries actually residing in `/usr/local/libexec/darling` on the host is kind of an internal implementation detail, and you generally shouldn't call them from there. Instead, run it the same way as you did on macOS:

`$ darling shell /usr/bin/arch`

**Comment by yan12125** [comment]
Thanks - I use that trick as `shell` doesn't work fine on 4.10 kernels. (#259)

**Comment by ahyattdev** [comment]
https://github.com/darlinghq/darling-system_cmds/blob/master/arch.tproj/arch.c#L124


I think this is the line it gets the architecture on. 

Looks to be a CoreFoundation issue

I am on mobile now so I can investigate it

**Comment by yan12125** [comment]
Yep, this function ultimately calls into https://github.com/darlinghq/darling/blob/master/src/lkm/servers/mach_host.c#L128. Darling's codes are quite good. The question is: should Darling follow how macOS works, even the latter misbehaves?

**Comment by ahyattdev** [comment]
Haha, meant I can't investigate it

The mobile interface also lacks editing comments

**Comment by ahyattdev** [comment]
Since the new kernel module is based on the XNU source maybe it handles this correctly

**Comment by LubosD** [comment]
I confirm the bug. I remember that arch should be i386, but subarch should be x86_64.
