### ISSUE TITLE
Frameworks, PrivateFrameworks, and libraries that are missing

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#286]
Stubs needed:

- [x] `/System/Library/Frameworks/ImageIO.framework`
- [x] `/System/Library/PrivateFrameworks/login.framework`
- [x] `/System/Library/PrivateFrameworks/NetworkStatistics.framework`
- [x] `/System/Library/PrivateFrameworks/LoggingSupport.framework`
- [x] `/System/Library/PrivateFrameworks/ConfigurationProfiles.framework`
- [x] `/System/Library/PrivateFrameworks/AppleSystemInfo.framework`
- [x] `/System/Library/PrivateFrameworks/DiskImages.framework`
- [x] `/System/Library/PrivateFrameworks/PackageKit.framework`
- [x] `/System/Library/PrivateFrameworks/CrashReporterSupport.framework`
- [x] `/System/Library/PrivateFrameworks/AuthKit.framework`
- [x] `/System/Library/PrivateFrameworks/DiskManagement.framework`
- [x] `/System/Library/Frameworks/DiskArbitration.framework`
- [x] `/System/Library/PrivateFrameworks/PerformanceAnalysis.framework`
- [x] `/System/Library/Frameworks/SecurityFoundation.framework`
- [x] `/System/Library/Frameworks/ApplicationServices.framework`
- [x] `/System/Library/PrivateFrameworks/DebugSymbols.framework`
- [x] `/System/Library/PrivateFrameworks/CoreSymbolication.framework`
- [x] `/System/Library/PrivateFrameworks/IOPlatformPluginFamily.framework`
- [x] `/usr/lib/libsysmon.dylib`
- [x] `/System/Library/PrivateFrameworks/PlugInKit.framework`
- [x] `/usr/lib/libcompression.dylib`
- [x] `/System/Library/PrivateFrameworks/kperf.framework`
- [x] `/System/Library/Frameworks/Metal.framework`
- [x] `/System/Library/PrivateFrameworks/StreamingZip.framework`
- [x] `/System/Library/Frameworks/ScriptingBridge.framework`

From the real source:

- [x] `/usr/lib/libdtrace.dylib`
- [x] `/System/Library/Frameworks/CFNetwork.framework`

**Comment by oscarbg** [comment]
Brackets app needs ScriptingBridge.framework..
