### ISSUE TITLE
fuse.c fial

### ISSUE THREAD

**Issue by fervi** [darlinghq/darling#290]
Compilation stopped on 34%

Make:
http://meshnet-users.tk/paste/p/ajwu/q.txt

Dmesg:
http://meshnet-users.tk/paste/p/ajwt/u.txt

Debian Stretch

Maybe you have idea how to fix it?

**Comment by bugaevc** [comment]
The error is `Segmentation fault` near the end of you `make` log. This means that the bug is in the compiler you use, not in Darling.

Try:
* running `make` again
* reinstalling `clang`
* reinstalling your whole system

If the issue persists, report the bug to Debian/clang developers.

**Comment by yan12125** [comment]
> This means that the bug is in the compiler you use, not in Darling.

I guess not. The dmesg log says that it's ```wrapgen``` that crashes. @fervi It would be helpful if you run wrapgen manually under gdb. The complete command can be retrieved by ```make VERBOSE=1```

**Comment by bugaevc** [comment]
Oh, you're right, I didn't look at dmesg log.

**Comment by fervi** [comment]
Ok.
http://meshnet-users.tk/paste/p/ajwv/q.txt

gdb-backtrace:
http://meshnet-users.tk/paste/p/ajwv/z.txt

strace:
http://meshnet-users.tk/paste/p/ajww/r.txt

command crash:
../../startup/wrapgen libfuse.so /home/fervi/darling/build/src/external/darling-dmg/fuse.c

**Comment by yan12125** [comment]
Maybe there's something special in Debian's libfuse.so. Can I get a copy of this file without installing Debian?

**Comment by fervi** [comment]
http://ftp.at.debian.org/debian/pool/main/f/fuse/libfuse-dev_2.9.7-1_amd64.deb
Unar can unpack this archive (Probably other software also :P)

**Comment by yan12125** [comment]
Well, libfuse.so in this package is a symbolic link to /lib/x86_64-linux-gnu/libfuse.so.2.9.7

**Comment by fervi** [comment]
Yep, I update link (sorry)

**Comment by yan12125** [comment]
Thanks. wrapgen runs fine here. First let's check we're using the same file:
```
$ sha256sum lib/x86_64-linux-gnu/libfuse.so.2.9.7 
cfa582db878655561be5623e1bfb005d9129b7386f5661502e623b33af1156c9  lib/x86_64-linux-gnu/libfuse.so.2.9.7
```
If the file is identical, could you rebuild darling with ```cmake -DCMAKE_BUILD_TYPE=Debug``` and run wrapgen under gdb again?

**Comment by fervi** [comment]
Hmm, other checksum. Not sure why. Ok, reinstalling;

**Comment by fervi** [comment]
Ok, now working - thanks
