### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by Godspel** [darlinghq/darling#297]
Hello,

I have just installed Darling, it's a nice project with a bright future but i this present moment I have a little problem.

When I open a terminal and write "darling shell" into it, It load kernel, "Darling [~] $" appear and when I write something, nothing happening !!!

Can you help me please

**Comment by stek29** [comment]
Could you provide more information about your setup?

**Comment by Godspel** [comment]
Hello, 

Thank you to answer, I have the last Ubuntu in 64bits

**Comment by Godspel** [comment]
Everything is working right now !!! I have to check my hardware configuration (clip, hdd, ram, etc)... 

Thanks you even if it's fine.

**Comment by stek29** [comment]
@Godspel You can close the issue then :D

**Comment by bandrea** [comment]
@Godspel I also have this  problem, can I know how you fixed it?

Thank you

**Comment by Godspel** [comment]
Hello Bandrea,

You don't ask to the good person, but if it can help you, I had to check every composant of my computer like memory ram, hard drive disk, processor and then i restarted my computer and it worked. simply as that.

Good Luck !
