### ISSUE TITLE
[Help] Assertion Failed

### ISSUE THREAD

**Issue by wakatoyee** [darlinghq/darling#305]
I followed the building instructions, I installed it on debian (4.9.0-3-amd64) and I got this error upon using `installer` command and also `sw_vers`..

Assertion failed: (newSuper->isRealized()), function setSuperclass, file /home/user/darling/src/external/objc4/runtime/objc-runtime-new.mm, line 6546.
Illegal instruction: 4

`darling shell` seems to be working fine, I can navigate and use other tools like hdiutil, telnet, nano, etc.. but I can't tell if all files were in place, I haven't used osx before.. I `darling shutdown` and `reboot`, still got those errors.

**Comment by LubosD** [comment]
Sorry, this seems to be a regression of some sort. We've been fiddling with CoreFoundation lately.

**Comment by wakatoyee** [comment]
What do you suggest that I should do? I am sorry I'm such a noob :smile:

**Comment by ahyattdev** [comment]
We can assume that [this commit](https://github.com/darlinghq/darling-corefoundation/commit/eff82937b82d98c09c144f96870a4e1b9c3b6dfd) introduced the issue.

**Comment by ahyattdev** [comment]
The problem is there is no implementation for `NSMutableCharacterSet` but it is used [here](https://github.com/darlinghq/darling-corefoundation/commit/eff82937b82d98c09c144f96870a4e1b9c3b6dfd#diff-fe3bb48eedc6aa36dbdfaa93d640c3c0R1007).

**Comment by ahyattdev** [comment]
I think the problem is `NSNumber`'s implementation is in Foundation but it is used in CoreFoundation [here](https://github.com/darlinghq/darling-corefoundation/commit/eff82937b82d98c09c144f96870a4e1b9c3b6dfd#diff-fe3bb48eedc6aa36dbdfaa93d640c3c0R1006).

**Comment by LubosD** [comment]
I did some dirty testing in `CFInitialize()` and found out two things:
* The class_setSuperclass section causes the assertion failure noted above.
* Bridging CFUUID and CFMachPort causes further aborts (via invalid instruction).

I'll try to find out how it should be done, but I assume checking if Foundation has been loaded is one possible choice.
