### ISSUE TITLE
Application will not execute throwing: dyld: Library not loaded: /System/Library/Frameworks/Security.framework/Versions/A/Security

### ISSUE THREAD

**Issue by mathotp** [darlinghq/darling#307]
When trying to launch the Preview application I get the followig error,  it seems the security framework is missing:

```Darling [~/apps/mac/Preview.app/Contents/MacOS]$ ./Preview 
dyld: Library not loaded: /System/Library/Frameworks/Security.framework/Versions/A/Security
  Referenced from: /Volumes/SystemRoot/home/matph/apps/mac/Preview.app/Contents/MacOS/Preview
  Reason: image not found
Abort trap: 6
```

Checking in  the FrameWork directory I only have the following:

```Darling [/System/Library/Frameworks]$ ls -la
total 112
drwxr-xr-x  1 matph  matph  4096  2 Jun 07:00 .
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 ..
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 ApplicationServices.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 CoreFoundation.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 CoreServices.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 CryptoTokenKit.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 DiskArbitration.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 Foundation.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 IOKit.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 07:00 ImageIO.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 LocalAuthentication.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 Python.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 Ruby.framework
drwxr-xr-x  1 matph  matph  4096  2 Jun 06:59 SystemConfiguration.framework
Darling [/System/Library/Frameworks]$ 
```

And during the compilation of Darling I had the follwing error, it was all over the place during compilation, don't know if this is important:

```[100%] Linking CXX shared library libstdc++.6.dylib
ld: warning: directory not found for option '-F/System/Library/Frameworks/'
ld: warning: -rpath cannot be used with dylibs that will be in the dyld shared cache
ld: warning: directory not found for option '-F/System/Library/Frameworks/'
ld: warning: -rpath cannot be used with dylibs that will be in the dyld shared cache
[100%] Built target stdcxx
```

**Comment by LubosD** [comment]
We don't have that framework yet... it's a work in progress.

**Comment by bugaevc** [comment]
Please note that graphical applications aren't supported at the moment. We're working on it (though not right now — I'm taking my finals) and we'd gladly accept help.

That being said you're hitting an error about Security, @ahyattdev has been recently working on that.

**Comment by mathotp** [comment]
nice thanks for the update :)

**Comment by ahyattdev** [comment]
Security currently builds and exists at this path so I am going to close this issue. Let us know what other dynamic libraries and frameworks Preview needs.

**Comment by shubhsherl** [comment]
> Please note that graphical applications aren't supported at the moment. We're working on it (though not right now — I'm taking my finals) and we'd gladly accept help.

Are the graphical applications are supported now?

**Comment by pecavalheiro** [comment]
Hi! I wasn't able to find an open issue for this, so I'm writing a comment here. I'm having this same error when trying to run Fantastical 2. I guess it's due to being a graphical app, which is not fully supported at the moment. Are there any other open issues regarding this? Or anywhere I can update myself on support status for such library and/or application?

```
dyld: Library not loaded: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
  Referenced from: /Applications/Fantastical.app/Contents/MacOS/Fantastical
  Reason: image not found
abort_with_payload: reason: Library not loaded: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
  Referenced from: /Applications/Fantastical.app/Contents/MacOS/Fantastical
  Reason: image not found; code: 1
Abort trap: 6
```

Thank you!

**Comment by HinTak** [comment]
@pecavalheiro you are missing the CloudKit framework, nor Security. Completely different issue - you should file new issue.
