### ISSUE TITLE
CFConstantStringClassReference expected in Foundation framework

### ISSUE THREAD

**Issue by sylviedev** [darlinghq/darling#308]
Hi,

I have built and installed Darling on Debian and the shell works fine. Now I am trying to run a MacOS application which is linked with both CoreFoundation and Foundation frameworks and I get the following error from the loader :
dyld: Symbol not found: ___CFConstantStringClassReference
  Referenced from: /Volumes/SystemRoot/.../<app>
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

Did I miss something in Darling generation ? Any other idea ?

Thanks,
Sylvie

**Comment by LubosD** [comment]
I'm having a hard time reproducing the issue. This symbol is exported by CoreFoundation, which in turn is reexported by Foundation.

Could you please provide a link to the offending application?

**Comment by sylviedev** [comment]
Thanks for your time. In fact the executable was corrupted, I am sorry about that. The application was initially linked with the cocoa framework but I noticed that no symbol was imported from it. So I tried to remove the cocoa framework reference from the mach-o header but it corrupted the symbols imports.

**Comment by LubosD** [comment]
No problem.
