### ISSUE TITLE
Questions about AppleSystemInfo

### ISSUE THREAD

**Issue by npyl** [darlinghq/darling#310]
Hello, 
I saw the AppleSystemInfo directory in the source and I thought I may be able to help a bit with it with some ideas and some research I have done. ( Sorry it is not that much I know... )

I was wondering though:

- Could someone use Objective-C++ to write a framework for darling ??
- I have found that for the function ASI_CPUSpeedInHz we can gather information from /dev/cpuinfo or the /sys interface... Is this solution ok enough?? ( Because I have seen that in some Linux kernels the sysfs interface doesn't exist... ) Are there any problems with portability on the many Linux distros???

-  I have found that on macOS the ASI_CopyComputerModelName( int arg0 ) returns either a short form of the model name or a long form depending on the value of arg0.  

If arg0 = 0, it returns the short form.  If arg0 = 1, it returns the long form... ( It works as a bool, I guess it is a bool ( so maybe we need to change the int to bool  )).  
e.g. short form: MacBook Pro
e.g. long form: MacBookPro11,1

So we can have a config file in ~/.darling which will store the short and long model name,
and everytime we call the ASI_CopyComputerModelName it will read these values from the config file.

( This way the user will also be able to edit the model names in order to allow some software to run differently... I think I have seen some applications run differently on Mac Pros than MacBook Pros etc... )

When Darling runs for the first time, it can ask the user if he is using a Macintosh or a PC.
If he types "Macintosh", then Darling will try to find the ModelNames of his Mac from the DMI tables (  e.g. using dmidecode ( available on Linux ) ) and then it will store it in a config file in ~/.darling.
If he types "PC", then Darling will ask for a "Fake Macintosh Model Name (Short)" and a "Fake Macintosh Model Name (Long)", and it will store the values...

Edit: We can also have some code to identify on its own the platform... We could read the contents of the file /sys/class/dmi/id/sys_vendor when sysfs is enabled in the kernel.

- Also I have written an alpha version of the AppleSystemInfo.h I will include here... 
Please note, that I don't know how to reverse engineer a binary... What I did was to dump the functions from the AppleSystemInfo binary and to try to find return types so that using the AppleSystemInfo.framework would be possible..  ( Therefore these may not be the actual return types apple is using but they work (do they???) )

Also, please note that I haven't found the return types for ASI_CopyCPUDescription, CopyPropertyAsData, GetIOPlatformFeature, PlatformOverideExistsAndIsSet
This is why I have them in comments...

What is more, I made my "own" AppleSystemInfo framework that used this AppleSystemInfo.h and in AppleSystemInfo.mm I returned the values that the original-apple framework returns... Then I replaced the original of macOS with mine, rebooted and macOS booted... I think it worked... The only problem i encountered was that I hadn't code signed my framework and Xcode and Safari couldn't run.. ( I could also see in terminal, when running `man`,  that dyld printed an error about mmap()... I don't remember  )

EDIT: I haven't yet done research on the SPMachineTypes.plist and its job... It may have something to do though with the function ASI_CopyComputerModelName??? I don't know... 

```#ifndef APPLE_SYSTEM_INFO_H
#define APPLE_SYSTEM_INFO_H

#include <Cocoa/Cocoa.h>

//! Project version number for AppleSystemInfo.
FOUNDATION_EXPORT double AppleSystemInfoVersionNumber;                  // TODO1

//! Project version string for AppleSystemInfo.
FOUNDATION_EXPORT const unsigned char AppleSystemInfoVersionString[];   // TODO1

// In this header, you should import all the public headers of your framework using statements like #import <AppleSystemInfo/PublicHeader.h>

#include <CoreFoundation/CoreFoundation.h>
#include <SystemConfiguration/SystemConfiguration.h>

CF_IMPLICIT_BRIDGING_ENABLED
CF_EXTERN_C_BEGIN

CF_EXPORT long ASI_BusSpeedInHz(void); 
CF_EXPORT long ASI_CPUSpeedInHz(void);
CF_EXPORT CFStringRef ASI_CopyBusSpeedDescription(void);
//CF_EXPORT CFStringRef ASI_CopyCPUDescription(void);                 // doesn't work...
CF_EXPORT CFStringRef ASI_CopyCPUKind(void);
CF_EXPORT CFStringRef ASI_CopyComputerModelName( bool shortlong = 1 );   // bool??
                                                                    // FIXME 1: is the default value 1???
                                                                    // We could use the macros:
                                                                    //  #define ASI_COMPUTER_MODEL_NAME         0
                                                                    //  #define ASI_COMPUTER_MODEL_IDENTIFIER   1

CF_EXPORT CFStringRef ASI_CopyCurrentBusSpeedDescription(void);
CF_EXPORT CFStringRef ASI_CopyCurrentCPUDescription(void);
CF_EXPORT CFStringRef ASI_CopyCurrentRAMDescription(void);
CF_EXPORT CFStringRef ASI_CopyCurrentRAMDescriptionWithType(void);
CF_EXPORT CFStringRef ASI_CopyDiskSizeDescription(void);
CF_EXPORT CFStringRef ASI_CopyFormattedSerialNumber(void);
CF_EXPORT CFStringRef ASI_CopyHostUUID(void);
CF_EXPORT CFStringRef ASI_CopyMachineConfigurationCode(void);
CF_EXPORT CFStringRef ASI_CopyRAMDescription(void);

CF_EXPORT bool ASI_IsPlatformFeatureEnabled(void);
CF_EXPORT unsigned int ASI_NumberOfCPUs(void);
CF_EXPORT unsigned long ASI_PhysicalMemorySize(void);
CF_EXPORT CFStringRef CopyIOPlatformSerialNumberString(void);

// these dont work
//CF_EXPORT CFStringRef CopyPropertyAsData(void);
//CF_EXPORT CFStringRef GetIOPlatformFeature(void);
//CF_EXPORT CFStringRef PlatformOverideExistsAndIsSet(void);

CF_EXTERN_C_END
CF_IMPLICIT_BRIDGING_DISABLED

#endif

**Comment by stek29** [comment]
I'm not sure, but `ASI_CopyCPUDescription` seems to have 3 arguments, and quick look through shows that they are 3 bools (bools, not ints, since it checks some of them against 1 and some against 0)
`CopyPropertyAsData` seems to take 2 bool's, `GetIOPlatformFeature` takes 1 (and doesn't seem to use it, huh) and `PlatformOverideExistsAndIsSet` has `(bool, *bool, *bool)`

**Comment by LubosD** [comment]
FYI: This Apple-private framework is used by `xcodebuild`, but we don't have that tool running yet (more stubs need to be generated).

We prefer not to use C++ where C was used in the original framework, but it's not a big deal.

**Comment by npyl** [comment]
Thank you very much LubosD and stek29

**Comment by stek29** [comment]
@npyl Hopper is a nice (but proprietary and paid) disassembler for macOS/Linux, and it has demo which runs for 30 minutes till closing itself. It also has pseudocode generator, which may help if you're not so good with assembly.

**Comment by npyl** [comment]
Thank you, I will check it out!!
