### ISSUE TITLE
Socket is not connected

### ISSUE THREAD

**Issue by indra17ramadhan** [darlinghq/darling#311]
bash: cd: /Volumes/Xcode_7.2.1: Socket is not connected

Darling [/Volumes]$ ls
ls: Xcode_7.2.1: Socket is not connected
DarlingEmulatedDrive SystemRoot

**Comment by stek29** [comment]
What's mounted at Xcode_7.2.1? How was it mounted?

**Comment by indra17ramadhan** [comment]
I did the mounting with the command "hdiutils attach", and that's what happens when I open it in the "/Volumes" folder

**Comment by stek29** [comment]
Hm, same thing just happened to me -- I've downloaded CLI tools, attached them and started installer. Installer exited with lzma error, and then I saw that "socket is not connected".

**Comment by LubosD** [comment]
Problem reproduced.

**Comment by LubosD** [comment]
Can any one of you confirm that this is actually a kernel-based crash? You should see a crash backtrace in `dmesg` like this:

```
[1612855.142017] BUG: unable to handle kernel NULL pointer dereference at 00000000000000d8
[1612855.142198] IP: [<ffffffffb0c016be>] mutex_lock+0xe/0x30
```

**Comment by LubosD** [comment]
By the way, the bug is that the kernel module currently assumes that `thread_self_trap()` always gets called for new threads, which doesn't happen for threads spawned from Linux/ELF code.

**Comment by stek29** [comment]
> Can any one of you confirm that this is actually a kernel-based crash?

@LubosD Confirmed

**Comment by lesderid** [comment]
@LubosD I still have the same issue as @stek29 did with the CLI tools dmg.

**Comment by LubosD** [comment]
@lesderid To what extent? You need to be more specific?

**Comment by lesderid** [comment]
Sorry, this is the problem I'm having:

```
lesderid@ichi ~/darling> darling shutdown
lesderid@ichi ~/darling> darling shell
Bootstrapping the container with launchd...
Darling [/home/lesderid/darling]$ hdiutil attach Command_Line_Tools_macOS_10.13_for_Xcode_9_beta_4.dmg 
/Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9_beta_4
Darling [/home/lesderid/darling]$ cp /Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9_beta_4/Command\ Line\ Tools\ \(macOS\ version\ 10.13\).pkg .
cp: /Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9_beta_4/Command Line Tools (macOS version 10.13).pkg: Socket is not connected
cp: /Volumes/Command_Line_Tools_macOS_10.13_for_Xcode_9_beta_4/Command Line Tools (macOS version 10.13).pkg: could not copy extended attributes to ./Command Line Tools (macOS version 10.13).pkg: Socket is not connected
```

**Comment by stek29** [comment]
@lesderid do you have any messages in kernel log? (`dmesg`)

**Comment by lesderid** [comment]
@stek29 
Kernel messages when mounting: [mount.txt](https://github.com/darlinghq/darling/files/1189447/mount.txt)
Kernel messages when copying: [copy.txt](https://github.com/darlinghq/darling/files/1189446/copy.txt)

**Comment by stek29** [comment]
Are there any messages from FUSE?

**Comment by lesderid** [comment]
@stek29 I don't think so, no.

**Comment by LubosD** [comment]
@lesderid The bug has been identified and fixed.

**Comment by p182** [comment]
Same on newest self-compiled Darling from this commit: https://github.com/darlinghq/darling/commit/9393db2c6ed530acaa2a4a933c391f1363fea1e8, when I trying to copy Telegram.dmg

dmesg output:
`Unable to allocate a message buffer: Cannot allocate memory
Unable to obtain kernel buffer: Operation not permitted
`

**Comment by NightEule5** [comment]
The issue is still present as of 156c306.

In `dmesg` I'm getting quite a bit of messages like:

```
[ 1599.524403] not implemented: lck_mtx_destroy()
```
