### ISSUE TITLE
[Regression] Midnight Commander

### ISSUE THREAD

**Issue by fervi** [darlinghq/darling#312]
Some time ago it worked propertly

Now I got:
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_setspecific': Operation not permitted.  Aborting.
Abort trap: 6

Any idea or "try to find regression commit"? ;)

**Comment by LubosD** [comment]
Bug confirmed.

**Comment by LubosD** [comment]
For reasons not clear to me dyld preferred a weak implementation of pthread_setspecific() instead of the real one.
