### ISSUE TITLE
Missing some multilib pkgs from fresh Arch installation

### ISSUE THREAD

**Issue by stek29** [darlinghq/darling#313]
After fresh arch install, `lib32-glibc` is not installed, but it is required by darling. Please, update the wiki.
_Also, maybe `gcc-multilib` is required too, I'll try to build without it to check_

**Comment by LubosD** [comment]
Thanks!

I've added `lib32-glibc` into the wiki page, let me know if `gcc-multilib` is needed too.

**Comment by stek29** [comment]
@LubosD Yup, `gcc-multilib` is needed.
But it has `lib32-glibc` in its deps, so just `gcc-multilib` should be enough.

**Comment by LubosD** [comment]
Done, thanks again!
