### ISSUE TITLE
Implement CoreServices APIs used by vim

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#314]
Functions:
* CreateTextEncoding
* TECCreateConverter
* TECConvertText
* TECFlushText
* TECDisposeConverter

Types:
* TECObjectRef
* ConstTextPtr

Constants:
* kTextEncodingUnicodeDefault
* kTextEncodingDefaultVariant
* kUnicodeUTF8Format
* kUnicodeHFSPlusCompVariant
* kUnicodeCanonicalCompVariant
* kUnicode16BitFormat

**Comment by stek29** [comment]
Btw, Apple's vim links just to iconv, ncurses and libSystem.

It lacks clipboard and arabic/farsi/etc, but it works absolutely fine in darling -- `/usr/bin/vim` copied from Sierra runs fine on Darling.

Is Clipboard and some MBYTE features worth linking to ObjC, Cocoa, AppKit and etc?

**Comment by LubosD** [comment]
I guess not, especially if VIM bundled in macOS doesn't have this. Sadly, our build of VIM doesn't yet run, but it could be a broken build somehow.

**Comment by facekapow** [comment]
I'm not too familiar with vim, but I just tested it out and it appears to working fine.
