### ISSUE TITLE
map_pagezero() fails

### ISSUE THREAD

**Issue by tpimh** [darlinghq/darling#318]
Just compiled Darling on Arch Linux. I run it as a regular user, not root. When I try to run any application, I get this message:

    Cannot mmap page zero, some apps may crash because of this (Operation not permitted)

Any suggestions on how to solve it?

**Comment by LubosD** [comment]
See https://wiki.darlinghq.org/build_instructions#special_permissions

These permissions should get set automatically during installation, but I guess it may fail silently.

**Comment by tpimh** [comment]
Thanks, that fixed it.
