### ISSUE TITLE
Broken hdiutil detach

### ISSUE THREAD

**Issue by stek29** [darlinghq/darling#321]
Probably related to #302.

The only thing it prints is "Failed to execute fusermount!".
Here's the [strace log](https://gist.github.com/stek29/df973d84a0dc2291641790021256bc33).
On [line 923](https://gist.github.com/stek29/df973d84a0dc2291641790021256bc33#file-hdiutil-detach-strace-L923) it tries to exec `fusermount -u /Volumes/clixc`, but gets `ENOENT`.

(btw, what the hell is going on [lines 932-961](https://gist.github.com/stek29/df973d84a0dc2291641790021256bc33#file-hdiutil-detach-strace-L932-L961)? Why is it printing error message by one char?..)

**Comment by bugaevc** [comment]
Seems like it should use `posix_spanwp` instead of `posix_spawn` [here](https://github.com/darlinghq/darling-dmg/blob/master/src/main-hdiutil.cpp#L151-L160).

**Comment by LubosD** [comment]
@stek29 This is how Apple's libc sometimes behaves.
