### ISSUE TITLE
Cloning everything for development?

### ISSUE THREAD

**Issue by ylluminate** [darlinghq/darling#324]
So the instructions for pulling and building `darling` are pretty straight forward, but what about development work? I would like to clone all submodules as well and the primary project into a folder called `darlinghq` in order to be able to have all source in a central location.  What's the best way to do this?  Do I need to clone each project separately or is there a way to do them all in one command?

**Comment by ahyattdev** [comment]
For each repository that you make changes to, be it the main one or a submodule of it, you need to fork the repository on GitHub, change the remote URL of your cloned copy to be that of your fork, push your commits, and create a PR.

**Comment by stek29** [comment]
Just clone as usual (recursive follow submodules) and then do what @ahyattdev said: 

```sh
git remote add mine https://github.com/username/darling-something
git commit 
git push mine master
```
Or something like that

Then open PR on that submodule repo
You may also make a PR updating submodules to this repo, but I'm not sure if it should be done after PR in submodule gets merged so it points to merge commit, or it's ok to make it point to your commit.

**Comment by ahyattdev** [comment]
This wiki page walks you through submitting a PR, so I think it is documented enough to close this issue. 

https://wiki.darlinghq.org/contributing

**Comment by ylluminate** [comment]
Still not satisfied with this approach. We really need a comprehensive list of repos at least in case we want to pull them all in.  For example, @ahyattdev, on the page you noted, there should be a nice copy paste area if one were to want to clone all of the `darlinghq` repos and pertinent projects in a single location.  

Thoughts on this?  

Do I need to grunt it out and just build a list and share it here with you so you can add it to the wiki?... Or is there another / better way?

**Comment by bugaevc** [comment]
As already noted here and in the readme, a simple `git clone --recurse-submodules https://github.com/darlinghq/darling.git` will clone everything — most submodules (except newlkm) end up in `src/external`.

There are a few `darlinghq` repositories that we're not using it Darling (anymore) — GNUstep stuff, maybe something else — that you won't get this way, but I don't see why you would want to.

There's also the website repo, clone it manually if you want to.

**Comment by ylluminate** [comment]
The point though @bugaevc is to potentially contribute or make PRs. Can this be done via the `src/external`? I was under the impression that it was a cleaner process to have them at root level vs working in this manner. Admittedly, I've never had to work with externals much and so I'm not terribly familiar in this regard.

**Comment by bugaevc** [comment]
Yes, a git submodule is a git repository just like any other; you can make commits, work with branches, push/pull to remotes (and each repo can have a different set of remotes), create issues/pull requests in GitHub, and whatever else you can think of. I believe git repos don't even "know" whether they are submodules in another repo.

In fact, the contributing guide in the wiki demonstrates working with a submodule (`src/external/less`, aka `darlinghq/darling-less`).

**Comment by ylluminate** [comment]
Very interesting.  Thanks for clarifying.  I see what you're saying now about the external being used, but it did not click as that being an actual external in the example since it was not called out specifically.  It might be worth briefly explaining what you're saying therein for help if someone else pay perchance be confused.  Great to know.
