### ISSUE TITLE
Metal shader compilers (command line binaries) support?

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#326]
Hi,
I want to build iOS from Linux.. 
http://www.pmbaty.com/iosbuildenv/
this guy provides a build enviroment for Windows and on petition also for Linux and seems working..
sad it is that Metal shader compilers aren't open sourced so can't recompile this part of the build stack..
I wanted to know if metal compiler tolos (found inside Xcode.app iphoneos.sdk/usr/bin) like:
metal -std=osx-metal1.1 -o shaders.air shaders.metal
metal-ar r shaders.metal-ar shaders.air
metallib -o shaders.metallib shaders.metal-ar
are expected to run via Darling before building Darling stack..
there aren't any current Ubuntu repo to try?
thanks..

**Comment by ahyattdev** [comment]
We haven't tested the Metal toolchain yet, but `clang` works fine. 

There are currently no binary disributions of Darling.

**Comment by oscarbg** [comment]
thanks good to know..

so that makes probably metal compiler to work..

other question: is Darling compatible with Windows subsystem Linux for using it in Windows also?
if not can request enhancements to Microsoft WSL devs for implementating need features for allowing Darling to run on it?
thanks..

**Comment by resetnow** [comment]
See https://github.com/darlinghq/darling/issues/260

**Comment by LubosD** [comment]
`metal` seems to run. I didn't test it with any real input, but the binary doesn't depend on any dependencies we don't have. And it looks like yet another frontend to LLVM.

As @resetnow has commented, Darling cannot run under WSL, because WSL doesn't have a real Linux kernel.

**Comment by oscarbg** [comment]
very nice!!

**Comment by ahyattdev** [comment]
#328, #329, or #330 need to be fixed before this issue can be addressed.

**Comment by ahyattdev** [comment]
I tested all 3 of the tools you mentioned using [this example source](https://developer.apple.com/library/content/samplecode/AdoptingMetalI/Listings/MetalTexturedMesh_Shaders_metal.html) and it worked.

**Comment by jrmuizel** [comment]
This is currently broken for me because of #1765 and #1766
