### ISSUE TITLE
The command line tools for Xcode 6.4 fail to install

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#328]
The only output is the following line:

`bunzip2 error`

The issued command was as follows:

`installer -pkg /Volumes/Command_Line_Tools_OS_X_10.10_for_Xcode_6.4/Command\ Line\ Tools\ \(OS\ X\ 10.10\).pkg -target /`

**Comment by LubosD** [comment]
#328, #329, #330 all seem to be a crash in darling-dmg (and not the installer).

**Comment by LubosD** [comment]
And this is the reason - libfuse.so forks on its own and we now have stricter checks in the LKM:
```
[ 4216.737899] Darling Mach: <28516> Your /dev/mach fd was opened in a different process!
```

**Comment by stek29** [comment]
Maybe new #311 is caused by the same reason?

**Comment by LubosD** [comment]
@stek29 Most certainly yes.
