### ISSUE TITLE
Doesn't build: Undefined symbols for architecture i386: ___bzero

### ISSUE THREAD

**Issue by jpumc** [darlinghq/darling#331]
I get an error when trying to build darling.

```
Scanning dependencies of target system_kernel
[ 20%] Linking C shared library libsystem_kernel.dylib
Undefined symbols for architecture i386:
  "___bzero", referenced from:
      _linux_sigqueue in sigexc.o
      _linux_sigqueue_thread in sigexc.o
```

using:
clang 4.0
debian unstable

**Comment by LubosD** [comment]
Which version of clang?

**Comment by LubosD** [comment]
OK. I've tried it with clang 4.0 on Debian Testing and couldn't reproduce it.

This problem happens unless `-fno-builtin` is used, and it is used for all of system_kernel. So I wonder, are there any extra CFLAGS you passed to CMake or have set somewhere in your environment (that could override this flag)?

Alternatively, you could run `make VERBOSE=1` and check that `-fno-builtin` is part of the command that builds `sigexc.o`.

**Comment by jpumc** [comment]
I figured it out.

I was building it with CMAKE_BUILD_TYPE=Release.

Should a release build work? It worked before the Mach-O transition.

**Comment by Dekken** [comment]
This still breaks the build :|

**Comment by BrannonKing** [comment]
This needs to be repopened and fixed.

**Comment by ahyattdev** [comment]
Encountered this where having CFLAGS (even set to empty) and build type release set will fail.

**Comment by ahyattdev** [comment]
CMAKE_BUILD_TYPE_RELEASE doesn't seem to break it now
