### ISSUE TITLE
`make lkm` breaks in duct_kern_task.c

### ISSUE THREAD

**Issue by jgus** [darlinghq/darling#333]
First of all, awesome work! Was really excited to discover this project. :-) First time user, so it's possible I'm doing something wrong, but:

- Clean install of Ubuntu Server LTS 16.04.3 64-bit in VMWare; kernel is 4.4.0-91-generic
- Install deps per the "Ubuntu" line in https://wiki.darlinghq.org/build_instructions
- Clone the repo (as of commit 1d75c8b)
- Cmake per the build instructions
- `make` completes without errors
- `sudo make install` is happy too
- `make lkm` fails:

```
/home/josh/git/darling/src/lkm/osfmk/duct/duct_kern_task.c: In function ‘task_info’:
/home/josh/git/darling/src/lkm/osfmk/duct/duct_kern_task.c:499:30: error: ‘MM_SHMEMPAGES’ undeclared (first use in this function)
   shmem = get_mm_counter(mm, MM_SHMEMPAGES);
                              ^
/home/josh/git/darling/src/lkm/osfmk/duct/duct_kern_task.c:499:30: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:258: recipe for target '/home/josh/git/darling/src/lkm/osfmk/duct/duct_kern_task.o' failed
```

Happy to gather whatever other info would be helpful for diagnosis.

**Comment by stek29** [comment]
Looks like `MM_SHMEMPAGES` was added in 4.5...

**Comment by LubosD** [comment]
Yes, I'll add an `#if` to handle older kernels.

**Comment by jgus** [comment]
Thanks!
