### ISSUE TITLE
Is it legal?

### ISSUE THREAD

**Issue by VirtualMac** [darlinghq/darling#336]
Is this code actually some kind of _exported code from macOS_ or it is _written from scratch_ builded on _Apple Open Source_, so it is **legal to redistribute it** (on Mac)?

**Comment by LubosD** [comment]
We use sources from opensource.apple.com (and other GPL/BSD/... licensed code) and write our own to complement it.

**Comment by LubosD** [comment]
+ there is no reason why the code couldn't be used on an ordinary PC (so not just "on Mac").

**Comment by stek29** [comment]
Also, APSL and most licenses allow redistribution and modifications if license info is redistributed and kept.

**Comment by VirtualMac** [comment]
Thanks!

**Comment by stek29** [comment]
Check your local laws anyway, maybe it explicitly says "no darling or go to jail" :)

We don't provide any warranties, as stated in darling's license -- GPL.
