### ISSUE TITLE
can't build darling on fedora 26

### ISSUE THREAD

**Issue by Kidlike** [darlinghq/darling#338]
I followed the instructions here:

https://wiki.darlinghq.org/build_instructions

When I run `make`, it throws this error:
```
[ 95%] Built target elf
[ 95%] Built target dwarf
[ 95%] Built target ctf
[ 95%] Linking CXX shared library libdtrace.dylib
ld: warning: directory not found for option '-F/System/Library/Frameworks/'
ld: warning: -rpath cannot be used with dylibs that will be in the dyld shared cache
ld: warning: directory not found for option '-F/System/Library/Frameworks/'
ld: warning: -rpath cannot be used with dylibs that will be in the dyld shared cache
[ 96%] Built target dtrace
[ 96%] Building C object src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics_obj.dir/CGLPixelSurface.o
In file included from /home/vagrant/install/src/darling/darling/src/external/cocotron/CoreGraphics/CGLPixelSurface.m:9:
/home/vagrant/install/src/darling/darling/src/external/cocotron/AppKit/O2Surface_cairo.h:9:9: fatal error: 'cairo.h' file not found
#import <cairo.h>
        ^~~~~~~~~
1 error generated.
make[2]: *** [src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics_obj.dir/build.make:495: src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics_obj.dir/CGLPixelSurface.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:48864: src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics_obj.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This file exists in the following location though:

```
$ locate -r \/cairo.h$
/usr/include/cairo/cairo.h
```

Any ideas ?

Thanks

**Comment by stek29** [comment]
> Any ideas ?

Well, it includes `cairo.h` and not `cairo/cairo.h`, and `/usr/include/cairo` isn't in include path.

**Comment by bugaevc** [comment]
* It builds for me, or at least was building some time ago (I'll check when I get home)
* ` /usr/include/cairo` [should be](https://github.com/darlinghq/darling-cocotron/blob/master/CoreGraphics/CMakeLists.txt#L39) in the include path.

**Comment by bugaevc** [comment]
Yes, it build just fine for me.

Please check the output of `pkg-config --cflags cairo`, it should be:

```
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm
```
And run `make VERBOSE=1` to see the exact command used to build `CGLPixelSurface.m`

**Comment by Kidlike** [comment]
Sorry I'm not very familiar with either make or lib linking :)

```
$ pkg-config --cflags cairo
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fontconfig', required by 'cairo', not found
Package 'freetype2', required by 'cairo', not found
```

I already had `fontconfig` and `fontconfig-devel` installed, but `freetype2` not, and I can't find it with `dnf`.

**Comment by resetnow** [comment]
Do you use rpmfusion repositories? If so, might be worth a try to install freetypr-freeworld (you also get adequate font rendering as a bonus)

**Comment by bugaevc** [comment]
Indeed, it may be that something is wrong because of `freetype-freeworld`. You don't need it on F26+, because it ships with FreeType 2.7, which has [awesome font rendering by default](https://www.freetype.org/freetype2/docs/subpixel-hinting.html)

**Comment by Kidlike** [comment]
I tried with both `freetype-freeworld` installed and not. Exact same result.

I'm doing this on a test VM, which I was previously experimenting with fonts (fedy, some other CORP repos for fonts, etc...).

I will try again with a fresh install.

Also, might be worth mentioning that this is a vagrant image.

**Comment by Kidlike** [comment]
Unfortunately, I tried a fresh install (I attached the image I used), and I get the same issue.

[Vagrantfile.txt](https://github.com/darlinghq/darling/files/1247386/Vagrantfile.txt)

**Comment by bugaevc** [comment]
I've updated build dependencies list in the wiki (and F27 got released), so can you check if this still happens?

**Comment by andyneff** [comment]
I followed the wiki instructions on F27, and never saw this issue.

**Comment by Kidlike** [comment]
In that case the dependency issues have probably been resolved somehow.

I will try to test this as soon as possible.

**Comment by bugaevc** [comment]
> I will try to test this as soon as possible.

**Comment by bugaevc** [comment]
Fedora 26 EOLed a few months ago; besides, I regularly build & test Darling on Fedora and ensure new changes don't break it (e.g. see https://github.com/darlinghq/darling/commit/c28507ac2770125d7e9d804ee87e43db47d6b8ed and https://github.com/darlinghq/darling/commit/107adacd44a881fe42dc264373bea2c8b0671989).

I'm closing this, but feel free to reopen it or a file a new issue if you still have issues.
