### ISSUE TITLE
Cmake needs _kSecAttrLabel from Security.framework

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#340]
running a recent Cmake command line from Cmake app fails:
Make.app/Contents/bin/cmake    
dyld: Symbol not found: _kSecAttrLabel
  Referenced from: /Volumes/SystemRoot/media/ivan/datosx/progs/CMake.app/Contents/bin/cmake
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Volumes/SystemRoot/media/ivan/datosx/progs/CMake.app/Contents/bin/cmake
Abort trap: 6 (core dumped)
Darling [/Volumes/SystemRoot/media/ivan/datosx/progs]$ ls

**Comment by ahyattdev** [comment]
It works now
