### ISSUE TITLE
Brackets app needs ScriptingBridge.framework

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#341]
Brackets.app/Contents/MacOS/Brackets
dyld: Library not loaded: /System/Library/Frameworks/ScriptingBridge.framework/Versions/A/ScriptingBridge
  Referenced from: /Volumes/SystemRoot/media/ivan/datosx/progs/Brackets.app/Contents/MacOS/Brackets
  Reason: image not found
Abort trap: 6 (core dumped)

**Comment by LubosD** [comment]
There is no point in making bug reports that a random app needs a framework we don't have, because we don't have most frameworks... :-/

**Comment by ahyattdev** [comment]
https://github.com/darlinghq/darling/issues/286

Please leave a comment on this issue about missing frameworks.

**Comment by oscarbg** [comment]
Ok understood!
