### ISSUE TITLE
otool failts if /Applications/Xcode.app exists..

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#343]
I see on wiki talk about dyldd but can't find it..
instead I find otool included and it works but if I create /Applications/Xcode via "ln -sf" to real path /Volumes/SystemRoot/media/ivan/datosx/progs/Xcode.app"

using otool fails with
dyld: Library not loaded: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
  Referenced from: /Volumes/SystemRoot/media/ivan/datosx/progs/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Reason: image not found
Abort trap: 6 (core dumped)

I copied AudioToolbox.framework from real Macos but then says founds two archs witl "file too short"

**Comment by stek29** [comment]
You can run darling's built-in cctools with full path, for example /usr/libexec/Developer tools/otool.

I've never tried to symlink Xcode.app tbh

**Comment by bugaevc** [comment]
I don't think Apple's original AudioToolbox will work because for the sound to work on Linux, it needs to be bridged to Alsa/PulseAudio. IIUC, our own version of AudioToolbox implements that, but it wasn't updated for the Mach-O... way of things.

**Comment by oscarbg** [comment]
Interesting seems that you have some early implementation of AudioToolbox..
is much work to convert to "MachO way of things"? perhaps willing to help.. how learning to convert to MachO way?

**Comment by ahyattdev** [comment]
We have AudioToolbox stubs now
