### ISSUE TITLE
[INFO] A few questions

### ISSUE THREAD

**Issue by josepmc** [darlinghq/darling#345]
I've been looking around this project and the wiki and I do have a few questions. Would be great if you could help me with them because I did not find a clear answer to them.

I assume that there could be an updated FAQ as a few of these answers may be known already:
- Has anybody tried to get it working on docker? I'm aware that:
   - It does require privileged mode (for the kernel module).
   - One needs to use (apparently) overlay2 as the docker FS (by default I had AUFS).
- Does brew work under it? The install script fails, but manual installation should be feasible (my VM broke as the kernel module injection is apparently not that stable).
- Can it be used to compile iOS projects? If so, could share some steps on how to? E.g. I'm aware that there's an epic related to XCode tools, but as there's one issue outstanding I assumed it's already done.
- Do you have some kind of chat (e.g. gitter) where this project is discussed?

I'm aware that these questions could be answered by further research and trial - and I may eventually answer them myself - but would be appreciated if someone could lend a hand too.

Thanks in advance!

PS: XCode 8+ comes compressed in .xip. Luckly it can be uncompressed with Darling by using the following [snippet](https://stackoverflow.com/questions/40414645/how-to-extract-xip-archive-using-command-line)

**Comment by LubosD** [comment]
* Running Darling under Docker makes no sense, because Darling itself is a container.
* The iOS toolchain works, but `xcodebuild` does not yet (missing private frameworks) and codesigning probably doesn't work either (we don't have Security.framework working yet, but we're close).
* We use Slack for developer communication, we sometimes appear on IRC.

You can unpack XIP under Darling by running `unxip`.

**Comment by josepmc** [comment]
@LubosD Thanks! Let me follow up on the iOS topic then. So I assume there's no straight method to compile the application and instead we need to clang each file (e.g. create a Makefile) for it to be compiled?
Is there any oneliner that does this for us?

**Comment by stek29** [comment]
@josepmc no, there are no Xcodebuild reimplementations in darling

**Comment by sztomi** [comment]
Hey,

I've arrived here while looking for a way to sign macOS applications on Linux. Seeing this issue is a few months old, has there been any progress on supporting that?
