### ISSUE TITLE
xcode-tools

### ISSUE THREAD

**Issue by npyl** [darlinghq/darling#346]
Looking at the Darwin on ARM project I stumbled upon this Xcode-tools implementation!

I though this could be some help!

[xcode-tools project by b-man](https://github.com/b-man/xcode-tools)

There could be some specific implementation for Darwin on ARM project but I am not sure!

**Comment by stek29** [comment]
Darling already has it's xcode-select and xcrun, see src/xcselect
But thanks for suggestion :)

**Comment by npyl** [comment]
Thats great!!!!

**Comment by stek29** [comment]
It even has some tools like otool/nm without code cli/full installation :)

**Comment by npyl** [comment]
Awesome!!!!
