### ISSUE TITLE
Paths for some cmds don't match macOS path

### ISSUE THREAD

**Issue by stek29** [darlinghq/darling#352]
Following command:
`for tool in chown chgrp stty; do which $tool; done`

Gives this on darling:
```
/bin/chown
/bin/chgrp
/usr/bin/stty
```

And this on macOS:
```
/usr/sbin/chown
/usr/bin/chgrp
/bin/stty
```

This affects Homebrew, for example.

**Comment by ahyattdev** [comment]
👍
