### ISSUE TITLE
memberd missing

### ISSUE THREAD

**Issue by stek29** [darlinghq/darling#353]
Stuff like dsmemberutil depends on it

Also, Homebrew install script checks if user belongs to "admin" group via dsmemberutil and obviously fails.

**Comment by LubosD** [comment]
memberd is now named opendirectoryd. The last OpenDirectory code dump made by Apple was for [macOS 10.7.2](https://opensource.apple.com/release/mac-os-x-1072.html).

**Comment by ahyattdev** [comment]
Discussion on Discord a few months ago concluded that trying to get Apple memberd to work was futile.
