### ISSUE TITLE
Question for installing iTunes 12.7

### ISSUE THREAD

**Issue by trivialfis** [darlinghq/darling#360]
I tried to install iTunes with darling but wasn't successful. Here are some problems I encountered and what I have tried during the process:

1. Itunes comes with a dmg file which contains the following files (from ls):
```
.dmg_background.tiff 
'[HFS+ Private Data]'
'Install iTunes.pkg' 
'Read Before You Install iTunes.app'
.DS_Store
'.HFS+ Private Directory Data'$'\r'
.iTunesIcon
```
and the 'Install iTunes.pkg' doesn't contain the PackageInfo file. So I extracted this pkg file.

2. After extracting the package, there are 5 more pkg directories inside.
```
CoreADI.pkg 
CoreFP.pkg  
Distribution 
iTunesAccess.pkg  
iTunesX.pkg  
MobileDevice.pkg  
Resources
```
I tried to package those into respect archive with xar. But installer inside darling shell said that it can't read gzip header. Then I re-compress the  Payload and Scripts archives inside those pkg sub-directories and then package it again with xar. 

3. After the above two steps, I tried to install one of the pkg file "iTunesX.pkg", the installer was able to execute the install scripts. But many warning appear that said 
```
...
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-audible.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-cd.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-database.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-generic.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-ipa.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-ipg.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-ipsw.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-ite.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-itlp.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-itms.icns
Warning: cannot unlink //Applications/iTunes.app/Contents/Resources/iTunes-movie.icns
...
```
with one warning for each file. The install command I used is from the wiki:
`installer -pkg iTunesX.pkg -target /`
Also notice the weird added "/" before "/Applications" and I don't know how to remove it properly.

4. Nothing is installed.

I built the repo with master branch at a5431f02858b (the latest one). And I use Fedora 26.

I Google around and didn't find any solution or hints. But searching this repo, it seems that iTunes can be installed in some way. So, could you provide some instructions/hints for installing iTunes?

**Comment by LubosD** [comment]
We mention everywhere that GUI software currently does not run.

But we'll look into the unusual .pkg file structure.

**Comment by trivialfis** [comment]
Oh, sorry. How can I missed that. Thanks for the reply.

**Comment by bugaevc** [comment]
The package structure is still an issue though

**Comment by stek29** [comment]
> Also notice the weird added "/" before "/Applications" and I don't know how to remove it properly.

This should not cause any issues.

> But many warning appear that said ...

Likely installer deletes old iTunes installation, and obviously there is none.

**Comment by ahyattdev** [comment]
The installer gives off a lot of errors, but it manages to install all the files as far as I can tell (/Applications/iTunes.app is there).

I think the recent fixes to installer covered this.
