### ISSUE TITLE
crash on calling CC_MD5

### ISSUE THREAD

**Issue by pxb1988** [darlinghq/darling#361]
I have tried to execute clang in darling, it crash when calling the `ld`, after a several logging, i found the `ld` is crashed when calling `CC_MD5`. Here is a little code can repreduce the crash.

````c
#include <stdio.h>
#include <CommonCrypto/CommonDigest.h>
int main() {
printf("hello\n");
char wholeBuffer[567]={0};
int _fileSize = 567;
uint8_t digest[CC_MD5_DIGEST_LENGTH];
CC_MD5(wholeBuffer, _fileSize, digest);
return 0;
}
````

I also tried to use a "independent" md5 in the `CCDigest`, and every things works. i can compile a simple-hello-world program inside darling.
````c
// darling/src/external/commoncrypto/lib/CommonDigest.c
void md5(const unsigned char *input, unsigned int inputLen, unsigned char *output);
int CCDigest(CCDigestAlgorithm alg, const uint8_t *data, size_t len, uint8_t *out)
{
    if(alg == kCCDigestMD5) {
         md5((const unsigned char *)data, ( unsigned int ) len, out);
         return 0;
    }
    const struct ccdigest_info *di;
    
    CC_DEBUG_LOG("Entering Algorithm: %d, %p, %d, %p\n", alg, data, (int) len, out);
    if((di = CCDigestGetDigestInfo(alg)) != NULL) {
        CC_DEBUG_LOG("di is %p", di);
        ccdigest(di, len, data, out);
        return 0;
    }
    return kCCUnimplemented;
}
````
the clang is from xcode, both Xcode8 and Xcode9 is tried.
darling Ra5431f02858b33243445d283c9ee1703494b8aa7
Archlinux `Linux XXX 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`

**Comment by LubosD** [comment]
Thank you. These functions are largely untested (nothing uses them), I guess that changed with new XCode.

**Comment by zaplo00** [comment]
link causes crash with Xcode 7.2, maybe it's different problem but example doesn't work.
