### ISSUE TITLE
can't "make lkm" on Arch Linux (Kernel 4.14.3)

### ISSUE THREAD

**Issue by fredhdx** [darlinghq/darling#362]
"make and install" the main program is fine.

but "make lkm" fails due to error `error: conflicting types for ‘set_fs’` in file `src/lkm/osfmk/i386/proc_reg.h` and `arch/x86/include/asm/uaccess.h`:

In the darling src code `proc_reg.h`, the `set_fs` variable is fenced:

```C++
#ifndef set_fs
static inline void set_fs(uint16_t fs)                                                                                                 
{
›   __asm__ volatile("mov %0, %%fs" : : "r" (fs));
}
#endif
```

In arch kernel file `uaccess.h`, `set_fs` is NOT fenced:

```C++
static inline void set_fs(mm_segment_t fs)
{
	current->thread.addr_limit = fs;
	/* On user-mode return, check fs is correct */
	set_thread_flag(TIF_FSCHECK);
}
```

So I am assuming the error occured because the darling variable is loaded before the Arch variable.

I don't really know or dare to edit the Arch kernel file, so I am wondering if there is a fix on the darling's side, maybe by re-ordering the header file loading sequence?

Thanks a lot.

**Comment by fredhdx** [comment]
How stupid I am, I just comment out the `set_fs` block inside `proc_reg.h` file and it then worked.

But I would like to keep this question open for a while because I am amateur and might not know if there is side-effect by commenting those lines out.

**Comment by LubosD** [comment]
@fredhdx Yes, that's a way of fixing it. Basically, the XNU headers are full of stuff that conflicts with Linux kernel headers. 80% of the stuff in XNU headers isn't really needed for Darling's kernel module, but doing a full clean of the headers would be _totally_ overwhelming, so we go the way of working around collisions as they appear.

**Comment by fredhdx** [comment]
@LubosD Totally agree. Valuable lessons on good code practice on the kernel side I guess.

**Comment by bugaevc** [comment]
This still has to be fixed on our side
