### ISSUE TITLE
LKM deadlocks

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#367]
See kernel log.
[darling_deadlock.txt](https://github.com/darlinghq/darling/files/1619796/darling_deadlock.txt)

**Comment by npyl** [comment]
Hi, the txt file is empty!

**Comment by bugaevc** [comment]
No it's not, it just has a few blank lines at the begging.

**Comment by npyl** [comment]
oh, sorry for this (I opened it on my mac... and it shows blank)
