### ISSUE TITLE
Question about block devices

### ISSUE THREAD

**Issue by artem-nefedov** [darlinghq/darling#371]
Is it possible to access Linux block devices from Darling? The devices are listed inside '/dev/' directory, but any r/w attempt returns 'Permission denied', even though Darling shell is run via 'sudo', and the command itself is also called by 'sudo'. Same thing happens if device is accessed by '/Volumes/SystemRoot/dev/' path. I'm not sure if it's a bug or intended behavior.

**Comment by LubosD** [comment]
I must admit I don't fully remember the UID/EUID/SUID semantics, but you should rather run `darling shell` directly as root and not via sudo, e.g.:

```
sudo su
darling shell
```

We haven't really given much thought to the `/dev` contents yet.

**Comment by artem-nefedov** [comment]
Thank you for the clarification.
As you said, it works if I login into 'root' rather than launch shell via 'sudo'.
Consider adding it to the documentation.

**Comment by bugaevc** [comment]
Running `sudo darling shell` should work for starting the container as root — unless there is already a running container at that `DPREFIX`, in which case it'll just connect to that one (only root is allowed to connect to other users' containers). We should probably print a warning in that case to be more transparent about what's happening.

> Is it possible to access Linux block devices from Darling?

Block devices are named differently under macOS, so consider `/dev` being shared with the host a (perhaps temporary) implementation detail and always access host's `/dev` via `/Volumes/SystemRoot`.

What's your use-case, if you don't mind sharing?

> `sudo su`

Unrelated, but using `sudo -s` (for "shell") instead saves you a `su` invocation.

**Comment by artem-nefedov** [comment]
Actually, I still get 'Permission denied' if I login via `sudo -s`. It only seems to work if I login into root via `su`.
I don't have other Darling shell running at any moment in time.

My goal was to run native `fsck_hfs` on Linux.
It still failed with error:
```
Passing thru unhandled ioctl 0x40046418 on fd 10
Can't get device block size
```
But that's probably beyond the scope of this question.
