### ISSUE TITLE
Access denied on https://wiki.darlinghq.org/

### ISSUE THREAD

**Issue by nirouviere** [darlinghq/darling#373]
Hi,

I'm trying to build darling on my Ubuntu distribution, but when I try to access the [Build Instructions](https://wiki.darlinghq.org/build_instructions), I'm greeted with an 'Access denied' error.

Regards

**Comment by LubosD** [comment]
Fixed. No idea what happened, but all files had bad permission.

**Comment by nirouviere** [comment]
No problem. Thank you for you quick response and reaction.
