### ISSUE TITLE
More important than ever...

### ISSUE THREAD

**Issue by ylluminate** [darlinghq/darling#378]
This project is going to be more important than ever now:
https://www.zerohedge.com/news/2018-04-02/intel-crashes-apple-start-using-own-mac-chips-moving-away-intel

> ... Apple is planning to use its own chips in Mac computers beginning as early as 2020, and replacing processors from its existing partner, Intel.

**Comment by stek29** [comment]
Apple moving to ARM is quite interesting indeed z but is a bit offtopic 
Thanks fir sharing tho

**Comment by stek29** [comment]
Btw even if apple does move to ARM

- By that time probably people would eventually figure out booting iOS on non-apple hardware
- Darling isn't quite about binary translation and emulation

**Comment by ylluminate** [comment]
Yes, I just wanted to document this for your reference. I personally envision the ideal use case of Darling is to replace the Xnu/Darwin system with Linux so as to run things on top of this (and thus to have a superiorly accessible kernel, etc.).

**Comment by stek29** [comment]
Transition to arm also means that they'd likely use proper encryption for system stuff, not the dsmos one
