### ISSUE TITLE
 LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR

### ISSUE THREAD

**Issue by datamaskinen** [darlinghq/darling#386]
Hi there...
I'm on Ubuntu 18.04 ... i do not know if there is some library that is missing in the build instructions for ubuntu...

/opt/darling/build$ cmake ..
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindLibXml2.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/external/xcbuild/Libraries/plist/CMakeLists.txt:69 (find_package)

**Comment by ahyattdev** [comment]
try installing the required packages https://wiki.darlinghq.org/build_instructions

**Comment by datamaskinen** [comment]
yeah i did that but in the Ubuntu line (sudo apt-get xxxx) i can not find LibXml2....
so i am don't know ... is it libxml2-dev package i need  or what is it?

**Comment by bugaevc** [comment]
> is it libxml2-dev package i need or what is it?

Yes, please try installing `libxml2-dev`. If it solves the issue for you, we'll add it to the build instructions.

**Comment by datamaskinen** [comment]
yes it works now ... or at least i have now started to compile it ....
Wonderful job guys and girls ....

**Comment by ahyattdev** [comment]
The wiki page has been updated to reflect this dependency (Arch and Fedora not changed, someone familiar with them must do it).

**Comment by XyloPoP** [comment]
This link is no longer working: https://wiki.darlinghq.org/build_instructions
Where can I install the files from ro correct this?? I am using windows 10

**Comment by CuriousTommy** [comment]
The wiki.darlinghq.org website has been replaced with docs.darlinghq.org

You can find the build instructions here: https://docs.darlinghq.org/build-instructions.html
