### ISSUE TITLE
Build failing on Ubuntu 16.04.4 x64

### ISSUE THREAD

**Issue by pmannle** [darlinghq/darling#389]
I'm trying to run an apple pkg java library called iTMSTransporter on linux (anyone tried this?)

But, I can't get past the darling install. When I run make I getting a this pointer error:

/usr/local/darling/src/external/xcbuild/Libraries/pbxbuild/Sources/FileTypeResolver.cpp:34:70: error: default initialization of an object of const type 'const std::unordered_set<pbxspec::PBX::FileType::shared_ptr>'
      (aka 'const unordered_set<shared_ptr<pbxspec::PBX::FileType> >') without a user-provided default constructor
        const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;
                                                                     ^
                                                                             {}
1 error generated.
src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/build.make:158: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o' failed
make[2]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o] Error 1
CMakeFiles/Makefile2:4209: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all' failed
make[1]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Dekken** [comment]
I'm seeing this on Debian 9 with GCC 6.3.0

**Comment by Dekken** [comment]
here's a diff

diff --git a/Libraries/pbxbuild/Sources/FileTypeResolver.cpp b/Libraries/pbxbuild/Sources/FileTypeResolver.cpp
index 0b978b07..935d7f55 100644
--- a/Libraries/pbxbuild/Sources/FileTypeResolver.cpp
+++ b/Libraries/pbxbuild/Sources/FileTypeResolver.cpp
@@ -31,8 +31,7 @@ SortedFileTypes(std::vector<pbxspec::PBX::FileType::shared_ptr> const &fileTypes
         if (fileType->base() != nullptr) {
             graph.insert(fileType->base(), { fileType });
         }
-        const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;
-        graph.insert(fileType, emptySet);
+        graph.insert(fileType, {{}});
     }

**Comment by LubosD** [comment]
@Dekken GCC is not used for build, what's your version of Clang?

**Comment by Dekken** [comment]
```
clang -v
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64```

**Comment by senseisimple** [comment]
For Debian 9 it is necessary to install  `clang-4.0`; the default `clang` package is 3.8

**Comment by ahyattdev** [comment]
@senseisimple thanks for the package list, the wiki now includes instructions for Debian 9.

https://wiki.darlinghq.org/build_instructions
