### ISSUE TITLE
Use of cocotron as Cocoa implementation

### ISSUE THREAD

**Issue by RobertoEstrada** [darlinghq/darling#39]
Hi, I've been recently aware of this project and saw that it wants to make use of GNUstep as runtime. 

I don't know if you know the Cocotron project, but has been active for many years trying to provide a MIT licensed implementation of the whole Cocoa environment and I think it resembles more closely the full Cocoa runtime and frameworks than GNUStep, is cross platform and has a nearly full implementation so the need of reinventing the wheel can be reduced.

More info on the Cocotron project here: https://code.google.com/p/cocotron/

Hope this helps to the project.

**Comment by dumblob** [comment]
@LubosD how far are you with Qt Quick? If not far at all, I would reconsider the decision and tried to stick with something way simpler to embed like [Nuklear](https://github.com/vurtun/nuklear ).

**Comment by LubosD** [comment]
@dumblob Well, I don't need a GUI toolkit as much as I need a rendering system. For that purpose, Qt is the best.

**Comment by dumblob** [comment]
@LubosD oops, then I totally misunderstood it. What is the issue with using any of the existing well-proven rendering systems like Cairo (in case 2D is needed), SDL (in case 3D is needed), and many others?

**Comment by LubosD** [comment]
@dumblob Qt's pipeline is fully HW accelerated and provides functionality that matches Core Animation. Compared to Qt, Cairo is a "trivial" 2D drawing library.

**Comment by dumblob** [comment]
Ok, if Qt matches the Core Animation functionality (I did not compare it), then the Qt constraints and also the blob size should be a minor issue compared to reimplementing the non-trivial functionality.

Btw already in 2012 even Intel stated Cairo is very well accelerated https://lists.cairographics.org/archives/cairo/2012-October/023609.html , not to mention the official project page stating the same https://www.cairographics.org/ .

**Comment by lieff** [comment]
Qt is a GUI toolkit. Hardware accelerated 2d renderings: cairo, skia, fastuidraw.
CA Layers is some sort of OpenGL textures as I know, which transformed and composited in some way.
Pure OpenGL is preferred here (or use parts from other compositors such android SurfaceFlinger), do not see any easy way using QT here.

**Comment by LubosD** [comment]
@lieff Then you know very little about Qt.

**Comment by lieff** [comment]
May be. I know QT well supports OpenGL, I can do something like
[code]
Item {
    id: layerRoot
    layer.enabled: true
    layer.effect: ShaderEffect {
        fragmentShader: "
            uniform lowp sampler2D source; // this item
            uniform lowp float qt_Opacity; // inherited opacity of this item
            varying highp vec2 qt_TexCoord0;
            void main() {
                lowp vec4 p = texture2D(source, qt_TexCoord0);
                lowp float g = dot(p.xyz, vec3(0.344, 0.5, 0.156));
                gl_FragColor = vec4(g, g, g, p.a) * qt_Opacity;
            }"
    }
[/code]
But not sure it will be less code with Obj-С->QT Quick communication\sync of draw calls than pure gl.

**Comment by LubosD** [comment]
I'd say it will be less code + the great added benefit of portability and higher abstraction (e.g. from X to Wayland, from OpenGL to Vulkan or whatever). I know GNUstep went the way of using backends such as art and cairo and it's a slow mess with a ton of hacks for specific window managers.

**Comment by lieff** [comment]
No no cairo is what draw shapes (it also uses gl shaders to accelerate drawing, it's not fastest, skia is fast and used in browsers, fastuidraw seems fastest), it's not needed for composition. We need deep down to pure opengl anyway. Following code must work:
```
... associate CA Layer with framebuffer
    m_context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
    [EAGLContext setCurrentContext:m_context];
    [m_context renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer *)m_layer];
    glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_WIDTH, &m_backingWidth);
    glGetRenderbufferParameteriv(GL_RENDERBUFFER, GL_RENDERBUFFER_HEIGHT, &m_backingHeight);
... draw
    glClear(GL_COLOR_BUFFER_BIT);
... present
    [m_context presentRenderbuffer:GL_RENDERBUFFER];
    glFinish();
```
All this pure gl calls must draw into QT Quick layer pipeline, is it possible easily?

**Comment by LubosD** [comment]
Unfortunately, I can't give you a concrete answer. Qt appears to be closest to what can help expedite the development and I made some nice experiments with its scene graph in the past...

This is probably the most difficult decision of all:
a) Start developing and build it all from lowest layers up, risking that I'll get totally swamped writing code I can never finish without significant help from others.
b) Start developing and rely on another important framework, risking that not all is achievable with it.
c) Continue developing something from GNUstep (such as Opal or QuartzCore), risking they made some very bad choices and losing lots of time.

I've been burnt by both b) and c) in the past, but sometimes I feel that with a) macOS will cease to exist before something great is accomplished.

**Comment by LubosD** [comment]
Just as an example of how many annoyances must one overcome: the SDL you propose would seem like a great fit for abstracting away the process of creating a native window and receiving input events etc. At least at the first sight. Except that the design of SDL's video backends doesn't decouple running the event loop from the actual display server interaction :-(

For any AppKit implementation, however, it is crucial that the main event loop is run by CoreFoundation / libdispatch.

**Comment by lieff** [comment]
I`m not proposing sdl\glfw\glu for creating windows, neither deny them. Window creation lib can be any that fits (it cat be QT, wxWidgets or native egl\wgl as well). What I propose is use native gl code to composite CALayers of UIView.layer instances (use framebuffer textures). The only requirement to lib: support retrieving native gl context associated with window and working with native gl calls, just because CA supports that.

May be QT can be used for composition, but for now I do not know any documented way how to work with QT Quick layers framebuffers outside. May be C++ QOpenGLFramebufferObject\QOffscreenSurface can do the job, but I'm not sure it's better too. I have bad experience intermixing native and QT gl on sailfish. Also EAGLContext supports multiThreaded = YES, so we need own wrappers with locking anyway.
