### ISSUE TITLE
Consider moving away from Github

### ISSUE THREAD

**Issue by elypter** [darlinghq/darling#392]
If you haven't read it already Microsoft has bought Github. This feels very much like a tactical aquisition to combat free software. They are also known to let projects they bought from competitors rot or to actively make them bad. If you want to migrate to gitlab then it is quite easy. https://www.youtube.com/watch?v=VYOXuOg9tQI however i would not trust Microsoft to keep the required API accessible forever if they see users migrating.

**Comment by mitchellurgero** [comment]
Microsoft 1,800+ repositories on GitHub of FREE and Open Source software. Powershell and .NET Framework to name some popular ones. Not that I am saying this isn't a "tactical aquisition to combat free software" however it is very unlikely. Microsoft has been slowly moving towards free and open source for years now. Do some fact checking / research on Microsoft's now free (and some open source) projects. You will be surprised to see how far they are going with it. (Not to mention their on going partnership with Canonical).

Windows 10 in fact is free to use as well now, so really I do not see Microsoft doing anything negative with GitHub.

That being said: Self-hosting is always a better, more clear solution than almost any other cloud based hosting provider. I self host my own Git for private projects, my own web site, email, and NextCloud services.

GitLab, Gitea, Gogs, etc are all great ways to self-host git services with beautiful UI's to match.

Hmm I might have missed something, so I might edit this later.

**Comment by elypter** [comment]
microsoft has been moving towards using free software but that is for their own benefit because it either costs less or works better. this doesn't mean that they will treat competing software better in any way. instead of having a front line between proprietary and free software it might soon be straight through the terretory of free software. microsoft has stepped away from hating free software because they cannot afford it anymore but they still havent stepped away from being manipulative and attempting to lock people down where they can. a project platform is very vulnerable to this because everything that affects developers also affects all the users of their software. every change on a platform has a slight impact on its users, even just seemingly neutral design choices. even if microsoft doesnt want to deliberately harm free software they will always chose the option that benefits them more than others. even a small unnoticeable bias will have a considerable effect because of the multiplying aspect of influencing developers.

**Comment by mitchellurgero** [comment]
Trust me bud, I am not saying you are wrong per-se, I am just saying that Microsoft could have other plans, or maybe they wont change a thing. Who knows? Only Time will tell.

**Comment by elypter** [comment]
> EDIT: Also - Microsoft has a pretty good relationship with GNU/Linux Developers like Canonical afaik.

i don't know if that is relieving or frightening.

**Comment by mitchellurgero** [comment]
> i don't know if that is relieving or frightening.

Just to keep the conversation going in a positive and productive direction, here is a website you may or may not enjoy reading: https://open.microsoft.com/

Yes it is from Microsoft, but this is Microsoft's managers, project leaders, and employees, not big corporate ass-hats. I feel like everyday Microsoft is embracing open source more and more.

**Comment by elypter** [comment]
>sometimes big corporate =/= lying, scummy, shitty company

that is where the problem lies. customer, employees or even managers may have the best of trust and motives but that doesn't matter because in publicly traded companies there are always the investors at the top. it is just a question who they fool. they may decide to employ trustworthy people but their job is to generate trust. that trust is just one of may values of the company that is either grown or made into money. microsoft is in a phase of transformation. they go where the new money is so they tread softly. in the pc market where they have a monopoly and that is declining they go in the cash out phase hence windows 10 spy and adware. one day when they think they achieved their goals the switch the management and go into cashout in the open source world. any company where the ceo can be easily switched out is an evil scummy company.

**Comment by ahyattdev** [comment]
The bottom line is that it's hard to see a reason to pick up everything and move unless GitHub does something we don't like that directly affects us. That means breaking links, giving contributors a new website they may need to learn how to use. Microsoft hasn't changed anything that affects us here on GitHub.

**Comment by mitchellurgero** [comment]
> The bottom line is that it's hard to see a reason to pick up everything and move unless GitHub does something we don't like that directly affects us. That means breaking links, giving contributors a new website they may need to learn how to use. Microsoft hasn't changed anything that affects us here on GitHub.

Couldn't agree more.

**Comment by LubosD** [comment]
I think we can close the debate for now. We've reserved organization names on Bitbucket and GitLab just in case.
