### ISSUE TITLE
[ 53%] Generating fontconfig.c

### ISSUE THREAD

**Issue by HidePerson** [darlinghq/darling#394]
```
Cannot load libfontconfig.so: libfontconfig.so: cannot open shared object file: No such file or directory
src/native/CMakeFiles/fontconfig.dir/build.make:61: recipe for target 'src/native/fontconfig.c' failed
make[2]: *** [src/native/fontconfig.c] Error 1
make[2]: *** Deleting file 'src/native/fontconfig.c'
CMakeFiles/Makefile2:32126: recipe for target 'src/native/CMakeFiles/fontconfig.dir/all' failed
make[1]: *** [src/native/CMakeFiles/fontconfig.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by HidePerson** [comment]
Linux Debian 9 Stretch
Clang 4.0.1
All packages are installed.

**Comment by LubosD** [comment]
You sure you have libfontconfig.so?

**Comment by bugaevc** [comment]
> All packages are installed.

Strangely, our build instructions don't list Fc for Debian/Ubuntu

**Comment by HidePerson** [comment]
> You sure you have libfontconfig.so?

This file does not exist. But where can I download it? What library is it from?

`fontconfig-config is already the newest version (2.13.0-5)`

**Comment by HidePerson** [comment]
`libfontconfig1 is already the newest version (2.13.0-5).`

**Comment by bugaevc** [comment]
Try `libfontconfig1-dev`

**Comment by HidePerson** [comment]
> Try libfontconfig1-dev
This solved my problem, but there was another.
```
[ 53%] Generating cairo.c
Cannot load libcairo.so: libcairo.so: cannot open shared object file: No such file or directory
```
Is solved like this:
`apt-get install libcairo2 && apt-get install libcairo2-dev`
Thanks!)
