### ISSUE TITLE
(not spam)why not copy code of winehq(layer libs and compilation real time,not the windows part) code in darling?

### ISSUE THREAD

**Issue by raiogam** [darlinghq/darling#396]
why not copy code of winehq(layer libs and compilation real time,not the windows part) code in darling?
not copy all code(not turn darling a window emu) but the part  of skeleton(frame[because of the layers lib and frameworks of  layer of compilation real time,not the windows part]) of code is good and  good model and i never say for turn darling a windows emulation and yeas to a copy the code or/and edit to make better layer of emulation
please anwser with technical detail of why or not above question?

**Comment by LubosD** [comment]
WineHQ is an PE executable loader + reimplementation of Windows APIs. There is absolutely nothing that Darling could reuse.
