### ISSUE TITLE
Site copyright outdated

### ISSUE THREAD

**Issue by brodycas3** [darlinghq/darling#397]
The copyright on the bottom of the site still says 2017 and on the contact page says 2016
The site may also be outdated in other ways I haven't noticed.

![image](https://user-images.githubusercontent.com/19770864/41265517-ac437e2e-6dc0-11e8-8554-7ec2df25cdcd.png)

![image](https://user-images.githubusercontent.com/19770864/41265520-b17ba236-6dc0-11e8-8e4a-9764d6ac0884.png)

**Comment by brodycas3** [comment]
The copyright is still outdated unless the website just hasn't been updated yet

**Comment by ahyattdev** [comment]
@LubosD how do we get the web server to clone the website again?

**Comment by LubosD** [comment]
Manually... Done!
