### ISSUE TITLE
can not find AudioUint.framwork

### ISSUE THREAD

**Issue by tmyk104117** [darlinghq/darling#399]

**Comment by LubosD** [comment]
We lack a ton of frameworks, no point in opening issues like this.

**Comment by bugaevc** [comment]
I think we actually have an `AudioUnit.framework` of some sort, but it's not being built/installed?

**Comment by LubosD** [comment]
Yes, among other things because it should do calls into `CoreAudio` instead of talking to ALSA/PA directly.
