### ISSUE TITLE
Cannot make / Ubuntu 13.04 x86_64

### ISSUE THREAD

**Issue by kbeezie** [darlinghq/darling#40]
Cannot complete make with darling (pulled as if 8/8/2013 9:15AM EST/GMT-5)

~/darling$ CC=clang CXX=clang++ cmake .
-- No build type selected, default to Debug
-- This is a 64-bit build
-- Building ObjC ABI 2
You have called ADD_LIBRARY for library Carbon without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library AppKit without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Warning (dev) at src/thin/CMakeLists.txt:12 (add_library):
  Policy CMP0002 is not set: Logical target names must be globally unique.
  Run "cmake --help-policy CMP0002" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

You have called ADD_LIBRARY for library Carbon without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library auto without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kbeezie/darling

~/darling$ make
[  4%] Built target util
[  7%] Built target mach-o
[  8%] Built target motool
[  9%] Building CXX object src/dyld/CMakeFiles/dyld.dir/dl_public.o
/home/kbeezie/darling/src/dyld/dl_public.cpp:15:8: error: expected unqualified-id
static thread_local char g_lastError[1024];
       ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:16:8: error: expected unqualified-id
static thread_local bool g_lastErrorRead = false;
       ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:24:10: error: use of undeclared identifier 'g_lastError'
        strncpy(g_lastError, str.c_str(), sizeof(g_lastError));
                ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:25:2: error: use of undeclared identifier 'g_lastError'
        g_lastError[sizeof(g_lastError)-1] = 0;
        ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:25:21: error: use of undeclared identifier 'g_lastError'
        g_lastError[sizeof(g_lastError)-1] = 0;
                           ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:26:2: error: use of undeclared identifier 'g_lastErrorRead'
        g_lastErrorRead = false;
        ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:111:6: error: use of undeclared identifier 'g_lastErrorRead'
        if (g_lastErrorRead || !g_lastError[0])
            ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:111:26: error: use of undeclared identifier 'g_lastError'
        if (g_lastErrorRead || !g_lastError[0])
                                ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:114:2: error: use of undeclared identifier 'g_lastErrorRead'
        g_lastErrorRead = true;
        ^
/home/kbeezie/darling/src/dyld/dl_public.cpp:115:9: error: use of undeclared identifier 'g_lastError'
        return g_lastError;
               ^
10 errors generated.
make[2]: *** [src/dyld/CMakeFiles/dyld.dir/dl_public.o] Error 1
make[1]: *** [src/dyld/CMakeFiles/dyld.dir/all] Error 2
make: *** [all] Error 2

**Comment by LubosD** [comment]
Darling now has Continuous Integration which checks if build works against Debian Stable. Ubuntu should work just fine as well.
