### ISSUE TITLE
Write a GDB Jit Debug Info Reader

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#41]
Documentation at http://www.sourceware.org/gdb/onlinedocs/gdb/Writing-JIT-Debug-Info-Readers.html

It needs to be considered whether recreating ELF in memory is really harder than providing callbacks like `gdb_reader_funcs::unwind`.

**Comment by LubosD** [comment]
This is now finally being worked on. So far I can provide Mach-O symbol names to gdb, now I'm working on providing the .eh_frame data.

**Comment by ahyattdev** [comment]
Closing because we are not leaning towards LLDB

**Comment by ahyattdev** [comment]
@stek29 thanks, that was a critical typo 😆
