### ISSUE TITLE
[Documentation] Roadmap 

### ISSUE THREAD

**Issue by ErikEklund** [darlinghq/darling#413]
First, awesome job on this amazing project. Following it with great interest.

A "feature request" I have is to have a visual roadmap for the project on either Github or the project site. That is, a breakdown of either tasks, libraries, APIs or what makes most sense and some kind of progress indicator for each. Perhaps also milestones / releases mapped out.

I realize this would take some work to maintain, but I'm sure a lot of people would find it very informative.

**Comment by ahyattdev** [comment]
I think the discussion going on in Discord now covers this.
