### ISSUE TITLE
Fakechroot ELF code

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#415]
As a less radical alternative to #377

**Comment by LubosD** [comment]
My current plan is to fork fakechroot's code and modify its chroot expand/narrow functions located here: https://github.com/dex4er/fakechroot/blob/master/src/libfakechroot.h

I've already implemented a piece of kernel (module) code that accepts:

1. the chroot file descriptor 
2. path to evaluate
3. and optionally a base directory descriptor (for all the *at() syscalls)

and produces a valid absolute path wrt to the current processes _real_ root. This code would be placed into our LKM.
