### ISSUE TITLE
JRE 10 java exits without output

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#426]

**Comment by tajetaje** [comment]
Unfortunately there is very little information on this issue, but I just wanted to bump it by saying that the same issue persists on Java 11 (If that is it is the same issue). In my case, any Java program is run whether it be java, any one of the java binaries (tried them all), or even maven run with no errors, but do absolutely nothing. Type the command press enter, and it immediately returns.

**Comment by ahyattdev** [comment]
AdoptOpenJDK 11 actually starts now, so we can close this.
