### ISSUE TITLE
Unable to clone my fork of `darlinghq`

### ISSUE THREAD

**Issue by seanballais** [darlinghq/darling#430]
I am attempting to clone my fork of `darlinghq` to my local machine. However, I get the following message.

```
Submodule 'src/external/zsh' (https://github.com/seanballais/darling-zsh.git) registered for path 'src/external/zsh'
Submodule 'src/lkm' (https://github.com/seanballais/darling-newlkm.git) registered for path 'src/lkm'
Cloning into 'src/external/DSTools'...
Username for 'https://github.com': seanballais
Password for 'https://seanballais@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/seanballais/darling-DSTools.git/'
fatal: clone of 'https://github.com/seanballais/darling-DSTools.git' into submodule path 'src/external/DSTools' failed
```

It also fails when I use SSH. Do I need to clone from this repo (and not my fork) in order to clone successfully? Or is the issue from somewhere else?

When I decide to start contributing to projects, I start with forking the project repository so that I could easily modify the code. I would just need to do PR to let my changes be merged with project.

**Comment by bugaevc** [comment]
Yes, this is a consequence of using submodules the way that we do. Your options are:
* manually change submodule paths in `.gitmodules` to point to `https://github.com/darlinghq/darling-foo.git` instead of `../darling-foo.git`
* fork every single `darling-` repo, not just the root one
* clone from this repo, not your fork, and then add your fork as another remote
* make a valuable contribution, get on the team, get commit access to this repo without a need for forks ;)

**Comment by seanballais** [comment]
Thanks!

The third option seems the easiest option. I'll take that. The fourth one seems like an interesting challenge.

Would it be nice to include your answer to the official documentation? That'll help out developers new to the project.

**Comment by bugaevc** [comment]
@ahyattdev will you please add it to https://wiki.darlinghq.org/contributing

**Comment by ahyattdev** [comment]
@bugaevc the wiki has the one where you add your fork as a remote. The others seem pretty complicated! Which ones do you want on the wiki?

**Comment by bugaevc** [comment]
Right, but can you make it more clear what problem that works around — that we use submodules and relative paths, so you cannot just clone from your fork, etc. etc. And let's add links to that page and to https://wiki.darlinghq.org/what_to_try to the README so people know where to find info.

**Comment by TheBrokenRail** [comment]
You can also use ```git remote set-url origin https://github.com/darlinghq/darling.git``` after you have cloned the repository, but before you clone the submodules. You will have to reverse when committing though.
