### ISSUE TITLE
QUESTION: Is this new 10.13.6 source-release by apple in any way useful to Darling.

### ISSUE THREAD

**Issue by Guy1524** [darlinghq/darling#434]
https://opensource.apple.com/release/macos-10136.html

Has this stuff been released before, or will this have any impact on the project?  Is there any way you could use these open source components with darling directly instead of re-implementing them.

**Comment by bugaevc** [comment]
Hi,

I was actually surprised to see this being discussed on r/linux as if it was something completely new & unprecedented. Apple has been releasing the source code of Darwin (the core OS underlying macOS, iOS and others) for years, from the very 10.0 release. That link is for the latest code drop — you can see & navigate all of them at their front page, https://opensource.apple.com/

And yes, we are already using many of these components in Darling without reimplementing them! Everything from Mach and dyld to Core Foundation, JavaScriptCore and objc4. Without Darwin sources, it'd be nearly impossible and definitely much harder, to achieve the level of quirk-for-quirk compatibility that Darling has today.

So yes, this is not a new thing, we are well aware of it and have been making use if it for a long time. And before you ask, yes, we know about GNUstep, Cocotron, Swift Foundation, Apportable, winobjc and other Cocoa implementations, and we make use of them when we can, too.

Nevertheless, appreciate your trying to help 😀

**Comment by Guy1524** [comment]
Ah, thank you for the information!
