### ISSUE TITLE
crash on zipping file in darling

### ISSUE THREAD

**Issue by pxb1988** [darlinghq/darling#435]
I use the `zip` inside darling to zip some png files, it crash on a png of size 2585 bytes. the png is from ipa built by xcode

```
Darling [XXXXX]$ zip -9 a.zip AppIcon40x40@2x.png
  adding: AppIcon40x40@2x.png


zip error: Interrupted (aborting)
```

after some logging, i find the code crashed on function `fseekable`, it is called by function `filecompress` in `zip/zip30/zipup.c`

```c
         err = deflate(&zstrm, Z_FINISH);
         if (maybe_stored) {
             if (err == Z_STREAM_END && zstrm.total_out >= zstrm.total_in &&
                 fseekable(zipfile)) {   // !!! crashed here !!!
                 /* deflation does not reduce size, switch to STORE method */
                 unsigned len_out = (unsigned)zstrm.total_in;
                 if (zfwrite(f_ibuf, 1, len_out) != len_out) {

```
the var `zipfile` is the filename of type `const char*`, not the type `FILE *` expected by `fseekable`.

changing to `fseekable(y)` solves the crash

```patch
From 0d93a71c1b77a5f8ab3ecab6b01bb6e5b7a02db3 Mon Sep 17 00:00:00 2001
From: Bob Pan <pxb1988@gmail.com>
Date: Thu, 11 Oct 2018 13:53:58 +0800
Subject: [PATCH] fix "zip error: Interrupted (aborting)" on some png file

---
 zip/zip30/zipup.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/zip/zip30/zipup.c b/zip/zip30/zipup.c
index 39f7d9c..9f65996 100644
--- a/zip/zip30/zipup.c
+++ b/zip/zip30/zipup.c
@@ -1538,7 +1538,7 @@ local zoff_t filecompress(z_entry, cmpr_method)
         err = deflate(&zstrm, Z_FINISH);
         if (maybe_stored) {
             if (err == Z_STREAM_END && zstrm.total_out >= zstrm.total_in &&
-                fseekable(zipfile)) {
+                fseekable(y)) {
                 /* deflation does not reduce size, switch to STORE method */
                 unsigned len_out = (unsigned)zstrm.total_in;
                 if (zfwrite(f_ibuf, 1, len_out) != len_out) {
@@ -1874,7 +1874,7 @@ int *cmpr_method;
              */
             if (err == BZ_STREAM_END
                 && bstrm.total_out_lo32 >= bstrm.total_in_lo32
-                && fseekable(zipfile)) {
+                && fseekable(y)) {
                 /* BZIP2 compress does not reduce size,
                    switch to STORE method */
                 unsigned len_out = (unsigned)bstrm.total_in_lo32;
-- 
2.19.1

```

darling version 06475075f5a3c6fc3cad3f50a0c4ce45bc2e1a85
zip version 3ab7ab221633379c591ad93e5150afe528e9bf7f

**Comment by bugaevc** [comment]
Is the error present in the Apple's upstream zip sources (https://opensource.apple.com/source/zip/)? Has it been fixed in a new version (that we should upgrade to)? Are we actually applying their [patches](https://github.com/darlinghq/darling-zip/blob/master/zip/patch-Apple) in our CMake build?

**Comment by pxb1988** [comment]
seams the error is persent in Apple's `zip-11.1`,  the bugy code is is wrapped in `USE_ZLIB`

```c
#ifdef USE_ZLIB
    BUGGY here 
#else /* !USE_ZLIB */
    ...
#endif /* ?USE_ZLIB */
```
do we need undefine `USE_ZLIB`  ?

**Comment by bugaevc** [comment]
Does `zip` link to `libz.dylib` on macOS?

`USE_ZLIB` is defined [here](https://github.com/darlinghq/darling-zip/blob/master/zip/zip30/CMakeLists.txt#L12), can you check whether removing it (and unlinking libz) breaks anything?

**Comment by stek29** [comment]
@bugaevc 
> Does `zip` link to `libz.dylib` on macOS?

No, it does not.
```
❯ jtool -l /usr/bin/zip | grep DYLIB
LC 12: LC_LOAD_DYLIB         	/usr/lib/libSystem.B.dylib
```

**Comment by pxb1988** [comment]
> Does `zip` link to `libz.dylib` on macOS?
> 
> `USE_ZLIB` is defined [here](https://github.com/darlinghq/darling-zip/blob/master/zip/zip30/CMakeLists.txt#L12), can you check whether removing it (and unlinking libz) breaks anything?

i have confirmed `zip` is working fine without `-DUSE_ZLIB`

**Comment by bugaevc** [comment]
So, somebody commit it then? Or do you @pxb1988 want to make a pull request?
