### ISSUE TITLE
System Freeze

### ISSUE THREAD

**Issue by chunk734** [darlinghq/darling#441]
I am trying to ssh in to a user whose default shell i have defined as darling shell,but as soon as i try it ,the whole system freezes.Can you suggest something ??
I am using Ubuntu 16.04, 4GB RAM
Please help...

**Comment by bugaevc** [comment]
We'd need more details. What are you doing exactly, have you created a separate Linux user whose default shell is set to `darling shell`? Are you sure you've set it up correctly (`/etc/shells` and stuff)? Do you have any logs (try `dmesg -n 8` to make the kernel print everything to the console)?

**Comment by LubosD** [comment]
I don't think this is a good idea in general. `darling shell` is not a shell, it's also a trigger to create a new container.

**Comment by ahyattdev** [comment]
I use libvirt and qemu, no issues for a while.

**Comment by cryoff** [comment]
I have the same issue, using VirtualBox to run Ubuntu 20.04 to run darlinghq
