### ISSUE TITLE
Darling shell doesn't work with Linux 4.19-rc8

### ISSUE THREAD

**Issue by woachk** [darlinghq/darling#443]
"Cannot open mnt namespace file: No such file or directory" is the error message that I get.
strace also ends with a bunch of: "--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f6af353d9eb} ---" in kernel logs.

There are also issues in the kernel module.

[27428.209925] WARNING: CPU: 0 PID: 31975 at mm/slab_common.c:93 kmem_cache_create_usercopy+0x225/0x260

Spaces aren't allowed there...

**Comment by woachk** [comment]
setsebool -P mmap_low_allowed 1 made Darling work, so the kernel warnings remain...

**Comment by LubosD** [comment]
We don't really support SELinux...

**Comment by woachk** [comment]
@LubosD ok, so the cache issue (that is also there for other projects too) is that you aren't allowed to use spaces when creating if you don't want the MM to complain when CONFIG_DEBUG_VM is enabled. It's quite a straightforward fix.

About SELinux, I have some overrides for nVidia drivers to work, so one more doesn't change much at this point.

**Comment by ahyattdev** [comment]
I saw an instance of this message too on Ubuntu 18.10.

`Cannot open mnt namespace file`

It could be some sort of race condition because I ran `darling shell` immediately after and it succeeded.
