### ISSUE TITLE
Xcode 9 and 10 need some stubs

### ISSUE THREAD

**Issue by woachk** [darlinghq/darling#445]
This prevents running Xcode 9 CLI tools or any other recent Swift version.

**Comment by Dekken** [comment]
XCode comes with a version of make, so I just replaced the "system" one with that.

**Comment by Dekken** [comment]
There's at least three (and counting)

```
NSAffectedObjectsErrorKey
NSPersistentStoreSaveConflictsErrorKey
NSValidationKeyErrorKey
```

**Comment by ahyattdev** [comment]
Next ones needed:

```
dyld: Symbol not found: __xpc_event_key_name
  Referenced from: /Volumes/SystemRoot/media/sf_Applications/Xcode.app/Contents/MacOS/../Frameworks/libswiftXPC.dylib (which was built for Mac OS X 10.9)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/SystemRoot/media/sf_Applications/Xcode.app/Contents/MacOS/../Frameworks/libswiftXPC.dylib
```

**Comment by Dekken** [comment]
I'm quite ignorant to the internals of all this, but I recall using the same version of XCode previously and not having such problems - maybe I'm mistaken/confused

**Comment by ahyattdev** [comment]
Hi Dekken,

I am going off of all the symbols that the main 'Xcode' application executable relies on here. I'm not sure exactly which program is being run that creates this issue but hopefully this also fixes that.

**Comment by ahyattdev** [comment]
Next is `_kSecAttrAccess`.

**Comment by ahyattdev** [comment]
Next is `_NSAccessibilityActivationPointAttribute`, in AppKit.

**Comment by ahyattdev** [comment]
Next is `_NSAccessibilitySupportsMainThreadIdleNotificationAttribute`, in AppKit

**Comment by ahyattdev** [comment]
Next is `_kCGWindowAlpha`, in CoreGraphics. I will be away for a few days, will pick up later.

**Comment by ahyattdev** [comment]
Next is `_OBJC_CLASS_$_NSScriptCommand` in Foundation.

**Comment by ahyattdev** [comment]
Next is `_OBJC_CLASS_$_CAReplicatorLayer` in QuartzCore.

**Comment by ahyattdev** [comment]
Next is `_NSAnimateBinding` in AppKit.

**Comment by ahyattdev** [comment]
Xcode 10 finally has all the symbols it wants before it starts executing any code. It of course does not work yet, but that is outside of the scope of this issue.

For those who are curious, this is what happens when it is run:

```
objc[23]: Class CIAffineTransform is implemented in both /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage (0x7ffff01a3b20) and /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (0x7ffff36e4860). One of the two will be used. Which one is undefined.
Assertion failed: (isRealized()), function isMetaClass, file /home/andrewhyatt/darling/src/external/objc4/runtime/objc-runtime-new.h, line 1221.
Abort trap: 6 (core dumped)
```

**Comment by ahyattdev** [comment]
Related is #488.
