### ISSUE TITLE
make[2]: *** Нет правила для сборки цели «printwrapgen». Останов.

### ISSUE THREAD

**Issue by D042888-2** [darlinghq/darling#454]
make[2]: *** Нет правила для сборки цели «printwrapgen». Останов.
make[2]: выход из каталога «/mnt/Сборка/darling/darling-0.1.20181127ubuntu1/debbuild»
debian/rules:10: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: выход из каталога «/mnt/Сборка/darling/darling-0.1.20181127ubuntu1»
debian/rules:3: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: ошибка: debian/rules build subprocess returned exit status 2
Собирал deb пакет под Ubuntu 18.04, 18.10

**Comment by bugaevc** [comment]
@LubosD was `printwrapgen` goal [here](https://github.com/darlinghq/darling/blob/master/debian/rules#L10) supposed to run `wrapgen/print_wrapped_elf` or something? The error is that `make` cannot find a rule to build the `printwrapgen` goal when building the Debian package.

@D042888-2 если честно, мы не очень-то проверяем, что пакеты работают — но просто `cmake`, `make`, `make install` должно работать.

**Comment by LubosD** [comment]
I don't know, I didn't write that script AFAIK.

**Comment by bugaevc** [comment]
And we no longer use a separate `Toolchain.cmake`

**Comment by D042888-2** [comment]
Подскажите пожалуйста где чего нужно поменять чтобы собрать deb пакет.
Please tell me where you need to change what to build the deb package.
