### ISSUE TITLE
How to run .app files?

### ISSUE THREAD

**Issue by wusikijeronii** [darlinghq/darling#455]
Hello. How to run .app files?
Now my application is at the applications folder. What's a right command? I've tried that:
darling [software_name]
But I get: 
'software_name' is not a supported command or a file.
I also tried to use darling shell but then I get that:
[software_name] is the directory

**Comment by ahyattdev** [comment]
Hello wusikijeronii,

On macOS and once Darling has it, you can use the `open` command to open anything from applications to documents, as if it was double-clicked in Finder (#425).

For now, you can run `/Applications/MyApp.app/Contents/MacOS/MyApp`, where it is the path to the main executable of the application within its bundle.

As GUI support is limited at this point, it will likely not work as well as you may hope, but we can create a GitHub issue to track it's compatibility if it is a publicly available application.

Hope this helps.

**Comment by bugaevc** [comment]
**In the future**, you'll be able to run either:
`$ darling run /Applications/MyApp.app`
or
`$ darling open /Applications/MyApp.app`
or
`$ darling shell open /Applications/MyApp.app`
on _the host_, or
`Darling [~]$ open /Applications/MyApp.app`
from the Darling shell, and all of these are going to do essentially the same thing, run your app. And you're also going to be able to launch your app the same way you launch other native Linux apps you have installed (some sort of "start" or "applications" menu, depending on your DE).

**For now**,  you should run
`Darling [~]$ /Applications/MyApp.app/MacOS/MyApp`
from the Darling shell.

And programs as complex as Affinity Photo definitely won't work yet, so don't set your hopes too high.

**Comment by NewtronReal** [comment]
Hi I am an Ubuntu user and I am trying to install mac app store using darling. I mount dmg file and installed MacOSXUpd10.6.6.pkg to my folder. But in the folder it is shown a a directory. Can you please help me. And sorry for my bad English. Hope you will understand my problem.

Thanks.

**Comment by dragossido** [comment]
open VirtualDJ.app
LSOpenURLsWithRole STUB
Failed to launch: -4

**Comment by kasaiee** [comment]
@NewtronReal I have the oroblem too

**Comment by samyosm** [comment]
@dragossido I have that same issue as well

**Comment by unxed** [comment]
Trying to run [iTerm2](https://iterm2.com/downloads.html) under Darling. It is distributed as .zip archive containing iTerm.app folder. How do I run it? darling ./iTerm2.app is not working.

Thanks!

**Comment by Jeremi360** [comment]
Try to run Godot if I run godot using by runing Godot exe for inside Godot.app I get:
```
 code: 4
Abort trap: 6
```
but if I run `open Godot.app` I get:
```
Cannot load libtiff.so.5 (ELF): libtiff.so.5: cannot open shared object file: No such file or directory
Abort trap: 6
```

**Comment by CommanderGL** [comment]
@Jeremi360 You need to install libtiff

**Comment by Jeremi360** [comment]
> You need to install libtiff
I tried that using hbrew, on host os is already installed, but it would allow me to do it.
But it doesn't matter now - I trun out I didn't need mac version of godot.

**Comment by Lucachinou** [comment]
[hs_err_pid224.log](https://github.com/user-attachments/files/18022925/hs_err_pid224.log)

**Comment by CuriousTommy** [comment]
Hey @Lucachinou, this issue is about how to launch `.app` apps. For app compatibility issues, please make a new issue (if one does not already exist).
