### ISSUE TITLE
error: implicit declaration of function ‘put_filp’;

### ISSUE THREAD

**Issue by stawrocek** [darlinghq/darling#459]
Hello,
I am trying to build darling's kernel module and it results with an error:

```
darling/src/lkm/darling/traps.c:1462:2: error: implicit declaration of function ‘put_filp’; did you mean ‘get_file’? [-Werror=implicit-function-declaration]
  put_filp(f);
  ^~~~~~~~
  get_file
```

I have already seen this issue: https://github.com/darlinghq/darling/issues/295 but I think it's a different one.

My specs:
Debian
Kernel version 4.19.0-1-amd64
gcc 8.2.0
binutils 2.31

**Comment by LubosD** [comment]
Should be fixed now.

**Comment by stawrocek** [comment]
It compiles now
