### ISSUE TITLE
[Suggestion] Apply for GSOC?

### ISSUE THREAD

**Issue by ErikEklund** [darlinghq/darling#460]
I noticed that applications for open source projects that wants to be part of Google Summer of Code opens up in two weeks, I think Darling would make a great fit. Even if there might be some administrative work, I think it could be a great way to recruit new talent and get some good momentum / progress going for this project.

Just a thought :)

**Comment by stevennyman** [comment]
Organization registration is now open until February 6th at 3pm EST.

**Comment by Kreijstal** [comment]
this would be amazing, I might even hop in

**Comment by stevennyman** [comment]
Organization registration deadline is in 2 weeks.

**Comment by ahyattdev** [comment]
Here is a [wiki page](https://wiki.darlinghq.org/google_summer_of_code) that has been created to track task ideas for GSoC students. Feel free to contribute what you would like to see there. Keep in mind that they should be reasonable specific. If you don't have an account on the wiki please contact the email at the bottom of the [main page](https://wiki.darlinghq.org).

**Comment by stevennyman** [comment]
@ahyattdev  Maybe something involving partial Xcode compatibility? While difficult, it may be an interesting task for college students.

For reference, here are past projects/project ideas from similar organizations that show the size and scope of GSOC projects:
Wine: 
https://wiki.winehq.org/Summer_Of_Code
ReactOS:
https://reactos.org/wiki/Google_Summer_of_Code

**Comment by ErikEklund** [comment]
One day to go! Any action being taken on this?

**Comment by LubosD** [comment]
I think the best we can do is to start preparing for the next year(s).

We need to come up with a list of ideas that make sense and this requires some effort.

**Comment by ErikEklund** [comment]
Too bad we weren't able to get something going for this year. I do know it requires some preparation, that's why the ticket was posted a month before the deadline :). But let's plan for next years GSOC and keep adding to the Wiki list, and hopefully have something more for next year. Closing this as the application date has passed now.
