### ISSUE TITLE
LLDB cannot run a process anymore

### ISSUE THREAD

**Issue by zqxiaojin** [darlinghq/darling#467]
My application fail on run at darling.

So, I want to debug to check it.

However, when I install "Command_Line_Tools_OS_X_10.10_for_Xcode_7.2.dmg" and run lldb to launch my application.

The lldb show "Darling Mach kernel module reports different API level. Aborting."

What can I do for it?

I am OS is ：

~# lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by bugaevc** [comment]
Hi, this is a known issue. with the recent LKM. To work around it, downgrade LKM to https://github.com/darlinghq/darling-newlkm/commit/21732f2d1f73ab6736aeee44ad2e31fa91fa91b7.

**Comment by zqxiaojin** [comment]
Hi, thank you for help!

I go to ./src/lkm/ and checkout "21732f2" version.

Use the following command to rebuild it:
`make lkm
sudo make lkm_install`

However , it show the same error.

What should I do to fix it?

**Comment by bugaevc** [comment]
You have to reload the LKM from/to the running kernel. Either run `sudo rmmode darling_mach` or simply reboot to unload the old (newer) version, then when you run `darling shell` it'll automatically load up the new (older) one.

**Comment by zqxiaojin** [comment]
I reboot the machine

rm  -rf darling/build

and rebuild it "darling" and "lkm"

However , when I try to enter darling shell it show:

> modprobe: ERROR: could not insert 'darling_mach': Exec format error
> Failed to load the kernel module

Is it there some way to remove the old version and reinstall it?

**Comment by zqxiaojin** [comment]
When I switch the src/lkm to least version , and rebuild lkm.

It works.

Should I switch darling's version befor "Nov 8, 2018" ?

**Comment by LubosD** [comment]
The problem should be fixed now. `git pull` in the root of the tree and then run `git submodule update`.

After that run `make lkm` and `sudo make lkm_install` in your build directory.

If you have doubts about whether the kernel module is or isn't loaded and don't want to bother with it, just reboot.

**Comment by zqxiaojin** [comment]
thank you very much , it works!
