### ISSUE TITLE
Remove references to Rudix as it is dead

### ISSUE THREAD

**Issue by tpimh** [darlinghq/darling#474]

**Comment by npyl** [comment]
Why is rudix dead?

**Comment by tpimh** [comment]
rudix.org:

> Thank you for using Rudix all these years! (2005-2018)
> …and good-bye!
> Cry a little tear :_(

**Comment by npyl** [comment]
I saw it but I was wondering if you knew the real reasons behind this... I guess nobody knows...

**Comment by ahyattdev** [comment]
The new website doesn't have Rudix on it

**Comment by tpimh** [comment]
README.md still has it

**Comment by gusbemacbe** [comment]
@tpimh, @npyl and @ahyattdev 

It seems that Rudix is resurrected. The latest commit was 5 days ago. Check: https://github.com/rudix-mac/rudix. The site https://rudix.org/ is also alive now.
