### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by baerbock** [darlinghq/darling#477]
I'm building with [this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=darling-git). How may I overcome this error:
```
[  3%] Linking CXX executable x86_64-apple-darwin11-ld
In file included from ./src/external/compiler-rt/lib/builtins/emutls.c:10:

./src/darling/platform-include/pthread.h:326:5: warning: declaration of built-in function 'pthread_create' requires inclusion of the header <pthread.h> [-Wbuiltin-requires-header]
int pthread_create(pthread_t _Nullable * _Nonnull __restrict,
    ^
1 warning generated.
In file included from ./src/external/compiler-rt/lib/builtins/emutls.c:10:
./src/darling/platform-include/pthread.h:326:5: warning: declaration of built-in function 'pthread_create' requires inclusion of the header <pthread.h> [-Wbuiltin-requires-header]
int pthread_create(pthread_t _Nullable * _Nonnull __restrict,
    ^
[  3%] Built target compiler_rt_x86_64
1 warning generated.
[  3%] Built target compiler_rt_i386
[  3%] Built target x86_64-apple-darwin11-ld
make: *** [Makefile:130: all] Error 2
```

**Comment by ahyattdev** [comment]
I don’t see any errors in the attached text. It looks like that recipe builds Darling with multiple make jobs, so the error isn’t necessary at the bottom of the output. Please attach more text.

**Comment by baerbock** [comment]
Ok, sorry for reporting. -j1 solves my issue.

**Comment by ahyattdev** [comment]
Don’t worry about it, there’s nothing wrong with reporting this, I was just saying that the included text snippet didn’t contain the actual error.

If the build isn’t working with multiple jobs in your case then we would like to fix it.

**Comment by bugaevc** [comment]
Bump. Is there a build/linking error in case of multiple jobs, or is the compiler just getting oom-killed (as it happens)?

**Comment by baerbock** [comment]
@bugaevc Unless some _-Wstring-plus-int_ error **darling builds fine**. Probably my memory was not sufficient.

**Comment by bugaevc** [comment]
Closing then
