### ISSUE TITLE
Kubuntu 18.04 make error at 80% Quartz

### ISSUE THREAD

**Issue by Liemaeu** [darlinghq/darling#479]
`Scanning dependencies of target Quartz
[ 80%] Building C object src/Quartz/CMakeFiles/Quartz.dir/src/Quartz.o
[ 80%] Building C object src/Quartz/CMakeFiles/Quartz.dir/QuickLookUI/src/QLPreviewPanel.o
[ 80%] Building C object src/Quartz/CMakeFiles/Quartz.dir/QuickLookUI/src/QLPreviewView.o
[ 80%] Linking C shared library Quartz
ld: file not found: /home/richard/Programme/darling/build/src/QuickLook/QuickLook
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/Quartz/CMakeFiles/Quartz.dir/build.make:150: recipe for target 'src/Quartz/Quartz' failed
make[2]: *** [src/Quartz/Quartz] Error 1
CMakeFiles/Makefile2:48330: recipe for target 'src/Quartz/CMakeFiles/Quartz.dir/all' failed
make[1]: *** [src/Quartz/CMakeFiles/Quartz.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Liemaeu** [comment]
Ok, I refetched the repository and now it works. Don't no why

**Comment by ahyattdev** [comment]
I made QuickLook a dependency of Quartz. This wouldn’t solve why QuickLook failed and therefore Quartz because Quartz needs it but it will make the build stop at QuickLook like it should in that case.

**Comment by bugaevc** [comment]
> I made QuickLook a dependency of Quartz. This wouldn’t solve why QuickLook failed and therefore Quartz because Quartz needs it but it will make the build stop at QuickLook like it should in that case.

QuickLook did not fail, it just hasn't been built at the moment because CMake didn't know about the dependency. With the dependency info in place, CMake/make make sure that QuickLook is built before attempting to link Quartz, and it goes through as expected.
