### ISSUE TITLE
Check for uuid-dev and libssl-dev missing in cmake

### ISSUE THREAD

**Issue by thopiekar** [darlinghq/darling#48]
I just tried to build darling with minimal dependencies and I noticed there are checks missing in cmake for uuid and libssl - see: https://code.launchpad.net/~thopiekar/+archive/darling/+build/4898915/+files/buildlog_ubuntu-raring-amd64.darling_0.0.1-0~201308222335~rev1~pkg2~raring1_FAILEDTOBUILD.txt.gz

**Comment by LubosD** [comment]
Not used any more, closing.
