### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_NSCheapMutableString

### ISSUE THREAD

**Issue by cornejo** [darlinghq/darling#480]
I'm trying to run the xcode command line tools and discovered the following issue.

Setup:
- Install darling
- Copy Xcode.app (from a donor OSX machine) into /Application inside the darling environment
- Attempt to run /usr/bin/clang

Outcome:
dyld: Symbol not found: _OBJC_CLASS_$_NSCheapMutableString
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsSupport.framework/Versions/A/DevToolsSupport (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsSupport.framework/Versions/A/DevToolsSupport
Abort trap: 6 (core dumped)

I assume this is possibly a versioning issue? I'd be interested in a solution to make this work.

Note: Running the tools from inside Xcode itself works so my gut feeling is my Xcode is too new for my darling env.

Darling [/]$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
clang: error: no input files

**Comment by bugaevc** [comment]
Right, we should add some more string types from [this list](https://gist.github.com/Catfish-Man/bc4a9987d4d7219043afdf8ee536beb2).

The reason I haven't been doing this until now is we don't have unit tests or anything to test the implementation is actually going to behave correctly (this is not a problem for e.g. `__NSCFString` — if it didn't work, nothing would work), and since our frameworks don't create these missing string types, I hoped we could manage without 'em. But apparently Apple code uses/creates them outside of Foundation, so we have no choice.

**Comment by bugaevc** [comment]
Please try now :smiley:

**Comment by cornejo** [comment]
Hmm, no joy. But in case I did something wrong, here are the steps I did to test:

git pull
cd build
make -j8
sudo make install
DPREFIX=/tmp/test darling shell
> cd /Applications
> tar xf /Volumes/Systemroot/.../xcode.tar
> /usr/bin/clang

The final result is still
dyld: Symbol not found: _OBJC_CLASS_$_NSCheapMutableString
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsSupport.framework/Versions/A/DevToolsSupport (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsSupport.framework/Versions/A/DevToolsSupport
Abort trap: 6 (core dumped)

I used DPREFIX to ensure the environment was clean (/tmp/test did not previously exist)

FWIW I didn't recompile the kernel module because it didn't seem relevant. Also I forgot to pull submodules, but looking at the patch I don't think that was required. Just in case it's due to a stale build directory I'll destroy it and rebuild from scratch. I'll let you know if that works

**Comment by cornejo** [comment]
I can confirm, pulling latest submodules, deleting the build directory and following the rest of the steps above does not work. I discovered your work was actually in the darling-foundation submodule.

Is there a way I can tell my version/build timestamp inside the darling shell - I just wanted to confirm my test procedure was sane

**Comment by bugaevc** [comment]
Yes, you needed to pull submodules because the change is in Foundation (and LKM is indeed irrelevant).

Perhaps you forgot to `make install` it the second time? Or perhaps you did not use a fresh container again (you either need to use a fresh container or restart the existing one with `darling stutdown; darling shell` for the changes to take effect).

**Comment by cornejo** [comment]
You're right! My second test was flawed because I didn't look at the error message closely enough. Sorry about that. It's failing because another symbol was not found:

dyld: Symbol not found: _kUTTypeText
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/../Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore
Abort trap: 6 (core dumped)

Presumably: https://developer.apple.com/documentation/coreservices/kuttypetext

Thanks for responding so quickly!

**Comment by ahyattdev** [comment]
`kUTTypeText` has since been implemented.
