### ISSUE TITLE
error: Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by BrannonKing** [darlinghq/darling#481]
I'm getting the following error when trying to compile:
```
Undefined symbols for architecture i386:
  "___bzero", referenced from:
      _sigexc_handler in sigexc.o
      _linux_sigqueue in sigexc.o
      _linux_sigqueue_thread in sigexc.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/kernel/CMakeFiles/system_kernel.dir/build.make:1638: recipe for target 'src/kernel/libsystem_kernel.dylib' failed
```
I discovered that there was a closed, pre-existing issue for this: https://github.com/darlinghq/darling/issues/331

I then attempted to run with CXXFLAGS=-O2 and CFLAGS=-O2 and got this error instead:
```
Undefined symbols for architecture i386:
  "___bzero", referenced from:
      ___emutls_get_address in emutls.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/external/compiler-rt/lib/builtins/CMakeFiles/compiler_rt.dir/build.make:639: recipe for target 'src/external/compiler-rt/lib/builtins/libcompiler_rt.dylib' failed
```

Is it just a missing library?

Also, in addition to he libraries listed on the build instructions page, I also had to add these libraries before getting this far: g++-multilib libbsd-dev libtiff-dev libegl1-mesa-dev libcairo2-dev

**Comment by Dekken** [comment]
Don't specify any args or ```
CMAKE_BUILD_TYPE=Release```

**Comment by ahyattdev** [comment]
Yeah, can't really pass in args like that.

What OS are you on? We should update those dependency lists then

**Comment by ahyattdev** [comment]
Can't reproduce this

**Comment by thelongestusernameofall** [comment]
Similar Error.

Undefined symbols for architecture x86_64:
  "___bzero", referenced from:
      _sys_csops in csops.c.o
      _sys_csops_audittoken in csops.c.o
      _sys_flistxattr in flistxattr.c.o
      ___darling_vchroot_expand in vchroot_userspace.c.o
      _vchroot_expand in vchroot_userspace.c.o
      _vchroot_fdpath in vchroot_userspace.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/kernel/CMakeFiles/system_kernel.dir/build.make:1764: recipe for target 'src/kernel/libsystem_kernel.dylib' failed
make[2]: *** [src/kernel/libsystem_kernel.dylib] Error 1

**Comment by facekapow** [comment]
@thelongestusernameofall Did you pass `-DCMAKE_BUILD_TYPE=Release` to CMake when configuring the build?
