### ISSUE TITLE
__pthread_chdir() doesn't work inside non-root file systems

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#484]
```
(lldb) r
error: No such file or directory: /Volumes/SystemRoot/home/sergey
```

```c
openat(AT_FDCWD, "/sergey", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```
Our `sys_pthread_chdir()` calls `lkm_call(NR_path_at)` which uses `dentry_path_raw()`, which, as [this SO answer claims](https://stackoverflow.com/a/33253811/2750624), returns path relative to the last mount point. Sure enough, I've got `/home` on a separate volume on this machine.

**Comment by LubosD** [comment]
Could you try pulling master in the LKM submodule and retrying with that change?

**Comment by bugaevc** [comment]
Yep, that works, thanks!
(Leaving the issue open for you to close when you update the submodule)
