### ISSUE TITLE
Kernel hang when under load - IPC

### ISSUE THREAD

**Issue by cornejo** [darlinghq/darling#485]
This may be similar to issue #482

In investigating that issue I've encountered another issue which feels similar. I'm posting the backtrace for your consideration and I'm going back to working on issue #482.

In quick summary, my test VM locks up when under load. The load is:

while true; do date; done

Performed in 6 shells.

(gdb) target remote :1234
Remote debugging using :1234
native_safe_halt () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/irqflags.h:55
55	}
(gdb) add-symbol-file darling-mach.ko 0xffffffffc0622000 -s .data 0xffffffffc066b020 -s .bss 0xffffffffc0622000
add symbol table from file "darling-mach.ko" at
	.text_addr = 0xffffffffc0622000
	.data_addr = 0xffffffffc066b020
	.bss_addr = 0xffffffffc0622000
(y or n) y
Reading symbols from darling-mach.ko...done.
(gdb) c
Continuing.

^C
Thread 1 received signal SIGINT, Interrupt.
virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:68
68			while (atomic_read(&lock->val) != 0)
(gdb) info thread
  Id   Target Id         Frame 
* 1    Thread 1 (CPU#0 [running]) virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:68
  2    Thread 2 (CPU#1 [running]) __read_once_size (size=<optimised out>, res=<optimised out>, p=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/compiler.h:188
  3    Thread 3 (CPU#2 [running]) 0xffffffff810de405 in rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
  4    Thread 4 (CPU#3 [running]) rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
(gdb) bt
#0  virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:68
#1  native_queued_spin_lock_slowpath (lock=0xffff88040bd19b08, val=1) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/qspinlock.c:305
#2  0xffffffff8199f641 in pv_queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/paravirt.h:669
#3  queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:30
#4  queued_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/asm-generic/qspinlock.h:90
#5  do_raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock.h:161
#6  __raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock_api_smp.h:143
#7  _raw_spin_lock (lock=0xffff88040bd19b08) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/spinlock.c:144
#8  0xffffffffc06345bd in spin_lock (lock=<optimised out>) at ./include/linux/spinlock.h:310
#9  io_lock (io=<optimised out>) at /home/user/darling/src/lkm/osfmk/ipc/ipc_object.h:190
#10 ipc_port_copy_send (port=0xffff88040bd19b00) at /home/user/darling/src/lkm/osfmk/ipc/ipc_port.c:1124
#11 0xffffffffc064581e in task_get_special_port (task=0xffff880414e9f800, which=4, portp=0xffffc900105e7cc0) at /home/user/darling/src/lkm/osfmk/kern/ipc_tt.c:871
#12 0xffffffffc0635cf5 in darling_ipc_inherit (old_task=0xffff880414e9f800, new_task=0xffff880413af1400) at /home/user/darling/src/lkm/darling/traps.c:367
#13 0xffffffffc0635f2a in mach_dev_open (ino=<optimised out>, file=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:311
#14 0xffffffffc06381ed in xnu_task_setup () at /home/user/darling/src/lkm/darling/traps.c:450
#15 0xffffffffc065c91f in macho_load (bprm=0xffff88040a53af00) at /home/user/darling/src/lkm/darling/binfmt.c:127
#16 0xffffffff8127df67 in search_binary_handler (bprm=0xffff88040a53af00) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1650
#17 0xffffffff8127f727 in exec_binprm (bprm=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1692
#18 do_execveat_common (fd=<optimised out>, filename=0xffff88040b306000, flags=0, argv=..., envp=...) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1814
#19 0xffffffff8127fb21 in do_execve (__envp=<optimised out>, __argv=<optimised out>, filename=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1859
#20 SYSC_execve (envp=<optimised out>, argv=<optimised out>, filename=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1940
#21 SyS_execve (filename=<optimised out>, argv=93955566893968, envp=93955566875184) at /build/linux-uQJ2um/linux-4.15.0/fs/exec.c:1935
#22 0xffffffff81003ae3 in do_syscall_64 (regs=0xffff88040bd19b08) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/common.c:287
#23 0xffffffff81a00081 in entry_SYSCALL_64 () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/entry_64.S:237
#24 0x0000000000000000 in ?? ()
(gdb) thread 2
[Switching to thread 2 (Thread 2)]
#0  __read_once_size (size=<optimised out>, res=<optimised out>, p=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/compiler.h:188
warning: Source file is more recent than executable.
188		__READ_ONCE_SIZE;
(gdb) bt
#0  __read_once_size (size=<optimised out>, res=<optimised out>, p=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/compiler.h:188
#1  atomic_read (v=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/atomic.h:27
#2  virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:68
#3  native_queued_spin_lock_slowpath (lock=0xffff88040bd19b18, val=1) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/qspinlock.c:305
#4  0xffffffff8199f641 in pv_queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/paravirt.h:669
#5  queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:30
#6  queued_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/asm-generic/qspinlock.h:90
#7  do_raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock.h:161
#8  __raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock_api_smp.h:143
#9  _raw_spin_lock (lock=0xffff88040bd19b18) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/spinlock.c:144
#10 0xffffffffc0624c9f in spin_lock (lock=<optimised out>) at ./include/linux/spinlock.h:310
#11 ipc_kmsg_send (kmsg=0xffffc900105e1000, option=0, send_timeout=0) at /home/user/darling/src/lkm/osfmk/ipc/ipc_kmsg.c:1462
#12 0xffffffffc062c1b2 in mach_msg_overwrite_trap (args=<optimised out>) at /home/user/darling/src/lkm/osfmk/ipc/mach_msg.c:436
#13 0xffffffffc063642c in mach_msg_overwrite_entry (task=<optimised out>, in_args=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:726
#14 0xffffffffc0638453 in mach_dev_ioctl (file=0xffff8804148a8200, ioctl_num=<optimised out>, ioctl_paramv=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:637
#15 0xffffffff8128d088 in vfs_ioctl (arg=<optimised out>, cmd=<optimised out>, filp=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:46
#16 do_vfs_ioctl (filp=0xffff88040bd19b18, fd=<optimised out>, cmd=<optimised out>, arg=0) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:686
#17 0xffffffff8128d689 in SYSC_ioctl (arg=<optimised out>, cmd=<optimised out>, fd=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:701
#18 SyS_ioctl (fd=1023, cmd=4102, arg=140737486250264) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:692
#19 0xffffffff81003ae3 in do_syscall_64 (regs=0xffff88040bd19b18) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/common.c:287
#20 0xffffffff81a00081 in entry_SYSCALL_64 () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/entry_64.S:237
#21 0x0000000000000000 in ?? ()
(gdb) thread 3
[Switching to thread 3 (Thread 3)]
#0  0xffffffff810de405 in rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
warning: Source file is more recent than executable.
647		asm volatile("rep; nop" ::: "memory");
(gdb) bt
#0  0xffffffff810de405 in rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
#1  cpu_relax () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:652
#2  virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:69
#3  native_queued_spin_lock_slowpath (lock=0xffff8804107345b0, val=1) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/qspinlock.c:305
#4  0xffffffff8199f407 in pv_queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/paravirt.h:669
#5  queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:30
#6  queued_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/asm-generic/qspinlock.h:90
#7  do_raw_spin_lock_flags (flags=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock.h:172
#8  __raw_spin_lock_irqsave (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock_api_smp.h:119
#9  _raw_spin_lock_irqsave (lock=0xffff8804107345b0) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/spinlock.c:152
#10 0xffffffffc064287b in wait_queue_wakeup64_identity_locked (waitq=<optimised out>, event=<optimised out>, result=<optimised out>, unlock=<optimised out>)
    at /home/user/darling/src/lkm/osfmk/duct/duct_kern_waitqueue.c:453
#11 0xffffffffc0632131 in ipc_mqueue_post (mqueue=0xffff88040c3abe10, kmsg=0xffff88040a745500) at /home/user/darling/src/lkm/osfmk/ipc/ipc_mqueue.c:557
#12 0xffffffffc063235d in ipc_mqueue_send (mqueue=0xffff88040c3abe10, kmsg=0x1 <irq_stack_union+1>, option=<optimised out>, send_timeout=<optimised out>, s=582)
    at /home/user/darling/src/lkm/osfmk/ipc/ipc_mqueue.c:485
#13 0xffffffffc0624cbf in ipc_kmsg_send (kmsg=0xffff88040a745500, option=0, send_timeout=0) at /home/user/darling/src/lkm/osfmk/ipc/ipc_kmsg.c:1464
#14 0xffffffffc062c1b2 in mach_msg_overwrite_trap (args=<optimised out>) at /home/user/darling/src/lkm/osfmk/ipc/mach_msg.c:436
#15 0xffffffffc063642c in mach_msg_overwrite_entry (task=<optimised out>, in_args=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:726
#16 0xffffffffc0638453 in mach_dev_ioctl (file=0xffff88040e988300, ioctl_num=<optimised out>, ioctl_paramv=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:637
#17 0xffffffff8128d088 in vfs_ioctl (arg=<optimised out>, cmd=<optimised out>, filp=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:46
#18 do_vfs_ioctl (filp=0xffff8804107345b0, fd=<optimised out>, cmd=<optimised out>, arg=0) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:686
#19 0xffffffff8128d689 in SYSC_ioctl (arg=<optimised out>, cmd=<optimised out>, fd=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:701
#20 SyS_ioctl (fd=1023, cmd=4102, arg=140737314270024) at /build/linux-uQJ2um/linux-4.15.0/fs/ioctl.c:692
#21 0xffffffff81003ae3 in do_syscall_64 (regs=0xffff8804107345b0) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/common.c:287
#22 0xffffffff81a00081 in entry_SYSCALL_64 () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/entry_64.S:237
#23 0x00007fffffdff110 in ?? ()
#24 0x00007ffff59fab48 in ?? ()
#25 0x0000000000000000 in ?? ()
(gdb) thread 4
[Switching to thread 4 (Thread 4)]
#0  rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
647		asm volatile("rep; nop" ::: "memory");
(gdb) bt
#0  rep_nop () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:647
#1  cpu_relax () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/processor.h:652
#2  virt_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:69
#3  native_queued_spin_lock_slowpath (lock=0xffff88040bd19b08, val=1) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/qspinlock.c:305
#4  0xffffffff8199f641 in pv_queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/paravirt.h:669
#5  queued_spin_lock_slowpath (val=<optimised out>, lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/include/asm/qspinlock.h:30
#6  queued_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/asm-generic/qspinlock.h:90
#7  do_raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock.h:161
#8  __raw_spin_lock (lock=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/spinlock_api_smp.h:143
#9  _raw_spin_lock (lock=0xffff88040bd19b08) at /build/linux-uQJ2um/linux-4.15.0/kernel/locking/spinlock.c:144
#10 0xffffffffc062dd96 in spin_lock (lock=<optimised out>) at ./include/linux/spinlock.h:310
#11 io_lock (io=<optimised out>) at /home/user/darling/src/lkm/osfmk/ipc/ipc_object.h:190
#12 ipc_right_terminate (space=0xffff88040bb02600, name=<optimised out>, entry=0xffffc900105b50a8) at /home/user/darling/src/lkm/osfmk/ipc/ipc_right.c:612
#13 0xffffffffc06236a8 in ipc_space_terminate (space=0xffff88040bb02600) at /home/user/darling/src/lkm/osfmk/ipc/ipc_space.c:339
#14 0xffffffffc063fdee in duct_task_destroy (task=0xffff880414019c00) at /home/user/darling/src/lkm/osfmk/duct/duct_kern_task.c:125
#15 0xffffffffc0637ef3 in mach_dev_release (ino=<optimised out>, file=<optimised out>) at /home/user/darling/src/lkm/darling/traps.c:526
#16 0xffffffff8127895a in __fput (file=0xffff880414263800) at /build/linux-uQJ2um/linux-4.15.0/fs/file_table.c:211
#17 0xffffffff81278b2e in ____fput (work=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/fs/file_table.c:245
#18 0xffffffff810abf5d in task_work_run () at /build/linux-uQJ2um/linux-4.15.0/kernel/task_work.c:113
#19 0xffffffff8109145c in exit_task_work (task=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/include/linux/task_work.h:22
#20 do_exit (code=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/kernel/exit.c:865
#21 0xffffffff81091d33 in do_group_exit (exit_code=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/kernel/exit.c:968
#22 0xffffffff81091db4 in SYSC_exit_group (error_code=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/kernel/exit.c:979
#23 SyS_exit_group (error_code=<optimised out>) at /build/linux-uQJ2um/linux-4.15.0/kernel/exit.c:977
#24 0xffffffff81003ae3 in do_syscall_64 (regs=0xffff88040bd19b08) at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/common.c:287
#25 0xffffffff81a00081 in entry_SYSCALL_64 () at /build/linux-uQJ2um/linux-4.15.0/arch/x86/entry/entry_64.S:237
#26 0x0000000000000000 in ?? ()

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
