### ISSUE TITLE
Ubuntu build instructions outdated?

### ISSUE THREAD

**Issue by tommedema** [darlinghq/darling#496]
Curious if the build instructions are outdated.

I'm running 64 bit Ubuntu 18.04 on AWS (`AMI: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190212.1 (ami-06397100adf427136)`)

When running the mentioned [apt-get install](https://wiki.darlinghq.org/build_instructions) command I get:

```
E: Unable to locate package libc6-dev:i386
E: Unable to locate package libfreetype6-dev:i386
```

If I ignore these then later on I get (in sudo make install):

```
[ 80%] Linking C shared library QuartzCore
ld: file not found: /home/ubuntu/darling/build/src/CoreImage/CoreImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/external/cocotron/QuartzCore/CMakeFiles/QuartzCore.dir/build.make:673: recipe for target 'src/external/cocotron/QuartzCore/QuartzCore' failed
make[2]: *** [src/external/cocotron/QuartzCore/QuartzCore] Error 1
CMakeFiles/Makefile2:54797: recipe for target 'src/external/cocotron/QuartzCore/CMakeFiles/QuartzCore.dir/all' failed
make[1]: *** [src/external/cocotron/QuartzCore/CMakeFiles/QuartzCore.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Also note that I first tried to build on Amazon's own Linux distribution but there more packages were missing so I changed to Ubuntu. Would be great to get it to work on Amazon's linux distribution though because it would then be possible to run darling on AWS lambda.

**Comment by vilP1l** [comment]
Install `libc6-dev` and `libfreetype6-dev` and try running make with `-j2`

**Comment by bugaevc** [comment]
The linking error, same as https://github.com/darlinghq/darling/issues/492, is the result of https://github.com/darlinghq/darling-cocotron/commit/94403265abc41b1852d373c244c3017f7d1ba382 forgetting to tell CMake that QuartzCore now depends on CoreImage and CoreVideo (@ahyattdev Andrew, will you please push a fix?)

You can work around it by running `make src/CoreImage/CoreImage && make src/CoreVideo/CoreVideo && make`

**Comment by ahyattdev** [comment]
I don't think they are outdated, I did a clean install of 18.04 with those packages a week ago and ran into no issues.

Maybe Amazon has modified the distribution by getting rid of i386 packages?

**Comment by tommedema** [comment]
@bugaevc that gives me:

```
make src/CoreImage/CoreImage
make: *** No rule to make target 'src/CoreImage/CoreImage'.  Stop.
```

**Comment by ahyattdev** [comment]
Does [this](https://superuser.com/a/742163) help solve not being able to install the dependency package?

**Comment by tommedema** [comment]
@ahyattdev If my memory serves me correctly I believe I managed to build it using @vilP1l's advice, by simply replacing libc6-dev:i386 with libc6-dev etc.

If I come across this issue again I'll try enabling the i386 architecture as mentioned in your post

Much appreciated
