### ISSUE TITLE
JavaScriptCore does not compile

### ISSUE THREAD

**Issue by jamesu** [darlinghq/darling#497]
Trying to compile the JavaScriptCore in the current master results in the following:

```
[ 98%] Building CXX object src/external/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/tools/VMInspector.o
In file included from /darling/src/external/JavaScriptCore/runtime/VMEntryScope.cpp:35:
/darling/src/external/WTF/include/wtf/SystemTracing.h:101:5: error: use of undeclared identifier 'kdebug_trace'
    kdebug_trace(ARIADNEDBG_CODE(WEBKIT_COMPONENT, code), data1, data2, data3, data4);
    ^
```

This can be worked around by sticking a dummy implementation of kdebug_trace in `/darling/src/external/WTF/include/wtf/SystemTracing.h` but I suspect fixing the headers or defines or whatever is actually wrong would be a better idea.

**Comment by andyneff** [comment]
I've been tracking this problem down myself (for over a week now?).

It appears to have broken between dd543521799a6015484e47b1a61424b3184f521c and 4274c64141a1cf217f631b18490d3fd8b9b4e870.

I finally got it to compile after I removed the symlink `platform-include/System/sys`

Still testing...

**Comment by ahyattdev** [comment]
As a workaround you can use the option `-DFULL_BUILD=OFF` while configuring through `cmake`. It disables building JavaScriptCore.

**Comment by Natetronn** [comment]
I realize this is a year old and closed but, I'm running into this issue as well. Seems like it's stuck on a loop and at 98%.

Is running `cmake -DFULL_BUILD=OFF` still relevant a year later? I'll try it but, thought I'd ask first, just in case.

**Comment by HinTak** [comment]
@Natetronn you just need to be patient - the percentage is misleading - javascriptcore itself is 55% of compile time on my system. (it takes 4 hours for everything else, another 5 hours for Javascriptcore).

**Comment by Natetronn** [comment]
@HinTak thanks for the reply! 

Okay, I'm going to start over fresh and let 'er rip. Both versions on AUR were failing so, I'm building per the Darling docs (which was the case when I started seeing this issue.)

**Comment by HinTak** [comment]
@Natetronn good luck. As I said, if I do plain `make` (instead of `make -jN`, N twice the number of CPU you have), after 4 hours I would reach Javascriptcore at 95%, then another 5 hours when it gradually goes up 96, 97, 98, 99, at basically an hour each, for the last 5% .

**Comment by Natetronn** [comment]
@HinTak is it normal to get many warnings as it processes?

**Comment by HinTak** [comment]
@Natetronn yes. I think in Javascriptcore in particular, one of the headers has a warning about a number larger than long long and should be sufficed "LL", something like that, and it is included by almost every source file so you get the same message over and over. That might be where you get the impression it is in a loop - it is not, just same buggy header *.h included by different source *.c.

**Comment by Natetronn** [comment]
Ah, okay! Yes, that's the one. And you're right, it does make it seem like it's stuck in an endless loop and why I ended up here lol.

**Comment by HinTak** [comment]
Yes, if you scroll back or wait a bit, you would see it is a different source file being compiled, just including the same header :-) . It takes a long time but it will finish - hopefully!

**Comment by Natetronn** [comment]
@HinTak make finished in 3h 21m 24s! Finished the following installation step as well and now I'm seeing:

```
Darling [/Volumes/SystemRoot/home/username]$ uname
Darwin
Darling [/Volumes/SystemRoot/home/username]$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   Darling
```
:-D

**Comment by HinTak** [comment]
@Natetronn good to hear. I am going to go cry my eyes out - the fastest I can do a new clean build is 7 hours , disabling ccache and with `make -j4` (I have a dual core laptop). 9 hours at plain single CPU `make`; the first time I did a full clean build, about two months ago, was 12 hours (with ccache intercepting the compilation)...
