### ISSUE TITLE
Can't build kernel module in a Promox VM

### ISSUE THREAD

**Issue by vilP1l** [darlinghq/darling#498]
When I try to `make lkm` this happens:

➜  build git:(master) make lkm
Built target migcom
Built target migexe
Built target lkm_generate
Building the Linux kernel module
make[4]: Entering directory '/root/darling/src/lkm'
Running kernel version is 4.15.18-11-pve
rm -f darling-mach.mod.o
make -C /lib/modules/4.15.18-11-pve/build M=/root/darling/src/lkm modules
make[5]: Entering directory '/root/darling/src/lkm'
make[5]: *** /lib/modules/4.15.18-11-pve/build: No such file or directory.  Stop.
make[5]: Leaving directory '/root/darling/src/lkm'
Makefile:291: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/root/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:57: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:54209: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:54216: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:15010: recipe for target 'lkm' failed
make: *** [lkm] Error 2

**Comment by ahyattdev** [comment]
This may happen if the currently running system kernel is not installed. Particularly if your kernel was upgraded but you haven't rebooted yet.

It detects the kernel version with `uname -r`.

Please reboot your system.

**Comment by vilP1l** [comment]
A reboot didn't change anything.

**Comment by ahyattdev** [comment]
@vilP1l reboot, rebuild the kernel module, then reinstall it.

What does `uname -r` say? How does that compare to where Darling is installing the kernel module?

**Comment by vilP1l** [comment]
`uname -r` gives 4.15.18-11-pve but the only folders in /lib/modules/ are `4.15.0-47-generic` and `4.15.0-46-generic`

**Comment by ahyattdev** [comment]
@vilP1l well that would explain it, the kernel module build script is looking for /lib/modules/4.15.18-11-pve. I'm not sure what PVE is, but some searching brings up [this](https://pve.proxmox.com/wiki/Main_Page), is this it?

I'm not sure how kernel modules work with this, it isn't clear that they are supported by it.

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
