### ISSUE TITLE
.app is a folder and cant run through Darling

### ISSUE THREAD

**Issue by NewtronReal** [darlinghq/darling#499]
Hi I am an Ubuntu user and I am trying to install mac app store using darling. I mount dmg file and installed MacOSXUpd10.6.6.pkg to my folder. But in the folder it is shown a a directory. Can you please help me. And sorry for my bad English. Hope you will understand my problem.

Thanks.

**Comment by bugaevc** [comment]
Hi!

To run an app, run the `Contents/MacOS/AppName` executable inside the .app bundle, for example:

```
$ /Applications/HelloWorld.app/Contents/MacOS/HelloWorld
```

Note however that we still don't (officially) support running GUI apps, and AppStore is surely way too complex to work.

**Comment by NewtronReal** [comment]
Sorry for late respond. However I tried it and it not worked. I think Problem is in the package. Can you suggest any apps that you've tried and successfully ran in your darling system. Again. Sorry for my English.

**Comment by NewtronReal** [comment]
Sorry for late respond. I tried to launch app using this command .It worked. But it failed to launch the app says that "image not found". If app Store is incompatible with darling then please suggest some apps that works fine. Is there any option to run GUI apps in Darling. If it is not possible. Are you working to make Darling GUI compatible.

Thanks

**Comment by bugaevc** [comment]
Yes, we are planning to make it possible to run GUI apps in Darling, and actively working on it. Expect an announcement (somewhat) soon, but for now we do not support them.

For an overview of some programs (not GUI apps) that _do_ run on Darling, check out [this wiki page](https://wiki.darlinghq.org/what_to_try)
