### ISSUE TITLE
Is Darling OpenSource

### ISSUE THREAD

**Issue by NewtronReal** [darlinghq/darling#500]
Can I include Darling in My new operating system that I'm Working on. It target to use windows, linux, mac ,android ,and chrome apps in one OS. See the page. Is darling Project is open source? 
My OS Main Page
https://www.newosin.weebly.com

Thanks

**Comment by Dekken** [comment]
https://github.com/darlinghq/darling/blob/master/LICENSE

**Comment by Dekken** [comment]
You might want to check your https cert there

**Comment by bugaevc** [comment]
Yes, Darling is open source / free software.

You may want to check out the license (linked above by @Dekken). It's [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html), basically this means that if your system is based on Darling, it also has to be open source & available under the terms of GPLv3 (so not BSD or MIT or anything). This is also the license many, many of other Linux components use, so if your system is based on Ubuntu, you're already bounded by that.

Note that Darling includes lots of third party code, some of which is under APSL, some under other licenses.

**Comment by zaoqi** [comment]
> Can I include Darling in My new operating system that I'm Working on. It target to use windows, linux, mac ,android ,and chrome apps in one OS. See the page. Is darling Project is open source?
> My OS Main Page
> https://www.newosin.weebly.com
> 
> Thanks

It this OS open source?

**Comment by NewtronReal** [comment]
Yes

**Comment by ahyattdev** [comment]
@NewtronReal where can we find the source? I don't see it on your website.
