### ISSUE TITLE
Darling building Errors on Backbox (Ubuntu)

### ISSUE THREAD

**Issue by mistaproper** [darlinghq/darling#501]
Hello
I was following building instructions but
`

- [  2%] Built target ext
- [  2%] Built target util_xcbuild
- [  2%] Built target plist
- [  2%] Built target xcassets
- [  2%] Built target dependency
- [  2%] Built target graphics
- [  2%] Built target bom
- [  2%] Built target car
- [  2%] Built target process
- [  2%] Built target acdriver
- [  2%] Built target actool
- [  2%] Built target pbxsetting
- [  2%] Built target builtin
- [  2%] Built target builtin-copyPlist
- [  2%] Built target builtin-infoPlistUtility
- [  2%] Built target builtin-copy
- [  2%] Built target builtin-validationUtility
- [  2%] Built target builtin-copyTiff
- [  2%] Built target builtin-lsRegisterURL
- [  2%] Built target builtin-productPackagingUtility
- [  2%] Built target builtin-copyStrings
- [  2%] Built target builtin-embeddedBinaryValidationUtility
- [  2%] Built target dump_dependency
- [  2%] Built target dependency-info-tool
- [  2%] Built target dump_car
- [  2%] Built target lsbom
- [  2%] Built target dump_bom
- [  2%] Built target ninja
- [  2%] Built target xcworkspace
- [  2%] Built target pbxproj
- [  2%] Built target pbxspec
- [  2%] Built target xcscheme
- [  2%] Built target xcsdk
- [  2%] Building CXX object src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o
- /home/noname/darling/src/external/xcbuild/Libraries/pbxbuild/Sources/FileTypeResolver.cpp:34:70: error: 
-       default initialization of an object of const type 'const
-       std::unordered_set<pbxspec::PBX::FileType::shared_ptr>' (aka 'const
-       unordered_set<shared_ptr<pbxspec::PBX::FileType> >') without a
-       user-provided default constructor
-         const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;
-                                                                      ^
-                                                                              {}
- 1 error generated.
- src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/build.make:158: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o' failed
- make[2]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o] Error 1
- CMakeFiles/Makefile2:2076: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all' failed
- make[1]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all] Error 2
- Makefile:127: recipe for target 'all' failed
- make: *** [all] Error 2

`

This solution :
Install clang-4.0 and set a higher priority:
`update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 400`

didn't help:
`update-alternatives: используется /usr/bin/clang-4.0 для предоставления /usr/bin/clang (clang) в автоматическом режиме
update-alternatives: ошибка: ошибка создания символьной ссылки «/etc/alternatives/clang.dpkg-tmp»: Permission denied
`
sorry for Russian. Commonly it is written that used for automatical mode and a failure of creating of symbol link.

I'm totally new to all of the stuff (linux, darling) and hope for understanding. Could someone help please?

**Comment by bugaevc** [comment]
> Install clang-4.0 and set a higher priority:
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 400
> 
> didn't help:
> update-alternatives: используется /usr/bin/clang-4.0 для предоставления /usr/bin/clang (clang) в автоматическом режиме update-alternatives: ошибка: ошибка создания символьной ссылки «/etc/alternatives/clang.dpkg-tmp»: Permission denied

You need `sudo`:

```bash
$ sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 400
```

But before you do that, what version of clang are you using now? (run `clang -v` to check) If it's clang 3, go ahead and update it, but if it's _newer_ than 4, then we need to find another way to solve this.

**Comment by mistaproper** [comment]
`noname@noname:~$ sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 400
[sudo] password for noname: 
update-alternatives: используется /usr/bin/clang-4.0 для предоставления /usr/bin/clang (clang) в автоматическом режиме
noname@noname:~$ clang -v
clang version 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
`

**Comment by mistaproper** [comment]
now it is:
`

- noname@noname:~$ git clone --recursive https://github.com/darlinghq/darling.git
- fatal: destination path 'darling' already exists and is not an empty directory.
- noname@noname:~$ make lkm
- make: *** No rule to make target 'lkm'.  Stop.
- noname@noname:~$ sudo make lkm_install
- make: *** No rule to make target 'lkm_install'.  Stop.
- noname@noname:~$ cd darling
- noname@noname:~/darling$ mkdir build && cd build
- mkdir: cannot create directory ‘build’: File exists
- noname@noname:~/darling$ cmake ..
- CMake Error: The source directory "/home/noname" does not appear to contain CMakeLists.txt.
- Specify --help for usage, or press the help button on the CMake GUI.
- noname@noname:~/darling$ make
- make: *** No targets specified and no makefile found.  Stop.
- noname@noname:~/darling$ sudo make install
- make: *** No rule to make target 'install'.  Stop.
- noname@noname:~/darling$ `

**Comment by CuriousTommy** [comment]
> fatal: destination path 'darling' already exists and is not an empty directory.
> mkdir: cannot create directory ‘build’: File exists

Remember, you already cloned darling and created the build directory. Just `cd` into the build directory.

**Comment by mistaproper** [comment]
> > fatal: destination path 'darling' already exists and is not an empty directory.
> > mkdir: cannot create directory ‘build’: File exists
> 
> Remember, you already cloned darling and created the build directory. Just `cd` into the build directory.

thanks!
but still:
`

- noname@noname:~/darling$ cd build
- noname@noname:~/darling/build$ cmake ..
- -- Found dsymutil: /usr/bin/llvm-dsymutil-3.9
- -- Compiler include path detected as /usr/lib/llvm-4.0/bin/../lib/clang/4.0.0/include/
- CMake Warning (dev) at src/external/bind9/bind9/bin/nsupdate/CMakeLists.txt:12 (add_definitions):
-   Policy CMP0005 is not set: Preprocessor definition values are now escaped
-   automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
-   the cmake_policy command to set the policy and suppress this warning.
- This warning is for project developers.  Use -Wno-dev to suppress it.
- 
- -- Configuring done
- -- Generating done
- -- Build files have been written to: /home/noname/darling/build
- noname@noname:~/darling/build$ make
- [  2%] Built target ext
- [  2%] Built target util_xcbuild
- [  2%] Built target plist
- [  2%] Built target xcassets
- [  2%] Built target dependency
- [  2%] Built target graphics
- [  2%] Built target bom
- [  2%] Built target car
- [  2%] Built target process
- [  2%] Built target acdriver
- [  2%] Built target actool
- [  2%] Built target pbxsetting
- [  2%] Built target builtin
- [  2%] Built target builtin-copyPlist
- [  2%] Built target builtin-infoPlistUtility
- [  2%] Built target builtin-copy
- [  2%] Built target builtin-validationUtility
- [  2%] Built target builtin-copyTiff
- [  2%] Built target builtin-lsRegisterURL
- [  2%] Built target builtin-productPackagingUtility
- [  2%] Built target builtin-copyStrings
- [  2%] Built target builtin-embeddedBinaryValidationUtility
- [  2%] Built target dump_dependency
- [  2%] Built target dependency-info-tool
- [  2%] Built target dump_car
- [  2%] Built target lsbom
- [  2%] Built target dump_bom
- [  2%] Built target ninja
- [  2%] Built target xcworkspace
- [  2%] Built target pbxproj
- [  2%] Built target pbxspec
- [  2%] Built target xcscheme
- [  2%] Built target xcsdk
- [  2%] Building CXX object src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o
- /home/noname/darling/src/external/xcbuild/Libraries/pbxbuild/Sources/FileTypeResolver.cpp:34:70: error: 
-       default initialization of an object of const type 'const
-       std::unordered_set<pbxspec::PBX::FileType::shared_ptr>' (aka 'const
-       unordered_set<shared_ptr<pbxspec::PBX::FileType> >') without a
-       user-provided default constructor
-         const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;
-                                                                      ^
-                                                                              {}
- 1 error generated.
- src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/build.make:158: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o' failed
- make[2]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o] Error 1
- CMakeFiles/Makefile2:2076: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all' failed
- make[1]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all] Error 2
- Makefile:127: recipe for target 'all' failed
- make: *** [all] Error 2
- noname@noname:~/darling/build$ sudo make install
- [sudo] password for noname: 
- [  0%] Built target ext
- [  0%] Built target util_xcbuild
- [  1%] Built target plist
- [  2%] Built target xcassets
- [  2%] Built target dependency
- [  2%] Built target graphics
- [  2%] Built target bom
- [  2%] Built target car
- [  2%] Built target process
- [  2%] Built target acdriver
- [  2%] Built target actool
- [  2%] Built target pbxsetting
- [  2%] Built target builtin
- [  2%] Built target builtin-copyPlist
- [  2%] Built target builtin-infoPlistUtility
- [  2%] Built target builtin-copy
- [  2%] Built target builtin-validationUtility
- [  2%] Built target builtin-copyTiff
- [  2%] Built target builtin-lsRegisterURL
- [  2%] Built target builtin-productPackagingUtility
- [  2%] Built target builtin-copyStrings
- [  2%] Built target builtin-embeddedBinaryValidationUtility
- [  2%] Built target dump_dependency
- [  2%] Built target dependency-info-tool
- [  2%] Built target dump_car
- [  2%] Built target lsbom
- [  2%] Built target dump_bom
- [  2%] Built target ninja
- [  2%] Built target xcworkspace
- [  2%] Built target pbxproj
- [  2%] Built target pbxspec
- [  2%] Built target xcscheme
- [  2%] Built target xcsdk
- [  2%] Building CXX object src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o
- /home/noname/darling/src/external/xcbuild/Libraries/pbxbuild/Sources/FileTypeResolver.cpp:34:70: error: 
-       default initialization of an object of const type 'const
-       std::unordered_set<pbxspec::PBX::FileType::shared_ptr>' (aka 'const
-       unordered_set<shared_ptr<pbxspec::PBX::FileType> >') without a
-       user-provided default constructor
-         const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;
-                                                                      ^
-                                                                              {}
- 1 error generated.
- src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/build.make:158: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o' failed
- make[2]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o] Error 1
- CMakeFiles/Makefile2:2076: recipe for target 'src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all' failed
- make[1]: *** [src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/all] Error 2
- Makefile:127: recipe for target 'all' failed
- make: *** [all] Error 2

`

**Comment by bugaevc** [comment]
<blockquote><pre>noname@noname:~$ git clone --recursive https://github.com/darlinghq/darling.git
fatal: destination path 'darling' already exists and is not an empty directory.
noname@noname:~$ make lkm
make: *** No rule to make target 'lkm'. Stop.
noname@noname:~$ sudo make lkm_install
make: *** No rule to make target 'lkm_install'. Stop.
noname@noname:~$ cd darling
noname@noname:~/darling$ mkdir build && cd build
mkdir: cannot create directory ‘build’: File exists
noname@noname:~/darling$ cmake ..
CMake Error: The source directory "/home/noname" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
noname@noname:~/darling$ make
make: *** No targets specified and no makefile found. Stop.
noname@noname:~/darling$ sudo make install
make: *** No rule to make target 'install'. Stop.
noname@noname:~/darling$ </pre></blockquote>

I'm sorry to say this 😔, but I think you need way more experience with Unix/Linux before you can hack on Darling if you're running into / cannot figure out problems like these.

When Darling is ready to be used by regular users, it'll be easily installable using whatever way you're used to install software on your system (some sort of Software Center app, for example). But for now, you need _some_ development or advanced user background to install & use it; at least you have to know how to `cd` around your filesystem.

When you get Darling to build, all that awaits you is another shell, which will be useless to you if you're not familiar with using shells.

If I were you, I would go and learn more about Unix/Linux shell basics, about using git, make/makefiles, CMake, and other stuff; then come back to Darling.

On the actual build error: perhaps try an even newer compiler (clang 8 is out...), or just disable xcbuild in `src/CMakeLists.txt` (by commenting it out or just deleting the line altogether).

**Comment by kvanhecke** [comment]
I had the same build error (in FileTypeResolver.cpp) until I did the same thing for clang++:

`sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-4.0 400`

**Comment by shangweiluo** [comment]
I had the same build error!

I exec the command @kvanhecke and other!

Like this:
`update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 400`
`update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-4.0 400`

It works!

**Comment by ahyattdev** [comment]
I documented this on the build instructions page https://wiki.darlinghq.org/build_instructions
