### ISSUE TITLE
TGE based games: Missing Function stubs in Carbon & ApplicationServices

### ISSUE THREAD

**Issue by jamesu** [darlinghq/darling#504]
The following functions/symbols don't appear to be present, thus TGE-based games such as "Marble Blast" will not currently get past dyld when binding these frameworks. In this particular case, having stubs implemented would probably be sufficient enough to run in "headless" mode (i.e. no gui).

/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon

   _ActivateTSMDocument
   _DeactivateTSMDocument
   _CallNextEventHandler
   _CreateEvent
   _CreateStandardAlert
   _CreateWindowGroup
   _FlushEvents
   _GetApplicationEventTarget
   _GetEventClass
   _GetEventDispatcherTarget
   _GetEventKind
   _GetEventParameter
   _GetMainEventQueue
   _GetScrapByName
   _GetScrapFlavorData
   _GetScrapFlavorSize
   _GetStandardAlertDefaultParams
   _GetWindowBounds
   _GetWindowEventTarget
   _GetWindowGroupLevel
   _GetWindowGroupOfClass
   _GetWindowPort
   _GetWindowPortBounds
   _HideMenuBar
   _InstallEventHandler
   _IsValidWindowPtr
   _NMInstall
   _NewEventHandlerUPP
   _NewTSMDocument
   _PostEventToQueue
   _ProcessHICommand
   _PutScrapFlavor
   _ReceiveNextEvent
   _ReleaseEvent
   _ReleaseWindow
   _RemoveEventHandler
   _RunApplicationEventLoop
   _RunStandardAlert
   _SelectWindow
   _SendEventToEventTarget
   _SetEventMask
   _SetEventParameter
   _SetWindowContentColor
   _SetWindowGroup
   _SetWindowGroupLevel
   _SetWindowTitleWithCFString
   _ShowMenuBar
   _TransitionWindowWithOptions
   _UseInputWindow
   _GetKeys

/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

   _ATSFontFindFromName
   _ATSFontGetHorizontalMetrics
   _ATSUCreateStyle
   _ATSUCreateTextLayout
   _ATSUDisposeStyle
   _ATSUDisposeTextLayout
   _ATSUDrawText
   _ATSUGetUnjustifiedBounds
   _ATSUMeasureTextImage
   _ATSUSetAttributes
   _ATSUSetLayoutControls
   _ATSUSetRunStyle
   _ATSUSetTextPointerLocation
   _ATSUSetTransientFontMatching
   _CGCursorIsVisible
   _CGDisplayAvailableModes
   _CGDisplayBounds
   _CGDisplayHideCursor
   _CGDisplayIDToOpenGLDisplayMask
   _CGDisplayMoveCursorToPoint
   _CGDisplayRestoreColorSyncSettings
   _CGDisplayShowCursor
   _CGGetActiveDisplayList
   _CGGetDisplayTransferByFormula
   _CGGetDisplayTransferByTable
   _CGGetLastMouseDelta
   _CGMainDisplayID
   _CGSetDisplayTransferByFormula
   _CGSetDisplayTransferByTable
   _CGSetLocalEventsSuppressionInterval
   _CGShieldingWindowLevel
   _DMGetFirstScreenDevice
   _DMGetNextScreenDevice
   _FMGetFontFromATSFontRef
   _GetMainDevice
   _InitCursor
   _QDGetCGDirectDisplayID

/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
   _DebugStr

**Comment by jamesu** [comment]
Can confirm at least with stubs this allows TGE games to partially load, though at some point the stack is being corrupted. Currently seeing if I can narrow down where this happens.

**Comment by ahyattdev** [comment]
@jamesu did you create stubs for these symbols? Please submit a PR with those if so! 😄

**Comment by jamesu** [comment]
@ahyattdev I have stubs for these in my local copy, but bumped into a weird threading issue meaning the threads lock up when trying to print logging info so didn't quite get around to putting them into a PR yet.

Also not 100% sure what to do about the carbon gui stuff in general: there is cocoatron in the cocoa framework, but I can't really access that from the carbon framework (though not strictly necessary to address for just stubs). Would be handy if there was some sort of implementation of CGWindow* or something to fall back on.

**Comment by bugaevc** [comment]
> but I can't really access that from the carbon framework

Why not? I thought it was decided that our (future/potential) Carbon can link to & wrap Cocoa.

> Would be handy if there was some sort of implementation of CGWindow* or something to fall back on.

There is [`CGWindow`](https://github.com/darlinghq/darling-cocotron/blob/master/CoreGraphics/include/CoreGraphics/CGWindow.h), but its actual implementations are in AppKit backends, and they assume you are actually using AppKit.

**Comment by jamesu** [comment]
Ah ok, will keep all that in mind then ;)

**Comment by jamesu** [comment]
Nearly have stubs done for these, just doing some double checking and will submit later.

**Comment by jamesu** [comment]
Submitted a PR for this. Provided the OpenAL.framework is replaced (since it uses AudioUnit which isn't in darling yet), torque games will now start executing but there seems to be some sort of issue during startup which prevents the entry script from loading, causing an assert to fire in the semaphore code (I don't think this indicates an actual problem with the threading code though since it seems to work fine in a basic test case, but more prodding is needed on that end).
