### ISSUE TITLE
SteamCMD fails to execute (dyld: Symbol not found: _kCFProxyAutoConfigurationURLKey)

### ISSUE THREAD

**Issue by CuriousTommy** [darlinghq/darling#507]
Note that it is not possible to [download SteamCMD]( https://developer.valvesoftware.com/wiki/SteamCMD#OS_X) from the darling shell due to https://github.com/darlinghq/darling/issues/463

Downloading the files through Linux and trying to [run SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD#Linux.2FOS_X) on Darling results in this error:
```
Darling [~/Steam]$ ./steamcmd.sh 
dyld: Symbol not found: _kCFProxyAutoConfigurationURLKey
  Referenced from: /Volumes/SystemRoot/home/thomasjohnarouge/Steam/osx32/steamcmd
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

Abort trap: 6 (core dumped)
```

**Comment by ahyattdev** [comment]
It now fails here
Cannot load libfontconfig.so.1 (ELF): libfontconfig.so.1: cannot open shared object file: No such file or directory

**Comment by ahyattdev** [comment]
Relevant issues are #377 and #415.

@bugaevc does this look like a duplicate of our ELF loading in container woes?

**Comment by CuriousTommy** [comment]
I seem to run into this issue
```
$ ./steamcmd.sh 
Unable to determine CPU Frequency. Try defining CPU_MHZ.
```

**Comment by bugaevc** [comment]
> `Cannot load libfontconfig.so.1 (ELF): libfontconfig.so.1: cannot open shared object file: No such file or directory`
> @bugaevc does this look like a duplicate of our ELF loading in container woes or is this a new issue?

No, ELF loading itself should work; in particular loading fontconfig works for me. Do you have `libfontconfig.so.1` on the host (and where is it)?
