### ISSUE TITLE
Library not found when I run DMG software

### ISSUE THREAD

**Issue by nwxufo** [darlinghq/darling#508]
Darling [/Volumes/DingTalk_v4.6.25.2]$ /Applications/DingTalk.app/Contents/MacOS/DingTalk

[/Volumes/DingTalk_v4.6.25.2]$ /Applications/DingTalk.app/Contents/MacOS/DingTalk 
dyld: Library not loaded: /System/Library/Frameworks/EventKit.framework/Versions/A/EventKit
  Referenced from: /Applications/DingTalk.app/Contents/MacOS/DingTalk
  Reason: image not found
Abort trap: 6 (core dumped)

**Comment by ahyattdev** [comment]
Thanks for reporting this, EventKit stubs have since been added
