### ISSUE TITLE
Cannot make Ubuntu 12.04

### ISSUE THREAD

**Issue by wrkrbee** [darlinghq/darling#51]
I can't upgrade to newer Ubuntu right because when I tried I ran into all kinds of problems -- more than I have time to mess with right now.  So I'm stuck on 12.04 LTS.

I followed the Ubuntu build instructions, and received a few errors during the GNU makes / make install processes which are typically normal, but I documented anyway.  I will not post it here unless asked since they are rather long.

So then I moved onto the Ordinary build instructions and got to here with the following errors.

Code:
CC=clang CXX=clang++ cmake .
-- The C compiler identification is Clang
-- The CXX compiler identification is Clang
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- No build type selected, default to Debug
-- This is a 32-bit build
-- checking for module 'libbsd >= 0.4.2'
--   package 'libbsd >= 0.4.2' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:36 (pkg_check_modules)

-- checking for module 'libudev'
--   found libudev, version 175
-- The ASM-ATT compiler identification is GNU
-- Found assembler: /usr/bin/as
-- The ASM_NASM compiler identification is unknown
-- Found assembler: /usr/bin/nasm
-- Looking for bsd/wchar.h
-- Looking for bsd/wchar.h - not found
You have called ADD_LIBRARY for library Carbon without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library AppKit without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library auto without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGNUSTEPBASE_INCLUDE_DIR
   used as include directory in directory /home/juice/darling
   used as include directory in directory /home/juice/darling/src/motool
   used as include directory in directory /home/juice/darling/src/util
   used as include directory in directory /home/juice/darling/src/libmach-o
   used as include directory in directory /home/juice/darling/src/libdyld
   used as include directory in directory /home/juice/darling/src/dyld
   used as include directory in directory /home/juice/darling/src/libSystem
   used as include directory in directory /home/juice/darling/src/libltdl
   used as include directory in directory /home/juice/darling/src/Cocoa
   used as include directory in directory /home/juice/darling/src/libobjcdarwin
   used as include directory in directory /home/juice/darling/src/CoreFoundation
   used as include directory in directory /home/juice/darling/src/libncurses
   used as include directory in directory /home/juice/darling/src/CoreSecurity
   used as include directory in directory /home/juice/darling/src/CoreServices
   used as include directory in directory /home/juice/darling/src/ExceptionHandling
   used as include directory in directory /home/juice/darling/src/IOKit
   used as include directory in directory /home/juice/darling/src/Foundation
   used as include directory in directory /home/juice/darling/src/Carbon
   used as include directory in directory /home/juice/darling/src/CoreVideo
   used as include directory in directory /home/juice/darling/src/OpenGL
   used as include directory in directory /home/juice/darling/src/thin
   used as include directory in directory /home/juice/darling/src/libstdc++darwin
LIBGNUSTEPCOREBASE_INCLUDE_DIR
   used as include directory in directory /home/juice/darling
   used as include directory in directory /home/juice/darling/src/motool
   used as include directory in directory /home/juice/darling/src/util
   used as include directory in directory /home/juice/darling/src/libmach-o
   used as include directory in directory /home/juice/darling/src/libdyld
   used as include directory in directory /home/juice/darling/src/dyld
   used as include directory in directory /home/juice/darling/src/libSystem
   used as include directory in directory /home/juice/darling/src/libltdl
   used as include directory in directory /home/juice/darling/src/Cocoa
   used as include directory in directory /home/juice/darling/src/libobjcdarwin
   used as include directory in directory /home/juice/darling/src/CoreFoundation
   used as include directory in directory /home/juice/darling/src/libncurses
   used as include directory in directory /home/juice/darling/src/CoreSecurity
   used as include directory in directory /home/juice/darling/src/CoreServices
   used as include directory in directory /home/juice/darling/src/ExceptionHandling
   used as include directory in directory /home/juice/darling/src/IOKit
   used as include directory in directory /home/juice/darling/src/Foundation
   used as include directory in directory /home/juice/darling/src/Carbon
   used as include directory in directory /home/juice/darling/src/CoreVideo
   used as include directory in directory /home/juice/darling/src/OpenGL
   used as include directory in directory /home/juice/darling/src/thin
   used as include directory in directory /home/juice/darling/src/libstdc++darwin
LIBOBJC2_INCLUDE_DIR
   used as include directory in directory /home/juice/darling
   used as include directory in directory /home/juice/darling/src/motool
   used as include directory in directory /home/juice/darling/src/util
   used as include directory in directory /home/juice/darling/src/libmach-o
   used as include directory in directory /home/juice/darling/src/libdyld
   used as include directory in directory /home/juice/darling/src/dyld
   used as include directory in directory /home/juice/darling/src/libSystem
   used as include directory in directory /home/juice/darling/src/libltdl
   used as include directory in directory /home/juice/darling/src/Cocoa
   used as include directory in directory /home/juice/darling/src/libobjcdarwin
   used as include directory in directory /home/juice/darling/src/CoreFoundation
   used as include directory in directory /home/juice/darling/src/libncurses
   used as include directory in directory /home/juice/darling/src/CoreSecurity
   used as include directory in directory /home/juice/darling/src/CoreServices
   used as include directory in directory /home/juice/darling/src/ExceptionHandling
   used as include directory in directory /home/juice/darling/src/IOKit
   used as include directory in directory /home/juice/darling/src/Foundation
   used as include directory in directory /home/juice/darling/src/Carbon
   used as include directory in directory /home/juice/darling/src/CoreVideo
   used as include directory in directory /home/juice/darling/src/OpenGL
   used as include directory in directory /home/juice/darling/src/thin
   used as include directory in directory /home/juice/darling/src/libstdc++darwin

-- Configuring incomplete, errors occurred!

Code:
make
make: *** No targets specified and no makefile found.  Stop.

I downloaded clang and cmake as per the Ubuntu build instructions.  So what am I missing?

**Comment by LubosD** [comment]
Not relevant any more, the build system has changed substantially.

**Comment by DeadNumbers** [comment]
@thopiekar Now you PPA is disabled?

**Comment by thopiekar** [comment]
Yes, I wasn't updated for a long time and it was using upstream gnustep
packages. It was a lot of work and time consuming to keep the packages up
to date.
Oh, and the kernel module was new. A DKMS package would be needed here.

That's why I disabled the PPA.

**Comment by DeadNumbers** [comment]
@thopiekar So sad. But can you share old packages?

**Comment by thopiekar** [comment]
I can but I also can image that otger people might expect that these are up
to date and I'm sure Luboš does not want to waste time on old bugs (at
least reading them).

**Comment by DeadNumbers** [comment]
@thopiekar share it's, please. I dont reporting old bugs, just test on my Precise.
