### ISSUE TITLE
Error make lkm

### ISSUE THREAD

**Issue by twofortyone** [darlinghq/darling#512]
I was trying to install lkm after installing darling but these errors appear when I run make lkm 
What can I do?
```
Built target migcom
Built target migexe
Built target lkm_generate
Building the Linux kernel module
make[4]: Entering directory '/home/paalpago/darling/src/lkm'
Running kernel version is 5.0.10-200.fc29.x86_64
rm -f darling-mach.mod.o
make -C /lib/modules/5.0.10-200.fc29.x86_64/build M=/home/paalpago/darling/src/lkm modules
make[5]: Entering directory '/home/paalpago/darling/src/lkm'
make[5]: *** /lib/modules/5.0.10-200.fc29.x86_64/build: No such file or directory.  Stop.
make[5]: Leaving directory '/home/paalpago/darling/src/lkm'
make[4]: *** [Makefile:292: default] Error 2
make[4]: Leaving directory '/home/paalpago/darling/src/lkm'
make[3]: *** [src/lkm/CMakeFiles/lkm.dir/build.make:58: src/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:54340: src/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:54347: src/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15036: lkm] Error 2

```

**Comment by bugaevc** [comment]
It looks like you've updated your kernel and the supporting files for the version you're still running have already been uninstalled (normally dnf keeps three lastest kernel versions and uninstalls the older ones — perhaps you've updated your kernel more than two times without rebooting). In this case a reboot should help.

Otherwise, try to figure out why `/lib/modules/5.0.10-200.fc29.x86_64/build` is missing.

P.S. you should update to F30, because Clang 7 has problems building Core Foundation.

**Comment by ahyattdev** [comment]
Will reopen if reboot doesn't solve it

**Comment by hayyaun** [comment]
> It looks like you've updated your kernel and the supporting files for the version you're still running have already been uninstalled (normally dnf keeps three lastest kernel versions and uninstalls the older ones — perhaps you've updated your kernel more than two times without rebooting). In this case a reboot should help.
> 
> Otherwise, try to figure out why `/lib/modules/5.0.10-200.fc29.x86_64/build` is missing.
> 
> P.S. you should update to F30, because Clang 7 has problems building Core Foundation.

Try installing ```linux-headers```, that might be one reason why ```/lib/modules/<version>/build``` is not being present.

**Comment by BoscoHan** [comment]
> Try installing `linux-headers`, that might be one reason why `/lib/modules/<version>/build` is not being present.

This solved it for me
