### ISSUE TITLE
cant make the darling-mach kernel module with ubuntu

### ISSUE THREAD

**Issue by DragonWIn64** [darlinghq/darling#513]
hello everyone

I have been working around my Chromebook I've downloaded Ubuntu 18.04 and have gone through the darling steps until the darling-mach coding which doesn't work for me im not sure what's gone wrong as all the previous files have downloaded. any suggestions?

**Comment by CuriousTommy** [comment]
You should also copy/paste the content that is displayed on the terminal screen. Also what Chromebook do you have?

> have gone through the darling steps until the darling-mach coding which doesn't work for me im not sure what's gone wrong as all the previous files have downloaded. any suggestions?

So are you getting the error when you do `make`, or do you mean something else?

**Comment by DragonWIn64** [comment]
yeah the make lkm comes up with an error and my copy and paste function doesn't work so I type it and check and recheck it for errors in the typing and the Chromebook is an Acer Chromebook 14

**Comment by CuriousTommy** [comment]
>  my copy and paste function doesn't work

Huh... that's interesting. Maybe you can [pipe the output to a file](https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file) instead and upload that file. Without the exact error messages, it is hard for others to help you with your problem.

**Comment by DragonWIn64** [comment]
yeah I can't paste into it but I can copy out of it I'm just in the process of restarting the download from scratch and seeing if the problem persists I will paste the code if it comes up again like I'm expecting

**Comment by jeanthom** [comment]
Hi, I'm running into an issue with make lkm too, but on Fedora 29:

```
Built target migcom
Built target migexe
Built target lkm_generate
Building the Linux kernel module
make[4]: Entering directory '/root/darling/src/lkm'
Running kernel version is 4.20.13-200.fc29.x86_64
rm -f darling-mach.mod.o
make -C /lib/modules/4.20.13-200.fc29.x86_64/build M=/root/darling/src/lkm modules
make[5]: Entering directory '/root/darling/src/lkm'
make[5]: *** /lib/modules/4.20.13-200.fc29.x86_64/build: No such file or directory.  Stop.
make[5]: Leaving directory '/root/darling/src/lkm'
make[4]: *** [Makefile:292: default] Error 2
make[4]: Leaving directory '/root/darling/src/lkm'
make[3]: *** [src/lkm/CMakeFiles/lkm.dir/build.make:58: src/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:54343: src/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:54350: src/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15036: lkm] Error 2
```

**Comment by jeanthom** [comment]
I found the solution: /lib/modules/4.20.13-200.fc29.x86_64/build is a symlink to a folder holding kernel-devel things, and Fedora 29 doesn't provide that for Linux 4.20.

Upgrading to Linux 5 solved this issue.

**Comment by DragonWIn64** [comment]
unfortunatly that solution doesnt work for ubuntu its searching for
 a file that doesnt exsist /lib/modules/3.18.0-19030-g15d00031737b/build

**Comment by ahyattdev** [comment]
If it's the same Ubuntu 18.04 as all the other computers I'm not sure why the Chromebook part matters. If this is installed on the hardware, not virtualized or some weird container, it should be same.

Please post your build output with the error. To copy text in the Ubuntu terminal it's ctrl+shift+c.

**Comment by Austcool-Walker** [comment]
I'm trying to make an dkms source `.deb` but its failing with ```DKMS make.log for darling-mach-2573.4120631 for kernel 5.0.0-31-generic (x86_64)
Mon Oct  7 16:13:32 EDT 2019
Running kernel version is 5.0.0-31-generic
rm -f darling-mach.mod.o
make -C /lib/modules/5.0.0-31-generic/build M=/var/lib/dkms/darling-mach/2573.4120631/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.0.0-31-generic'
Running kernel version is 5.0.0-31-generic
Invoked by kernel build system, building for 5.0.0-31-generic
  CC [M]  /var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_entry.o
  CC [M]  /var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_hash.o
  CC [M]  /var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_space.o
  CC [M]  /var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_kmsg.o
/var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_kmsg.c:87:10: fatal error: mach/mach_vm.h: No such file or directory
 #include <mach/mach_vm.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:284: recipe for target '/var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_kmsg.o' failed
make[2]: *** [/var/lib/dkms/darling-mach/2573.4120631/build/osfmk/ipc/ipc_kmsg.o] Error 1
Makefile:1608: recipe for target '_module_/var/lib/dkms/darling-mach/2573.4120631/build' failed
make[1]: *** [_module_/var/lib/dkms/darling-mach/2573.4120631/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-31-generic'
Makefile:291: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by ahyattdev** [comment]
@Austcool-Walker could you share the steps for which you're using to make this deb?

**Comment by ahyattdev** [comment]
Issues building the deb have been fixed, and check out the releases on this github for packages.

**Comment by drumit** [comment]
==> ERROR: Failure while creating working copy of darling-swift git repo
    Aborting...
error making: darling (darling-mach-dkms)
