### ISSUE TITLE
error: Server does not allow request for unadvertised object 

### ISSUE THREAD

**Issue by zaoqi** [darlinghq/darling#515]
error: Server does not allow request for unadvertised object 09def92e3ef6b5f567ea9fc79ab5478ff2633da2
Fetched in submodule path 'src/external/darling-dmg', but it did not contain 09def92e3ef6b5f567ea9fc79ab5478ff2633da2. Direct fetching of that commit failed.

**Comment by bugaevc** [comment]
The commit *is* there: https://github.com/darlinghq/darling-dmg/commit/09def92e3ef6b5f567ea9fc79ab5478ff2633da2

That being said, it looks like we haven't updated darling-dmg submodule for a long time...

**Comment by ahyattdev** [comment]
Maybe weird GitHub issue

**Comment by ahyattdev** [comment]
HEAD of darling-dmg is now a new commit anyway, which I pulled fine.
