### ISSUE TITLE
Cannot make on Ubuntu 13.10. 'ltdl.h' file not found

### ISSUE THREAD

**Issue by segadude** [darlinghq/darling#52]
After following all the build instructions for Ubuntu, I tried to make darling. It got to 64% and gave me this:
[ 64%] Building CXX object src/libltdl/CMakeFiles/ltdl.dir/libltdl.o
In file included from /home/brandon/darling/src/libltdl/libltdl.cpp:1:
/home/brandon/darling/src/libltdl/libltdl.h:3:10: fatal error: 'ltdl.h' file not
      found
# include <ltdl.h>

```
     ^
```

1 error generated.
make[2]: **\* [src/libltdl/CMakeFiles/ltdl.dir/libltdl.o] Error 1
make[1]: **\* [src/libltdl/CMakeFiles/ltdl.dir/all] Error 2
make: **\* [all] Error 2
brandon@brandon-Lenovo:~/darling$ make
[  4%] Built target util
[  8%] Built target mach-o
[  8%] Built target motool
[ 20%] Built target dyld
[ 22%] Built target dyld-bin
[ 22%] Built target dyldd
[ 63%] Built target System
Scanning dependencies of target ltdl
[ 64%] Building CXX object src/libltdl/CMakeFiles/ltdl.dir/libltdl.o
/home/brandon/darling/src/libltdl/libltdl.cpp:1:10: fatal error: 'libltdl.h'
      file not found
# include "libltdl.h"

```
     ^
```

1 error generated.
make[2]: **\* [src/libltdl/CMakeFiles/ltdl.dir/libltdl.o] Error 1
make[1]: **\* [src/libltdl/CMakeFiles/ltdl.dir/all] Error 2
make: **\* [all] Error 2

Why is this file missing? Or am I doing something wrong?

**Comment by RajKumarPandey** [comment]
Install libltdl-dev
sudo apt-get update
sudo apt-get install libltdl-dev
