### ISSUE TITLE
Real/copy of a real mac os installation

### ISSUE THREAD

**Issue by flutterbrony** [darlinghq/darling#520]
Hello, I was wondering if it is possible to use a reall mac os installation, or a copy of it as a DPREFIX for darlinghq ? And if yes, wich version of mac os ?
I tried to copy files from my mac os 10.12 installation in the .darlinghq directory, but it seems it doesn't work, I see no improvement over the files already present in that directory

**Comment by ahyattdev** [comment]
Sorry, we cannot help you with this as it is against the EULA of macOS.

Our goal is to create an open source compatibility layer for running Cocoa applications on other operating systems, independent of Apple's distribution.
