### ISSUE TITLE
unable to build with ninja: multiple rules generate iokitmigServer.c

### ISSUE THREAD

**Issue by arnetheduck** [darlinghq/darling#534]
Tried generating Ninja build files for a smoother build, but it looks like there are dependency problems - presumably in Makefile build also, though `make` doesn't detect them.

This is on a fresh clone, following instructions until `ninja` invokation:

```
[arnetheduck@tempus build]$ cmake -GNinja ..
...
[arnetheduck@tempus build]$ ninja
ninja: error: build.ninja:60969: multiple rules generate src/external/IOKitUser/iokitmigServer.c [-w dupbuild=err]

[arnetheduck@tempus build]$ cmake --version
cmake version 3.14.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[arnetheduck@tempus build]$ ninja --version
1.9.0
[arnetheduck@tempus build]$ cd ..
[arnetheduck@tempus darling]$ git rev-parse HEAD
a567e86cb72ddfb00f53c33ecb205d0670db7e2b
[arnetheduck@tempus darling]$ uname -a
Linux tempus 5.1.11-300.fc30.x86_64 #1 SMP Mon Jun 17 19:33:15 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


```

Happy to close if `ninja` is not supported.

**Comment by bugaevc** [comment]
> Happy to close if ninja is not supported.

Well yeah, ninja is not supported, but I'm actually using it (with some patches to make it work), so let's keep this open as a reminder for me to upstream the changes.

**Comment by bugaevc** [comment]
This should work now, although there still seem to be some issues with the Ninja build.
