### ISSUE TITLE
make on Ubuntu 18.04 fails: c++: error: unrecognized command line option ‘-fblocks’

### ISSUE THREAD

**Issue by mdwhitis** [darlinghq/darling#535]
Building CXX object src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/ld/InputFiles.o
c++: error: unrecognized command line option ‘-fblocks’
src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/build.make:62: recipe for target 'src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/ld/InputFiles.o' failed
make[2]: *** [src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/ld/InputFiles.o] Error 1
CMakeFiles/Makefile2:3471: recipe for target 'src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/all' failed
make[1]: *** [src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jamesbrink** [comment]
Shot in the dark but double check your dependencies. If you're just looking to get it working sometimes rolling back to an older commit gets it going

I have commit 
ab56f3209d75ad67a140e1f3e6baccfdca7a1c78

Working on 18.04

Be sure to do git submodule update after check out.
You can use my Dockerfile as a reference for building if that helps
https://github.com/utensils/docker-darling/blob/master/Dockerfile

**Comment by ibcz** [comment]
Your clang version is wrong (clang has the blocks plugin but since it’s missing, the argument is passed to g++? which does not have it either, hence the error). If you installed the clang from the recommended dependencies, remove it and install the most recent one: sudo apt-get -y purge clang-* && sudo apt-get install clang

This is not the only problem though, due to a typo in code, the current version break build on ca. 38%. I developed a fix for it, if anyone needs, I can post it.

**Comment by Newbytee** [comment]
The issue seems to occur if `c++` on your system refers to gcc rather than Clang. I was able to solve this issue by removing gcc and g++ (could probably have updated alternatives instead of doing this though).

**Comment by ahyattdev** [comment]
Maybe we could solve this by requiring `clang++`

**Comment by ahyattdev** [comment]
Can someone experiencing this run this in their build folder and post the output here?

`cat CMakeCache.txt | grep CMAKE_CXX_COMPILER`

**Comment by ahyattdev** [comment]
This is how we get the c++ compiler now:

```
if (NOT DEFINED CMAKE_CXX_COMPILER)
	find_program(CMAKE_CXX_COMPILER NAMES
		"clang++"
		"clang++-4.0"
		"clang++-7")
endif(NOT DEFINED CMAKE_CXX_COMPILER)
```

**Comment by ahyattdev** [comment]
Works on 18.04.3 LTS using instructions on the wiki

**Comment by dinana** [comment]
Still an issue on Debian 10:
Scanning dependencies of target x86_64-apple-darwin11-ld
[  0%] Building CXX object src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/ld/InputFiles.cpp.o
c++: error: unrecognized command line option ‘-fblocks’
make[2]: *** [src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/build.make:63: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/ld/InputFiles.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:915: src/external/cctools-port/cctools/ld64/src/CMakeFiles/x86_64-apple-darwin11-ld.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

`cat CMakeCache.txt | grep CMAKE_CXX_COMPILER` outputs:
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-8
CMAKE_CXX_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-8
//ADVANCED property for variable: CMAKE_CXX_COMPILER
CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_AR
CMAKE_CXX_COMPILER_AR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_COMPILER_RANLIB
CMAKE_CXX_COMPILER_RANLIB-ADVANCED:INTERNAL=1

**Comment by ahyattdev** [comment]
@dinana well that explains it, `CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++` is definetly not `clang`

Could you post what clang version you have installed and the command to run it? Like `clang++-6.0` or something?

**Comment by jasonclane** [comment]
I am running debian 10 and I have the same issue. The CMakeCache.txt looks just line dinana's version. Here is my clang version info:

clang --version


clang version 7.0.1-8 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by ahyattdev** [comment]
@jasonclane do you have the command `clang++-7` installed? This is how we are currently finding the compiler

```
if (NOT DEFINED CMAKE_C_COMPILER)
        find_program(CMAKE_C_COMPILER NAMES
                "clang"
                "clang-4.0"
                "clang-7")
endif(NOT DEFINED CMAKE_C_COMPILER)

if (NOT DEFINED CMAKE_CXX_COMPILER)
        find_program(CMAKE_CXX_COMPILER NAMES
                "clang++"
                "clang++-4.0"
                "clang++-7")
endif(NOT DEFINED CMAKE_CXX_COMPILER)
```

**Comment by jasonclane** [comment]
Actually. I had the clang-6 on earlier and removed it and install clang-7, but I didn't rerun the cmake after that. I just deleted all the files in build (this time) and re-ran cmake and now make is still running. I think it has gotten further along this time. Will update after it finishes.

**Comment by ahyattdev** [comment]
I found that we weren't automatically detecting `clang-6.0` and `clang++-6.0`. I modified our detection to cover that.

However, I noticed that it wouldn't work until I **deleted `CMakeCache.txt`** from my built folder.

So when in doubt or when you change your clang package, please delete `CMakeCache.txt` or delete your build folder entirely.

**Comment by judikaelB** [comment]
hello @jasonclane you may need to specifie on the CmakeCache.txt this line : `CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++` by this line `CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++`, this work well for me on fedora 31. if that not work go to documentation at : https://docs.darlinghq.org/build-instructions.html , and install dependencies, after that ensure you have clag++ at this line in CmakeCache.txt `CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++` after that you can make easilly.

hope this help
