### ISSUE TITLE
Support for running with an alternate homedir

### ISSUE THREAD

**Issue by moon-chilled** [darlinghq/darling#538]
Would it be possible to add support for darling creating its own homedir instead of co-opting your own?  I want a separation between my darling homedir and my main one.

**Comment by bugaevc** [comment]
You mean placing `/Users/$USER` somewhere other than your home directory on the host?

**Comment by Elronnd** [comment]
Yes.

**Comment by ahyattdev** [comment]
The prefix now has it's own home folder. There are a few symlinks made, for stuff like `Downloads`, but I believe you can accomplish what you want by deleting those and making them folders.
