### ISSUE TITLE
Adding binfmt support

### ISSUE THREAD

**Issue by thopiekar** [darlinghq/darling#54]
Made some researches executing Mach-0-64 and Universal (aka fat binaries) using binfmt.

The result is that it isn't needed anymore to execute a mach-0/universal binary using dyld, just executing it as a native binary.

Mach-0-64:

```
package darling
interpreter /usr/bin/dyld
offset 0
magic \xCA\xFE\xBA\xBE
```

Universal

```
package darling
interpreter /usr/bin/dyld
offset 0
magic \xCA\xFE\xBA\xBE
```

Both need to be added into /usr/share/binfmts, eg. as "darling-mach-0-64bit" and "darling-universal" and finally "sudo update-binfmts".

**Comment by jcoffland** [comment]
Shouldn't ``/usr/share/binfmts/darling-mach-0-64bit`` contain?:

```
package darling
interpreter /usr/bin/dyld64
offset 0
magic \xCA\xFE\xBA\xBE
```

Other sources use ``/usr/bin/dyld64``.  Otherwise the two files are the same.

**Comment by thopiekar** [comment]
Yes, thats correct. I worked on this in the past when I had darling only working on one architecture.
(Please note the date when I created the PR.)

I haven't been working on Ubuntu/Debian packaging for a long time and also haven't used darling for a long time, too, but I believe the code above should still work 😉

**Comment by jcoffland** [comment]
Thanks for this.

For future reference, I found that there are actually at least 6 different magics needed for different binaries:

Fat binaries ``/usr/share/binfmts/darling_universal``:
```
package darling
interpreter /usr/bin/dyld64
offset 0
magic \xca\xfe\xba\xbe`
```

Fat binaries, reverse order ``/usr/share/binfmts/darling_universal_reverse``:
```
package darling
interpreter /usr/bin/dyld64
offset 0
magic \xbe\xba\xfe\xca`
```

64-bit binaries ``/usr/share/binfmts/darling_macho_64bit``:
```
package darling
interpreter /usr/bin/dyld64
offset 0
magic \xfe\xed\xfa\xcf`
```

64-bit binaries, reverse order ``/usr/share/binfmts/darling_macho_64bit_reverse``:
```
package darling
interpreter /usr/bin/dyld64
offset 0
magic \xcf\xfa\xed\xfe`
```


32-bit binaries ``/usr/share/binfmts/darling_macho_32bit``:
```
package darling
interpreter /usr/bin/dyld
offset 0
magic \xfe\xed\xfa\xce`
```

32-bit binaries, reverse order ``/usr/share/binfmts/darling_macho_32bit_reverse``:
```
package darling
interpreter /usr/bin/dyld
offset 0
magic \xce\xfa\xed\xfe`
```

Cheers!

**Comment by LubosD** [comment]
dyld32 is supposed to be used for 32-bit binaries or just use dyld for everything.

**Comment by jcoffland** [comment]
I'm not sure.  It should be tested.
