### ISSUE TITLE
Problem during compilation  "'tiffio.h' file not found"

### ISSUE THREAD

**Issue by goerster87** [darlinghq/darling#544]
I get a problem when I want to make the project:

/home/dfoerster/darling/darling/src/external/cocotron/Onyx2D/O2TIFFImageDirectory.m:19:9: fatal error: 'tiffio.h' file not found
#import <tiffio.h>
        ^~~~~~~~~~

I'm trying to make the project on Ubuntu 16.04.6 LTS. 'libtiff5-dev' is already installed...

**Comment by goerster87** [comment]
I'm using cmake version 3.15.1 and clang version 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1)

**Comment by CuriousTommy** [comment]
How did you download the darling project? Did you use `git clone --recursive`?

**Comment by goerster87** [comment]
Yes, I used the command from the how to

`git clone --recursive https://github.com/darlinghq/darling.git`

**Comment by ahyattdev** [comment]
`git submodule init && git submodule update`?

**Comment by goerster87** [comment]
Done. But it doesn't change anything.

**Comment by goerster87** [comment]
I had also the problem, that the file '/usr/include/jconfig.h' was missing, so I created it manually. Is it possible, that that has something to do with the problem?

**Comment by goerster87** [comment]
Solved... the problem was, that this file (and some others) were in another directory (/usr/include/x86_64-linux-gnu/tiffio.h). I created a softlink for each 'missing' file.
