### ISSUE TITLE
curl not working

### ISSUE THREAD

**Issue by princeofgiri** [darlinghq/darling#547]
I try curl some website without https, and it just keep silent.

**Comment by ahyattdev** [comment]
We hope to get this working soon!

We are tracking it here: https://github.com/darlinghq/darling/issues/463

In short, we need to implement some of the cryptography functions that it requires.

**Comment by CuriousTommy** [comment]
@ahyattdev Normal HTTP websites should work though, right?

**Comment by bugaevc** [comment]
Yep, plain HTTP works
