### ISSUE TITLE
Request detachment of darling-foundation repo from gnustep/libs-base repo

### ISSUE THREAD

**Issue by d235j** [darlinghq/darling#548]
Even though the README for https://github.com/darlinghq/darling-foundation indicates that this is not a fork, the repo is still showing as a fork.

To reduce confusion, it would be a good idea to request that GitHub Support detach the fork:
https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by ahyattdev** [comment]
Cool, I contacted support for this

**Comment by ahyattdev** [comment]
They took care of it!
