### ISSUE TITLE
Can I use Xcode on Linux using Darling

### ISSUE THREAD

**Issue by Joe23232** [darlinghq/darling#551]
Is it possible to use Xcode on Linux using` Darling`?

Additionally I want to know does `Darling` sandbox applications? And can I chose what directory does it have full access to?

**Comment by ahyattdev** [comment]
Xcode currently doesn't work. Also, please read the license agreement for Xcode before using it. It only allows for it to run on Apple hardware, so Linux on a Mac is OK but not Linux on PC hardware.

It works similar to WINE in that there is a Prefix but we currently put your home folder as the home folder for your prefix.

There isn't any file system access sandboxing at the moment.

**Comment by Joe23232** [comment]
@ahyattdev 

> Xcode currently doesn't work.

Would it eventually work?


> Also, please read the license agreement for Xcode before using it.

I just need to use Xcode for my university subject and not actually use it for commercial use.

**Comment by ahyattdev** [comment]
Our goal is for our API coverage to eventually be good enough for it to work!

EULAs apply regardless of purpose, including noncommercial. They are why we want FOSS 😉

**Comment by Joe23232** [comment]
@ahyattdev 

> Most EULAs apply regardless of purpose, including noncommercial.

Would their EULA prevent me from using the application by any chance?

> They are why we want FOSS wink

Off course same here =D I really hate how proprietary software always limits you or spies on you etc.

One other question
> There isn't any file system access sandboxing at the moment.

So does this mean that the entire application is sandboxed and it can't access any directory on Linux?

**Comment by tarekwiz** [comment]
@Joe23232 No it means that the entire Linux filesystem is exposed to the darling instance

**Comment by ahyattdev** [comment]
@Joe23232 the EULA prevents you from using it legally, but there is no DRM of sorts if that's what you're asking.

Like @tarekwiz said, there isn't much focus on security at the moment, so no sandboxing. So only run trusted software in Darling. Or run Darling on a Linux VM.
