### ISSUE TITLE
Anybody tested with success Brew package manager..

### ISSUE THREAD

**Issue by oscarbg** [darlinghq/darling#553]
Hi, tried installing brew on darling mainly for mc,wget,etc..
run script:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

I check I have correct Ruby:
 /usr/bin/ruby -v

`ruby 2.0.0p648 (2015-12-16 revision 53162) [universal-darwin16]`

and also curl:

 curl --version
```
curl 7.43.0 (Darling) libcurl/7.43.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```
it fails at end with:
```
 -e:1: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
-e:2: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
..._internal called: In ModuleImpl::activate, mAppNotifyCallbac...
...                               ^
-e:3: syntax error, unexpected tINTEGER, expecting keyword_do or '{' or '('
_os_log_internal called: create 0x7ffada40d532 for 0x7ffada40d530
                                              ^
```

full log :
[brewdarlingerr.txt](https://github.com/darlinghq/darling/files/3531496/brewdarlingerr.txt)

EDIT: notice I'm running darling on WSL2.. don't know if on native Linux distro will fail or not..

**Comment by CuriousTommy** [comment]
It also fails on a native Linux distro. You are running into https://github.com/darlinghq/darling/issues/463. Trying to access https websites does not currently work.

Also, brew relies on user management tools (such as `dsmemberutil`), that are not properly implemented on Darling.

**Comment by oscarbg** [comment]
thanks.. yep even the recomended rudix manager fails similarly..

**Comment by ahyattdev** [comment]
We currently need more crypto functions. The cause of this issue is TLS doesn't work yet. Help wanted!

#463
