### ISSUE TITLE
  Could not find toolchain file: ../../Toolchain-x86_64.cmake Call Stack

### ISSUE THREAD

**Issue by kpodosky** [darlinghq/darling#556]
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file: ../../Toolchain-x86_64.cmake
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

**Comment by ahyattdev** [comment]
These instructions are outdated, you just need `cmake ..` from within the build folder now.
