### ISSUE TITLE
Abstract Darling from kernel (/ core OS dependencies) so as to facilitate macOS Darling release for 32bit app execution

### ISSUE THREAD

**Issue by ylluminate** [darlinghq/darling#559]
This may sound a little crazy at first, but I think there's a huge potential and enormous market adoption opportunity: With the coming of Catalina and the death of 32bit support, it would be very nice to have an abstraction of Darling that would facilitate running atop Xnu/Darwin so that the 32bit emulation that WINE / CodeWeavers is working on could be leveraged to still run 32bit macOS apps ON macOS 10.15+ (Catalina and beyond).

Aside from this facilitating 32bit app execution, which is super important to a huge number of people, it could also facilitate the use of "unsupported" apps as such support is added over time, similar to how WINE is sometimes used for various and older Windows apps.

**Comment by ahyattdev** [comment]
While this would be cool, it would be a lot of effort since we heavily rely on Linux. For people wanting to use Darling to run 32-bit apps I think it makes more sense for them to run Linux in a VM and run their programs there.
