### ISSUE TITLE
Can't compile due to OpenDirectory files missing

### ISSUE THREAD

**Issue by Spenk009** [darlinghq/darling#560]
Darling won't compile with the given [instructions](https://wiki.darlinghq.org/build_instructions) on my machine (Linux Mint 19.1 Tessa x86_64). I was able to work around it, but wanted to make light of the issue.

Builds failed at two "#include <opendirectory/odipc.h>" and one "#include <opendirectory/DSlibinfoMIG_types.h>"
I have three directories called "OpenDirectory", "OpenDirectoryOld" and "opendirectory_W541_Sep-12-155033-2019_CaseConflict" in the src folder. The CaseConflict folder has the missing file "odipc.h", which I copied into the OpenDirectory folder. Then I changed the #include files from "#include opendirectory/odipc.h" to "#include <OpenDirectory/odipc.h>" in both " "/src/libinfo/membership.subproj/membership.c".
The same operation was required for "DSlibinfoMIG_types.h", in "src/libinfo/lookup.subproj/ds_module.c".

my relevant input commands were:
sudo apt-get install cmake clang bison flex xz-utils libfuse-dev libudev-dev pkg-config libc6-dev:i386 linux-headers-generic gcc-multilib libcap2-bin libcairo2-dev libgl1-mesa-dev libtiff5-dev libfreetype6-dev libfreetype6-dev:i386 git libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev
git clone --recurse-submodules https://github.com/darlinghq/darling.git
sudo apt-get install cmake clang bison flex xz-utils libfuse-dev libudev-dev pkg-config libc6-dev:i386 linux-headers-generic gcc-multilib libcap2-bin libcairo2-dev libgl1-mesa-dev libtiff5-dev libfreetype6-dev libfreetype6-dev:i386 git libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev
cd darling/
mkdir build && cd build
cmake ..
sudo make install

**Comment by CuriousTommy** [comment]
@Spenk009 Are you by any chance using [Synology Cloud Sync](https://www.reddit.com/r/synology/comments/5obu3v/caseconflict/)? The `opendirectory_W541_Sep-12-155033-2019_CaseConflict` should be named `opendirectory`.

Try setting up the darling repo in another directory and see if it works there.

**Comment by tarnh** [comment]
I'm using ArchLinux and getting a failure to clone OpenDirectory before any compilation could start.

Sorry, it's German:
```
Klone nach ./darling-git/src/darling/src/lkm' ...
Fertig.
fatal: Repository ./darling-git/darling-opendirectory.git' existiert nicht.
fatal: Klonen von './darling-git/darling-opendirectory.git' in Submodul-Pfad './darling-git/src/darling/src/external/OpenDirectory' fehlgeschlagen
Zweiter Versuch 'src/external/OpenDirectory' zu klonen fehlgeschlagen, breche ab.
```

**Comment by ahyattdev** [comment]
Did not encounter this on a clean build, so closing. If you have an old copy, try running `git submodule init` then `git submodule update`
