### ISSUE TITLE
Library not loaded: CoreLocation

### ISSUE THREAD

**Issue by cassvail** [darlinghq/darling#567]
Library CoreLocation is missing while launching
```
/Applications/Affinity\ Photo.app/Contents/MacOS/Affinity\ Photo     
dyld: Library not loaded: /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
```

**Comment by CuriousTommy** [comment]
Do you by any chance have a real Mac and some experience with `git`? If so, would you be willing to [follow this guide](https://wiki.darlinghq.org/generating_stubs) and submit a pull request?

Also, keep in mind that GUI support is currently not supported.

**Comment by cassvail** [comment]
PR https://github.com/darlinghq/darling/pull/568

**Comment by ahyattdev** [comment]
Closing because related PR was merged
