### ISSUE TITLE
Implement C++ name (de)mangler for libstdc++

### ISSUE THREAD

**Issue by LubosD** [darlinghq/darling#57]
There are naming incompatibilities between Darwin and Linux versions of libstdc++.

x86-64:
Darwin: long long (x)
Linux: long (l)

i386:
Darwin: unsigned long (m)
Linux: unsigned int (j)

These functions are ABI-compatible, but have different names, so dyld cannot find them.

**Comment by trishume** [comment]
This would be awesome. I found something that could be an awesome real-world useful application for darling but it would need this.

Dragon Dictate for mac has all of its core speech rec code in dynamic libraries that only depend on libsystem and libstdc++.

If libstdc++ worked completely and a wrapper around that library was written it is possible that it could be used to provide very high quality dictation on Linux (with a purchase of Dragon of course).

**Comment by LubosD** [comment]
This problem is fixed in the darling-libsystem branch, soon to be merged into master. Closing.
