### ISSUE TITLE
Can't use curl: curl: (35) Unknown SSL protocol error in connection to raw.githubusercontent.com

### ISSUE THREAD

**Issue by SUPERCILEX** [darlinghq/darling#574]
I'm guessing it's related to #463, but if that's the case, how does one follow https://www.darlinghq.org/introduction/? That tutorial uses a curl command to an HTTPS site.

**Comment by Bernd-L** [comment]
I had the same issue back then.

Apparently you don't. No SSL for Darling.

**Comment by ahyattdev** [comment]
Yup, related

**Comment by kakolisgay** [comment]
Also have this issue, darlinghq should either try to add tls support or remove the https examples in the Things to Do section of the wiki.

**Comment by ahyattdev** [comment]
TLS support is a work-in-progress, tracked by #574

OK, removed uses of HTTPS from that page (where possible, GitHub sends 301 redirects when you try to use http).

**Comment by hassan91** [comment]
> Yup, related

Any Update ?
