### ISSUE TITLE
Build failed jconfig.h not found

### ISSUE THREAD

**Issue by manhnt9** [darlinghq/darling#578]
OS: Ubuntu 18.04
Darling failed to build on latest commit as well as v0.2019.8 tag due to jconfig.h not found.

This file belongs to libjpeg-turbo library, installing `libjpeg-turbo8-dev` and libjpeg-turbo0-dev` doesn't solve the issue, jconfig.h isn't included: https://packages.ubuntu.com/bionic/amd64/libjpeg-turbo8-dev/filelist

I had to go [here](https://sourceforge.net/projects/libjpeg-turbo/files/) and download `libjpeg-turbo-official_2.0.3_amd64.deb` to have jconfig.h.

Please consider to warn Ubuntu users about this.

**Comment by manhnt9** [comment]
I meet exactly 2 problems described in #544. jconfig and tiffio.h was not found.

**Comment by ahyattdev** [comment]
I develop on Ubuntu, so it tends to have the good support.

I'm trying to figure out how to reproduce this. On fresh builds of 18.04.3 (desktop and server) using the dependencies specified on the Wiki I run into no issues. Is there anything about your setup that may help?

**Comment by manhnt9** [comment]
Thanks @ahyattdev, I got around these include errors, only #579 left.
