### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by Kreyren** [darlinghq/darling#582]
![image](https://user-images.githubusercontent.com/11302521/70015361-63579180-157d-11ea-826d-64386ca46a05.png)

![image](https://user-images.githubusercontent.com/11302521/70015366-6d799000-157d-11ea-829a-5fb7cc528893.png)

Wine Is Not an Emulator same should apply to a darling no?

**Comment by ahyattdev** [comment]
This can be debated in the Discord (https://discord.gg/XRD3mQA), we tend to use "translation" and emulation" interchangeably.
