### ISSUE TITLE
make crashes on install (with Makefile:130) on Ubuntu 19.10

### ISSUE THREAD

**Issue by ProgrammerPlays** [darlinghq/darling#583]
Running clean 19.10; connected to the box via tmux in ssh. 

It crashes at 51% after building nm_cctools_misc with make: *** [Makefile:130: all] Error 2

Looked at other suggestions from SuperUser and *nix Stack Exchange as well as issue trackers on here but nothing seems to work.

**Comment by ProgrammerPlays** [comment]
Heres my *nix post: https://unix.stackexchange.com/questions/555646/make-fails-while-installing-darling

**Comment by ahyattdev** [comment]
Could you include more text from the build output? Also, please don't use `-j4` when getting that failure snipped because the error is buried under the output of the other jobs typically.

**Comment by ProgrammerPlays** [comment]
@ahyattdev https://paste.ubuntu.com/p/FxjnKwxknt

**Comment by CuriousTommy** [comment]
@ProgrammerPlays Does that link contain the entire log? I don't seem the error on there.

**Comment by ProgrammerPlays** [comment]
@CuriousTommy when i restart it it starts at 51%, idk why, maybe because its checking the stuff so fast idk, i also don't see the end of it there, which confuses me. ill check the contents of the log; is there a problem with using tee? maybe tee only echoes stdouts and not sterrs?

**Comment by BppleMan** [comment]
When I used "make -j4" I encountered the same error, then I used "make" to build and got the following error
`
[ 64%] Built target xip_extract_cpio
[ 65%] Built target zsh
[ 65%] Built target colcrt
[ 65%] Built target checknr
[ 65%] Built target makewhatis
[ 65%] Built target uudecode
[ 65%] Built target mesg
[ 65%] Built target write
[ 65%] Built target uuencode
[ 65%] Built target ncal
[ 65%] Built target calendar
[ 65%] Built target cal
[ 65%] Built target tsort
[ 65%] Built target units
[ 65%] Built target diffstat
[ 65%] Built target dsmemberutil
[ 65%] Building C object src/external/cocotron/Onyx2D/CMakeFiles/Onyx2D.dir/O2Encoder_JPG.o
In file included from /home/bppleman/Documents/darling/src/external/cocotron/Onyx2D/O2Encoder_JPG.m:5:
/usr/include/jpeglib.h:29:10: fatal error: 'jconfig.h' file not found
#include "jconfig.h"            /* widely used configuration options */
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/external/cocotron/Onyx2D/CMakeFiles/Onyx2D.dir/build.make:297: src/external/cocotron/Onyx2D/CMakeFiles/Onyx2D.dir/O2Encoder_JPG.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:49833: src/external/cocotron/Onyx2D/CMakeFiles/Onyx2D.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by ProgrammerPlays** [comment]
@CuriousTommy @ahyattdev here's the full error:
https://paste.ubuntu.com/gCwcYdptkg

**Comment by CuriousTommy** [comment]
> @CuriousTommy @ahyattdev here's the full error:
> https://paste.ubuntu.com/gCwcYdptkg

> The Paste you are looking for does not currently exist.

**Comment by TheBrokenRail** [comment]
I got:
```
In file included from /home/<USERNAME>/Documents/darling/darling/src/libstdcxx/src/compatibility.cc:52:
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/sstream:120:3: error: exception specification needed for member of incomplete class 'std::basic_stringbuf<char>'
                ~basic_stringbuf() {}
                ^
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:264:25: note: in evaluation of exception specification for 'std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf' needed here
  extern template class basic_stringbuf<char>;
                        ^
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:264:25: note: in instantiation of template class 'std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >' requested here
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:264:25: note: definition of 'std::basic_stringbuf<char>' is not complete until the closing '}'
In file included from /home/<USERNAME>/Documents/darling/darling/src/libstdcxx/src/compatibility.cc:52:
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/sstream:120:3: error: exception specification needed for member of incomplete class 'std::basic_stringbuf<wchar_t>'
                ~basic_stringbuf() {}
                ^
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:270:25: note: in evaluation of exception specification for 'std::basic_stringbuf<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::~basic_stringbuf' needed here
  extern template class basic_stringbuf<wchar_t>;
                        ^
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:270:25: note: in instantiation of template class 'std::basic_stringbuf<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >' requested here
/home/<USERNAME>/Documents/darling/darling/src/libstdcxx/include/c++/4.2.1/bits/sstream.tcc:270:25: note: definition of 'std::basic_stringbuf<wchar_t>' is not complete until the closing '}'
2 errors generated.
```

**Comment by CuriousTommy** [comment]
@TheBrokenRail For the time being, you can use this patch: https://github.com/darlinghq/darling/issues/573#issuecomment-549157768

**Comment by TheBrokenRail** [comment]
That seems to have fixed it!

**Comment by ahyattdev** [comment]
@ProgrammerPlays that paste link you provided is broken

We fixed a number of build issues within the past few weeks, so please pull the latest sources and try again.  Closing until we see that this is separate
