### ISSUE TITLE
[Suggestion] GSOC 2020

### ISSUE THREAD

**Issue by ErikEklund** [darlinghq/darling#584]
Last year I proposed to apply Darling for Google Summer of Code in ticket #460. A [wiki page](https://wiki.darlinghq.org/google_summer_of_code) was also created to track potential areas to work on, but sadly Darling did not apply that year.

I think Darling would be an excellent fit for GSOC and could benefit greatly from some dedicated people solving key issues. Applications open up on January 14, so I would suggest that the Wiki page is updated with the latest "key issues" where help is needed, and that we try to actually get an application sent in this year :).

More information at [GSOC 2020 Website](https://summerofcode.withgoogle.com/)

**Comment by ErikEklund** [comment]
Application for organizations is [now open](https://summerofcode.withgoogle.com/org-signup/).

Is anyone interested in organizing this? Or perhaps brainstorm suitable tasks?

Some suggestions:
- Implement most common missing CoreCrypto functions
- Get curl to work
- Homebrew support
- Chip away at GUI support, exact task tbd, but get a simple application to run
- Get MacPorts to run

Please feel free to fill in more ideas (or discard any that might be unreasonable). Would be great to get some more people involved.

**Comment by TheBrokenRail** [comment]
Here are my ideas:
- Get the LKM to build on newer Linux kernels (sounds like a big issue): #617
- Reduce warnings during build (there are a lot of warnings when building Darling)
- Speed up Darling's build time (is this possible?)
- All of https://wiki.darlinghq.org/google_summer_of_code

**Comment by TheBrokenRail** [comment]
Also #377 seems like it would fix a lot of problems.

**Comment by CuriousTommy** [comment]
This is my personal list.

* Build Darling for ARM64 device. It would be pretty cool to get Darling to run on those device. 
* Lay the groundwork for selecting which OS to build for (MacOS, iOS/iPadOS, tvOS, etc.). Right now Darling is built mainly with MacOS in mind.

**Comment by TheBrokenRail** [comment]
If ARM64 support is added, potentially Android support could be added (obviously with root because a kernel module is needed). This could allow eventually running iOS apps on Android.

**Comment by TheBrokenRail** [comment]
Also a lot of syscalls are unimplemented.

**Comment by ErikEklund** [comment]
Wanted to bump this and note that there is now two weeks left to apply. Is there any interest from the maintainers to enter Darling for GSOC?

**Comment by TheBrokenRail** [comment]
GSOC could help get a ton of problems fixed and features implemented in Darling.

**Comment by TheBrokenRail** [comment]
Any updates on this? @ahyattdev @bugaevc @LubosD

**Comment by TheBrokenRail** [comment]
There is only about 1 week left to apply.

**Comment by ErikEklund** [comment]
Exactly 1 week left today. Any plans to persue this @LubosD @bugaevc @ahyattdev ? (sorry for spamming this thread but the deadline is approaching fast)

**Comment by bugaevc** [comment]
Yes, please stop spamming this thread. I don't have any plans to participate in the GSoC, and it doesn't look like others do.

**Comment by ErikEklund** [comment]
Ok, thanks for the clarification, was not sure if it wasn't interesting to you or if people just hadn't had time to look into it. Closing so that we can stop spamming :)
