### ISSUE TITLE
Download binary on Release

### ISSUE THREAD

**Issue by LucasMW** [darlinghq/darling#585]
I failed trying to compile darling into my server at digital ocean. It ran out of disk space. 
Would it be possible to provide pre-built binaries, either verified or provided by a CI-CD service?

**Comment by ahyattdev** [comment]
What format do you want packages in?

**Comment by LucasMW** [comment]
My server is running Ubuntu 18.04 x64. 
I believe an ubuntu build would be pretty standard.
I think I am ok with a static binary allowed by chmod+x, called from terminal

**Comment by bugaevc** [comment]
> a static binary allowed by chmod+x, called from terminal.

It sounds like you grossly underestimate what a Darling installation consists of :D

**Comment by LucasMW** [comment]
Maybe you're right. I was looking forward something like wine.
I can do 
`wine a.exe` on linux
I was hoping to do 
`./darling maccmdapp` on linux also. 
I know wine simulates the file system, but I assumed the the binary was responsible for assembling "volume Z"  (Or whatever they call it)
But I really don't know how wine installation actually works.
Maybe it will be necessary an `apt install darling` in private apt repository first

**Comment by bugaevc** [comment]
That is the point of Darling, and using Darling as a user looks close to that. But for that to work, much more than a single executable is necessary.

A Darling installation consists of tons of libraries, executables and resources, and additionally a Linux kernel module (that has to be built against your exact version of the kernel). This is a far cry from a single portable statically linked executable.

**Comment by ahyattdev** [comment]
Hi @andyneff, trying to use the tools you created for making DEBs of Darling in response to this issue.

I get this error:

```
➜  darling git:(master) ✗ tools/makedeb
 dpkg-buildpackage -rfakeroot -us -uc -ui -b
dpkg-buildpackage: info: source package PACKAGE
dpkg-buildpackage: info: source version 0.1.20191231-1
dpkg-buildpackage: info: source distribution testing
dpkg-buildpackage: info: source changed by Darling build server <noreply@darlinghq.org>
 dpkg-source --before-build darling
dpkg-buildpackage: info: host architecture amd64
dpkg-source: error: source package name 'PACKAGE' is illegal: character 'P' not allowed
dpkg-buildpackage: error: dpkg-source --before-build darling subprocess returned exit status 25
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -b failed
```

Do you have any ideas why it's doing this? the changelog looks like this:

```
PACKAGE (0.1.20191231-1) testing; urgency=low

  * Daily build

 -- Darling build server <noreply@darlinghq.org>  Tue, 31 Dec 2019 00:37:42 -0500
```

Are there additional parameters that your `makedeb` script needs?

**Comment by andyneff** [comment]
@ahyattdev While I may be the last one to touch a file in there, I've only edited one line in there. I know far less about deb packaging than rpms.

```
docker run -it --rm -v `pwd`:/src debian:9
# Following https://wiki.darlinghq.org/build_instructions, debian 8 didn't work due to some weird freetype conflict, but that was after I did dpkg --add-architecture i386, so maybe I just screwed up that test altogether
apt install cmake clang-4.0 bison flex xz-utils libfuse-dev libudev-dev pkg-config libc6-dev-i386 linux-headers-amd64 libcap2-bin git libcairo2-dev libgl1-mesa-dev libtiff5-dev libfreetype6-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev build-essential devscripts clang ninja-build
cd /src
./tools/makedeb
```

And... I get the exact same problem!
I've never used `dch` so I don't have a clue how it is supposed to be used.

Theory: Fix the changelog to say `darling` instead of `PACKAGE`.

- Adding `--package darling` to the `dch` command works, but I have no idea how compatible the flag is in debian-land

```
cd /src
./tools/makedeb
```

Got further before crashing

```
make[1]: Entering directory '/src'
mkdir debbuild
cd debbuild && CFLAGS="" CXXFLAGS="" CPPFLAGS="" LDFLAGS="" cmake .. -DCMAKE_TOOLCHAIN_FILE=../Toolchain.cmake -DCMAKE_INSTALL_PREFIX=/usr
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineSystem.cmake:94 (message):
  Could not find toolchain file: ../Toolchain.cmake
```

At this point, I don't know why `rules` references a  `Toolchain.cmake` file that does not exist? I don't use that flag in the RPMs. Sorry I can't be of more help.

**Comment by ahyattdev** [comment]
Reopening until we post the packages somewhere

**Comment by ahyattdev** [comment]
Packages under github releases

**Comment by pquiring** [comment]
Would it be possible to post an updated DEB?  At least yearly?
Thanks,
