### ISSUE TITLE
How do I add a Framework to the /PrivateFrameworks/ folder?

### ISSUE THREAD

**Issue by Jwhite077** [darlinghq/darling#587]
I am trying to run a private CLI applications. When I attempt to run it inside Darling Shell, I am given the following error:

`dyld: Library not loaded: /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice`

I've tried adding MobileDevice.framework to the Darling folder in my home path, however, Darling doesn't seem to load the framework.

How can I resolve this issue?

**Comment by ahyattdev** [comment]
A stub can be created this way: https://wiki.darlinghq.org/generating_stubs

I am testing a commit that adds MobileDevice right now

**Comment by Jwhite077** [comment]
I managed to get the application I wanted to run fully however even thoughMobileDevice is added, it seems Darling isn't wanting to communicate with my iPhone. Any idea of how I could get this working?

**Comment by ahyattdev** [comment]
A stub for MobileDevice was added, but it doesn't have any functionality.

The stubs just have all the methods and functions and makes then do nothing.

You can see which stubs are being called by setting the environmental variable `STUB_VERBOSE`
