### ISSUE TITLE
USB Device Communication?

### ISSUE THREAD

**Issue by Jwhite077** [darlinghq/darling#588]
**Application inside Darling is unable to see connected USB devices.**

My Macbook Air was recently stolen and I had created an application that I use to restore my iPhone similar to iTunes, but with more customization. The recent commit to Darling has helped greatly and my CLI application is running in Darling without any errors. I really appreciate you taking your time to help me. I'm running into one more issue with Darling. My application starts by looking for an iPhone that is in DFU mode and is connected to the computer. My KUbuntu 9.10 is able to detect the device and I am able to send commands to the device just fine, however, when I run the application inside Darling...It appears the program is unable to see the phone in DFU mode at all. I was wondering if there was any additional steps I would have to do to get Darling to see USB devices or if I'm perhaps overthinking something? Thank you for creating Darling, It's vitally helpful in development and research when you don't a Mac around.

**Comment by ahyattdev** [comment]
Hi @Jwhite077, sorry to head your macbook was stolen. Thanks for the kind words!

Unfortunately we don't have USB device support yet, it has been a want for a while as issue #11 

Closing this as a duplicate
