### ISSUE TITLE
Automated uninstall through "make uninstall" and uninstall instructions on wiki

### ISSUE THREAD

**Issue by mujehoxe** [darlinghq/darling#590]

**Comment by LubosD** [comment]
???

**Comment by mujehoxe** [comment]
> ???

how can we uninstall darling.

**Comment by bugaevc** [comment]
> how can we uninstall darling

```bash
$ rm -rm /usr/local/libexec/darling
$ rm /usr/local/bin/darling*
```

and remove the kernel module wherever that gets installed on your system

**Comment by CuriousTommy** [comment]
@bugaevc Should I make a note about uninstalling darling in the wiki?

**Comment by ahyattdev** [comment]
@CuriousTommy yes, that would be useful. Another enhancement could be a `make uninstall` command that automates it in addition.

**Comment by CuriousTommy** [comment]
@ahyattdev I added a rough draft on the build instruction.

**Comment by ahyattdev** [comment]
Wiki page created https://wiki.darlinghq.org/uninstall
