### ISSUE TITLE
Remove FRAMEWORK_APPKIT and FRAMEWORK_COREAUDIO CMake options

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#601]
I can't seem to find anywhere where ```FRAMEWORK_APPKIT``` or ```FRAMEWORK_COREAUDIO``` are used.

**Comment by ahyattdev** [comment]
They are artifacts from when building each of those frameworks was optional. Now they have no use

**Comment by TheBrokenRail** [comment]
```FRAMEWORK_COREAUDIO``` seems to be used in ```CoreServices``` (https://github.com/darlinghq/darling/blob/e68d9249e7f8eef029b5d2c7b7fbc5278c45f1ea/src/CoreServices/Components.cpp) but the CMake code to build the ```CoreAudio``` component referenced by ```CoreServices``` when ```FRAMEWORK_COREAUDIO``` is activated is commented out (https://github.com/darlinghq/darling/blob/24f09b59e300183230c8c2e5356a81948ea48cae/src/CMakeLists.txt). It also looks like ```FRAMEWORK_APPKIT``` used to include additional code but that is also commented out (https://github.com/darlinghq/darling/blob/24f09b59e300183230c8c2e5356a81948ea48cae/src/CMakeLists.txt).
