### ISSUE TITLE
Darling Shell Crashing

### ISSUE THREAD

**Issue by Jwhite077** [darlinghq/darling#608]
I am using Ubuntu 9.10 with the latest commit of Darling.
When I try to run 'Darling shell', I get the following results:
```
Bootstrapping the container with launchd...
Cannot open mnt namespace file: No such file or directory
```
I've uploaded a copy of strace on the darling shell command below.
Could you possibly take a look when you get a chance?

[strace_output.txt](https://github.com/darlinghq/darling/files/4022293/strace_output.txt)

**Comment by bjorn3** [comment]
https://wiki.darlinghq.org/build_instructions

> On SELinux you may see the following error when starting darling:
> > Cannot open mnt namespace file: No such file or directory
> To work around this try this command: setsebool -P mmap_low_allowed 1.

**Comment by ahyattdev** [comment]
Closing unless this is distinct from the known SELinux issue

**Comment by Jwhite077** [comment]
> Closing unless this is distinct from the known SELinux issue

It’s not. SELinux is disabled.

**Comment by ahyattdev** [comment]
Ah, my mistake, looks like  #610 covers this now.
