### ISSUE TITLE
LLDB Doesn't Work

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#614]
```
Darling [~/Documents]$ lldb
dyld: Library not loaded: /usr/lib/libform.5.4.dylib
  Referenced from: /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
  Reason: image not found
Abort trap: 6 (core dumped)
```
This also happens if you call ```swift``` with no arguments.

I found this while trying to debug #600, and noticed no core dumps seem to be generated, even after running ```ulimit -c unlimited```.

**Comment by TheBrokenRail** [comment]
Fgured out how to get a core dump, turned out ```apport``` was blocking it.

**Comment by TheBrokenRail** [comment]
Reinstalled my prefix and it works now!

**Comment by ahyattdev** [comment]
@TheBrokenRail could you share how you got a core dump from Darling?

**Comment by TheBrokenRail** [comment]
I had to use ```sydctl``` to change ```kernel.core_pattern``` temporarily and run ```ulimit -c unlimited````.

**Comment by TheBrokenRail** [comment]
Was accidentally using an older version of the CLT, this is till an issue.

**Comment by ahyattdev** [comment]
Note: You may run into LKM freezing. Please follow instructions on the wiki for a working lldb.

https://wiki.darlinghq.org/debugging
