### ISSUE TITLE
DMG Input/Output Error

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#620]
```
Loaded the kernel module
Bootstrapping the container with launchd...
$ hdiutil attach Downloads/Command_Line_Tools_for_Xcode_11.3.dmg 
/Volumes/Command_Line_Tools_for_Xcode_11.3
$ cd Documents/
$ cp /Volumes/Command_Line_Tools_for_Xcode_11.3/Command\ Line\ Tools.pkg .
cp: /Volumes/Command_Line_Tools_for_Xcode_11.3/Command Line Tools.pkg: Input/output error
```
This is the latest build of Darling, and this DMG worked before.

**Comment by TheBrokenRail** [comment]
The issue doesn't happen when the DMG was mounted by the host (using ```darling-dmg``` manually).

**Comment by TheBrokenRail** [comment]
Turns out this was just a case of a broken ```hdiutil``` file that was solved by recompiling.

**Comment by AlisterH** [comment]
> Turns out this was just a case of a broken hdiutil

It would be nice to know how to avoid this; I had to resort to darling-dmg instead.
