### ISSUE TITLE
Confusion regarding LKM build system?

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#630]
The rest of Darling uses CMake, so why does the LKM use a mixture of CMake and Make, also why does the LKM have an older version of ```libsyscall``` than the rest of Darling? Whats the difference between ```Makefile``` and ```Makefile.orig```?

**Comment by ahyattdev** [comment]
The LKM uses Makefiles in order to work with DKMS. I assume the "orig" Makefile came with XNU

it has a different libsyscall because that one is from the source of the XNU version we are using.

**Comment by TheBrokenRail** [comment]
OK, but why keep it if this repo is just for the kernel module now?

**Comment by ahyattdev** [comment]
I'm not sure, I didn't work on the LKM much. Sometimes it's useful to keep those files because they can be useful to see what the files/targets were meant to be.

**Comment by TheBrokenRail** [comment]
OK, thank you!
