### ISSUE TITLE
Will there be a 2020 Q1 progress update?

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#631]
Also some stuff on the website (https://github.com/darlinghq/www.darlinghq.org/tree/master/content/developer-zone) and wiki (https://wiki.darlinghq.org/high_priority_stuff, https://wiki.darlinghq.org/roadmap, and https://wiki.darlinghq.org/google_summer_of_code) seems outdated?

**Comment by ahyattdev** [comment]
Yeah we should. Missed one for Q3/Q4 2019, but not not too many attention grabbing stuff happened then that we can put in a report.

**Comment by TheBrokenRail** [comment]
Darling now uses the VCHROOT, and some (example) GUI apps (kinda) work now.

**Comment by ahyattdev** [comment]
Yes, lots to talk about now. Towards the end of March we can discuss it in the Discord. Closed with answer "yes" :smile:

**Comment by bugaevc** [comment]
Also, please use Discord rather than the issue tracker for questions & discussions 🙂
