### ISSUE TITLE
compiling AudioToolbox problem

### ISSUE THREAD

**Issue by olegfusion** [darlinghq/darling#64]
ubuntu 13.10, getting here:

[ 96%] Building CXX object src/AudioToolbox/CMakeFiles/AudioToolbox.dir/AudioConverter.o
In file included from /home/user/darling-master/src/AudioToolbox/AudioConverter.cpp:2:
/home/user/darling-master/src/AudioToolbox/AudioConverterImpl.h:26:14: error: 
      ISO C++ forbids forward references to 'enum' types
        static enum AVCodecID CACodecToAV(const...

may anybody help?

**Comment by LubosD** [comment]
Not relevant any more.
