### ISSUE TITLE
Why is the LKM located in src ratherthan src/external?

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#645]

**Comment by TheBrokenRail** [comment]
Should I make a PR to move it to ```src/external/lkm```?

**Comment by bugaevc** [comment]
> Why is the LKM located in src ratherthan src/external?

The answer is, it used to be in the main repo (in `src/lkm`) because it wasn't based on XNU source, it was completely our own code. I wouldn't be against moving it, if you want to work on that.
