### ISSUE TITLE
CMake Error at src/CMakeLists.txt:52 (add_subdirectory):

### ISSUE THREAD

**Issue by nymba** [darlinghq/darling#648]
~/darling/build$ cmake ..
-- Found dsymutil: /usr/bin/llvm-dsymutil-6.0
-- Compiler include path detected as /usr/lib/llvm-6.0/lib/clang/6.0.0/include/
CMake Error at src/CMakeLists.txt:52 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/ld64/src"
  which is not an existing directory.

CMake Error at src/CMakeLists.txt:53 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/ar" which is
  not an existing directory.

CMake Error at src/CMakeLists.txt:55 (add_subdirectory):
  add_subdirectory given source "external/cctools-port/cctools/misc" which is
  not an existing directory.

CMake Warning (dev) at src/CMakeLists.txt:209 (add_subdirectory):
  The source directory

    /home/nymba/darling/src/external/libkqueue

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:211 (add_subdirectory):
  The source directory

    /home/nymba/darling/src/external/libplatform

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:212 (add_subdirectory):
  The source directory

    /home/nymba/darling/src/external/libpthread

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:217 (add_subdirectory):
  The source directory

    /home/nymba/darling/src/external/darling-dmg

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/libnotify/CMakeLists.txt:46 (add_darling_executable):
  Unknown CMake command "add_darling_executable".

-- Configuring incomplete, errors occurred!

any help?

**Comment by ahyattdev** [comment]
Did you follow the build instructions on the wiki? You need to recursively clone to get the sub modules.
