### ISSUE TITLE
Updating platform-include to include ARM64 code

### ISSUE THREAD

**Issue by CuriousTommy** [darlinghq/darling#649]
During my ARM64 adventures, I noticed that the source code in `platform-include` is missing some arm64 code, causing compile errors. A few examples are [boolean.h](https://github.com/darlinghq/darling/blob/master/platform-include/mach/machine/boolean.h#L32), [alignment.h](https://github.com/darlinghq/darling/blob/11b494915b9e3230caf3df4164f56328054fe690/platform-include/architecture/alignment.h#L37), and [machine.h](https://github.com/darlinghq/darling/blob/11b494915b9e3230caf3df4164f56328054fe690/platform-include/machine/limits.h#L5).

I am currently doing some research into where the files in `platform-include` come from and dumping new files in there, hoping for the best. From what I understand, most of the code comes from `xnu`. I made a personal list to keep track of where the files come from:
* `architecture` from `architecture`
* `mach` from `xnu/osfmk/mach`
* `sys` from `xnu/bsd/sys`
* `machine` from `xnu/bsd/machine`
* `net` from `xnu/bsd/net`

While I am making progress, I am wondering if dumping new files from the latest `xnu` source code is a good idea. Should I continue what I am doing, or should I redo my approach?

**TD:LR** - I am dumping code from a newer `xnu` source into `platform-include`. Is this okay or not?

**Comment by ahyattdev** [comment]
Not sure the specifics of libplatform, a quick search doesn't reveal much information. Not from Apple nor third parties.

**Comment by CuriousTommy** [comment]
I saw your comment on discord. I agree with you that libplatform should not be too problematic to get working on the Pinebook Pro (since the Arm code is there).

I am more worried about the `platform-include` folder located [in the darling directory](https://github.com/darlinghq/darling/tree/master/platform-include). This folder is the one causing most of the compile errors on my machine.

**Comment by CuriousTommy** [comment]
I'm going to close this issue since facekapow has redesigned how header files are stored. It's a lot more easier now to update the header files.
