### ISSUE TITLE
Darling Shell: dyld: stack buffer overrun

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#654]
When starting the latest version of Darling, this happens:
```
$ darling shell
Loaded the kernel module
Bootstrapping the container with launchd...
dyld: stack buffer overrun
Cannot open mnt namespace file: No such file or directory
```

**Comment by TheBrokenRail** [comment]
Any updates? When I run ```sudo strace -f darling shell```, it has some interesting message such as:
```
lstat("/usr/libexec/darling/usr/lib/dyld_sim", 0x7fffffdf9fb8) = -1 ENOENT (No such file or directory)
```
and:
```
openat(AT_FDCWD, "/proc/1/smaps", O_RDONLY) = 3
<Repeat read()s thogh /proc/1/smaps>
```

**Comment by TheBrokenRail** [comment]
In case it matters this is using the Debian packaging.

**Comment by LubosD** [comment]
I'm still wondering what might be causing this... This is a result of a buffer overrun somewhere in `dyld`.

What's your full prefix path?

**Comment by TheBrokenRail** [comment]
I am using the DEB so ```/usr```.

**Comment by LubosD** [comment]
@TheBrokenRail No, I mean like `/home/lubos/.darling`

**Comment by TheBrokenRail** [comment]
Its ```/home/<6-Letter Username>/.darling```.

**Comment by bugaevc** [comment]
Perhaps you could debug where the overrun is happening? For one thing, if it aborts there should be a core file (try `ulimit -c unlimited`) that we could inspect.

**Comment by TheBrokenRail** [comment]
Here's a core file:
[core.zip](https://github.com/darlinghq/darling/files/4205094/core.zip)

**Comment by TheBrokenRail** [comment]
Reverting a571a9b181eb96820263d67b6d33e10e04420ca1 fixed the problem!

**Comment by TheBrokenRail** [comment]
It seems this has been fixed by: https://github.com/darlinghq/darling/commit/346b0d59b5f20c73eed729e601bb12141ec79f6a.

**Comment by LubosD** [comment]
Ah, that makes sense! Good to know.
