### ISSUE TITLE
osx installation

### ISSUE THREAD

**Issue by M1cha** [darlinghq/darling#69]
just a idea. Wouldn't it be better to allow using original libraries from a osx installation so darling only needs to focus on kernel translation?

This way we could provide a theoretical 100% compatibility if the kernel works good enough.

**Comment by LubosD** [comment]
Darling now does focus on kernel translation.

**Comment by M1cha** [comment]
actually I have found some great information about this topic:
http://2004.eurobsdcon.org/uploads/media/EBSD04_21.pdf

It's a very good read and I hope it will help u.

**Comment by LubosD** [comment]
I already know that one, but thanks ;-)
The "darling-libsystem" branch now emulates BSD system calls. Some difficult ones and most Mach system calls are implemented in a kernel module (darling-mach).
