### ISSUE TITLE
Darling build failure

### ISSUE THREAD

**Issue by megastallman** [darlinghq/darling#696]
Hi guys! Could you please help me with the standard build procedure, that has worked before?
My build system - is Kubuntu 20.04. Tried different clang versions(9,7,6.0)
`[  3%] Building C object src/kernel/emulation/linux/CMakeFiles/emulation.dir/signal/sigpending.o
make[2]: *** No rule to make target 'src/kernel/emulation/linux/../../libsyscall/mach/exc_internal.h', needed by 'src/kernel/emulation/linux/CMakeFiles/emulation.dir/signal/sigexc.o'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:10655: src/kernel/emulation/linux/CMakeFiles/emulation.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by LubosD** [comment]
Should be fixed now.
