### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by hassan91** [darlinghq/darling#697]
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
CMake Error at cmake/MacroEnsureOutOfSourceBuild.cmake:4 (message):
  In-source builds are not allowed.

   CMake would overwrite the Linux kernel module Makefile.
   Please create a directory and run cmake from there, passing the path
   to this source directory as the last argument.
   This process created the file `CMakeCache.txt' and the directory `CMakeFiles'.
   Please delete them.
Call Stack (most recent call first):
  CMakeLists.txt:32 (MACRO_ENSURE_OUT_OF_SOURCE_BUILD)

**Comment by LubosD** [comment]
I'm not sure what you expect us to do here. The error message is telling you exactly what you should do differently.

**Comment by hassan91** [comment]
i tried again by removing the mentioned file and folder but still it didn't work out.

**Comment by hassan91** [comment]
> I'm not sure what you expect us to do here. The error message is telling you exactly what you should do differently.

i tried again by removing the mentioned file and folder but still it didn't work out.

**Comment by LubosD** [comment]
Including "Please create a directory and run cmake from there, passing the path
to this source directory as the last argument." ?

**Comment by hassan91** [comment]
> Including "Please create a directory and run cmake from there, passing the path
> to this source directory as the last argument." ?

Yes , i followed the steps mentioned in the build document
1) sudo apt install cmake clang bison flex libfuse-dev libudev-dev pkg-config libc6-dev-i386 linux-headers-generic gcc-multilib libcairo2-dev libgl1-mesa-dev libtiff5-dev libfreetype6-dev git libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev libxrandr-dev libxcursor-dev libgif-dev
2) git clone --recursive https://github.com/darlinghq/darling.git
3)  cd darling
4) mkdir build && cd build
5) cmake ../CMakeLists.txt
