### ISSUE TITLE
Error on Pop OS

### ISSUE THREAD

**Issue by JezWal** [darlinghq/darling#702]
I keep on getting this error code 

`-- Found dsymutil: /usr/bin/llvm-dsymutil-6.0
-- Compiler include path detected as /usr/lib/llvm-9/lib/clang/9.0.0/include/
CMake Warning (dev) at src/CMakeLists.txt:238 (add_subdirectory):
  The source directory

    /home/jez/darling/src/external/zlib

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:304 (add_subdirectory):
  The source directory

    /home/jez/darling/src/external/vim

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/CMakeLists.txt:307 (add_subdirectory):
  add_subdirectory given source "external/zip/zip/zip30" which is not an
  existing directory.

CMake Error at src/CMakeLists.txt:308 (add_subdirectory):
  add_subdirectory given source "external/zip/unzip/unzip-5.52" which is not
  an existing directory.

CMake Warning (dev) at src/CMakeLists.txt:316 (add_subdirectory):
  The source directory

    /home/jez/darling/src/external/top

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:321 (add_subdirectory):
  The source directory

    /home/jez/darling/src/external/zsh

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/CMakeLists.txt:377 (add_subdirectory):
  The source directory

    /home/jez/darling/src/external/usertemplate

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/jez/darling/build/CMakeFiles/CMakeOutput.log".
See also "/home/jez/darling/build/CMakeFiles/CMakeError.log".`

**Comment by bjorn3** [comment]
Did you run `git submodule init; git submodule update`?

**Comment by JezWal** [comment]
> Did you run `git submodule init; git submodule update`?

Yes

**Comment by bjorn3** [comment]
Did it return any errors?

**Comment by JezWal** [comment]
> Did it return any errors?

fatal: remote error: upload-pack: not our ref 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'src/external/top', but it did not contain 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4. Direct fetching of that commit failed.

**Comment by bjorn3** [comment]
Try running `git submodule update` again. There may have been a spurious network error or something like that.

**Comment by JezWal** [comment]
> Try running `git submodule update` again. There may have been a spurious network error or something like that.

didnt work same error

**Comment by JezWal** [comment]
jez@pop-os:~/darling$ git submodule update
fatal: remote error: upload-pack: not our ref 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'src/external/top', but it did not contain 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4. Direct fetching of that commit failed.

**Comment by bjorn3** [comment]
I don't know how to fix it. Maybe someone else has an idea?

**Comment by JezWal** [comment]
i saw another post with the same error and they said that it was a bad clone or something and they said to check the read me i dont know what to do on the read me

**Comment by JezWal** [comment]
https://github.com/darlinghq/darling/issues/301h

**Comment by JezWal** [comment]
https://github.com/darlinghq/darling/issues/301

**Comment by Yingsheng-eroad** [comment]
> > Did it return any errors?
> 
> fatal: remote error: upload-pack: not our ref 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4
> fatal: the remote end hung up unexpectedly
> Fetched in submodule path 'src/external/top', but it did not contain 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4. Direct fetching of that commit failed.

Actually, this happens when I git clone the repo.
the repo is not cloned properly, so "does not contain a CMakeLists.txt file" happened when executing "cmake"

**Comment by ahyattdev** [comment]
This should be fixed now.
