### ISSUE TITLE
Library not loaded: /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit

### ISSUE THREAD

**Issue by Yingsheng-eroad** [darlinghq/darling#706]
When I tried to run an application.
I got an error like this:
`
dyld: Library not loaded: /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
  Referenced from: /Applications/xxx.app/Contents/MacOS/xxx
  Reason: image not found
Abort trap: 6 (core dumped)
`

**Comment by CuriousTommy** [comment]
The error message is telling you that the [AVKit framework](https://developer.apple.com/documentation/avkit?language=objc) does not exist in Darling.

> When I tried to run an application.

What application are you trying to run?

**Comment by Yingsheng-eroad** [comment]
> The error message is telling you that the [AVKit framework](https://developer.apple.com/documentation/avkit?language=objc) does not exist in Darling.
> 
> > When I tried to run an application.
> 
> What application are you trying to run?

Thanks. I knew that. I was trying to run WeChat.app which I installed from a dmg file.
Can I add AVKit framework manually?  I didn't find a way to do that.

**Comment by CuriousTommy** [comment]
> Can I add AVKit framework manually? I didn't find a way to do that.

Yes, you can generate a stub and add it to darling. [You can find the instructions here](https://wiki.darlinghq.org/generating_stubs). Just keep in mind that you will need a real mac for this.

Otherwise, I can generate one for you and add it when I get some free time.

**Comment by Yingsheng-eroad** [comment]
> > Can I add AVKit framework manually? I didn't find a way to do that.
> 
> Yes, you can generate a stub and add it to darling. [You can find the instructions here](https://wiki.darlinghq.org/generating_stubs). Just keep in mind that you will need a real mac for this.
> 
> Otherwise, I can generate one for you and add it when I get some free time.

Thanks. I will try by myself first.

**Comment by Yingsheng-eroad** [comment]
> > Can I add AVKit framework manually? I didn't find a way to do that.
> 
> Yes, you can generate a stub and add it to darling. [You can find the instructions here](https://wiki.darlinghq.org/generating_stubs). Just keep in mind that you will need a real mac for this.
> 
> Otherwise, I can generate one for you and add it when I get some free time.

There are a lot of stubs missing for my App. 
Is there a way to avoid building the whole project?
I don't want to build the whole project for every missing stub since it only tells me that one module is missing when I am trying to run the App.
Thanks.

**Comment by bjorn3** [comment]
Run `otool -L` on the program to see a list of all required dylib.

**Comment by CuriousTommy** [comment]
@Yingsheng-eroad I asked a similar question on discord.

`nm` is pretty useful if you don't care about the selectors (methods).
Otherwise, you may have to use a disassembler, like hopper for example.

**Comment by Yingsheng-eroad** [comment]
> Run `otool -L` on the program to see a list of all required dylib.

thanks. I'll try it.

**Comment by Yingsheng-eroad** [comment]
> @Yingsheng-eroad I asked a similar question on discord.
> 
> `nm` is pretty useful if you don't care about the selectors (methods).
> Otherwise, you may have to use a disassembler, like hopper for example.

Thanks.

**Comment by CuriousTommy** [comment]
> can I just run the command "make install" after adding a new stub?

I recommend you run `make` first; otherwise, you might accidentally generate binaries that are owned by root.

**Comment by Yingsheng-eroad** [comment]
> > can I just run the command "make install" after adding a new stub?
> 
> I recommend you run `make` first; otherwise, you might accidentally generate binaries that are owned by root.

OK, thanks.
