### ISSUE TITLE
Symbol not found: _kCGWindowNumber

### ISSUE THREAD

**Issue by Yingsheng-eroad** [darlinghq/darling#710]
I fixed issue #706 after I added the stub AVKit.
But another error comes up when I am running the App.
I thought the cause is the version of CoreGraphics is out of date for the App.
I also tried to replace the CoreGraphics with a new version, but it causes problems when building the project.
Is there a way to fix this properly? thanks.

`dyld: Symbol not found: _kCGWindowNumber
  Referenced from: /Applications/WeChat.app/Contents/MacOS/../Frameworks/JietuFramework.framework/Versions/A/JietuFramework (which was built for Mac OS X 10.10)
  Expected in: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
 in /Applications/WeChat.app/Contents/MacOS/../Frameworks/JietuFramework.framework/Versions/A/JietuFramework
Abort trap: 6 (core dumped)`

**Comment by Yingsheng-eroad** [comment]
I ran "nm /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics", there was no "_kCGWindowNumber" in the result.
But when generating the CoreGraphics on Mac, it has a "_kCGWindowNumber"

**Comment by CuriousTommy** [comment]
> I fixed issue #706 after I added the stub AVKit.

Don't forget to submit a pull request!

> I thought the cause is the version of CoreGraphics is out of date for the App.

I don't think that is the issue. I believe you just need to add in the missing symbol.

> Is there a way to fix this properly?

You need to find out where the code for the CoreGraphics library is located and add the symbol to the right source file. I believe the library is located in the [cocotron repo](https://github.com/darlinghq/darling-cocotron).

You can also use [Apple's developer website](https://developer.apple.com/documentation/coregraphics/kcgwindownumber?language=objc) to get a better understanding of what the value type is.

> I ran "nm /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics", there was no "_kCGWindowNumber" in the result.

I don't seem to have issues finding it.

```
% nm /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
...
00000000006d76e0 S _kCGWindowLayer
00000000006d7708 S _kCGWindowMemoryUsage
00000000006d7720 S _kCGWindowName
00000000006d76d0 S _kCGWindowNumber
00000000006d7718 S _kCGWindowOwnerName
```

**Comment by Yingsheng-eroad** [comment]
> I don't seem to have issues finding it.
> 
> ```
> % nm /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
> ...
> 00000000006d76e0 S _kCGWindowLayer
> 00000000006d7708 S _kCGWindowMemoryUsage
> 00000000006d7720 S _kCGWindowName
> 00000000006d76d0 S _kCGWindowNumber
> 00000000006d7718 S _kCGWindowOwnerName
> ```
I mean run "nm" on darling.
```
Darling [~]$ nm /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics |grep _kCGWindow
000000000000ea98 S _kCGWindowAlpha
000000000000eaa0 S _kCGWindowBounds
000000000000eaa8 S _kCGWindowLayer
000000000000eab0 S _kCGWindowOwnerPID
```

**Comment by CuriousTommy** [comment]
> I mean run "nm" on darling.

Oh. In that case, it would make sense that darling can't find `_kCGWindowNumber`. Otherwise, you would not get that `Symbol not found` error.

**Comment by Yingsheng-eroad** [comment]
> > I mean run "nm" on darling.
> 
> Oh. In that case, it would make sense that Darling can't find `_kCGWindowNumber`. Otherwise, you would not get that `Symbol not found` error.

**Comment by CuriousTommy** [comment]
> Is there a way to update the CoreGraphics?

@Yingsheng-eroad If you want, we can continue this discussion on Discord.

**Comment by ahyattdev** [comment]
@Yingsheng-eroad sorry, forgot to reply.

Yes, it's not too difficult. If you want to see how check out this commit:

https://github.com/darlinghq/darling-cocotron/commit/abe8c14bd846b0332a9c82abc8fee7b15b428073

**Comment by Yingsheng-eroad** [comment]
> @Yingsheng-eroad sorry, forgot to reply.
> 
> Yes, it's not too difficult. If you want to see how check out this commit:
> 
> [darlinghq/darling-cocotron@abe8c14](https://github.com/darlinghq/darling-cocotron/commit/abe8c14bd846b0332a9c82abc8fee7b15b428073)

You already added, thanks.
