### ISSUE TITLE
Cannot determine your user name (linuxmint 19.3)

### ISSUE THREAD

**Issue by dewiweb** [darlinghq/darling#715]
On freshly installed last deb packages on linuxmint 19.3 (ubuntu 18.04 based), darling shell returns me:

Loaded the kernel module
Cannot determine your user name
Cannot open mnt namespace file: No such file or directory

**Comment by lekv** [comment]
This happens to me on a fresh Xubuntu 18.04.4, too. It only happens in a graphical terminal though. If I login on a physical terminal (ctrl-alt-F1), then darling works and the error does not show up.

**Comment by argosback** [comment]
I have the same issue with ementary OS 5.1.3 Hera (Ubuntu 18.04)

```
Loaded the kernel module
Cannot determine your user name
Cannot open mnt namespace file: No such file or directory
```

I add `session optional pam_loginuid.so` on a separate line to `/etc/pam.d/lightdm` and I get

```
Cannot determine your user name
```

only work with `CTRL+ALT+F1`

---

**OS Info**

```
OS: elementary OS 5.1.3 Hera x86_64 
Host: 81LW Lenovo IdeaPad L340-15API 
Kernel: 5.3.0-46-generic 
Shell: bash 4.4.20 
Resolution: 1920x1080, 1920x1080 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: Elementary [GTK3] 
Icons: Elementary [GTK3] 
Terminal: io.elementary.t 
CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: AMD Picasso 
Memory: 2733MiB / 5883MiB
```

**Comment by LubosD** [comment]
I've hopefully fixed the bug. Report back if not.

**Comment by argosback** [comment]
I will reinstall it to try again, thanks for the great work.

**Comment by Martheus** [comment]
I had the same problem. My system is Ubuntu 20.04 with kernel 5.4.0-26, Intel i3 2.2GHz, 8GB RAM. After update this day and build, every time I try to run darling, kernel panic happens and then restart. I tried older kernel with older module, but it won't work at all.

**Comment by HinTak** [comment]
@Martheus kernel panic and restart is a different matter. You should try to take a screenshot of the panic message (perhaps with your phone) and file a new issue.
