### ISSUE TITLE
Darling kernel module not working on latest build

### ISSUE THREAD

**Issue by fox8091** [darlinghq/darling#720]
Trying to run `darling shell` yields

```Bootstrapping the container with launchd...
Darling Mach kernel module reports different API level. Aborting.
Darling Mach kernel module reports different API level. Aborting.
Darling Mach kernel module reports different API level. Aborting.
Darling Mach kernel module reports different API level. Aborting.
Error connecting to shellspawn in the container (/var/run/shellspawn.sock): No such file or directory```

I'm unable to get an strace for this bug, as trying to run `darling shell` under strace causes it to complain about setuid, and when running strace under sudo with my user with Darling, it mistakenly tries to create the darling prefix in /root.

**Comment by bugaevc** [comment]
You're happens when your Darling userspace was built for a different (incompatible) version of the Darling LKM. You may need to rebuild and reinstall the outdated one of the two.

**Comment by fox8091** [comment]
They were both built today, from `master`. Latest commits should be compatible between the two.

**Comment by bugaevc** [comment]
Perhaps you've built the LKM for a newer kernel you have installed, and did not reboot, and so you're not using the latest LKM?

**Comment by fox8091** [comment]
No, it's for the current kernel (the AUR package won't build with a pending kernel update). And I don't have any other version of the LKM installed.

**Comment by LubosD** [comment]
Something must be wrong with your build, because both the kernel module and userspace tools take the API version from the same header file.

**Comment by bugaevc** [comment]
Well then, you're going to have to figure out which API version the LKM you have exports, and which version the userspace expects, and see which one's outdated.

**Comment by fox8091** [comment]
I managed to work around this by patching and converting the latest deb releases. Speaking of which, those could probably use a hotfix, at least the lkm one, to fix the build error fixed in the asm file.
