### ISSUE TITLE
LLDB is broken

### ISSUE THREAD

**Issue by facekapow** [darlinghq/darling#730]
I know this has already been pointed out before and @LubosD has said in Discord that new commits have broken LLDB more and more, but I'm going to formally create this as an issue, because it really is an issue (a pretty big one, too).

### Stepping does not work
A few commits ago (~90, I think?), LLDB at least sometimes stepped correctly, but this was unpredictable. Now, it cannot step at all. Pausing on a breakpoint and then trying to step through a single instruction resumes the entire process and it doesn't pause again until the next breakpoint (or ever, if no more breakpoints get hit).

### Breakpoints are unpredictable
About 70% of the time when starting a new process with LLDB and running until a breakpoint, LLDB will stop on ``dyld`_dyld_debugger_notification``. For example:
```
(lldb) run
There is a running process, kill it and restart?: [Y/n]
Process 202 exited with status = 9 (0x00000009)
Process 213 launched: '/usr/bin/curl' (x86_64)
Process 213 stopped
* thread #1, name = 'curl', stop reason = EXC_BREAKPOINT (code=EXC_I386_SGL, subcode=0x0)
    frame #0: 0x00007ffff804ad94 dyld`_dyld_debugger_notification + 4
dyld`_dyld_debugger_notification:
->  0x7ffff804ad94 <+4>:  movl   %edi, -0x4(%rbp)
    0x7ffff804ad97 <+7>:  movq   %rsi, -0x10(%rbp)
    0x7ffff804ad9b <+11>: movq   %rdx, -0x18(%rbp)
    0x7ffff804ad9f <+15>: popq   %rbp
Target 0: (curl) stopped.
```

In addition, this usually occurs continuously (i.e. multiple `run` commands in a row will produce this bug).

## Workarounds
Until these issues are fixed, I'm going to document some workarounds I know about for them here.

### Workaround for stepping
Set a breakpoint on the next desired place or use `thread until <line-number>`. It's pretty uncomfortable, but it works for now.

### Workaround for breakpoints
Execute `run` continuously (and press enter to confirm to kill the current process) until LLDB breaks on the breakpoint correctly instead of breaking on ``dyld`_dyld_debugger_notification``.

**Comment by LubosD** [comment]
Should be much better now. File new reports for individual bugs.
