### ISSUE TITLE
wxWidgets program: missing InstallDebugAssertOutputHandler

### ISSUE THREAD

**Issue by Arucard1983** [darlinghq/darling#739]
One of my research programs which uses wxWidgets for the GUI in order to reuse the code to compile for MacOS still don't run on Darling. Fortunately some missing functions was been implemented.
The next one is the InstallDebugAssertOutputHandler function from CoreServices framework.
It is feasible to be implemented soon ?

**Comment by LubosD** [comment]
I've implemented the function you mentioned, because it was low hanging fruit, but I'm pretty sure there'll be a lot more which we won't be able to implement that quickly. We're a pretty small team.
