### ISSUE TITLE
Configuring error , no ERROR log..

### ISSUE THREAD

**Issue by sbwtw** [darlinghq/darling#74]
command:
CC=clang CXX=clang++ cmake ../.. -DSUFFIX=64

cmake log:

-- No build type selected, default to Debug
-- This is a 64-bit build
-- Building Darling for OS X binary translation
-- Building ObjC ABI 2
You have called ADD_LIBRARY for library Carbon without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library AppKit without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library auto without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGNUSTEPBASE_INCLUDE_DIR
   used as include directory in directory /home/fly/darling/src/motool
   used as include directory in directory /home/fly/darling/src/util
   used as include directory in directory /home/fly/darling/src/libmach-o
   used as include directory in directory /home/fly/darling/src/libdyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/libSystem
   used as include directory in directory /home/fly/darling/src/libltdl
   used as include directory in directory /home/fly/darling/src/Cocoa
   used as include directory in directory /home/fly/darling/src/libobjcdarwin
   used as include directory in directory /home/fly/darling/src/CoreFoundation
   used as include directory in directory /home/fly/darling/src/libncurses
   used as include directory in directory /home/fly/darling/src/CoreSecurity
   used as include directory in directory /home/fly/darling/src/CoreServices
   used as include directory in directory /home/fly/darling/src/ExceptionHandling
   used as include directory in directory /home/fly/darling/src/IOKit
   used as include directory in directory /home/fly/darling/src/Foundation
   used as include directory in directory /home/fly/darling/src/Carbon
   used as include directory in directory /home/fly/darling/src/SystemConfiguration
   used as include directory in directory /home/fly/darling/src/CoreVideo
   used as include directory in directory /home/fly/darling/src/OpenGL
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/libstdc++darwin
LIBGNUSTEPCOREBASE_INCLUDE_DIR
   used as include directory in directory /home/fly/darling/src/motool
   used as include directory in directory /home/fly/darling/src/util
   used as include directory in directory /home/fly/darling/src/libmach-o
   used as include directory in directory /home/fly/darling/src/libdyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/libSystem
   used as include directory in directory /home/fly/darling/src/libltdl
   used as include directory in directory /home/fly/darling/src/Cocoa
   used as include directory in directory /home/fly/darling/src/libobjcdarwin
   used as include directory in directory /home/fly/darling/src/CoreFoundation
   used as include directory in directory /home/fly/darling/src/libncurses
   used as include directory in directory /home/fly/darling/src/CoreSecurity
   used as include directory in directory /home/fly/darling/src/CoreServices
   used as include directory in directory /home/fly/darling/src/ExceptionHandling
   used as include directory in directory /home/fly/darling/src/IOKit
   used as include directory in directory /home/fly/darling/src/Foundation
   used as include directory in directory /home/fly/darling/src/Carbon
   used as include directory in directory /home/fly/darling/src/SystemConfiguration
   used as include directory in directory /home/fly/darling/src/CoreVideo
   used as include directory in directory /home/fly/darling/src/OpenGL
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/libstdc++darwin
LIBKQUEUE_INCLUDE_DIR
   used as include directory in directory /home/fly/darling/src/motool
   used as include directory in directory /home/fly/darling/src/util
   used as include directory in directory /home/fly/darling/src/libmach-o
   used as include directory in directory /home/fly/darling/src/libdyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/libSystem
   used as include directory in directory /home/fly/darling/src/libltdl
   used as include directory in directory /home/fly/darling/src/Cocoa
   used as include directory in directory /home/fly/darling/src/libobjcdarwin
   used as include directory in directory /home/fly/darling/src/CoreFoundation
   used as include directory in directory /home/fly/darling/src/libncurses
   used as include directory in directory /home/fly/darling/src/CoreSecurity
   used as include directory in directory /home/fly/darling/src/CoreServices
   used as include directory in directory /home/fly/darling/src/ExceptionHandling
   used as include directory in directory /home/fly/darling/src/IOKit
   used as include directory in directory /home/fly/darling/src/Foundation
   used as include directory in directory /home/fly/darling/src/Carbon
   used as include directory in directory /home/fly/darling/src/SystemConfiguration
   used as include directory in directory /home/fly/darling/src/CoreVideo
   used as include directory in directory /home/fly/darling/src/OpenGL
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/libstdc++darwin
LIBOBJC2_INCLUDE_DIR
   used as include directory in directory /home/fly/darling/src/motool
   used as include directory in directory /home/fly/darling/src/util
   used as include directory in directory /home/fly/darling/src/libmach-o
   used as include directory in directory /home/fly/darling/src/libdyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/dyld
   used as include directory in directory /home/fly/darling/src/libSystem
   used as include directory in directory /home/fly/darling/src/libltdl
   used as include directory in directory /home/fly/darling/src/Cocoa
   used as include directory in directory /home/fly/darling/src/libobjcdarwin
   used as include directory in directory /home/fly/darling/src/CoreFoundation
   used as include directory in directory /home/fly/darling/src/libncurses
   used as include directory in directory /home/fly/darling/src/CoreSecurity
   used as include directory in directory /home/fly/darling/src/CoreServices
   used as include directory in directory /home/fly/darling/src/ExceptionHandling
   used as include directory in directory /home/fly/darling/src/IOKit
   used as include directory in directory /home/fly/darling/src/Foundation
   used as include directory in directory /home/fly/darling/src/Carbon
   used as include directory in directory /home/fly/darling/src/SystemConfiguration
   used as include directory in directory /home/fly/darling/src/CoreVideo
   used as include directory in directory /home/fly/darling/src/OpenGL
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/thin
   used as include directory in directory /home/fly/darling/src/libstdc++darwin

-- Configuring incomplete, errors occurred!
See also "/home/fly/darling/build/64/CMakeFiles/CMakeOutput.log".

// no CMakeError.log 

// CMakeOutput.log here:
The system is: Linux - 3.14.9-200.fc20.x86_64 - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/clang 
Build flags: 
Id flags: 

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is Clang, found in "/home/fly/darling/build/64/CMakeFiles/2.8.12.2/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/clang++ 
Build flags: 
Id flags: 

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is Clang, found in "/home/fly/darling/build/64/CMakeFiles/2.8.12.2/CompilerIdCXX/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec74325289/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec74325289.dir/build.make CMakeFiles/cmTryCompileExec74325289.dir/build
gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec74325289.dir/testCCompiler.c.o
/usr/bin/clang    -o CMakeFiles/cmTryCompileExec74325289.dir/testCCompiler.c.o   -c /home/fly/darling/build/64/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTryCompileExec74325289
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec74325289.dir/link.txt --verbose=1
/usr/bin/clang       CMakeFiles/cmTryCompileExec74325289.dir/testCCompiler.c.o  -o cmTryCompileExec74325289 -rdynamic 
gmake[1]: Leaving directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'

Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec329404125/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec329404125.dir/build.make CMakeFiles/cmTryCompileExec329404125.dir/build
gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o
/usr/bin/clang    -o CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake/Modules/CMakeCCompilerABI.c
Linking C executable cmTryCompileExec329404125
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec329404125.dir/link.txt --verbose=1
/usr/bin/clang     -v CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec329404125 -rdynamic  
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3
 "/usr/bin/ld" -export-dynamic --hash-style=gnu --no-add-needed --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTryCompileExec329404125 /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../.. -L/lib -L/usr/lib CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o
gmake[1]: Leaving directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:/usr/bin/gmake "cmTryCompileExec329404125/fast"]
  ignore line: [/usr/bin/gmake -f CMakeFiles/cmTryCompileExec329404125.dir/build.make CMakeFiles/cmTryCompileExec329404125.dir/build]
  ignore line: [gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp']
  ignore line: [/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1]
  ignore line: [Building C object CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/clang    -o CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTryCompileExec329404125]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec329404125.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/clang     -v CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec329404125 -rdynamic  ]
  ignore line: [clang version 3.4 (tags/RELEASE_34/final)]
  ignore line: [Target: x86_64-redhat-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
  ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3]
  ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
  link line: [ "/usr/bin/ld" -export-dynamic --hash-style=gnu --no-add-needed --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTryCompileExec329404125 /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../.. -L/lib -L/usr/lib CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o]
    arg [/usr/bin/ld] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--no-add-needed] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-o] ==> ignore
    arg [cmTryCompileExec329404125] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o] ==> ignore
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64]
    arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
    arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..]
    arg [-L/lib] ==> dir [/lib]
    arg [-L/usr/lib] ==> dir [/usr/lib]
    arg [CMakeFiles/cmTryCompileExec329404125.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o] ==> ignore
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3] ==> [/usr/lib/gcc/x86_64-redhat-linux/4.8.3]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64] ==> [/usr/lib64]
  collapse library dir [/lib/../lib64] ==> [/lib64]
  collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..] ==> [/usr/lib]
  collapse library dir [/lib] ==> [/lib]
  collapse library dir [/usr/lib] ==> [/usr/lib]
  implicit libs: [c]
  implicit dirs: [/usr/lib/gcc/x86_64-redhat-linux/4.8.3;/usr/lib64;/lib64;/usr/lib;/lib]
  implicit fwks: []

Determining if the CXX compiler works passed with the following output:
Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec1489065942/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1489065942.dir/build.make CMakeFiles/cmTryCompileExec1489065942.dir/build
gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec1489065942.dir/testCXXCompiler.cxx.o
/usr/bin/clang++     -o CMakeFiles/cmTryCompileExec1489065942.dir/testCXXCompiler.cxx.o -c /home/fly/darling/build/64/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
Linking CXX executable cmTryCompileExec1489065942
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1489065942.dir/link.txt --verbose=1
/usr/bin/clang++        CMakeFiles/cmTryCompileExec1489065942.dir/testCXXCompiler.cxx.o  -o cmTryCompileExec1489065942 -rdynamic 
gmake[1]: Leaving directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec1088390350/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1088390350.dir/build.make CMakeFiles/cmTryCompileExec1088390350.dir/build
gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o
/usr/bin/clang++     -o CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp
Linking CXX executable cmTryCompileExec1088390350
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1088390350.dir/link.txt --verbose=1
/usr/bin/clang++      -v CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o  -o cmTryCompileExec1088390350 -rdynamic  
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3
 "/usr/bin/ld" -export-dynamic --hash-style=gnu --no-add-needed --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTryCompileExec1088390350 /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../.. -L/lib -L/usr/lib CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o
gmake[1]: Leaving directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'

Parsed CXX implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:/usr/bin/gmake "cmTryCompileExec1088390350/fast"]
  ignore line: [/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1088390350.dir/build.make CMakeFiles/cmTryCompileExec1088390350.dir/build]
  ignore line: [gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp']
  ignore line: [/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1]
  ignore line: [Building CXX object CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o]
  ignore line: [/usr/bin/clang++     -o CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp]
  ignore line: [Linking CXX executable cmTryCompileExec1088390350]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1088390350.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/clang++      -v CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o  -o cmTryCompileExec1088390350 -rdynamic  ]
  ignore line: [clang version 3.4 (tags/RELEASE_34/final)]
  ignore line: [Target: x86_64-redhat-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
  ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3]
  ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
  link line: [ "/usr/bin/ld" -export-dynamic --hash-style=gnu --no-add-needed --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTryCompileExec1088390350 /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../.. -L/lib -L/usr/lib CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o]
    arg [/usr/bin/ld] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--no-add-needed] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-o] ==> ignore
    arg [cmTryCompileExec1088390350] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crt1.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crti.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o] ==> ignore
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3]
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64]
    arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
    arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
    arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..]
    arg [-L/lib] ==> dir [/lib]
    arg [-L/usr/lib] ==> dir [/usr/lib]
    arg [CMakeFiles/cmTryCompileExec1088390350.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
    arg [-lstdc++] ==> lib [stdc++]
    arg [-lm] ==> lib [m]
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [-lgcc] ==> lib [gcc]
    arg [-lc] ==> lib [c]
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [-lgcc] ==> lib [gcc]
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o] ==> ignore
    arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/crtn.o] ==> ignore
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3] ==> [/usr/lib/gcc/x86_64-redhat-linux/4.8.3]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64] ==> [/usr/lib64]
  collapse library dir [/lib/../lib64] ==> [/lib64]
  collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
  collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.3/../../..] ==> [/usr/lib]
  collapse library dir [/lib] ==> [/lib]
  collapse library dir [/usr/lib] ==> [/usr/lib]
  implicit libs: [stdc++;m;c]
  implicit dirs: [/usr/lib/gcc/x86_64-redhat-linux/4.8.3;/usr/lib64;/lib64;/usr/lib;/lib]
  implicit fwks: []

Checking whether the ASM-ATT compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
GNU assembler version 2.23.2
Copyright 2012 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
Checking whether the ASM_NASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
GNU assembler version 2.23.2
Copyright 2012 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
Determining if the include file bsd/wchar.h exists passed with the following output:
Change Dir: /home/fly/darling/build/64/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3696322518/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3696322518.dir/build.make CMakeFiles/cmTryCompileExec3696322518.dir/build
gmake[1]: Entering directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3696322518.dir/CheckIncludeFile.c.o
/usr/bin/clang    -o CMakeFiles/cmTryCompileExec3696322518.dir/CheckIncludeFile.c.o   -c /home/fly/darling/build/64/CMakeFiles/CMakeTmp/CheckIncludeFile.c
Linking C executable cmTryCompileExec3696322518
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3696322518.dir/link.txt --verbose=1
/usr/bin/clang       CMakeFiles/cmTryCompileExec3696322518.dir/CheckIncludeFile.c.o  -o cmTryCompileExec3696322518 -rdynamic 
gmake[1]: Leaving directory `/home/fly/darling/build/64/CMakeFiles/CMakeTmp'

my system:
fedora 20 x86_64

**Comment by LubosD** [comment]
Not relevant to current code base / build scripts any more.
