### ISSUE TITLE
Failed to start darling shell

### ISSUE THREAD

**Issue by SamLukeYes** [darlinghq/darling#744]
`yes@Auriel ~/Downloads> darling shell`
 `Loaded the kernel module `
 `Cannot mount overlay: Stale file handle `
 `Cannot open mnt namespace file: No such file or directory `
 `yes@Auriel ~/Downloads [1]> `

My OS is manjaro 19.0.2 with linux kernel 4.19.114-1-surface-lts, and I'm sure that I've got a full darling installation, including the kernel module. No error while installing.

I built and installed darling and successfully launched darling shell a few days ago, and I've run uninstall.sh before installing the current build. Does that matter?

**Comment by Shinmera** [comment]
Experiencing the same issue on Arch Linux 5.7.7, never before installed Darling, built from fa5348c8a9b338746b91a53a801343a8d046a66d

**Comment by Dadoum** [comment]
Same here

**Comment by ahyattdev** [comment]
Does make it go away?

**Comment by Dadoum** [comment]
I recompiled it without aur package, and cleaned prefix to fix it

**Comment by superbonaci** [comment]
@Dadoum how did you do to recompile without aur prefix?

**Comment by Dadoum** [comment]
delete ~/.darling and ~/.darling-workdir
Then follow the build instructions [here instead](https://docs.darlinghq.org/build-instructions.html)

**Comment by superbonaci** [comment]
> 
> 
> delete ~/.darling and ~/.darling-workdir
> Then follow the build instructions [here instead](https://docs.darlinghq.org/build-instructions.html)

This is the guide I am using, which guide do you think I'm following?

**Comment by Dadoum** [comment]
The issue here was that the compilation in the AUR (Arch Linux) package was not updated to follow the real build instructions. Now, if you remove just .darling and .darling-workdir and that you are sure that darling has been compiled the right way, it should work, or at least, it should fix the issue that was occuring on AUR package users.

**Comment by superbonaci** [comment]
It's on Ubuntu didn't try yet Arch. Do you recommend me to try on Arch? I'm using a virtual machine as recommended.

**Comment by Dadoum** [comment]
It should not matter, your issue is definively different to the one I had then (especially if deleting ~/.darling does not work)

**Comment by superbonaci** [comment]
Why do I have `~/.darling.workdir` instead of `~/.darling-workdir`?

**Comment by Dadoum** [comment]
It's because I didn't checked the name on my computer

**Comment by superbonaci** [comment]
Fine will try again after removing all ~/.darling* and fetching new source clean build.

**Comment by superbonaci** [comment]
For some reason now it worked, thanks a lot!
````
User@ubuntu:~$ darling shell
Setting up a new Darling prefix at /home/User/.darling
Bootstrapping the container with launchd...

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Darling [/Volumes/SystemRoot/home/User]$
````
What I did is to delete all .darling* folders from my home, and delete the entire source code folder and fetch and compile everything again.

**Comment by superbonaci** [comment]
If it's fixed please close the issue 👍.

**Comment by Dadoum** [comment]
I can't it's not mine
