### ISSUE TITLE
wxWidgets program: uncaught exception of +[NSColor setIgnoresAlpha:]:

### ISSUE THREAD

**Issue by Arucard1983** [darlinghq/darling#745]
My research program are almost running on Darling, and once fixed the missing API, there's an unhanded exception that cause to stop:

`2020-04-15 15:25:10.814 ERYA-Profiling-OSX[79:3e8] Terminating app due to uncaught exception 'NSException', reason: '+[NSColor setIgnoresAlpha:]: unrecognized selector sent to instance 0x7ffff7039918'
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6`

Since my research programs are now freely online and built for three operating systems, it can be downloaded from:
https://sites.fct.unl.pt/nuclear/software

**Comment by LubosD** [comment]
I suspect there'll be a lot more. Don't be shy to submit a PR in case you'd know how to fix things.

**Comment by Arucard1983** [comment]
The next bug is this stub related to Foundation Framework...
SForwardSignatureError: invoked with 6 args, but 2 expected. Selector setEventHandler:andSelector:forEventClass:andEventID:, class NSAppleEventManager
2020-04-16 22:05:00.306 ERYA-Bulk-OSX[54:3e8] Stub called: setEventHandler:andSelector:forEventClass:andEventID: in NSAppleEventManager
NSForwardSignatureError: invoked with 6 args, but 2 expected. Selector setEventHandler:andSelector:forEventClass:andEventID:, class NSAppleEventManager
2020-04-16 22:05:00.307 ERYA-Bulk-OSX[54:3e8] Stub called: setEventHandler:andSelector:forEventClass:andEventID: in NSAppleEventManager
NSForwardSignatureError: invoked with 6 args, but 2 expected. Selector setEventHandler:andSelector:forEventClass:andEventID:, class NSAppleEventManager
2020-04-16 22:05:00.307 ERYA-Bulk-OSX[54:3e8] Stub called: setEventHandler:andSelector:forEventClass:andEventID: in NSAppleEventManager

**Comment by Arucard1983** [comment]
Since any small wxWidgets programs returns the same initialization values it could be a good idea to pursue further bugs.

**Comment by Arucard1983** [comment]
A very simple wxWidgets program even return another stub, and then segfaults

`
Stub called: currentApplication in NSRunningApplication
Segmentation fault: 11
`
