### ISSUE TITLE
SSL certificate problem when fetching rustup installer via curl

### ISSUE THREAD

**Issue by Newbytee** [darlinghq/darling#748]
After executing `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`, as the rustup installer website tells you to do, I get the following errors:

```sh
curl: (35) SSL certificate problem: Couldn't understand the server certificate format
sh: line 1: syntax error near unexpected token `('
sh: line 1: `struct ccrng_state *ccDRBGGetRngState(int *) just putting this here until we build CommonCrypto'
```

I'm presuming the certificate issue is what's relevant here.

**Comment by facekapow** [comment]
Yeah, this is because of #463. I'm currently implementing the code needed in CoreCrypto to get HTTPS working.
