### ISSUE TITLE
Adding Qt support.

### ISSUE THREAD

**Issue by mateli** [darlinghq/darling#75]
As many mac applications are implemented in Qt it makes sense to implement Qt libraries that makes use of native Qt libraries. That way those applications can function without needing support from AppKit and similar API:s.

**Comment by MiJyn** [comment]
It might turn out to be less work if Darling implemented the MacOS APIs, instead of trying to port various other libraries.

**Comment by mateli** [comment]
I don't think so. Various other libraries can rely on their native counterparts while the MacOS API:s instead may need to rely on those various other libraries. 

I suggested Qt because it has native counterparts virtually everywhere and because many OS X programs may be able to run with Qt support.
