### ISSUE TITLE
Unable to launch LLDB

### ISSUE THREAD

**Issue by Newbytee** [darlinghq/darling#751]
When I attempt to run LLDB via the command `lldb`, every combination of parameters I have tried so far (`lldb /Applications/<Appname>.app`, `lldb --help`, `lldb`, `lldb </path/to/executable>`) has resulted in the following error:
```sh
Invoked with: /Library/Developer/DarlingCLT/usr/bin/xcrun lldb /Applications/<Appname>.app
Executing /Library/Developer/Darling/DarlingCLT/usr/bin/lldb
Failed to execute program /Library/Developer/DarlingCLT/usr/bin/lldb
```

I compiled Daring with LLVM 10. Perhaps noteworthy is that when I run `cmake ..` from the build directory it complains about missing llvm-dsymutil. Could that be why this occurs? I can also try compiling with LLVM 9 instead if it is of interest.

**Comment by bugaevc** [comment]
> Failed to execute program /Library/Developer/DarlingCLT/usr/bin/lldb

Do you actually have LLDB installed there? What happens if you run it directly?

> it complains about missing llvm-dsymutil. Could that be why this occurs?

No, but having dsymutil (and thus debug symbols) would help you with debugging once you get LLDB working.

**Comment by Newbytee** [comment]
> > Failed to execute program /Library/Developer/DarlingCLT/usr/bin/lldb
> 
> Do you actually have LLDB installed there? What happens if you run it directly?
> 

Turns out I don't. Misunderstood the docs. Got it working now (downloaded from the link in the docs). Thanks.
