### ISSUE TITLE
`<dbus/dbus.h>` not found

### ISSUE THREAD

**Issue by facekapow** [darlinghq/darling#754]
Building the lastest master on Ubuntu 18.10, the build fails on:
```
/home/me/git/darling/src/external/dbuskit/Source/DKObjectPathNode.h:26:10: fatal error: 'dbus/dbus.h' file not found
#include <dbus/dbus.h>
```

I installed `libdbus-1-dev`, and `/usr/include/dbus-1.0/dbus/dbus.h` exists, but I guess Darling is including `/usr/include`, not `/usr/include/dbus-1.0`.

**Comment by bugaevc** [comment]
Try to re-run CMake.

> I guess Darling is including `/usr/include`, not `/usr/include/dbus-1.0`

We ask pkg-config for the include path (as we should). But if you ran CMake first and then installed the package, pkg-config is not going to see it.

**Comment by facekapow** [comment]
That was it, thanks. I'll have to remember to do that whenever I update to the latest sources.
