### ISSUE TITLE
changing the target Operating System

### ISSUE THREAD

**Issue by TheDharc** [darlinghq/darling#76]
Hi LobusD,
I really think the best choise you can do is change the target Operating System to Free or NetBSD because they have more likely to be compatible with OS X/Darwin than Linux. I already tried to run Linux's Steam on FreeBSD and and it automatically identified that I was trying to run Steam on Mac OS X.
Just a suggestion.

**Comment by vasili111** [comment]
It will be very nice to have Darling on FreeBSD. Since Mac OS X was initially made from FreeBSD it could be easier to make Darling for FreeBSD than for the Linux.

**Comment by LubosD** [comment]
The fact that XNU uses parts of FreeBSD's kernel doesn't make things all that easier.

**Comment by TheDharc** [comment]
wrong, NextBSD uses a lot of important parts of Darwin's userland + Mach IPC and it remains being FreeBSD. makes no sense do it on Linux.

**Comment by LubosD** [comment]
And how many people use NextBSD compared to Linux?

It doesn't matter how much Darwin userland is included in NextBSD, because it doesn't guarantee ABI compatibility, so it needs to be rebuilt anyway. Darling will carry its own userland just like Wine.

**Comment by TheDharc** [comment]
"And how many people use NextBSD compared to Linux?"

so let's use Windows and Mac because there is just 1% desktop Linux users

**Comment by LubosD** [comment]
No, wrong. I'm using Linux, so I want a solution for Linux. Why should I be building a solution for a system I don't use, and except for a few geeks no one else uses either?

**Comment by vasili111** [comment]
@LubosD 
I understand that you don't want to make software for OS that you are not using but I don't agree that FreeBSD is an OS "for a few geeks no one else uses either".

**Comment by LubosD** [comment]
We're talking about NextBSD.

**Comment by msva** [comment]
Anyway, to state a point of @LubosD as I see it and fully accept it): he has absolutelly no plans to port darling to BSD (and that wasn't the case of the project). But if anyone (including issue author or anybody) want to see darling there — patches are welcome.

**Comment by X0rg** [comment]
It's a huge work to run OS X applications on Linux. @LubosD is the main developper for this project, he gives his time to do this. Add a port to *BSD need more work (and I have never read about NextBSD ; FreeBSD is the most popular). I agree with @msva.
