### ISSUE TITLE
AppkiDo fails because of no. Webkit - _OBJC_CLASS_$_WebPreferences.

### ISSUE THREAD

**Issue by stuaxo** [darlinghq/darling#770]
Appkido http://appkido.com/ - a cocoa docs browser, seemed like an interesting thing to try

I installed the lastest darling + kernel module debs and tried running it.
It looks like it's looking for WebPreferences in Webkit.

```
 ./AppKiDo.app/Contents/MacOS/AppKiDo 
dyld: Symbol not found: _OBJC_CLASS_$_WebPreferences
  Referenced from: /Volumes/SystemRoot/home/stu/Downloads/AppKiDo.app/Contents/MacOS/AppKiDo
  Expected in: /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
 in /Volumes/SystemRoot/home/stu/Downloads/AppKiDo.app/Contents/MacOS/AppKiDo
Abort trap: 6 (core dumped)
```

**Comment by bugaevc** [comment]
Seems interesting indeed!

But it uses WebKit, so it's not going to display the docs even if the add the missing symbol.

**Comment by stuaxo** [comment]
I had a suspicion that might be the case.

I'm guessing there isn't a browser component, and that it's a massive pain ?

I wonder how many webkit APIs they actually use.

Would there be any value in using something like Webkit GTK initially ?

**Comment by LubosD** [comment]
@stuaxo No, the only option is to add WebKit to Darling's build, which is not for the faint of heart. But we will do it eventually, that's for sure.

**Comment by stuaxo** [comment]
Heh, I guess my choice of "simple looking graphical app", ended up relying on the most complex API of all.

I'm going to close this for now, since that seems a long way off, so this isn't super useful.
