### ISSUE TITLE
CMake Error at src/external/cocotron/AppKit/CMakeLists.txt:31 (message): xkbfile not found

### ISSUE THREAD

**Issue by user32000** [darlinghq/darling#775]
Trying to install on Ubuntu 18.04 in VirtualBox - please let me know what information you need

[CMakeOutput.log](https://github.com/darlinghq/darling/files/4594432/CMakeOutput.log)

**Comment by CuriousTommy** [comment]
There is a recent change @LubosD made to cocotron. The docs have not been updated yet, but you will need to install `libxkbfile-dev` with `apt-get`.

**Comment by user32000** [comment]
Ignore your edit - the original comment was good.  libxkbfile-dev was not installed on my ubuntu 18.04 VM. However, even after `apt install libxkbfile-dev` I get 

```
CMake Error at src/external/cocotron/AppKit/CMakeLists.txt:31 (message):
  xkbfile not found


-- Configuring incomplete, errors occurred!
See also "/home/michael/darling/build/CMakeFiles/CMakeOutput.log".
```
