### ISSUE TITLE
Cannot open mnt namespace file: No such file or directory

### ISSUE THREAD

**Issue by odror** [darlinghq/darling#776]
OS: ubuntu 20.04
after compiling and installing
when running the command **darling shell**
I get the following error:
```
Loaded the kernel module
Setting up a new Darling prefix at /home/dror/.darling
Cannot mount overlay: Invalid argument
Cannot open mnt namespace file: No such file or directory

```

**Comment by LubosD** [comment]
Could you please take a peek into dmesg? Overlayfs surely says what argument it doesn't like.

**Comment by odror** [comment]
dmesg | 
```
[192238.522591] overlayfs: filesystem on '/home/dror/.darling' not supported as upperdir
[192268.315835] snd_hda_codec_hdmi hdaudioC3D0: HDMI: invalid ELD data byte 2

```
Ok what does that mean and how i can fix it.  Thanks. This is a new 20.04 install

**Comment by bjorn3** [comment]
What filesystem are you using. You can use `df -T` to show the filesystem for all mounts.

**Comment by odror** [comment]
I use zfs. 
`pool/ROOT/ubuntu_mj0kfs                         zfs       205543424   16859648 188683776   9% /
`

**Comment by HinTak** [comment]
Known issue with zfs - https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1718761

**Comment by odror** [comment]
This is an old bug. I do not think that it will be fixed anytime soon. Any workaround for darling?

**Comment by LubosD** [comment]
`export DPREFIX=/another/place` pointing to a non-zfs filesystem.

**Comment by LubosD** [comment]
I've now [documented](https://docs.darlinghq.org/build-instructions.html#file-system-support) this overlayfs restriction.

**Comment by tajetaje** [comment]
I have encountered the same issue under ext4. The only odd thing I can think of is that my "/home" is a different partition than "/".

```
Bootstrapping the container with launchd...
Cannot open mnt namespace file: No such file or directory
```

**Comment by facekapow** [comment]
@tajetaje This is a problem with your filesystem, and it's clear that this is an issue with your filesystem and not Darling because you get another `suid` error when trying to run `sudo` (in that second case, it never even executes Darling). Pay special attention to that second message: `effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`. Check if your filesystem is somehow mounted with `nosuid`. Are you able to use `sudo` normally with other programs?

**Comment by facekapow** [comment]
@tajetaje Ah sorry, my bad, didn't realize `suid` doesn't work normally with `strace`. If you want to run `strace` on suid programs like Darling, try [this](https://access.redhat.com/solutions/3673651).

**Comment by tajetaje** [comment]
> @tajetaje Ah sorry, my bad, didn't realize `suid` doesn't work normally with `strace`. If you want to run `strace` on suid programs like Darling, try [this](https://github.com/darlinghq/darling/issues/828#issuecomment-642555421):
> 
> ```
> sudo strace -fu $USER darling shell
> ```

Thanks, in the end I don’t think it was a problem with darling, I ended up just using one of the pre-built .deb packages instead of building myself and it worked fine so I expect it was an error in the build process.

**Comment by joshwolff1** [comment]
I'm pasting my very strange encounter with this error here. Totally unclear what caused it and then resolved it. Hopefully this helps someone...

`ubuntu@ip-172-31-11-146:~$ ls
darling  main
ubuntu@ip-172-31-11-146:~$ ./main
Segmentation fault
ubuntu@ip-172-31-11-146:~$ darling
This is Darling, translation layer for macOS software.

Copyright (C) 2012-2020 Lubos Dolezel

Usage:
	darling program-path [arguments...]
	darling shell [arguments...]

Environment variables:
DPREFIX - specifies the location of Darling prefix, defaults to ~/.darling
ubuntu@ip-172-31-11-146:~$ darling main
Setting up a new Darling prefix at /home/ubuntu/.darling
Bootstrapping the container with launchd...
'main' is not a supported command or a file.
ubuntu@ip-172-31-11-146:~$ darling ./main
'./main' is not a supported command or a file.
ubuntu@ip-172-31-11-146:~$ darling shell

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Darling [/Volumes/SystemRoot/home/ubuntu]$ ./main
OUTPUT: {"data": {"error_message": "Invalid execution."}, "response_code": 400}
Darling [/Volumes/SystemRoot/home/ubuntu]$ ./main ping '{}'
OUTPUT: {"data": {}, "response_code": 200}
Darling [/Volumes/SystemRoot/home/ubuntu]$ exit
logout
ubuntu@ip-172-31-11-146:~$ darling ~/.darling/usr/local/bin/^C
ubuntu@ip-172-31-11-146:~$ pwd
/home/ubuntu
ubuntu@ip-172-31-11-146:~$ darling /home/ubuntu/main 
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling ~/home/ubuntu/main 
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling ~/home/ubuntu/main 
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling ls
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling shell
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ ls
darling  main
ubuntu@ip-172-31-11-146:~$ darling shell
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling
This is Darling, translation layer for macOS software.

Copyright (C) 2012-2020 Lubos Dolezel

Usage:
	darling program-path [arguments...]
	darling shell [arguments...]

Environment variables:
DPREFIX - specifies the location of Darling prefix, defaults to ~/.darling
ubuntu@ip-172-31-11-146:~$ darling shell
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling $installation_prefix/libexec/darling
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ darling $installation_prefix/libexec/darling^C
ubuntu@ip-172-31-11-146:~$ darling shell
Cannot open mnt namespace file: No such file or directory
ubuntu@ip-172-31-11-146:~$ cat /home/ubuntu/.darling
cat: /home/ubuntu/.darling: Is a directory
ubuntu@ip-172-31-11-146:~$ cd /home/ubuntu/.darling
ubuntu@ip-172-31-11-146:~/.darling$ ls
Applications  Library  System  Users  Volumes  bin  private  proc  sbin  usr  var
ubuntu@ip-172-31-11-146:~/.darling$ darling
This is Darling, translation layer for macOS software.

Copyright (C) 2012-2020 Lubos Dolezel

Usage:
	darling program-path [arguments...]
	darling shell [arguments...]

Environment variables:
DPREFIX - specifies the location of Darling prefix, defaults to ~/.darling
ubuntu@ip-172-31-11-146:~/.darling$  cd
ubuntu@ip-172-31-11-146:~$ ls
darling  main
ubuntu@ip-172-31-11-146:~$ darling
This is Darling, translation layer for macOS software.

Copyright (C) 2012-2020 Lubos Dolezel

Usage:
	darling program-path [arguments...]
	darling shell [arguments...]

Environment variables:
DPREFIX - specifies the location of Darling prefix, defaults to ~/.darling
ubuntu@ip-172-31-11-146:~$`

**Comment by joshwolff1** [comment]
`sudo darling shell` 

Fixed it for me (adding `sudo`)
