### ISSUE TITLE
Xcode 6.1 Beta 2 fails to load

### ISSUE THREAD

**Issue by 1div0** [darlinghq/darling#78]
Xcode-Beta.app/Contents/MacOS/Xcode from the xcode_6.1_beta_2.dmg fails to load properly with following error:

loader command type=19
segment __LINKEDIT: vmaddr=28000 vmsize=14000 file_offset=28000 file_size=13a80 maxprot=7 init_prot=1 nsects=0 flags=0
loader command type=d
loader command type=80000022
dyld info: rebase_off=163840 rebase_size=1192 bind_off=165032 bind_size=1600 weak_bind_off=0 weak_bind_size=0 lazy_bind_off=166632 lazy_bind_size=3016 export_off=169648 export_size=2336
add rebase! seg_index=0 seg_offset=0 type=0 vmaddr=(nil)
**unknown op: e0**
bind: op=10 imm=2 @0x7fe80586d4a8, bindsStart at 0x7fe80586d4a8
bind: op=a0 imm=6 @0x7fe80586d4a9, bindsStart at 0x7fe80586d4a8
BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB
add bind! (null) seg_index=0 seg_offset=0 type=1 ordinal=2 addend=0 vmaddr=(nil) is_weak=0
Segmentation fault (core dumped)

**Comment by maci0** [comment]
maybe an appdb like they have at winehq.org ?

**Comment by LubosD** [comment]
AppDB is going to appear on http://appdb.darlinghq.org in due time. The first things to appear in there will be Apple's Clang toolchain and some common apps from www.rudix.org.

As far as Xcode is concerned, I see no load problems with Xcode 7.2 (with Darling libsystem branch), just missing libs:

````
$ darling shell
Darling [/tmp]$ /Applications/Xcode.app/Contents/MacOS/Xcode 
dyld: Cannot execute binary file: dyld: Library not loaded: /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
````

The missing libs are Cocoa (obviously), AuthKit (private framework, but simple enough) and libcompression (#111).

Therefore I will close this issue.
