### ISSUE TITLE
compilation faild on ubuntu 18.04 

### ISSUE THREAD

**Issue by odror** [darlinghq/darling#780]
```
[ 41%] Building C object src/external/python/2.7/Python-2.7.10/CMakeFiles/Python.dir/Modules/_math.o
[ 41%] Linking C shared library Python
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
[ 41%] Built target Python
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

Any ideas how to fix. I was able to compile with an older version from 2 weeks ago.

**Comment by facekapow** [comment]
This doesn't show the actual error. Could you try posting your full build log? You can use `tee` to copy the output to a file and then attach that file to a comment. (e.g. `make | tee build-log.txt`).

By the way, this happens because when the build system encounters an error, it will finish executing any other targets it had queued up.

**Comment by odror** [comment]
Ok I was missing the libdbus library. Now I got a different issue. See also log file.

```
[ 60%] Linking C executable instruments
src/frameworks/ApplicationServices/QD/CMakeFiles/QD.dir/build.make:62: recipe for target 'src/frameworks/ApplicationServices/QD/CMakeFiles/QD.dir/src/QD.c.o' failed
CMakeFiles/Makefile2:50763: recipe for target 'src/frameworks/ApplicationServices/QD/CMakeFiles/QD.dir/all' failed
[ 60%] Building C object src/private-frameworks/AppleSystemInfo/CMakeFiles/AppleSystemInfo.dir/src/functions.c.o
[ 60%] Linking C executable xcscontrol
[ 60%] Built target sdp_shim

```

[build-log.txt](https://github.com/darlinghq/darling/files/4605104/build-log.txt)

**Comment by facekapow** [comment]
Could you try running it again with verbose output enabled? (e.g. `make VERBOSE=1 | tee build-log.txt`). This output (and the build log) says that building `QD.c` fails, but it doesn't say why.

Line 62 in `src/frameworks/ApplicationServices/QD/CMakeFiles/QD.dir/build.make` in the build folder is just a command that prints the current progress to the console (at least on my locally generated build directory). That's a weird place for the build to fail, because it's technically not building anything there (unless `make` is wrong and the failing line is actually line 63).

Also, what clang version are you using? (`clang --version`)

**Comment by odror** [comment]
OK now It is more clear. See also attachment
```
Scanning dependencies of target mkdep_shim
make[2]: Leaving directory '/home/dror/work/darling/build'
make -f src/xcselect/CMakeFiles/mkdep_shim.dir/build.make src/xcselect/CMakeFiles/mkdep_shim.dir/build
In file included from /home/dror/work/darling/src/frameworks/ApplicationServices/QD/src/QD.c:25:
In file included from /home/dror/work/darling/src/external/cocotron/CoreGraphics/include/CoreGraphics/CGDirectDisplay.h:3:
/home/dror/work/darling/src/external/cocotron/CoreGraphics/include/CoreGraphics/CGError.h:3:22: error: expected identifier or '('
typedef enum CGError : int32_t {

```

[build-log.txt](https://github.com/darlinghq/darling/files/4606250/build-log.txt)

**Comment by facekapow** [comment]
Ah, ok. This is an issue that has been fixed in the latest master. [Update your sources](https://docs.darlinghq.org/build-instructions.html#updating-sources) and try again.

**Comment by odror** [comment]
Thanks. now I am at 80% with this error:
```

      'FAN_MARK_FILESYSTEM'
        int rv = fanotify_mark(g_fanotify, FAN_MARK_ADD | FAN_MARK_FILESYSTEM,
                                                          ^
/home/dror/work/darling/src/frameworks/CoreServices/src/FSEvents/fseventsd.m:150:3: error: use of undeclared identifier 'FAN_CREATE'
                FAN_CREATE | FAN_DELETE | FAN_MOVED_FROM | FAN_MOVED_TO | FAN_MODIFY | FAN_ONDIR, AT_FDCWD, "/");
                ^
/home/dror/work/darling/src/frameworks/CoreServices/src/FSEvents/fseventsd.m:150:16: error: use of undeclared identifier 'FAN_DELETE'
                FAN_CREATE | FAN_DELETE | FAN_MOVED_FROM | FAN_MOVED_TO | FAN_MODIFY | FAN_ONDIR, AT_FDCWD, "/");
                             ^
/home/dror/work/darling/src/frameworks/CoreServices/src/FSEvents/fseventsd.m:150:29: error: use of undeclared identifier 'FAN_MOVED_FROM'
                FAN_CREATE | FAN_DELETE | FAN_MOVED_FROM | FAN_MOVED_TO | FAN_MODIFY | FAN_ONDIR, AT_FDCWD, "/");
                                          ^
[ 80%] Built target vecLib
/home/dror/work/darling/src/frameworks/CoreServices/src/FSEvents/fseventsd.m:150:46: error: use of undeclared identifier 'FAN_MOVED_TO'
                FAN_CREATE | FAN_DELETE | FAN_MOVED_FROM | FAN_MOVED_TO | FAN_MODIFY | FAN_ONDIR, AT_FDCWD, "/");
                                                           ^

```

See attached log
[build-log.txt](https://github.com/darlinghq/darling/files/4606499/build-log.txt)

**Comment by LubosD** [comment]
@odror I've hopefully just fixed this one as well. Jenkins should tell me in 20 minutes.

**Comment by LubosD** [comment]
Looks OK now, Jenkins build is passing.
