### ISSUE TITLE
NSOpenGLView Only Animates When Interacted With

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#786]
It will only animate when mouse leaves or enter the window, or the window is moved.

Use the Cocotron NSOpenGLView example to test.

**Comment by bugaevc** [comment]
That is definitely not what my experience was. It uses a timer to animate, doesn't it?

**Comment by TheBrokenRail** [comment]
When interacting with the window, the animation will "snap" to it correct position, my guess is that the animation is animating, but it is not rendering until the window is interacted with.

**Comment by facekapow** [comment]
This should be fixed on master
