### ISSUE TITLE
running darling-stub-gen under darling - python3 missing

### ISSUE THREAD

**Issue by HinTak** [darlinghq/darling#807]
Since one can unpack genuine lib / framework with or without darling, it would be interesting to drop the requirements that stub generation requires genuine mac os x.

**Comment by bugaevc** [comment]
Obviously, you have to install Python 3 if you want to use a Python 3 script.

**Comment by HinTak** [comment]
I was trying to run class-dump under darling itself... Which does not provide python3 .

**Comment by CuriousTommy** [comment]
@HinTak Does a clean macOS install provide python3 out-of-the-box?

**Comment by bugaevc** [comment]
No. But it does provide an `xcrun` proxy/shim for it.

**Comment by HinTak** [comment]
@CuriousTommy @bugaevc yes, I was a bit curious about the "DarlingCLT" part. It would be nice that it runs on stock mac os x (which means python2, afaik) and also stock darling (which also means python2 at the moment).

I had a quick look at it yesterday - the script is not hard to fix - do you mind if I modify it, or add a new version, which runs against python2?

**Comment by HinTak** [comment]
Yes, catalina has a `usr/bin/python3` which is just a shim to xcrun . python2 is available in full. So darling-stub-gen should be python2 based, really.

**Comment by bugaevc** [comment]
> So darling-stub-gen should be python2 based, really.

How so?

**Comment by HinTak** [comment]
You want a clean mac os x to be able to run it, right? Apple ships python2, but shim python3, in catalina.

**Comment by bugaevc** [comment]
Not necessarily; the point is to run it, not to run it without installing CLDTs. Python 2 is long deprecated and discontinued; nothing should use it.

**Comment by facekapow** [comment]
Closing since this is intended. To run a Python 3 script, you should install Python 3. You should be able to do that via `brew install python` now, since Homebrew is working (just tried this out myself; you might have to kill it and re-run it if it gets stuck for a few minutes; this is a known bug).

**Comment by HinTak** [comment]
It is simpler than that - the python script does nothing more than just parsing the text output of `class-dump` and `llvm-nm` . `llvm-nm` works on linux too, so it is just `class-dump` that needs to run under darling - the other two can run as a 2nd stage under the linux host. My recent patches were prepared that way.
