### ISSUE TITLE
hung on shutdown

### ISSUE THREAD

**Issue by HinTak** [darlinghq/darling#809]
I tried to do `launchctl shutdown` (before unloading the kernel module and upgradinng...) - it worked the last few times, but this time it hung after exiting.

There used to be a `bash` process connected to `pts/11` (which no longer has a terminal, after existing the darling shell).

```
  374640 ?        I<     0:00 [mach_thread_cal]
 374641 ?        S      0:00 [ux_exception]
 374642 ?        S      0:00 [darling-foreign]
 374643 ?        Dsl    0:00 /sbin/launchd
 374742 ?        Zs     0:00 [shellspawn] <defunct>
 374799 ?        Z      0:00 [ftxinstalledfon] <defunct>
 375411 ?        Z      0:00 [ftxinstalledfon] <defunct>
```

I think linux provides a mechanism to force kernel modules to be unloaded? Anyway, it would be nice for `modprobe -r darling_mach` to actually does what it is supposed to do - kill everything and shutdown darling, by any means.

**Comment by LubosD** [comment]
It's not the responsibility of a kernel module to kill any processes. If the process is in the D state, you may find some clues in `dmesg`.

**Comment by HinTak** [comment]
Well, if I say `modprobe -r darling_mach` it should just unload, and let any userland process die. That's what most network/wifi device kernel modules do - shutdown any network connection at that point, before unloading. I am talking from first-hand experience (I officially maintain one very small area of the linux kernel in that area)

**Comment by LubosD** [comment]
No, that's not possible. If you unload a WiFi module, you're not letting any processes die - just the network interface goes away.

But you cannot unload an executable loader and expect all processes to just terminate. The kernel doesn't work that way.

**Comment by bugaevc** [comment]
We should figure out all those zombies though.

**Comment by HinTak** [comment]
Wine has a few "server" processes, like the desktop tray, etc. It is possible to kill those, and everything started by wine goes...

The kernel allows a few foreign binary loaders to be registered via the bin_miscformat module (wine, mono, jvm), and afaik, they can be shut down cleanly...

**Comment by HinTak** [comment]
`ftxinstallfont` was one of those I played with (part of apple's font tool suite). The others I am not responsible :-( .

**Comment by LubosD** [comment]
binfmt_misc is just a simple hack, you can't compare it to what the Darling LKM does at all. As long as there's a process using services of a module, that module cannot be unloaded - simple fact.

launchd would normally collect these zombies, but it's apparently stuck and that's the main problem here.

**Comment by HinTak** [comment]
Yes. I did `launchctl shutdown` from darling shell , it became half-dead, and after I exited from darling shell, I could neither do kill it or restart it. (ended up rebooting - and even that was hung, I waited for 10 minutes for systemd's watchdog to kick it, it did not, so I long-pressed the power button)

**Comment by HinTak** [comment]
I am wondering if it is a race condition, if you do `launchctl shutdown` twice, within a few seconds apart. I may have done that.

**Comment by HinTak** [comment]
Because I just tried to do similar things as I did; while I have those zombie processes again, when I do `launchctl shutdown` this time, everything goes away, except the three kernel threads.

**Comment by facekapow** [comment]
These sorts of system hangs should be impossible now that we no longer use a kernel module. Closing.
