### ISSUE TITLE
Clang cannot be loaded by darling but can be loaded by maloader

### ISSUE THREAD

**Issue by kad-ecoli** [darlinghq/darling#81]
I have unpack Xcode 4.2.1 for Mac OSX Lion according to instruction by maloader unpack_xcode.sh script <https://github.com/shinh/maloader/blob/master/unpack_xcode.sh>

Darling can load gcc and g++ of command line tools provided that correct symlink is restored.
However, clang in the command line tools can not be loaded.

$ ld-mac usr/bin/clang -v
Apple clang version 3.0 (tags/Apple/clang-211.12) (based on LLVM 3.0svn)
Target: x86_64-apple-darwin10.6.0
Thread model: posix
$ dyld usr/bin/clang -v
dyld: Cannot execute binary file: Symbol not found: ___ashldi3

However, clang and clang++ can be loaded by maloader if it was linked against libc++. Since part of darling was based on maloader code, it is weird that maloader can load mach-o binaries that darling cannot. So I wondered if the missing symbol was due to the fact the dyld was linked against libstdc++ (GLIBCXX) instead of libc++ (LIBCXX); and that whether allowing darling to be linked against libc++ can improve the situation.

**Comment by LubosD** [comment]
clang & Apple ld now fully work under Darling (darling-libsystem branch in the repository). All you need to do is specify the right SDKROOT environment variable, e.g.:

````
SDKROOT=/somewhere/MacOSX10.8.sdk/ dyld /somewhere/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang helloworld.c -o /tmp/helloworld
````
