### ISSUE TITLE
make lkm error

### ISSUE THREAD

**Issue by ogre25** [darlinghq/darling#812]
hello,i run make lkm get these error:

/home/darling/src/external/lkm/overlayfs/copy_up.c:142:11: error: too many arguments to function ‘do_clone_file_range’
  cloned = do_clone_file_range(old_file, 0, new_file, 0, len, 0);
           ^~~~~~~~~~~~~~~~~~~
In file included from /home/apple/darling/src/external/lkm/overlayfs/copy_up.c:8:
/usr/src/linux-headers-4.19.0-9-common/include/linux/fs.h:1852:12: note: declared here
 extern int do_clone_file_range(struct file *file_in, loff_t pos_in,
            ^~~~~~~~~~~~~~~~~~~
make[8]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309：/home/xxxxxx/darling/src/external/lkm/overlayfs/copy_up.o] 错误 1
make[7]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537：_module_/home/apple/darling/src/external/lkm] 错误 2
make[6]: *** [Makefile:146：sub-make] 错误 2
make[5]: *** [Makefile:8：all] 错误 2
make[5]: 离开目录“/usr/src/linux-headers-4.19.0-9-amd64”
make[4]: *** [Makefile:346：default] 错误 2
make[4]: 离开目录“/home/apple/darling/src/external/lkm”
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58：src/external/lkm/CMakeFiles/lkm] 错误 2
make[2]: *** [CMakeFiles/Makefile2:56608：src/external/lkm/CMakeFiles/lkm.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:56615：src/external/lkm/CMakeFiles/lkm.dir/rule] 错误 2
make: *** [Makefile:15686：lkm] 错误 2

my kernel is:

$ uname -a
Linux blackmatrix 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

my system is:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

clang version is:

$ clang-6.0 --version
clang version 6.0.1-10 (tags/RELEASE_601/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

please help me ,thank you very much

**Comment by HinTak** [comment]
Kernel too old...

**Comment by ogre25** [comment]
thanks

> Kernel too old... The darling kernel code was made to work for <5.4 only a week or so ago. (current is 5.6/5.7....)

thanks,i update the kernel

**Comment by facekapow** [comment]
Does it build properly now?

**Comment by ogre25** [comment]
> Does it build properly now?

yes thank you
