### ISSUE TITLE
syslogd malloc: *** error on starting darling shell

### ISSUE THREAD

**Issue by HinTak** [darlinghq/darling#814]
I think I have seen this often right at the beginning of starting darling shell, or soon after, so it is unrelated to anything I try to run under darling. code is up to date to about a week or so.

```
$ darling shell
Loaded the kernel module
Bootstrapping the container with launchd...
syslogd(12,0x7ffff472b000) malloc: *** error for object 0x7f8f2740bb48: incorrect checksum for freed object - object was probably modified after being freed.
     *** set a breakpoint in malloc_error_break to debug
```

**Comment by HinTak** [comment]
Probably related, I just launched darling shell and run xattr ( as in https://github.com/darlinghq/darling/issues/819 )  and my laptop's fan starts going crazy - syslogd is consuming 80-95% of one cpu core!

**Comment by facekapow** [comment]
This should be fixed on master; both the malloc issue and the excessive CPU usage issue.

**Comment by bugaevc** [comment]
What was the malloc issue fix?

**Comment by facekapow** [comment]
It was trying to use and free objects that weren't allocated in the first place due to stubs. I've seen no more issues with syslogd since the libxpc rewrite.
