### ISSUE TITLE
darling_overlay.ko built and installed but not used

### ISSUE THREAD

**Issue by HinTak** [darlinghq/darling#820]
Afaik darling_overlay.ko is not used, so why build/install it? Or the opposite, if it is meant to be used (in the future) some of the docs need to be updated, e.g. Regarding module signing and secure boot. I asked because the module signing instruction is wrong and ubuntu-specific - part of the pull : 

https://github.com/darlinghq/darling-docs/pull/12

I added the updates of non-ubuntu signing of the darling_overlay module then realized it has no effect.

**Comment by LubosD** [comment]
Because you're on Git master, and not on a stable release or something... This stuff may change day to day.

**Comment by HinTak** [comment]
Well, that's "in the future" part of my question then. So one way or the other, the doc can sync or the module can go before the next release. Meanwhile somebody can merge/cherry-pick the correction for module signing?

**Comment by LubosD** [comment]
We could be changing the docs every day like this. Honestly, if someone's not capable of dealing with this problem on their own, then Darling's probably not for them at this point anyway...

**Comment by HinTak** [comment]
:-). I have been updating the docs about something else at the moment. I'll just keep appending to my "misc doc update" pull request then.

**Comment by facekapow** [comment]
Closing, since darling_overlay is disabled now in master
