### ISSUE TITLE
lkm and lkm_install error build

### ISSUE THREAD

**Issue by luoniisan** [darlinghq/darling#823]
don't build the lkm:
make lkm
make lkm_install

logs:
  LD [M]  /tmp/repositories/darling/src/external/lkm/darling-mach.o
  CC [M]  /tmp/repositories/darling/src/external/lkm/overlayfs/copy_up.o
/tmp/repositories/darling/src/external/lkm/overlayfs/copy_up.c: In function ‘ovl_copy_up_data’:
/tmp/repositories/darling/src/external/lkm/overlayfs/copy_up.c:142:11: error: too many arguments to function ‘do_clone_file_range’
  cloned = do_clone_file_range(old_file, 0, new_file, 0, len, 0);
           ^~~~~~~~~~~~~~~~~~~
In file included from /tmp/repositories/darling/src/external/lkm/overlayfs/copy_up.c:8:
/usr/src/linux-headers-4.19.0-9-common/include/linux/fs.h:1852:12: note: declared here
 extern int do_clone_file_range(struct file *file_in, loff_t pos_in,
            ^~~~~~~~~~~~~~~~~~~
make[8]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309: /tmp/repositories/darling/src/external/lkm/overlayfs/copy_up.o] Error 1
make[7]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/tmp/repositories/darling/src/external/lkm] Error 2
make[6]: *** [Makefile:146: sub-make] Error 2
make[5]: *** [Makefile:8: all] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make[4]: *** [Makefile:346: default] Error 2
make[4]: Leaving directory '/tmp/repositories/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[3]: Leaving directory '/tmp/repositories/darling/build'
make[2]: *** [CMakeFiles/Makefile2:46256: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[2]: Leaving directory '/tmp/repositories/darling/build'
make[1]: *** [CMakeFiles/Makefile2:46263: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make[1]: Leaving directory '/tmp/repositories/darling/build'
make: *** [Makefile:15712: lkm] Error 2
make[1]: Entering directory '/tmp/repositories/darling/build'
make[2]: Entering directory '/tmp/repositories/darling/build'
make[3]: Entering directory '/tmp/repositories/darling/build'
Scanning dependencies of target lkm_install
make[3]: Leaving directory '/tmp/repositories/darling/build'
make[3]: Entering directory '/tmp/repositories/darling/build'
Installing the Linux kernel module
make[4]: Entering directory '/tmp/repositories/darling/src/external/lkm'
Running kernel version is 4.19.0-9-amd64
make -C /lib/modules/4.19.0-9-amd64/build M=/tmp/repositories/darling/src/external/lkm modules_install
make[5]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
  INSTALL /tmp/repositories/darling/src/external/lkm/darling-mach.ko
cp: cannot stat '/tmp/repositories/darling/src/external/lkm/darling-mach.ko': No such file or directory

**Comment by facekapow** [comment]
Older kernels like 4.19 are unsupported. Anything 5.0 and up should work.

**Comment by luoniisan** [comment]
/lib/modules# ls
4.19.0-9-amd64	5.6.0-2-amd64

**Comment by r-wilbur** [comment]
@facekapow  Sounds like we should update the build instructions which currently say you need v4.19+.  Should we specify 5.0+?

On a related note:  The build instructions presently recommend at least clang v3.8.  Should we update that to recommend v9+?

**Comment by facekapow** [comment]
@luoniisan What does `uname -r` say? Because your build output shows that the LKM is being built for 4.19.0-9.

@r-wilbur Yeah, we should, for both things. I'm unsure what's the earliest version that are needed for each, but those are good recommendations: 5.0+ for the kernel, clang 8/9+ for the compiler (I *think* it should still work with clang 8).

**Comment by luoniisan** [comment]
uname -r
4.19.0-9-amd64

how am i supposed to change ^^?

**Comment by r-wilbur** [comment]
@facekapow :  With whom should I confirm the new minimum Linux kernel version and clang version requirements before I go and update the documentation?

**Comment by facekapow** [comment]
@r-wilbur I'd say @LubosD (he knows the kernel module best and is the original creator of Darling). You'll have to open a PR in darling-docs, so it'll be reviewed for accuracy by the team anyways.

**Comment by r-wilbur** [comment]
@facekapow, @LubosD :  Our build instructions for debian10 presently call for installing clang6.0.  I just looked at debian.org and the most recent they have for buster(stable) is clang7.0.  So I'm wondering to what version you think we should update our minimum version guidance for clang?

Likewise, I see a commit to support pre-5.4 linux kernel headers but don't know what new minimum kernel version to specify.
