### ISSUE TITLE
make darling don't work but make module work

### ISSUE THREAD

**Issue by luoniisan** [darlinghq/darling#826]
with the old kernel I can only build darling, and since I have updated my kernel I can build only the modules

make
make install

->

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/repositories/darling/build
make[1]: Entering directory '/tmp/repositories/darling/build'
make[2]: Entering directory '/tmp/repositories/darling/build'
Scanning dependencies of target elfloader_dummy32
make[2]: Leaving directory '/tmp/repositories/darling/build'
make[2]: Entering directory '/tmp/repositories/darling/build'
[  0%] Building C object src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/elfcalls.c.o
In file included from /tmp/repositories/darling/src/libelfloader/native/elfcalls.c:4:
In file included from /usr/include/errno.h:28:
In file included from /usr/include/bits/errno.h:26:
/usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
#include <asm/errno.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/build.make:63: src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/elfcalls.c.o] Error 1
make[2]: Leaving directory '/tmp/repositories/darling/build'
make[1]: *** [CMakeFiles/Makefile2:10421: src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/all] Error 2
make[1]: Leaving directory '/tmp/repositories/darling/build'
make: *** [Makefile:130: all] Error 2
make[1]: Entering directory '/tmp/repositories/darling/build'
make[2]: Entering directory '/tmp/repositories/darling/build'
make[2]: Leaving directory '/tmp/repositories/darling/build'
make[2]: Entering directory '/tmp/repositories/darling/build'
[  0%] Building C object src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/elfcalls.c.o
In file included from /tmp/repositories/darling/src/libelfloader/native/elfcalls.c:4:
In file included from /usr/include/errno.h:28:
In file included from /usr/include/bits/errno.h:26:
/usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
#include <asm/errno.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/build.make:63: src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/elfcalls.c.o] Error 1
make[2]: Leaving directory '/tmp/repositories/darling/build'
make[1]: *** [CMakeFiles/Makefile2:10421: src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/all] Error 2
make[1]: Leaving directory '/tmp/repositories/darling/build'
make: *** [Makefile:130: all] Error 2

**Comment by LubosD** [comment]
You obviously don't have `asm/errno.h` for 32-bit x86, so sort that out and continue.

**Comment by luoniisan** [comment]
i have fix for me by:
ln -s /usr/include/asm-generic /usr/include/asm

**Comment by HinTak** [comment]
It is not adviceable to do random sym-links in your system directory. The correct procedure is to add i386 as a sub-architecture, and install the 32-bit version of glibc header!
