### ISSUE TITLE
/root/.darling/var/run/shellspawn.sock (No such file or directory)

### ISSUE THREAD

**Issue by luoniisan** [darlinghq/darling#827]
:/# grep overlay /proc/modules
overlay 135168 0 - Live 0xffffffffc1353000

:/# grep overlay /proc/filesystems
nodev   overlay

:/# darling shell
Setting up a new Darling prefix at /root/.darling
Cannot mount overlay: No such file or directory
Cannot open mnt namespace file: No such file or directory

:/# strace -f -u root bin/darling shell ls
execve("bin/darling", ["bin/darling", "shell", "ls"], 0x7ffe48491b10 /* 31 vars */) = 0
brk(NULL)                               = 0xadd000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=133211, ...}) = 0
mmap(NULL, 133211, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1dc0835000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\22\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14720, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1dc0833000
mmap(NULL, 16656, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1dc082e000
mmap(0x7f1dc082f000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f1dc082f000
mmap(0x7f1dc0830000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1dc0830000
mmap(0x7f1dc0831000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1dc0831000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 o\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1831600, ...}) = 0
mmap(NULL, 1844568, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1dc066b000
mmap(0x7f1dc0690000, 1351680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x25000) = 0x7f1dc0690000
mmap(0x7f1dc07da000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16f000) = 0x7f1dc07da000
mmap(0x7f1dc0824000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b8000) = 0x7f1dc0824000
mmap(0x7f1dc082a000, 13656, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1dc082a000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1dc0668000
arch_prctl(ARCH_SET_FS, 0x7f1dc0668740) = 0
mprotect(0x7f1dc0824000, 12288, PROT_READ) = 0
mprotect(0x7f1dc0831000, 4096, PROT_READ) = 0
mprotect(0x409000, 4096, PROT_READ)     = 0
mprotect(0x7f1dc087e000, 4096, PROT_READ) = 0
munmap(0x7f1dc0835000, 133211)          = 0
geteuid()                               = 0
getuid()                                = 0
getgid()                                = 0
setuid(0)                               = 0
setgid(0)                               = 0
brk(NULL)                               = 0xadd000
brk(0xafe000)                           = 0xafe000
openat(AT_FDCWD, "/proc/modules", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "wacom 122880 0 - Live 0xffffffff"..., 1024) = 1024
close(3)                                = 0
getcwd("/", 4096)                       = 2
stat("/root/.darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/root/.darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/root/.darling/.init.pid", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=7, ...}) = 0
read(3, "1018439", 4096)                = 7
read(3, "", 4096)                       = 0
close(3)                                = 0
kill(1018439, 0)                        = -1 ESRCH (No such process)
unlink("/root/.darling/.init.pid")      = 0
unlink("/root/.darling/var/run/shellspawn.sock") = -1 ENOENT (No such file or directory)
stat("/root/.darling.workdir", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
pipe([3, 4])                            = 0
unshare(CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWPID) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 1040793 attached
, child_tidptr=0x7f1dc0668a10) = 1040793
[pid 1040792] close(4 <unfinished ...>
[pid 1040793] close(3)                  = 0
[pid 1040793] unshare(CLONE_NEWNS <unfinished ...>
[pid 1040792] <... close resumed>)      = 0
[pid 1040792] read(3,  <unfinished ...>
[pid 1040793] <... unshare resumed>)    = 0
[pid 1040793] mount(NULL, "/", NULL, MS_REC|MS_SLAVE, NULL) = 0
[pid 1040793] umount2("/dev/shm", 0)    = 0
[pid 1040793] mount("tmpfs", "/dev/shm", "tmpfs", MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = 0
[pid 1040793] mount("overlay", "/root/.darling", "overlay", 0, "lowerdir=/tmp/development.build/"...) = -1 ENOENT (No such file or di>
[pid 1040793] write(2, "Cannot mount overlay: No such fi"..., 48Cannot mount overlay: No such file or directory
) = 48
[pid 1040793] exit_group(1)             = ?
[pid 1040792] <... read resumed>"", 1)  = 0
[pid 1040793] +++ exited with 1 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1040793, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
close(3)                                = 0
setresuid(-1, 0, -1)                    = 0
setresgid(-1, 0, -1)                    = 0
openat(AT_FDCWD, "/root/.darling/.init.pid", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
setresuid(-1, 0, -1)                    = 0
setresgid(-1, 0, -1)                    = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(3, "1040793", 7)                  = 7
close(3)                                = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=1, tv_nsec=0}, 0x7fff89b1f060) = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=1, tv_nsec=0}, {tv_sec=0, tv_nsec=103733577}) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
restart_syscall(<... resuming interrupted nanosleep ...>) = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=1, tv_nsec=0}, 0x7fff89b1f060) = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=1, tv_nsec=0}, 0x7fff89b1f060) = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=1, tv_nsec=0}, ^C strace: Process 1040792 detached
 <detached ...>

loop on:
nanosleep({tv_sec=1, tv_nsec=0}, 0x7fff89b1f060) = 0
access("/root/.darling/var/run/shellspawn.sock", F_OK) = -1 ENOENT (No such file or directory)

**Comment by HinTak** [comment]
The name space error is a sign of selinux blocking it, I think. You need to do `setsebool -P mmap_low_allowed 1`, I think. Read darling docs.

**Comment by HinTak** [comment]
Btw, the darling launcher is already setuid root - you don't need to run it as root.

**Comment by luoniisan** [comment]
i install selinux on my debian and run ``setsebool -P mmap_low_allowed 1
`` but don't works

**Comment by HinTak** [comment]
There is no point in posting piles and piles of logs if you did not summarize what you did which is different from default:
```
"overlay", "/root/.darling", "overlay", 0, "lowerdir=/tmp/development.build/"...) = -1 
```

What file system is `/root` on, and `/tmp` on? Both of those are non-default...

**Comment by luoniisan** [comment]
/tmp/development.build/ is my cmake target but after file is mov to the systeme

**Comment by HinTak** [comment]
You still have not answered what file systems they are on. Overlayfs, notably  does not work on zfs. And I assume /tmp is a ramdisk on tmpfs? That's also not a good choice.

**Comment by luoniisan** [comment]
ext4 one partition

**Comment by HinTak** [comment]
tmpfs likely won't work because "nodev" is the default for tmpfs. Can't you put it on something more "normal"? You are making it hard for yourself...

**Comment by bugaevc** [comment]
> tmpfs likely won't work because "nodev" is the default for tmpfs.

But we're not creating any devices on the file system, are we?

**Comment by HinTak** [comment]
The darling binary is setuid root, and probably does not work well on tmpfs if that's where you put it too!

**Comment by luoniisan** [comment]
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,seclabel,size=8141920k,nr_inodes=2035480,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=1638052k,mode=755)
/dev/nvme0n1p1 on / type ext4 (rw,relatime,seclabel,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime,seclabel)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,devices)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,blkio)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11786)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime,seclabel)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime,seclabel)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=1638048k,mode=700)

**Comment by HinTak** [comment]
Hmm, is there any errors in `dmesg`? And does `/root/.darling/var/run/shellspawn.sock` exist?  It is a socket (`srw------`)

**Comment by luoniisan** [comment]
the folder exist /root/.darling/var/run/
but the file no exist /root/.darling/var/run/shellspawn.sock

/:#dmsg
[    3.379324] input: Logitech Unifying Device. Wireless PID:408a Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0005/input/input27
[    3.380032] input: Logitech Unifying Device. Wireless PID:408a Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0005/input/input28
[    3.380499] input: Logitech Unifying Device. Wireless PID:408a Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0005/input/input29
[    3.380731] input: Logitech Unifying Device. Wireless PID:408a System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0005/input/input30
[    3.380977] hid-generic 0003:046D:408A.0005: input,hidraw1: USB HID v1.11 Keyboard [Logitech Unifying Device. Wireless PID:408a] on usb-0000:00:14.0-2/input2:1
[    3.381865] input: Logitech Unifying Device. Wireless PID:4082 Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:4082.0006/input/input34
[    3.382540] input: Logitech Unifying Device. Wireless PID:4082 Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:4082.0006/input/input35
[    3.382789] hid-generic 0003:046D:4082.0006: input,hidraw2: USB HID v1.11 Keyboard [Logitech Unifying Device. Wireless PID:4082] on usb-0000:00:14.0-2/input2:2
[    3.706570] Console: switching to colour frame buffer device 240x67
[    3.724567] input: Logitech MX Keys as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0005/input/input39
[    3.725376] logitech-hidpp-device 0003:046D:408A.0005: input,hidraw1: USB HID v1.11 Keyboard [Logitech MX Keys] on usb-0000:00:14.0-2/input2:1
[    3.828318] i915 0000:00:02.0: fb0: i915drmfb frame buffer device
[    3.838206] input: Logitech MX Master 3 as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:046D:C52B.0003/0003:046D:4082.0006/input/input40
[    3.838579] logitech-hidpp-device 0003:046D:4082.0006: input,hidraw2: USB HID v1.11 Keyboard [Logitech MX Master 3] on usb-0000:00:14.0-2/input2:2
[    4.168796] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    4.170418] Bluetooth: BNEP filters: protocol multicast
[    4.171850] Bluetooth: BNEP socket layer initialized
[    5.000902] IPv6: ADDRCONF(NETDEV_CHANGE): enx00e04c68048f: link becomes ready
[    5.001220] r8152 2-1:1.0 enx00e04c68048f: carrier on
[   52.466015] logitech-hidpp-device 0003:046D:408A.0005: HID++ 4.5 device connected.
[   57.561418] Bluetooth: RFCOMM TTY layer initialized
[   57.561437] Bluetooth: RFCOMM socket layer initialized
[   57.561461] Bluetooth: RFCOMM ver 1.11
[   63.899719] logitech-hidpp-device 0003:046D:4082.0006: HID++ 4.5 device connected.
[   64.237718] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[   75.080016] darling_mach: loading out-of-tree module taints kernel.
[   75.080341] darling_mach: module verification failed: signature and/or required key missing - tainting kernel
[   75.092715] darling_xnu_init () called
[   75.092716] darling.xnu.init.1 ()
[   75.092789] <1579> WQ[wql_init]: init linktable with max:262144 elements (8388608 bytes)
[   75.092808] <1579> WQ[wqp_init]: init prepost table with max:262144 elements (8388608 bytes)
[   75.092914] <1579> mig_table_max_displ = 1
[   75.093031] not implemented: host_notify_init()
[   75.093092] current_thread(0x0000000043f3630f)
[   75.093095] kernel_task(0x00000000d495d368)
[   75.093096] calling clock_service_create
[   75.093245] <1582> about to schedule - my state: 1
[   75.199927] Darling Mach: kernel emulation loaded, API version 18
[   75.242364] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  127.949572] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[  136.480033] SELinux:  Class lockdown not defined in policy.
[  136.480036] SELinux: the above unknown classes and permissions will be allowed
[  136.480181] SELinux:  Converting 1616 SID table entries...
[  137.588551] SELinux:  policy capability network_peer_controls=1
[  137.588554] SELinux:  policy capability open_perms=1
[  137.588555] SELinux:  policy capability extended_socket_class=1
[  137.588555] SELinux:  policy capability always_check_network=0
[  137.588556] SELinux:  policy capability cgroup_seclabel=1
[  137.588557] SELinux:  policy capability nnp_nosuid_transition=1
[  139.279036] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  160.728565] SELinux:  Class lockdown not defined in policy.
[  160.728567] SELinux: the above unknown classes and permissions will be allowed
[  160.728712] SELinux:  Converting 1616 SID table entries...
[  161.834793] SELinux:  policy capability network_peer_controls=1
[  161.834795] SELinux:  policy capability open_perms=1
[  161.834796] SELinux:  policy capability extended_socket_class=1
[  161.834796] SELinux:  policy capability always_check_network=0
[  161.834797] SELinux:  policy capability cgroup_seclabel=1
[  161.834798] SELinux:  policy capability nnp_nosuid_transition=1
[  163.573760] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  196.093892] SELinux:  Class lockdown not defined in policy.
[  196.093895] SELinux: the above unknown classes and permissions will be allowed
[  196.094058] SELinux:  Converting 1618 SID table entries...
[  197.206003] SELinux:  policy capability network_peer_controls=1
[  197.206005] SELinux:  policy capability open_perms=1
[  197.206006] SELinux:  policy capability extended_socket_class=1
[  197.206007] SELinux:  policy capability always_check_network=0
[  197.206007] SELinux:  policy capability cgroup_seclabel=1
[  197.206008] SELinux:  policy capability nnp_nosuid_transition=1
[  198.390131] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  259.024086] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  313.101572] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[  320.150699] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[ 2147.717291] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[ 4030.429115] overlayfs: failed to resolve '/tmp/development.build/libexec/darling': -2
[ 5339.948241] perf: interrupt took too long (2548 > 2500), lowering kernel.perf_event_max_sample_rate to 78250
[ 6947.386799] perf: interrupt took too long (3245 > 3185), lowering kernel.perf_event_max_sample_rate to 61500
[ 9417.836958] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[ 9425.770804] perf: interrupt took too long (4097 > 4056), lowering kernel.perf_event_max_sample_rate to 48750
[10492.605805] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[11807.079451] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[12552.225208] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[14270.778379] perf: interrupt took too long (5133 > 5121), lowering kernel.perf_event_max_sample_rate to 38750
[15413.962358] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15
[17365.046385] logitech-hidpp-device 0003:046D:4082.0006: multiplier = 15

**Comment by HinTak** [comment]
That's really screwy - did you do `make install` at all? And why is the installed location `/tmp/development.build/libexec/darling` inside your cmake build directory?

**Comment by luoniisan** [comment]
cd /tmp/darling/
rm -r build/
mkdir -p build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/tmp/development.build/ ../
make
make install
make lkm
make lkm_install
mv /tmp/development.build/* /

**Comment by luoniisan** [comment]
cd /tmp/darling/
rm -r build/
mkdir -p build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/tmp/development.build/ ../
make
make install
make lkm
make lkm_install
dpkg-deb --build /tmp/development.build/
rm -r /tmp/development.build/
apt install ./development.build.deb

is remove after install @HinTak ^^"

**Comment by TheBrokenRail** [comment]
I'm pretty sure the prefix is hard-coded inside the ```darling``` executable, moving it might be whats breaking it.

**Comment by luoniisan** [comment]
@TheBrokenRail yep ^^"

**Comment by HinTak** [comment]
I think the debian packaging is screwy. Anyway, `make`, `make install`, `make lkm`, `make lkm_install` creates one single file `/usr/local/bin/darling`, a wholé tree of `/usr/local/libexec/darling`, and two kernel modules under `/lib/modules/$(uname -r)/extra`, and is not particularly painful to remove by hand.

At first run, `$HOME/.darling` is created and overlay'ed on top of `/usr/local/libexec/darling`, so that's the 4th things you want to remove if you want to remove things by hand (besides the single bin/darling, the libexec/darling directory , and the two darling_*.ko's).

**Comment by luoniisan** [comment]
but I don't want to delete it I want it to work ^^"

**Comment by HinTak** [comment]
I meant these last three steps of yours are probably wrong:

```
dpkg-deb --build /tmp/development.build/
rm -r /tmp/development.build/
apt install ./development.build.deb
```

**Comment by luoniisan** [comment]
no it works for all projects, even Darling before you add the OVERLAY ^^" @HinTak

**Comment by facekapow** [comment]
@luoniisan The recommended method of building and installing is described in the [docs](https://docs.darlinghq.org/build-instructions.html#building-and-installing):
```sh
mkdir build && cd build
cmake ..
make
sudo make install
make lkm
sudo make lkm_install
```

If you *really* want to build the `deb`s, take a look at [`.circleci/config.yml`](https://github.com/darlinghq/darling/blob/master/.circleci/config.yml), particularly this:
```sh
export DEB_DISTRO=$(lsb_release -cs)
tools/makedeb
```

Note that building the deb might require some additional dependencies (e.g. `debhelper`, `devscripts`). Also note that with the recommended method, you can use `CMAKE_INSTALL_PREFIX`, but not with the deb (or, well, you could, but you'd have to modify [`debian/rules`](https://github.com/darlinghq/darling/blob/master/debian/rules)).

For either one of these options, the best thing to do first would be to remove what you installed and start from scratch.

**Comment by luoniisan** [comment]
@facekapow thx you but i set up all github projects by CMAKE_INSTALL_PREFIX is only Darling have a problem with CMAKE_INSTALL_PREFIX

**Comment by luoniisan** [comment]
@facekapow thx you but i set up all github projects by CMAKE_INSTALL_PREFIX is only Darling have a problem with CMAKE_INSTALL_PREFIX

creating a deb is an example, i want to demonstrate the CMAKE_INSTALL_PREFIX does not work

**Comment by luoniisan** [comment]
![image](https://user-images.githubusercontent.com/66533820/84181032-c7a56180-aa88-11ea-9a8e-0055f58ed28f.png)

the Prefix should not be found in the Darling program

**Comment by LubosD** [comment]
@luoniisan Why? Who says that? `CMAKE_INSTALL_PREFIX` specifies where the application will live. There are no guarantess on relocatability of the installation.

Aren't you mistaking it for `DESTDIR`?

**Comment by luoniisan** [comment]
but I only find this problem with Darling probably because you use absolute links ^^"

**Comment by LubosD** [comment]
Not our problem. There are many applications which will malfunction if you relocate them.

**Comment by luoniisan** [comment]
I'm not saying the opposite, but it's just a suggestion for improvement ^^"

**Comment by LubosD** [comment]
That's no improvement. `CMAKE_INSTALL_PREFIX` exists for the very purpose of knowing where the application will live.
