### ISSUE TITLE
New Build Issue

### ISSUE THREAD

**Issue by AndJayJet** [darlinghq/darling#835]
I have an error while building Darling

```
[ 48%] Built target Xcursor
[ 48%] Built target gif
[ 48%] Built target magic
[ 48%] Built target file
[ 48%] Generating ../../../certs/Certificates.bundle
  File "../../../../src/external/openssl_certificates/scripts/generate-ca-bundle.py", line 106
    tag: DERTag
       ^
SyntaxError: invalid syntax
src/external/openssl_certificates/CMakeFiles/build-security-certificates.dir/build.make:80: recipe for target 'certs/Certificates.bundle' failed
make[2]: *** [certs/Certificates.bundle] Error 1
CMakeFiles/Makefile2:31948: recipe for target 'src/external/openssl_certificates/CMakeFiles/build-security-certificates.dir/all' failed
make[1]: *** [src/external/openssl_certificates/CMakeFiles/build-security-certificates.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

I saw on this forum a solution to this problem

`the first error was at ~ 48% because libdbus-1.so was not installed, I installed it from apt install libdbus-1-dev (it is not there in the docs ...)`

But this did not solve my problem, libdbus-1.so was already installed. Help me, please.

P.S.
```
clang version 6.0.1-0+deb8u1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie
```

**Comment by facekapow** [comment]
Do you have Python 3 installed? If not, try installing it.

Sorry, that's my bad. I originally wrote that script for Python 3 (as I though we already had it in our dependencies), but I'll rewrite it later for Python 2 (since I *know* that's one of our dependencies).

**Comment by AndJayJet** [comment]
Yes, I have python 3:

```
python3 --version
Python 3.4.2
```

In my **_dpkg --list_**
```
rc  python                2.7.9-1         amd64           interactive high-level object-oriented language
ii  python-minimal        2.7.9-1         amd64           minimal subset of the Python language (default 
rc  python2.7             2.7.9-2+deb8u5  amd64           Interactive high-level object-oriented language
ii  python2.7-minimal     2.7.9-2+deb8u5  amd64           Minimal subset of the Python language (version 
rc  python3               3.4.2-2         amd64           interactive high-level object-oriented language
rc  python3-gi            3.14.0-1        amd64           Python 3 bindings for gobject-introspection lib
ii  python3-minimal       3.4.2-2         amd64           minimal subset of the Python language (default 
ii  python3.4             3.4.2-1+deb8u7  amd64           Interactive high-level object-oriented language
ii  python3.4-minimal     3.4.2-1+deb8u7  amd64 
```

**Comment by facekapow** [comment]
Ok, I should've been a bit more specific: do you have Python 3.5+? (and I already know the answer from your comment above: no). The thing is, I'm so used to strictly-typed languages that I decided to use Python 3.5's various type hinting features (in case it isn't obvious, I don't write much Python).

For now, try seeing if you can install Python 3.8. I'm going to rewrite the script for Python 2 in a bit.

**Comment by bugaevc** [comment]
> since I know that's one of our dependencies

Wait, is it?

**Comment by HinTak** [comment]
Debian 8 is also rather old - you'll likely encounter the issue about building the darling kernel module against extremely old kernel too

**Comment by facekapow** [comment]
> > since I know that's one of our dependencies
> 
> Wait, is it?

Yup:

> **Debian 10**
> `... libcap2-bin git python2 libglu1-mesa-dev ...`

> **Debian Testing**
> `... libcap2-bin git python2 libglu1-mesa-dev ...`

> **Ubuntu 18.04/20.04**
> For Ubuntu 20.04, also install `python2`.

> **Arch Linux & Manjaro**
> `... cairo libtiff python2 mesa llvm ...`

> **Fedora and CentOS**
> `... dbus-devel flex python2 glibc-devel.i686 ...`

---

I honestly don't think we should write scripts for Python 2 since it's officially deprecated, but I do think I should at least rewrite the script to remove the type hints to allow older Python 3 versions to run it.

**Comment by AndJayJet** [comment]
Thanks for your advice.

It so happened that stopped at python version 3.6. Now the whole trouble is to run the command "cmake .." from official instruction.

```
cmake ..
-bash: / usr / local / bin / cmake: / usr / bin / python: bad interpreter: No such file or directory
```

The fact is that Python is installed at /usr/local/bin/python3.6, and it searches for it in another directory. How to change the default version of Python?

**Comment by bugaevc** [comment]
> I honestly don't think we should write scripts for Python 2 since it's officially deprecated, but I do think I should at least rewrite the script to remove the type hints to allow older Python 3 versions to run it.

Exactly, Python 2 is loooong deprecated, any idea what do we need it for? And yeah, let's supported older Python 3's.

**Comment by LubosD** [comment]
We use Python 2 to `pyc` the Apple Python 2 files we bundle.

**Comment by facekapow** [comment]
> It so happened that stopped at python version 3.6. Now the whole trouble is to run the command "cmake .." from official instruction.
> 
> ```
> cmake ..
> -bash: / usr / local / bin / cmake: / usr / bin / python: bad interpreter: No such file or directory
> ```

@AndJayJet Are you sure you're getting this error during configuration and not when trying to build? Because if you *are* getting the error during configuration, then it sounds like your system's somehow broken. We don't run any Python scripts during configuration (at least as far as I can tell).

How did you install Python 3.6? And did you uninstall Python 3.4? A temporary solution would be to create a symlink in `/usr/bin` to the correct executable (you said it's in `/usr/local/bin/python3.6`), but I would recommend reverting back to the Python your system came with and just waiting until that script is rewritten (I'm going to rewrite it right now).

**Comment by HinTak** [comment]
Before you guys spend more time on this particular issue - debian 8 apparently ships a 3.x kernel, and @AndJayJet probably need to mention if he/she is willing to run something a lot newer. FWIW, AFAIK darling does not even support the 4.x kernels! (v5.8 is currently in RC, I think)

**Comment by facekapow** [comment]
@AndJayJet Alright, you should be able to use your system's default Python 3 now (after updating to the latest code on master). Note that as @HinTak said, Debian 8 ships a pretty old kernel, and last I checked, Darling only builds on 5.x kernels, so you might run into an issue later when building the kernel module.

**Comment by AndJayJet** [comment]
I decided to upgrade the OS from Debian 8.2 to Ubuntu latest version. And the installation was successful without any errors. After installing according to the instructions, I ran the 
`darling shell`
 and it does not find this command. 
`darling: command not found`
I think I forgot to do some small thing. What did I forget to do?

**Comment by HinTak** [comment]
@AndJayJet your messages clearly show you are using a version 4.x kernel ( the `4.15.0-106-generic` part), which is too old. Besides, you did not do `make lkm` nor `make lkm_install` (which would have failed, as the old kernel issue)

**Comment by AndJayJet** [comment]
Thank you very much! I updated the kernel and now darling works!

I take this opportunity to ask the following question:

When I launch the application, it displays the following:

```
dyld: Library not loaded: /System/Library/Frameworks/CoreAudioKit.framework/Versions/A/CoreAudioKit
Reason: image not found; code: 1
```

CoreAudioKit.framework really is not exists. How can I add it?

**Comment by facekapow** [comment]
That looks like a framework we haven’t created/implemented yet. Copying over frameworks from a real Mac won’t work. What you can do is try to stub it with [these instructions](https://docs.darlinghq.org/contributing/generating-stubs.html). Note that stubs only allow the application to load; they won’t actually do what they’re supposed to do.

If everything else is working properly, I’m going to go ahead and close this issue (since it’s for a build issue).
