### ISSUE TITLE
darling shell runs only once (after install and before reboot)

### ISSUE THREAD

**Issue by m-menon** [darlinghq/darling#837]
I had previously used darling and this time I tried installing it on a newly installed Ubuntu 20 (`Linux localhost 5.4.0-37-generic #41-Ubuntu`). I made sure that all the prerequisites are installed. 

After the install, I can run `darling shell` immediately and it works fine. It ran fine with a hello world program. Once I reboot the machine `darling` works but not `darling shell`. I get the following error

```
root@localhost:~# darling shell
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.4.0-37-generic
Failed to load the kernel module
```

It seems to be something like a linking issue or something but I am no expert on Linux so any pointers would be of great help. I even tried couple of things mentioned in this [issue](https://github.com/darlinghq/darling/issues/134) including using the switch `-DCMAKE_INSTALL_PREFIX=/usr/local` but to no avail.

I can find `darling-mach.ko` file in the following locations.
```
root@localhost:~# find / -name "darling-mach*"
/root/darling/src/external/lkm/darling-mach.ko
/root/darling/src/external/lkm/darling-mach.mod.c
/root/darling/src/external/lkm/darling-mach.mod.o
/root/darling/src/external/lkm/darling-mach.o
/root/darling/src/external/lkm/darling-mach.mod
/usr/lib/modules/5.4.0-26-generic/extra/darling-mach.ko
```

If I just run `darling`, then it runs fine and I get this result

```
root@localhost:~# darling
This is Darling, translation layer for macOS software.

Copyright (C) 2012-2020 Lubos Dolezel

Usage:
        darling program-path [arguments...]
        darling shell [arguments...]

Environment variables:
DPREFIX - specifies the location of Darling prefix, defaults to ~/.darling
```

**Comment by HinTak** [comment]
Well, I think if you check the time stamp of `/usr/lib/modules/5.4.0-26-generic/extra/darling-mach.ko` and also you reboot/login record, `last`, you would likely find that you were using 5.4.0-26 before reboot, then rebooted to 5.4.0-27...

**Comment by m-menon** [comment]
> you were using 5.4.0-26 before reboot, then rebooted to 5.4.0-27

  hmm, not sure how it would reboot into 5.4.0-27 because it is a fresh install of Ubuntu 20 and I only installed darling on it once. I had all the prerequisites installed and the installation went smoothly.

I again tried the installation on a fresh Ubuntu 20; once with the `-DCMAKE_INSTALL_PREFIX=/usr/local` and once without that option (again on a fresh install). Even then I face the exact same problem. `darling` works but `darling shell` does not. It throws the same error

```
root@localhost:~/darling/build# darling shell
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.4.0-37-generic
Failed to load the kernel module
```

**Comment by HinTak** [comment]
`apt update && apt upgrade` would install a new kernel, and newly installed kernel become the default. That's the standard behavior. Have you checked `last` what kernel versions you booted with the last few times?

**Comment by m-menon** [comment]
Oops, I have already started reinstalling the OS (Debian 10 this time). I'll try with Ubuntu 20 again and report the outcome.

**Comment by m-menon** [comment]
The darling installation went absolutely smooth with a different Ubuntu 20 image installation. So it could be that the earlier one I tried probably had some auto update set on first run. @HinTak, greatly appreciate your help.
