### ISSUE TITLE
Cannot load libavresample.so

### ISSUE THREAD

**Issue by hantrongbinh** [darlinghq/darling#842]
**Build Log**
What is the build error?
```
[ 35%] Generating avresample.c
Cannot load libavresample.so: libavresample.so: cannot open shared object file: No such file or directory
make[2]: *** [src/CoreAudio/CMakeFiles/avresample.dir/build.make:82: src/CoreAudio/avresample.c] Error 1
make[2]: *** Deleting file 'src/CoreAudio/avresample.c'
make[1]: *** [CMakeFiles/Makefile2:18704: src/CoreAudio/CMakeFiles/avresample.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
[build.log](https://github.com/darlinghq/darling/files/4868575/build.log)

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 10.0.0 |
| CMake | 3.17.3 |
| Linux Kernel | 5.6.16-1-MANJARO |
| Darling | 07515744c968a490091d9f3da2fa940dd128e56e |

**Comment by LubosD** [comment]
Well, so install that library...

**Comment by hantrongbinh** [comment]
> Well, so install that library...

Sorry, my mistake
