### ISSUE TITLE
lkm build on debian stable error: too many arguments to function 'do_clone_file_range'

### ISSUE THREAD

**Issue by ghost** [darlinghq/darling#853]
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-9-amd64 

make lkm
make lkm_install
```
  LD [M]  /darling/src/external/lkm/darling-mach.o
  CC [M]  /darling/src/external/lkm/overlayfs/copy_up.o
/darling/src/external/lkm/overlayfs/copy_up.c: In function 'ovl_copy_up_data':
/darling/src/external/lkm/overlayfs/copy_up.c:142:11: error: too many arguments to function 'do_clone_file_range'
  cloned = do_clone_file_range(old_file, 0, new_file, 0, len, 0);
           ^~~~~~~~~~~~~~~~~~~
In file included from /darling/src/external/lkm/overlayfs/copy_up.c:8:
/usr/src/linux-headers-4.19.0-9-common/include/linux/fs.h:1852:12: note: declared here
 extern int do_clone_file_range(struct file *file_in, loff_t pos_in,
            ^~~~~~~~~~~~~~~~~~~
make[8]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309: /darling/src/external/lkm/overlayfs/copy_up.o] Error 1
make[7]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/darling/src/external/lkm] Error 2
make[6]: *** [Makefile:146: sub-make] Error 2
make[5]: *** [Makefile:8: all] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make[4]: *** [Makefile:346: default] Error 2
make[4]: Leaving directory '/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:56720: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:56727: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15712: lkm] Error 2
Scanning dependencies of target lkm_install
Installing the Linux kernel module
make[4]: Entering directory '/darling/src/external/lkm'
Running kernel version is 4.19.0-9-amd64
make -C /lib/modules/4.19.0-9-amd64/build M=/darling/src/external/lkm modules_install
make[5]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
  INSTALL /darling/src/external/lkm/darling-mach.ko
cp: cannot stat '/darling/src/external/lkm/darling-mach.ko': No such file or directory
  DEPMOD  4.19.0-9-amd64
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[5]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make[4]: Leaving directory '/darling/src/external/lkm'
depmod: WARNING: could not open modules.order at /lib/modules/4.19.0-9-amd64: No such file or directory
depmod: WARNING: could not open modules.builtin at /lib/modules/4.19.0-9-amd64: No such file or directory
Built target lkm_install
```

darling shell ls
```
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/4.19.0-9-amd64
Failed to load the kernel module
```

**Comment by HinTak** [comment]
4.19 is too old.

**Comment by luoniisan** [comment]
your wiki is in fault
https://cdn.discordapp.com/attachments/703714884545806346/736561782092595232/2020-07-25-143312_370x325_scrot.png

an debian stable is in default on 4.19

**Comment by HinTak** [comment]
It is not mine - just another user. The kernel module code was only made to run for 5.4 a couple of months ago, and had always been for latest kernel release before that, I think.

**Comment by luoniisan** [comment]
no problem thanks for the info it would be good to notify them that the wiki has not updated

**Comment by HinTak** [comment]
I do read git log occasionally - according to https://github.com/darlinghq/darling-newlkm/commit/8153f635cddc8cc7108f22ced4c2818a12cf6d71 , it was only made to work for "< 5.4" on 15 May, a little over two months ago. This implies that, more than two months ago it only worked for 5.5/5.6 (5.7 was not out then, I think).

**Comment by luoniisan** [comment]
OS: Debian GNU/Linux 10 (buster) x86_64 
Kernel: 5.4.53


Scanning dependencies of target lkm
Building the Linux kernel module
make[4]: Entering directory '/darling/src/external/lkm'
Running kernel version is 5.4.53
rm -f darling-mach.mod.o
make -C /lib/modules/5.4.53/build M=/darling/src/external/lkm modules
make[5]: Entering directory '/darling/src/external/lkm'
make[5]: *** /lib/modules/5.4.53/build: No such file or directory.  Stop.
make[5]: Leaving directory '/darling/src/external/lkm'
make[4]: *** [Makefile:346: default] Error 2
make[4]: Leaving directory '/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:56720: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:56727: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15712: lkm] Error 2
Scanning dependencies of target lkm_install
Installing the Linux kernel module
make[4]: Entering directory '/darling/src/external/lkm'
Running kernel version is 5.4.53
make -C /lib/modules/5.4.53/build M=/darling/src/external/lkm modules_install
make[5]: Entering directory '/darling/src/external/lkm'
make[5]: *** /lib/modules/5.4.53/build: No such file or directory.  Stop.
make[5]: Leaving directory '/darling/src/external/lkm'
make[4]: *** [Makefile:361: install] Error 2
make[4]: Leaving directory '/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm_install.dir/build.make:58: src/external/lkm/CMakeFiles/lkm_install] Error 2
make[2]: *** [CMakeFiles/Makefile2:56785: src/external/lkm/CMakeFiles/lkm_install.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:56792: src/external/lkm/CMakeFiles/lkm_install.dir/rule] Error 2
make: *** [Makefile:15738: lkm_install] Error 2


5.4 don't work for me ^^"

**Comment by HinTak** [comment]
You are missing a lot of who-own-what info, and I highly doubt that the kernel was built / installed by the user account. (and you use /darling for your source code, really?'??)

Try to make sure /lib/modules etc is readable by the account building darling....)

**Comment by HinTak** [comment]
This is a bit crazy - you used a few days ago you were using 5.7, then you are on 4.19, then 5.4 . And you seem to have a history of doing random customization and hackery to your own system. Can you not try just take all the official packages and try to get them work first? Ie start from a plain recent system and "do not randomly link / install /copy / "?

**Comment by HinTak** [comment]
You have been told 6 weeks ago that 4.19 is too old. https://github.com/darlinghq/darling/issues/823 why are making the same mistakes over and over?

**Comment by HinTak** [comment]
There is no need to build you own kernel - and I highly suspect that you are doing it wrong... - Anyway, you can get them ready-made and done correctly too, from the official source : https://packages.debian.org/search?suite=buster-backports&keywords=kernel

**Comment by luoniisan** [comment]
oups yes sorry i miss mount my /lib/module/ on my bootstrap used for the build so sorry ^^"

**Comment by HinTak** [comment]
This is what I meant by random hackery - /lib/modules should be on / and not on a separate mount. No linux system is set up by default that way. Why are you making life difficult for yourself with these random modifications? 

You are wasting your own time ( nearly two months) and wasting everybody else's.

**Comment by luoniisan** [comment]
yes i think, but when I try with a fresh debian installed it doesn't work

**Comment by facekapow** [comment]
Kernel was too old, plus user deleted their account :/
