### ISSUE TITLE
Failed to execute program /Library/Developer/DarlingCLT/usr/bin/make

### ISSUE THREAD

**Issue by hongyi-zhao** [darlinghq/darling#858]
Hi,

Under Ubuntu 2.04, I try to use the darling to run [this project](https://github.com/AlexanderWillner/runMacOSinVirtualBox) according to the instructions [here](https://rderik.com/blog/understanding-disk-images-by-building-a-macos-catalina-iso-image/).

I firstly cloned the runMacOSinVirtualBox repo to my local machine as following:

```
# I'll clone it
$ git clone https://github.com/AlexanderWillner/runMacOSinVirtualBox.git runMacOSinVirtualBox.git 
$ cd runMacOSinVirtualBox.git
```

Then I enter the darling shell to do the following job:

```
$ darling shell
# I'm going to name my Virtual Machine macOS-Catalina
Darling [/Volumes/SystemRoot/home/werner/runMacOSinVirtualBox.git]$ VM_NAME=macOS-Catalina make vm
Invoked with: /Library/Developer/DarlingCLT/usr/bin/xcrun make vm
Executing /Library/Developer/DarlingCLT/usr/bin/make
Failed to execute program /Library/Developer/DarlingCLT/usr/bin/make
Darling [/Volumes/SystemRoot/home/werner/runMacOSinVirtualBox.git]$ 
```

Any hints for this problem?

Regards
HY

**Comment by HinTak** [comment]
I think you are supposed to install xcode under darling, first, before you can use `xcrun make`.

**Comment by hongyi-zhao** [comment]
Any hints for the step of installation of xcode under darling?

Another question is that I really noted the xcrun has already been available from darling shell:

```
Darling [~]$ which xcrun 
/usr/bin/xcrun
```

But I can't run it at all:

```
Darling [~]$ xcrun --help
Invoked with: /Library/Developer/DarlingCLT/usr/bin/xcrun --help
Executing /Library/Developer/DarlingCLT/usr/bin/--help
Failed to execute program /Library/Developer/DarlingCLT/usr/bin/--help
```

**Comment by HinTak** [comment]
https://github.com/darlinghq/darling-docs/blob/master/src/installing-software.md

**Comment by hongyi-zhao** [comment]
The above mentioned document doesn't have instructions for this type of file:

https://download.developer.apple.com/Developer_Tools/Xcode_12_beta_4/Xcode_12_beta_4.xip

**Comment by HinTak** [comment]
See https://github.com/darlinghq/darling/issues/345#issuecomment-331861558 - darling ships `unxip`.

**Comment by hongyi-zhao** [comment]
Does darling support the lastest version of xcode, i.e., Xcode 12 beta 4?

**Comment by HinTak** [comment]
No idea. You can try and find out, and update the doc.

**Comment by facekapow** [comment]
Okay, so you just didn't have any sort of command line tools installed. I'll go ahead and close this. You can use `xcode-select --install` for the ones Darling installs, or you can install Xcode itself. However, if you want Xcode, see #488 for issues with this. I think xcrun itself works, but some of the tools (like Git) don't.
