### ISSUE TITLE
Use homebrew within darling to install popular tools/utilities.

### ISSUE THREAD

**Issue by hongyi-zhao** [darlinghq/darling#859]
Hi,

See [here](https://github.com/Homebrew/brew/issues/8238) for this question.

Regards
HY

**Comment by bugaevc** [comment]
Yes, it is possible (since recently).

**Comment by hongyi-zhao** [comment]
Thank you for letting me know this. Is the installation method exactly same as for the real MacOS?

**Comment by bugaevc** [comment]
Yes!

You may run into some hangs though — in that case, just interrupt the process with Ctrl-C and restart it.

**Comment by hongyi-zhao** [comment]
What do you mean by saying _some hangs_? Are they fatal and will induce a failed installation?

**Comment by facekapow** [comment]
@hongyi-zhao It is currently known (#357) that the initial Homebrew installation requires at least 3 tries (possibly more if Git decides to hang during the clone). In every case, just retry the installation and it'll eventually work.

After the initial installation of Homebrew itself, `brew install <whatever>` will also *usually* work, with the occasional hang while trying to update the list of Homebrew software or while downloading packages. Like @bugaevc mentioned above, Ctrl-C it and restart it and everything should be fine.

**Comment by hongyi-zhao** [comment]
Got it. It seems very good. Thanks a lot.
