### ISSUE TITLE
Ubuntu build instructions should include step on installing gnustep-coreback

### ISSUE THREAD

**Issue by andlabs** [darlinghq/darling#86]
The Ubuntu build instructions page on the website is missing a step needed to run Darling at all: install gnustep-coreback. This appears to be the same as all the other GNUstep steps.

Without this step, you get errors about GNUstep being "Unable to find backend back".

Note: I installed to a separate prefix `/opt/darling`; IDK if installing it to the default would make any difference (though I did have to fiddle with `LD_LIBRARY_PATH` and `LDFLAGS` in a few places...).

**Comment by LubosD** [comment]
No longer relevant, Darling bundles its own CoreFoundation framework.
