### ISSUE TITLE
Incorrect dependancies for ubuntu 20.41

### ISSUE THREAD

**Issue by demhademha** [darlinghq/darling#865]
I **don't know** if this belongs here, but when running sudo apt install cmake clang bison flex libfuse-dev libudev-dev pkg-config libc6-dev-i386 \ linux-headers-generic gcc-multilib libcairo2-dev libgl1-mesa-dev libglu1-mesa-dev libtiff5-dev \ libfreetype6-dev git libelf-dev libxml2-dev libegl1-mesa-dev libfontconfig1-dev libbsd-dev \ libxrandr-dev libxcursor-dev libgif-dev libavutil-dev libpulse-dev libavformat-dev libavcodec-dev \ libavresample-dev libdbus-1-dev libxkbfile-dev libssl-dev python2 (following the docs) I get the following errors:
E: Unable to locate package  linux-headers-generic
E: Unable to locate package  libfreetype6-dev
E: Unable to locate package  libxrandr-dev
E: Unable to locate package  libavresample-dev
It appears that the dependancies or missing / incorrect.
Any help would be greatly appreciated

**Comment by facekapow** [comment]
This was discussed and resolved in the Discord (https://discordapp.com/channels/587344761107513532/664302140298362880/745738686506860685):

> nvm, it seems my terminal wasn't happy with the \\(s) and now it's fixed
