### ISSUE TITLE
Issue with brew on darling

### ISSUE THREAD

**Issue by demhademha** [darlinghq/darling#868]
**Expected Result**
What did you expect to happen?
I expected git to install after running "brew install git"
**Actual Result**
What did happen?

When running say brew install git, I get the following error Pouring gettext-0.21.mojave.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gettext`
Error: Invalid argument @ rb_dir_s_empty_p - /usr/local/var/homebrew/linked/gettext
Error: Git must be installed and in your PATH!
Error: Invalid argument @ rb_dir_s_empty_p - /usr/local/var/homebrew/linked/gettext

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?
1. Run the brew install script found at brew.sh
2. Let it install (first attempt fails) that is an issue with darling,
3. brew installs successfully 
4. Running brew install git gives the above error
**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| Linux Kernel | X.Y.Z |
| Darling | Git Commit Hash |

I am running ubuntu 20.04.1
Thank you, any support would be appreciated gravely

**Comment by andrzejd-pl** [comment]
I've the same problem when want to install wget

**Comment by demhademha** [comment]
^

**Comment by Arsen6331** [comment]
I am pretty sure I know the source of this issue. Brew itself actually uses git. It cannot install git if git is not installed, if I am right and this is the actual issue, then you would need to install the Xcode Command Line Tools which I don't know how to accomplish on Darling.

**Comment by exebook** [comment]
I have the same error message when I try to install almost anything. For example 'tcc' and 'the_silver_searcher'.

**Comment by demhademha** [comment]
> I have the same error message when I try to install almost anything. For example 'tcc' and 'the_silver_searcher'.
> 
> 
> 
> ```rb
> 
> Error: Invalid argument @ rb_dir_s_empty_p - /usr/local/var/homebrew/linked/pcre
> 
> ```


For me, using the update-sources branch fixed this issue

**Comment by facekapow** [comment]
Now that update-sources has been merged, this should be fixed.
