### ISSUE TITLE
Unable to build LKM

### ISSUE THREAD

**Issue by MrRubberDucky99** [darlinghq/darling#869]
**Expected Result**
What did you expect to happen?
I expected LKM to build

**Actual Result**
What did happen?
`make[4]: Entering directory '/home/judah/darling/src/external/lkm'
Running kernel version is 4.19.104-microsoft-standard
rm -f darling-mach.mod.o
make -C /lib/modules/4.19.104-microsoft-standard/build M=/home/judah/darling/src/external/lkm modules
make[5]: Entering directory '/home/judah/darling/src/external/lkm'
make[5]: *** /lib/modules/4.19.104-microsoft-standard/build: No such file or directory.  Stop.
make[5]: Leaving directory '/home/judah/darling/src/external/lkm'
make[4]: *** [Makefile:346: default] Error 2
make[4]: Leaving directory '/home/judah/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:46348: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:46355: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15738: lkm] Error 2`

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?
Install darlig va Ubuntu WSL
**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
Put the command output here!
```
Nothing

**System Information**
What system are you using?
Windows 10 WSL Ubuntu
| Software | Ubuntu 20.04.1|
| --- | --- |
| Linux Kernel | 4.19.104-microsoft-standard |
| Darling | c03f2b9702c00bda95e580aae01e461cbeb2a0d0 |

**Comment by wellWINeo** [comment]
If i remember right, darling wont be to compile and run on wsl, but now i cant find this in docs

**Comment by wellWINeo** [comment]
Can I run Darling on Windows using WSL?
Unfortunately, no. Darling requires a real Linux kernel to run. See this (issue)[https://github.com/darlinghq/darling/issues/260] for more details.

https://www.darlinghq.org/
