### ISSUE TITLE
CMake is unable to found xrandr

### ISSUE THREAD

**Issue by ZErik19** [darlinghq/darling#870]
Hello guys,

I got an error from cmake:

--------------------------------------------------
cmake ..
-- Found dsymutil: /usr/bin/dsymutil-10
-- Compiler include path detected as /usr/lib/llvm-10/lib/clang/10.0.0/include/
-- Found FFMPEG or Libav: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so, /usr/include/x86_64-linux-gnu
FATALXRandR not found
-- Checking for one of the modules 'openssl'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'openssl' found
Call Stack (most recent call first):
  src/external/openssl_certificates/CMakeLists.txt:11 (pkg_search_module)

CMake Error at src/external/cocotron/AppKit/CMakeLists.txt:19 (message):
  XRandR not found

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xrandr_INCLUDE_PATH (ADVANCED)
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd
   used as include directory in directory /home/wzyerik/darling/src/external/iokitd

-- Configuring incomplete, errors occurred!
--------------------------------------------------

How to fix? Thank you

Ubuntu 20.04.1 LTS
Darling for Github

**Comment by CuriousTommy** [comment]
Did you install the dependencies listed in [the docs](https://docs.darlinghq.org/build-instructions.html)?

**Comment by bugaevc** [comment]
> How to fix?

Install xrandr 🙂

**Comment by ZErik19** [comment]
Naaa, or just restart lul. Thank you guys hahaha
