### ISSUE TITLE
Mac os on android!!!!!

### ISSUE THREAD

**Issue by Malaska678** [darlinghq/darling#874]
I would try this software on android. But first i would run linux on android. I will use andronix app to do that. Andronix do not run full linux on android. Instead, it use proot to run linux apps and vnc server for control. Will it work? Lol its a compatibility layer on top of another one.

**Comment by Ella-0** [comment]
It probably wont work since darling depends on a kernel module which I don't think you can load on android.

**Comment by Ella-0** [comment]
Android is Linux so you are running full Linux just a stripped down fork of it and without a complete user space.

**Comment by facekapow** [comment]
This is currently being tracked in #291 and #642.

**Comment by BryleHelll** [comment]
> Android is Linux so you are running full Linux just a stripped down fork of it and without a complete user space.

Well, no. Android uses very different libc, bionic libc

**Comment by TheAwesome98-Real** [comment]
> > Android is Linux so you are running full Linux just a stripped down fork of it and without a complete user space.
> 
> Well, no. Android uses very different libc, bionic libc

i'm assuming you're referring to glibc as "linux libc"
