### ISSUE TITLE
Spent all day building darling, and it doesn't launch.

### ISSUE THREAD

**Issue by skynurd** [darlinghq/darling#875]
**Expected Result**
What did you expect to happen? for it to launch.

**Actual Result**
What did happen? it didn't

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue? running darling shell (sends back that the command "darling" isn't found.

**```strace``` Output**
Run ```sudo strace -f -u $USER darling shell```, what is the output?
```
Put the command output here! 
```
strace: Can't stat 'darling': No such file or directory
**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
Put the command output here! 
```
didn't return anything.

**System Information**
What system are you running?

| Software | Version |
| ubuntu | 20.04 |
| Linux Kernel | X.Y.Z |
| Darling | Git Commit Hash |

**Comment by skynurd** [comment]
i have all the directories on my system. it's taking up space, so i know it installed. but when i run the command to start it, it just says "darling: command not found"... not upset necessarily at any dev, just kinda pissed that after all that time of building/waiting for it to build itself via the instructions given in the docs, it doesn't even find the command to launch the damn thing.

**Comment by bjorn3** [comment]
What is the output of `echo $PATH`? Does it include `/usr/local/bin`?

**Comment by CuriousTommy** [comment]
@skynurd Does `/usr/local/bin/darling` exist? Did you run `sudo make install`?

**Comment by skynurd** [comment]
> @skynurd Does `/usr/local/bin/darling` exist? Did you run `sudo make install`?

yes, i ran `sudo make install`. it took very long to install as well. but there's no folders in `usr/local/bin`

**Comment by skynurd** [comment]
> What is the output of `echo $PATH`? Does it include `/usr/local/bin`?

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` is what returned

**Comment by skynurd** [comment]
turns out i'm an idiot. i mistook the building process as it installing, and after running `sudo make install` for what i thought was a second time, i realize that i must've not ran it all all. anyway, sorry for being an idiot. i'll close this issue, and thanks to you two. @CuriousTommy @bjorn3
