### ISSUE TITLE
Error Install Darlink |Cmake Error|

### ISSUE THREAD

**Issue by Klubuntu** [darlinghq/darling#876]
**Cmake Error :**
$ cmake ..
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang
-- The ASM-ATT compiler identification is GNU
-- Found assembler: /usr/bin/as
-- Found dsymutil: /usr/bin/dsymutil-10
-- Found Setcap: /usr/sbin/setcap  
-- Compiler include path detected as /usr/lib/llvm-10/lib/clang/10.0.1/include/
-- Found BISON: /usr/bin/bison (found version "3.5.1") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'fuse'
--   Found fuse, version 2.9.9
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.54.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.29.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Found FFMPEG or Libav: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so, /usr/include/x86_64-linux-gnu
-- Found FFmpeg: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so  
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Checking for one of the modules 'openssl'
CMake Error: failed to create symbolic link '3c9a4d3b.0': operation not permitted
CMake Error: failed to create symbolic link 'ea169617.0': operation not permitted
CMake Error: failed to create symbolic link 'c8763593.0': operation not permitted
CMake Error: failed to create symbolic link '5f47b495.0': operation not permitted
CMake Error: failed to create symbolic link '3c58f906.0': operation not permitted
CMake Error: failed to create symbolic link 'e268a4c5.0': operation not permitted
CMake Error: failed to create symbolic link 'a2df7ad7.0': operation not permitted
CMake Error: failed to create symbolic link '052e396b.0': operation not permitted
CMake Error: failed to create symbolic link 'e48193cf.0': operation not permitted
CMake Error: failed to create symbolic link '86212b19.0': operation not permitted
CMake Error: failed to create symbolic link 'dbc54cab.0': operation not permitted
CMake Error: failed to create symbolic link 'ccc52f49.0': operation not permitted
CMake Error: failed to create symbolic link 'fac084d7.0': operation not permitted
CMake Error: failed to create symbolic link 'b872f2b4.0': operation not permitted
CMake Error: failed to create symbolic link 'd16a5865.0': operation not permitted
CMake Error: failed to create symbolic link '3ad48a91.0': operation not permitted
CMake Error: failed to create symbolic link '72f369af.0': operation not permitted
CMake Error: failed to create symbolic link '82223c44.0': operation not permitted
CMake Error: failed to create symbolic link '2d9dafe4.0': operation not permitted
CMake Error: failed to create symbolic link 'd64f06f3.0': operation not permitted
CMake Error: failed to create symbolic link '21855f49.0': operation not permitted
CMake Error: failed to create symbolic link '9576d26b.0': operation not permitted
CMake Error: failed to create symbolic link 'd5727d6a.0': operation not permitted
CMake Error: failed to create symbolic link '9282e51c.0': operation not permitted
CMake Error: failed to create symbolic link '895cad1a.0': operation not permitted
CMake Error: failed to create symbolic link '5a3f0ff8.0': operation not permitted
CMake Error: failed to create symbolic link '89c02a45.0': operation not permitted
CMake Error: failed to create symbolic link 'd4c339cb.0': operation not permitted
CMake Error: failed to create symbolic link 'ee7cd6fb.0': operation not permitted
CMake Error: failed to create symbolic link 'a0bc6fbb.0': operation not permitted
CMake Error: failed to create symbolic link '262ba90f.0': operation not permitted
CMake Error: failed to create symbolic link 'fde84897.0': operation not permitted
CMake Error: failed to create symbolic link '7672ac4b.0': operation not permitted
CMake Error: failed to create symbolic link 'd6e6eab9.0': operation not permitted
CMake Error: failed to create symbolic link '17b51fe6.0': operation not permitted
CMake Error: failed to create symbolic link '6e8bf996.0': operation not permitted
CMake Error: failed to create symbolic link '95aff9e3.0': operation not permitted
CMake Error: failed to create symbolic link '1eb37bdf.0': operation not permitted
CMake Error: failed to create symbolic link '1676090a.0': operation not permitted
CMake Error: failed to create symbolic link 'ff588423.0': operation not permitted
CMake Error: failed to create symbolic link '75680d2e.0': operation not permitted
CMake Error: failed to create symbolic link '02b73561.0': operation not permitted
CMake Error: failed to create symbolic link '124bbd54.0': operation not permitted
CMake Error: failed to create symbolic link '343eb6cb.0': operation not permitted
CMake Error: failed to create symbolic link '1df5a75f.0': operation not permitted
CMake Error: failed to create symbolic link 'd7746a63.0': operation not permitted
CMake Error: failed to create symbolic link '1dac3003.0': operation not permitted
CMake Error: failed to create symbolic link '12d55845.0': operation not permitted
CMake Error: failed to create symbolic link '4e18c148.0': operation not permitted
CMake Error: failed to create symbolic link '69105f4f.0': operation not permitted
CMake Error: failed to create symbolic link '8d6437c3.0': operation not permitted
CMake Error: failed to create symbolic link 'c491639e.0': operation not permitted
CMake Error: failed to create symbolic link '399e7759.0': operation not permitted
CMake Error: failed to create symbolic link 'c90bc37d.0': operation not permitted
CMake Error: failed to create symbolic link 'ed39abd0.0': operation not permitted
CMake Error: failed to create symbolic link '81b9768f.0': operation not permitted
CMake Error: failed to create symbolic link 'a2c66da8.0': operation not permitted
CMake Error: failed to create symbolic link 'cb156124.0': operation not permitted
CMake Error: failed to create symbolic link 'f80cc7f6.0': operation not permitted
CMake Error: failed to create symbolic link 'aeb67534.0': operation not permitted
CMake Error: failed to create symbolic link '91739615.0': operation not permitted
CMake Error: failed to create symbolic link '3e7271e8.0': operation not permitted
CMake Error: failed to create symbolic link 'bf64f35b.0': operation not permitted
CMake Error: failed to create symbolic link 'b3fb433b.0': operation not permitted
CMake Error: failed to create symbolic link '455f1b52.0': operation not permitted
CMake Error: failed to create symbolic link '594f1775.0': operation not permitted
CMake Error: failed to create symbolic link '74c26bd0.0': operation not permitted
CMake Error: failed to create symbolic link 'e7b8d656.0': operation not permitted
CMake Error: failed to create symbolic link '7999be0d.0': operation not permitted
CMake Error: failed to create symbolic link '57692373.0': operation not permitted
CMake Error: failed to create symbolic link '9772ca32.0': operation not permitted
CMake Error: failed to create symbolic link '27af790d.0': operation not permitted
CMake Error: failed to create symbolic link 'c7e2a638.0': operation not permitted
CMake Error: failed to create symbolic link 'e775ed2d.0': operation not permitted
CMake Error: failed to create symbolic link '87753b0d.0': operation not permitted
CMake Error: failed to create symbolic link '0d69c7e1.0': operation not permitted
CMake Error: failed to create symbolic link '2add47b6.0': operation not permitted
CMake Error: failed to create symbolic link 'b0f3e76e.0': operation not permitted
CMake Error: failed to create symbolic link '111e6273.0': operation not permitted
CMake Error: failed to create symbolic link '1e8e7201.0': operation not permitted
CMake Error: failed to create symbolic link '9f533518.0': operation not permitted
CMake Error: failed to create symbolic link '219d9499.0': operation not permitted
CMake Error: failed to create symbolic link 'bc3f2570.0': operation not permitted
CMake Error: failed to create symbolic link '40dc992e.0': operation not permitted
CMake Error: failed to create symbolic link '9685a493.0': operation not permitted
CMake Error: failed to create symbolic link '58a44af1.0': operation not permitted
CMake Error: failed to create symbolic link 'd18e9066.0': operation not permitted
CMake Error: failed to create symbolic link '4be590e0.0': operation not permitted
CMake Error: failed to create symbolic link '48a195d8.0': operation not permitted
CMake Error: failed to create symbolic link '119afc2e.0': operation not permitted
CMake Error: failed to create symbolic link 'f61bff45.0': operation not permitted
CMake Error: failed to create symbolic link 'e8651083.0': operation not permitted
CMake Error: failed to create symbolic link '60afe812.0': operation not permitted
CMake Error: failed to create symbolic link '5a5372fc.0': operation not permitted
CMake Error: failed to create symbolic link '635ccfd5.0': operation not permitted
CMake Error: failed to create symbolic link 'add67345.0': operation not permitted
CMake Error: failed to create symbolic link '8317b10c.0': operation not permitted
CMake Error: failed to create symbolic link '2fa87019.0': operation not permitted
CMake Error: failed to create symbolic link '3a3b02ce.0': operation not permitted
CMake Error: failed to create symbolic link 'dfc0fe80.0': operation not permitted
CMake Error: failed to create symbolic link '8c24b137.0': operation not permitted
CMake Error: failed to create symbolic link '5cf9d536.0': operation not permitted
CMake Error: failed to create symbolic link '52b525c7.0': operation not permitted
CMake Error: failed to create symbolic link '7a819ef2.0': operation not permitted
CMake Error: failed to create symbolic link '1f58a078.0': operation not permitted
CMake Error: failed to create symbolic link '9339512a.0': operation not permitted
CMake Error: failed to create symbolic link 'e442e424.0': operation not permitted
CMake Error: failed to create symbolic link '8470719d.0': operation not permitted
CMake Error: failed to create symbolic link 'fb126c6d.0': operation not permitted
CMake Error: failed to create symbolic link 'f559733c.0': operation not permitted
CMake Error: failed to create symbolic link '631c779f.0': operation not permitted
CMake Error: failed to create symbolic link 'ab5346f4.0': operation not permitted
CMake Error: failed to create symbolic link 'cf701eeb.0': operation not permitted
CMake Error: failed to create symbolic link 'bdacca6f.0': operation not permitted
CMake Error: failed to create symbolic link '9dbefe7b.0': operation not permitted
CMake Error: failed to create symbolic link 'd59297b8.0': operation not permitted
CMake Error: failed to create symbolic link 'a3896b44.0': operation not permitted
CMake Error: failed to create symbolic link '755f7420.0': operation not permitted
CMake Error: failed to create symbolic link 'a7605362.0': operation not permitted
CMake Error: failed to create symbolic link '3c6676aa.0': operation not permitted
CMake Error: failed to create symbolic link 'cdaebb72.0': operation not permitted
CMake Error: failed to create symbolic link '3d441de8.0': operation not permitted
CMake Error: failed to create symbolic link '5a250ea7.0': operation not permitted
CMake Error: failed to create symbolic link '23f4c490.0': operation not permitted
CMake Error: failed to create symbolic link '85cde254.0': operation not permitted
CMake Error: failed to create symbolic link '10531352.0': operation not permitted
CMake Error: failed to create symbolic link '33815e15.0': operation not permitted
CMake Error: failed to create symbolic link '33815e15.0': operation not permitted
CMake Error: failed to create symbolic link 'ee90b008.0': operation not permitted
CMake Error: failed to create symbolic link '3c860d51.0': operation not permitted
CMake Error: failed to create symbolic link '46b2fd3b.0': operation not permitted
CMake Error: failed to create symbolic link '5046c355.0': operation not permitted
CMake Error: failed to create symbolic link 'e60bf0c0.0': operation not permitted
CMake Error: failed to create symbolic link '450c6e38.0': operation not permitted
CMake Error: failed to create symbolic link '9ab62355.0': operation not permitted
CMake Error: failed to create symbolic link 'd06393bb.0': operation not permitted
CMake Error: failed to create symbolic link '1e1eab7c.0': operation not permitted
CMake Error: failed to create symbolic link '7a481e66.0': operation not permitted
CMake Error: failed to create symbolic link 'd66b55d9.0': operation not permitted
CMake Error: failed to create symbolic link 'b0ed035a.0': operation not permitted
CMake Error: failed to create symbolic link 'b7db1890.0': operation not permitted
CMake Error: failed to create symbolic link '1dcd6f4c.0': operation not permitted
CMake Error: failed to create symbolic link '63a2c897.0': operation not permitted
CMake Error: failed to create symbolic link 'c51c224c.0': operation not permitted
CMake Error: failed to create symbolic link '418595b9.0': operation not permitted
CMake Error: failed to create symbolic link '0d5a4e1c.0': operation not permitted
CMake Error: failed to create symbolic link '6645de82.0': operation not permitted
CMake Error: failed to create symbolic link '04f60c28.0': operation not permitted
CMake Error: failed to create symbolic link '35105088.0': operation not permitted
CMake Error: failed to create symbolic link '9ec3a561.0': operation not permitted
CMake Error: failed to create symbolic link 'ff783690.0': operation not permitted
CMake Error: failed to create symbolic link '5e4e69e7.0': operation not permitted
CMake Error: failed to create symbolic link 'facacbc6.0': operation not permitted
CMake Error: failed to create symbolic link '524d9b43.0': operation not permitted
CMake Error: failed to create symbolic link '2edf7016.0': operation not permitted
CMake Error: failed to create symbolic link 'c19d42c7.0': operation not permitted
CMake Error: failed to create symbolic link '11f154d6.0': operation not permitted
CMake Error: failed to create symbolic link 'ed62f4e3.0': operation not permitted
CMake Error: failed to create symbolic link 'd78a75c7.0': operation not permitted
CMake Error: failed to create symbolic link '7651b327.0': operation not permitted
CMake Error: failed to create symbolic link '72fa7371.0': operation not permitted
CMake Error: failed to create symbolic link '7d453d8f.0': operation not permitted
CMake Error: failed to create symbolic link '7651b327.0': operation not permitted
CMake Error: failed to create symbolic link '6fcc125d.0': operation not permitted
CMake Error: failed to create symbolic link '08aef7bb.0': operation not permitted
CMake Error: failed to create symbolic link '961f5451.0': operation not permitted
CMake Error: failed to create symbolic link '03f2b8cf.0': operation not permitted
CMake Error: failed to create symbolic link '76579174.0': operation not permitted
CMake Error: failed to create symbolic link '882de061.0': operation not permitted
CMake Error: failed to create symbolic link '9d6523ce.0': operation not permitted
CMake Error: failed to create symbolic link '00673b5b.0': operation not permitted
CMake Error: failed to create symbolic link 'a7d2cf64.0': operation not permitted
CMake Error: failed to create symbolic link '67495436.0': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/shell_cmds/groups': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/shell_cmds/whoami': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/gunzip': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/gzcat': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/chgrp': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/unlink': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/readlink': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/gunzip': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/gzcat': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/zcat': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/gunzip': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/zcmp': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/file_cmds/zmore': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/bash/sh': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/less/more': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/grep/egrep': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/grep/fgrep': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/zip/unzip/unzip-5.52/zipinfo': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/installer/uninstaller': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/installer/pkgutil': operation not permitted
CMake Error: failed to create symbolic link '/media/klubuntu/5E27-2008/Softwares/MacOSApp/darling/build/src/external/installer/lsbom': operation not permitted
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Performing Test CFLAG_Wno_unknown_pragmas
-- Performing Test CFLAG_Wno_unknown_pragmas - Success
-- Performing Test CFLAG_Wno_unused_variable
-- Performing Test CFLAG_Wno_unused_variable - Success
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Checking for module 'egl'
--   Found egl, version 1.5
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.10.1") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.1.0") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found GIF: /usr/local/lib/libgif.so (found version "5.2.1") 
-- Checking for module 'fontconfig'
--   Found fontconfig, version 2.13.1
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Checking for module 'dbus-1'
--   Found dbus-1, version 1.12.16
-- Configuring done
CMake Error at cmake/darling_lib.cmake:16 (add_library):
  Cannot find source file:

    AUPublic/AUBase/AUBase.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  cmake/darling_bundle.cmake:3 (add_darling_library)
  src/CoreAudio/CoreAudioComponent/CMakeLists.txt:35 (add_darling_bundle)

CMake Error at cmake/darling_lib.cmake:16 (add_library):
  Cannot find source file:

    AFPublic/AudioFileComponentBase.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  cmake/darling_bundle.cmake:3 (add_darling_library)
  src/CoreAudio/AFAVFormatComponent/CMakeLists.txt:25 (add_darling_bundle)

CMake Error at cmake/darling_lib.cmake:16 (add_library):
  No SOURCES given to target: CoreAudioComponent
Call Stack (most recent call first):
  cmake/darling_bundle.cmake:3 (add_darling_library)
  src/CoreAudio/CoreAudioComponent/CMakeLists.txt:35 (add_darling_bundle)

CMake Error at cmake/darling_lib.cmake:16 (add_library):
  No SOURCES given to target: AFAVFormatComponent
Call Stack (most recent call first):
  cmake/darling_bundle.cmake:3 (add_darling_library)
  src/CoreAudio/AFAVFormatComponent/CMakeLists.txt:25 (add_darling_bundle)

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Steps To Reproduce**
1. Please fix error

**System Information**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Processor Info**
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz
stepping        : 5
microcode       : 0x7
cpu MHz         : 2926.102
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 5320.11
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz
stepping        : 5
microcode       : 0x7
cpu MHz         : 2926.323
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 5320.11
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz
stepping        : 5
microcode       : 0x7
cpu MHz         : 3117.888
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 2
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 5320.11
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz
stepping        : 5
microcode       : 0x7
cpu MHz         : 3084.009
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 2
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 5320.11
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

| Software | Version |
| --- | --- |
| Darling | Download new version |
| Lubuntu| which install git clone --recursive |

**Comment by HinTak** [comment]
I think the message says what it says : you are building on an external removable media `/media/klubuntu/5E27-2008` which is formatted with a filesystem that does not support symbolic links. Try building elsewhere.

**Comment by Klubuntu** [comment]
How to install on USB Device formatted Fat32 
  Dnia 01 października 2020 21:28 HinTak   napisał(a):  
 I think the message says what it says : you are building on an external removable media  /media/klubuntu/5E27-2008  which is formatted with a filesystem that does not support symbolic links. Try building elsewhere.

**Comment by HinTak** [comment]
You cannot - installation only works on file systems which allows symbolic links.
