### ISSUE TITLE
[Docs] Caught small typo in release docs

### ISSUE THREAD

**Issue by joe733** [darlinghq/darling#878]
**Screenshot** :

![Screenshot from 2020-10-10 08-38-03](https://user-images.githubusercontent.com/38415384/95644403-149b5200-0ad4-11eb-9777-1b845cb399ae.png)

**Diff** :

```diff
- .... Both must in installed.
+ .... Both must be installed.
```

**Comment by bugaevc** [comment]
Please submit a fix to https://github.com/darlinghq/darling-docs 😃

**Comment by joe733** [comment]
@bugaevc I didn't seem to find the release-notes in the docs. [Docs summary](https://github.com/darlinghq/darling-docs/blob/master/src/SUMMARY.md). Please show me if they are hiding somewhere 😄.  My guess, it's filled out when a release is made.

**Comment by bugaevc** [comment]
Oh, I see you've meant [the actual release notes, on GitHub releases page](https://github.com/darlinghq/darling/releases/tag/v0.1.20200331)! Thanks, fixed :slightly_smiling_face:
