### ISSUE TITLE
Darling Build error on Arch

### ISSUE THREAD

**Issue by cgjames907** [darlinghq/darling#883]
**Build Log**
What is the build error?
```
Configuring darling-git...
Running darling-setup=ld-so
/tmp/alpm_fnG7SA/.INSTALL: line 6: /usr/bin/darling-setup-ld-so: No such file or directory
Error: command failed to execute correctly
Running post-transaction hooks...
Arming ConditionNeedsUpdate...                                                                                                                 [1/2]
Install DKMS modules                                                                                                                           [2/2]
==> dkms install --no-depmod -m darling-mach -v r3141.1d3b09970 -k 5.8.11-1-MANJARO
==> depmod 5.8.11-1-MANJARO
Transaction successfully finished.

```

**System Information**
Linux sunshine 5.8.11-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:35:40 UTC 2020 x86_64 GNU/Linux

| Software | Version |
| --- | --- |
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) 

cmake version 3.18.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).| Darling | Git Commit Hash |

then when i launched a darling shell
ootstrapping the container with launchd...
Darling [/Volumes/SystemRoot/home/ibanez/Src]# No protocol specified
                                                                    No protocol specified
                                                                                         No protocol specified
                                                                                                              No protocol specified
                                                                                                                                   No protocol specified
    No protocol specified

**Comment by LubosD** [comment]
We can't support 3rd party package build scripts.

"No protocol specified" is not a problem, you can ignore that.

**Comment by taotieren** [comment]
AUR darling-bin 
```bash
https://aur.archlinux.org/packages/darling-bin/
```

**Comment by ahyattdev** [comment]
We do not support this script
