### ISSUE TITLE
src/CoreServices/LaunchServices.cpp does not compile 

### ISSUE THREAD

**Issue by krisk0** [darlinghq/darling#89]
$subj with clang version 3.5.0

Error message: no such function strdup (and 2 other functions)

Including ```<cstring>``` header solves the issue

```sh
sed "/\"UniChar.h\"/a#include <cstring>;" -i src/CoreServices/LaunchServices.cpp
```

**Comment by LubosD** [comment]
Shouldn't be a problem any more.
