### ISSUE TITLE
`rustup` can't download anything

### ISSUE THREAD

**Issue by facekapow** [darlinghq/darling#902]
**Expected Result**
`rustup` is currently working on master, it should work on `update-sources`, too.

**Actual Result**
```
info: profile set to 'default'
info: default host triple is x86_64-apple-darwin
info: syncing channel updates for 'stable-x86_64-apple-darwin'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/Users/dtest/.rustup/tmp/o3zwap79dacfgjaq_file'
error: caused by: failed to make network request
error: caused by: error sending request for url (https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256): error trying to connect: OSStatus -9810
error: caused by: error trying to connect: OSStatus -9810
error: caused by: OSStatus -9810
```

**Steps To Reproduce**
1. Paste the rustup installer command (`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`) into a Darling shell.
2. Type `1` and then hit enter to continue with the defaults.
3. The installer will fail with the given message.

**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| Linux Kernel | 5.8.0 |
| Darling | 9c8396e268f18db7b266ce49e3fb33f91f59c2d5 |

**Additional Information**
The `-9810` status code is something I saw frequently returned by CommonCrypto when implementing the necessary code for SSL/TLS in CoreCrypto (and when I was trying to set up certificate verification correctly). Something is probably broken there again.

**Comment by bugaevc** [comment]
Confirmed, that's exactly what happens here.

**Comment by facekapow** [comment]
This has been fixed in the latest commit to `update-sources` (c48605014df4327b3b63d1096580640a58ba7e2e)
