### ISSUE TITLE
CMake issues on "update-sources" branch

### ISSUE THREAD

**Issue by IngwiePhoenix** [darlinghq/darling#909]
**Build Log**
What is the build error?
```
CMake Error at src/external/security/OSX/libsecurityd/CMakeLists.txt:30 (file):
  file does not recognize sub-command CREATE_LINK


CMake Error at src/external/security/OSX/libsecurityd/CMakeLists.txt:35 (file):
  file does not recognize sub-command CREATE_LINK


CMake Error at src/external/security/OSX/libsecurityd/CMakeLists.txt:36 (file):
  file does not recognize sub-command CREATE_LINK


CMake Error at src/external/WTF/CMakeLists.txt:40 (file):
  file does not recognize sub-command CREATE_LINK


CMake Error at src/external/WTF/CMakeLists.txt:45 (file):
  file does not recognize sub-command CREATE_LINK


-- Configuring incomplete, errors occurred!
See also "/opt/darling/out/CMakeFiles/CMakeOutput.log".
See also "/opt/darling/out/CMakeFiles/CMakeError.log".
```

**System Information**
| Software | Version |
| --- | --- |
| Clang | 11.0.1 |
| CMake | 3.13.4 |
| Linux Kernel | `4.19.128-microsoft-standard` |
| Darling | `cdf48cddf3f22dbf9775ec68070c826c0ca0eaff` |

After a `git checkout updated-sources` and subsequent `git submodule update --init --recursive`, I went and made a new build output folder and tried to configure. And, this happened. From what I can gather, this might be an API issue in CMake. Maybe the backwards-compatibility setting is to be changed? Don't know though.

**Comment by IngwiePhoenix** [comment]
https://github.com/pthom/imgui_manual/issues/2

Oof. CMake 3.14 is needed for this. IIRC, CMake has a "mimimum requirement" that can be set. Set it to 3.14, maybe? :)

**Comment by bugaevc** [comment]
@facekapow if the issue is that older CMake doesn't support `CREATE_LINK`, we have https://github.com/darlinghq/darling/blob/master/cmake/InstallSymlink.cmake

**Comment by facekapow** [comment]
Right, but that happens at installation time. We're using `CREATE_LINK` to create links in the build directory at configuration time (for some headers). The only workaround for older CMake versions would be to create the link in our source directory (e.g. in `Developer/copy-to-build-dir`) and then copy those into the build directory at configuration time.

**Comment by facekapow** [comment]
I've pushed a fix for this to the `update-sources` branch. @IngwiePhoenix Can you check if it works now?

**Comment by ahyattdev** [comment]
Assuming fixed unless we hear back that it isn't
