### ISSUE TITLE
Include libcupsimage.2.dylib

### ISSUE THREAD

**Issue by rkjnsn** [darlinghq/darling#911]
I'm trying to use Darling to run the Cups filter from a macOS print driver. I haven't gotten my install working with 32-bit binaries yet (a different issue), but while troubleshooting, I noticed that running `otool -L` on the filter lists a dependency on `/usr/lib/libcupsimage.2.dylib`, which doesn't exist in the Darling installation.

**Comment by facekapow** [comment]
This is included now. I don't think cups works, but the dylib is included.

**Comment by rslsp1** [comment]
I'm trying the same for an EPSON driver. And unfortunately /usr/lib/libcups.2.dylib is still missing.   Can you also add these library?
