### ISSUE TITLE
Failing to link against libscu

### ISSUE THREAD

**Issue by Predaking2612** [darlinghq/darling#915]
libscu.a linking error

**Build Log**
What is the build error?
```
[1/17622] Linking ASM static library src/csu/libcsu.a
FAILED: src/csu/libcsu.a
: && /home/predaking2612/dev/tmp/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ar cr src/csu/libcsu.a  src/csu/CMakeFiles/csu.dir/crt1.10.6.o  && /home/predaking2612/dev/tmp/darling/build/src/external/cctools-port/cctools/ar/x86_64-apple-darwin19-ranlib src/csu/libcsu.a && :
ar: src/csu/libcsu.a is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
x86_64-apple-darwin19-ar: src/csu/libcsu.a: Invalid argument
[10/17622] Building C object src/external/BerkeleyDB/CMakeFiles/berkeley_db.dir/db/db/db_iface.c.o
ninja: build stopped: subcommand failed.
```

**System Information**
What system are you building with?
ArchLinux 

| Software | Version |
| --- | --- |
| Clang | 11.0.1 |
| CMake | 3.19.3 |
| Linux Kernel | 5.4.88-1-lts |
| Darling | f00820ece6383fc283eb97c359dca600d3d0cee2 |

**Comment by facekapow** [comment]
Yeah, this is a known issue when building with ninja. The workaround for this is to remove `src/csu/libcsu.a` and then try again.

**Comment by npyl** [comment]
Had this issue today on WSL2 (ubuntu) and I just want to say that some other parts may cause problems like: python7, Ruby etc.
I used the same technique mentioned above for python7 but for Ruby I just disabled the submodule from CMakeLists because It just wouldn't work.

**Comment by bugaevc** [comment]
Before it gets lost, this is a bug in upstream CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/24984

**Comment by hamishmb** [comment]
Is this still an issue? Probably should be re-opened if so, just so we can keep track of what's going on.
