### ISSUE TITLE
PackageInfo not found in the VOCALOID5 pkg

### ISSUE THREAD

**Issue by SeleDreams** [darlinghq/darling#920]
**Expected Result**
VOCALOID5 should properly install

**Actual Result**
Darling [/Applications]$ installer -pkg vocaloid.pkg -target /                    
installer: Package name is VOCALOID5 Editor
installer: Installing at base path /
installer: Installing selected choice VOCALOID5 Editor
ditor.pkg/PackageInfo not found in .pkg

**Steps To Reproduce**
1. Mount the VOCALOID5 dmg image
2. Get the pkg file from it
3. Install it

**System Information**
What system are you using?
Xubuntu 20.04
ryzen 7 3700x
16gb ram
nvidia rtx 2080

**Comment by LubosD** [comment]
Cannot fix this without having access to the pkg or dmg file :-/

**Comment by SeleDreams** [comment]
> Cannot fix this without having access to the pkg or dmg file :-/

yeah... the issue is that it's a proprietary software that costs around 300 without public demos (even though it enters in demo mode when we don't put a serial)

**Comment by LubosD** [comment]
@SeleDreams Could you possibly upload the package somewhere and mail me a link privately so that I can examine it? I certainly don't need the serial...

**Comment by SeleDreams** [comment]
> @SeleDreams Could you possibly upload the package somewhere and mail me a link privately so that I can examine it? I certainly don't need the serial...

I thought about it, what is the mail address you want me to send to ?

**Comment by LubosD** [comment]
> > @SeleDreams Could you possibly upload the package somewhere and mail me a link privately so that I can examine it? I certainly don't need the serial...
> 
> I thought about it, what is the mail address you want me to send to ?

Just use the one in my profile. I don't think the software will work under Darling, but it'll help us improve the `installer`.

**Comment by SeleDreams** [comment]
> > > @SeleDreams Could you possibly upload the package somewhere and mail me a link privately so that I can examine it? I certainly don't need the serial...
> > 
> > 
> > I thought about it, what is the mail address you want me to send to ?
> 
> Just use the one in my profile. I don't think the software will work under Darling, but it'll help us improve the `installer`.

Yeah I imagined, the windows version is in c# and uses net 4.6 and wpf to render, i wonder what it uses on macos that was mostly one of my reasons to want to install it on darling to be able to check its files
(even on wine i can't get the windows v to work atm)

**Comment by HinTak** [comment]
@SeleDreams off topic, but you might have better luck under wine using genuine dotnet instead of wine-mono. You need winetricks to remove wine-mono and put genuine dotnet in.

**Comment by SeleDreams** [comment]
I tried both but both didn't work, I made a post on winehq about it
https://forum.winehq.org/viewtopic.php?f=8&t=34890

**Comment by HinTak** [comment]
"Set property 'System.Windows.Controls.Primitives.ButtonBase.Command' threw an exception." sounds like a GUI / X11 issue. Oh, in the past I have found that some dotnet GUI app prefers native gdiplus (another winetricks item).
