### ISSUE TITLE
[QUESTION] Xamarin

### ISSUE THREAD

**Issue by jhay06** [darlinghq/darling#923]
Hi ,
  does anyone here try to build a xamarin app using darling ? 

Thanks

Regards,
jhay

**Comment by HinTak** [comment]
Why would you do that? When you can run xamarin studio natively on linux?

**Comment by jhay06** [comment]
> Why would you do that? When you can run xamarin studio natively on linux?

hi ,because building ios app requires a mac os , it would be great if darling can do the compilation for ios applications . thanks

**Comment by HinTak** [comment]
I think you'd have better luck using xamarin studio on linux to build ios app than using darling to run mac version of xamarin studio... That'd my impression (not official, just another darling user who is somewhat familiar with xamarin and mono).

**Comment by ahyattdev** [comment]
Hi, sorry we are not ready for something like that yet, unless you can do it from the CLI. I am closing this because general app comptability issues can be created once we get some sort of app DB.

**Comment by trungnt2910** [comment]
For anyone interested in Xamarin apps (or now known as `net6.0-macos`)

![image](https://user-images.githubusercontent.com/57174311/142422739-dcb835d6-3c47-4c9e-aa86-3804b97e8ddf.png)

You can _nearly_ build and debug them on the command line, but packaging them requires full Xcode.
