### ISSUE TITLE
Random error each time I run make

### ISSUE THREAD

**Issue by hatesgh** [darlinghq/darling#927]
Everytime I run `make -j8`, some random error occurs, and it is different every single time.

**CMake command:** `cmake -DTARGET_i386=off ..`

**Build Log:** https://pastebin.com/raw/K907Zbaq

**System Information**
| Software | Version |
| --- | --- |
| Clang | 11.0.1-1 |
| CMake | 3.19.4-1 |
| Linux Kernel | 5.10.15-artix1-1 |
| Darling | 7a3f77e4adf7e6e5856241741c1c65ad933ed40b |

**Comment by facekapow** [comment]
This is the same as #897.
