### ISSUE TITLE
make error 2 (Arch) (Ryzen) (5.10) (5.4) (5.9)

### ISSUE THREAD

**Issue by phoenix277yt** [darlinghq/darling#928]
I think this is an issue because of linux kernel headers as I think I need to re-install them (already installed)
This is where the build went wrong -

`
Scanning dependencies of target system_dyld_obj
[ 10%] Building CXX object src/dyld/CMakeFiles/system_dyld_obj.dir/src/dyldAPIsInLibSystem.o
clang-11: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang-11: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
/home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:34:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
In file included from /home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
/home/phoenix/darling/src/dyld/src/ImageLoader.h:46:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
In file included from /home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
In file included from /home/phoenix/darling/src/dyld/src/ImageLoader.h:53:
In file included from /home/phoenix/darling/src/dyld/dyld3/shared-cache/DyldSharedCache.h:41:
In file included from /home/phoenix/darling/src/dyld/dyld3/MachOAnalyzer.h:28:
In file included from /home/phoenix/darling/src/dyld/dyld3/MachOLoaded.h:29:
/home/phoenix/darling/src/dyld/dyld3/Array.h:33:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
/home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:85:41: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if __IPHONE_OS_VERSION_MIN_REQUIRED || TARGET_OS_DRIVERKIT
                                        ^
/home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1381:5: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_DRIVERKIT
    ^
/home/phoenix/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1488:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
6 errors generated.
make[2]: *** [src/dyld/CMakeFiles/system_dyld_obj.dir/build.make:82: src/dyld/CMakeFiles/system_dyld_obj.dir/src/dyldAPIsInLibSystem.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:16608: src/dyld/CMakeFiles/system_dyld_obj.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
`

**Comment by HinTak** [comment]
Same as https://github.com/darlinghq/darling/issues/856
