### ISSUE TITLE
Cannot build on Arch Linux

### ISSUE THREAD

**Issue by maz-1** [darlinghq/darling#93]
[ 72%] Building CXX object src/CoreFoundation/CMakeFiles/CoreFoundation.dir/AppleCFString.o
/home/ling/PKGS/darling/13_darling-git/src/darling/src/CoreFoundation/AppleCFString.mm:8:64: error: definition
      '__CFConstantStringClassReference' cannot also be an alias
Class* __CFConstantStringClassReference  __attribute__ ((weak, alias ("_OBJC_CLASS_AppleCFString")));
                                                               ^
1 error generated.
src/CoreFoundation/CMakeFiles/CoreFoundation.dir/build.make:86: recipe for target 'src/CoreFoundation/CMakeFiles/CoreFoundation.dir/AppleCFString.o' failed

**Comment by maz-1** [comment]
Change
    Class* __CFConstantStringClassReference __attribute ((weak, alias ("_OBJC_CLASS_AppleCFString")));
to
   extern Class* __CFConstantStringClassReference __attribute ((weak, alias ("_OBJC_CLASS_AppleCFString")));

seems to fix the problem,I'm not sure if it really works though.

**Comment by yan12125** [comment]
+1 @maz-1's patch works for me, too.
