### ISSUE TITLE
CloudKit framework missing when trying to run Fantastical

### ISSUE THREAD

**Issue by pecavalheiro** [darlinghq/darling#932]
Hello there! Thank you for the amazing effort in building this tool. I'm having some issues trying to run the application "Fantastical". I guess due to it being a graphical app, which is still not fully supported. Anyway, below are some details. Thank you in advance!

**Framework**
- CloudKit.framework

I don't have much experience with Apple's ecosystem, but this seems to be a proprietary package. [Here](https://developer.apple.com/documentation/cloudkit) is the documentation for it. Seems to be a package to integrate with iCloud and provide remote storage for the app.
I found some open source alternatives like [OpenCloudKit](https://github.com/BennyKJohnson/OpenCloudKit), but I unfortunately can't say much about compatibility.

**Test Application**
- [Fantastical](https://flexibits.com/fantastical)

**Steps To Reproduce**
- [Download](https://flexibits.com/fantastical/download) the app (.zip file)
- Extract and copy `Fantastical.app` to `/Applications`
- Try to run `/Applications/Fantastical.app/Contents/MacOS/Fantastical`
- Get error:
```
dyld: Library not loaded: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
  Referenced from: /Applications/Fantastical.app/Contents/MacOS/Fantastical
  Reason: image not found
abort_with_payload: reason: Library not loaded: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
  Referenced from: /Applications/Fantastical.app/Contents/MacOS/Fantastical
  Reason: image not found; code: 1
Abort trap: 6
```

**System Information**
Debian Testing (kernel 5.9.15-1)
Lenovo ThinkPad X1 Carbon (7th Gen)

| Software | Version |
| --- | --- |
| Darling | e5ae5fd68 |

**Comment by facekapow** [comment]
If you have access to a macOS installation, you can generate stubs for this framework by following [the instructions here](https://docs.darlinghq.org/contributing/generating-stubs.html).

**Comment by mrolappe** [comment]
Stubs are in master now.

**Comment by rodolforg** [comment]
Should this issue be closed?
