### ISSUE TITLE
Installing darling in wsl2 

### ISSUE THREAD

**Issue by Barshan-Mandal** [darlinghq/darling#941]
please help me to install darling in wsl2

**Comment by LubosD** [comment]
We don't really support WSL. Use a real Linux.

**Comment by Barshan-Mandal** [comment]
where should I submit the issue?

**Comment by LubosD** [comment]
What issue? We as the Darling team don't support WSL.

**Comment by Barshan-Mandal** [comment]
fuck you bitch
