### ISSUE TITLE
Make stops at 96%

### ISSUE THREAD

**Issue by DawPac** [darlinghq/darling#942]
**Build Log**
What is the build error?
```
[ 96%] Building CXX object src/external/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/assembler/MacroAssemblerX86Common.cpp.o
In file included from <built-in>:407:
<command line>:99:9: warning: 'U_SHOW_CPLUSPLUS_API' macro redefined [-Wmacro-redefined]
#define U_SHOW_CPLUSPLUS_API 1
        ^
<command line>:98:9: note: previous definition is here
#define U_SHOW_CPLUSPLUS_API 0
        ^
In file included from /home/dp/darling/src/external/JavaScriptCore/assembler/MacroAssemblerX86Common.cpp:29:
In file included from /home/dp/darling/src/external/JavaScriptCore/assembler/MacroAssembler.h:30:
In file included from /home/dp/darling/src/external/JavaScriptCore/runtime/JSCJSValue.h:36:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/MediaTime.h:32:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/JSONValues.h:36:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/text/StringHash.h:25:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/text/AtomString.h:25:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/text/AtomStringImpl.h:23:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/text/UniquedStringImpl.h:28:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wtf/text/StringImpl.h:26:
In file included from /home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unicode/ustring.h:21:
/home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unicode/utypes.h:83:2: warning: Do not set U_SHOW_CPLUSPLUS_API for code that ships with the OS, it is only for local tools. [-W#warnings]
#warning Do not set U_SHOW_CPLUSPLUS_API for code that ships with the OS, it is only for local tools.
 ^
/home/dp/darling/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unicode/utypes.h:84:2: warning: ICU C++ functionality may not be used by any OS client, it is not binary compatible across updates. [-W#warnings]
#warning ICU C++ functionality may not be used by any OS client, it is not binary compatible across updates.
 ^
3 warnings generated.
In file included from <built-in>:402:
<command line>:99:9: warning: 'U_SHOW_CPLUSPLUS_API' macro redefined [-Wmacro-redefined]
#define U_SHOW_CPLUSPLUS_API 1
        ^
<command line>:98:9: note: previous definition is here
#define U_SHOW_CPLUSPLUS_API 0
        ^
1 warning generated.

```

**System Information**
What system are you building with?

| Software | Version |
| Ubuntu | 20.04 LTS |
| Clang | 10.0.0-4ubuntu1 |
| CMake | 3.16.3 |
| Linux Kernel | 5.4.0-66-generic |

**Comment by DawPac** [comment]
I tried make it 2 time and i had the same issue

**Comment by facekapow** [comment]
Are you sure it stopped? JavaScriptCore takes quite a while to compile on most systems.

**Comment by DawPac** [comment]
This text was printing in loop for about 30 min then i stopped script by Ctrl+C

**Comment by facekapow** [comment]
Nope, not a loop, just a lot of warnings. Leave it running and it'll eventually finish.

**Comment by DawPac** [comment]
ok i try

**Comment by HinTak** [comment]
JavaScriptCore prints the same two or three warnings over and over, for me, over a period of about 4 hours(!), because the same header is included by almost every file. What you are seeing is normal...

**Comment by coracobra** [comment]
i have same problem :(

{96} :(
<command line>:99:9: warning: 'U_SHOW_CPLUSPLUS_API' macro redefined [-Wmacro-redefined]
#define U_SHOW_CPLUSPLUS_API 1

**Comment by LubosD** [comment]
There's no error described here, just a repeated benign warning.

I'm closing the issue, get a faster PC and Darling will build in under 30 minutes.

**Comment by hchen98** [comment]
It does not matter how good your computer is, it is always slow. Here I sent around 4 hours just to complete the build and my computer specs are as follows:
![Screenshot from 2021-08-11 13-59-08](https://user-images.githubusercontent.com/12217705/129082568-9f171d2b-f110-4d5c-92e1-92e1f2f3e7ef.png)

**Comment by HinTak** [comment]
Consider you lucky... On my system a full build takes 12 hours; disabling ccache cut it down to 9; enabling parallel build (make -j4) down to about 7 hours. And, as I mentioned earlier, 60% of the whole duration (7/9/12 hours) is spent on building JavacriptCore, despite it saying 96% by the time it is reached. The percentage is just misleading. But yes, darling takes many hours to build.

**Comment by deep-wen** [comment]
![2021-11-27 11-27-53 的屏幕截图](https://user-images.githubusercontent.com/43669697/143666762-b6a24820-612f-4673-b75b-4b4ca147ad7d.png)
有人说是硬盘空间不够了

**Comment by cooleybyte** [comment]
> There's no error described here, just a repeated benign warning.
> 
> I'm closing the issue, get a faster PC and Darling will build in under 30 minutes.

wow you're a dick
