### ISSUE TITLE
modprobe: FATAL: Module darling-mach not found

### ISSUE THREAD

**Issue by notbluu** [darlinghq/darling#949]
**Expected Result**
A shell

**Actual Result**
modprobe: FATAL: Module darling-mach not found in directory /lib/modules/5.11.7-arch1-1
Failed to load the kernel module

**Steps To Reproduce**
1. If possible, what steps can you take to reproduce the issue?

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
Put the command output here!
Nothing showed up.

**System Information**

| Software | Version |
| Arch| 5.11.7|
| Linux Kernel | 5.11.7 |

I built both the shell & the LKM module and have also installed them. No errors occurred during the build process yet this happens.

**Comment by facekapow** [comment]
What does `uname -r` say?

**Comment by 0x14307** [comment]
> What does `uname -r` say?

5.11.7-arch1-1

**Comment by JCWasmx86** [comment]
Did you upgrade the kernel after installing darling? This was an issue for me. Try to reinstall the kernel module

**Comment by facekapow** [comment]
Just to be sure, you ran the `lkm_install` target, correct? Does the module show up in `/lib/modules/5.11.7-arch1-1/extra`?

**Comment by 0x14307** [comment]
lkm_install shows this:

cat: /home/pope/darling/src/external/lkm/modules.order: No such file or directory
  DEPMOD  5.11.7-arch1-1

**Comment by facekapow** [comment]
Did you already run the `lkm` target?

**Comment by 0x14307** [comment]
I already ran "make lkm", so yes

**Comment by 0x14307** [comment]
@facekapow now seeing the lkm error, it says darling/src/external/lkm/modules.order: No such file or directory. Is this an issue?

**Comment by Manasx100** [comment]
i have the same issue

**Comment by facekapow** [comment]
I believe what was happening here is that the LKM module was actually failing to compile, probably from the kernel module not supporting 5.11 at the time. It should be supported now on the latest master. Try updating [according to the docs](https://docs.darlinghq.org/build-instructions.html#updating-sources) and rebuilding.

**Comment by notbluu** [comment]
I haven't checked yet, but I will try to when I get the chance.

**Comment by notbluu** [comment]
@facekapow Alright, I tried to rebuild it (this time on 5.12)

make[4]: Entering directory '/home/bluu/Desktop/darling/src/external/lkm'
Running kernel version is 5.12.10-arch1-1
rm -f darling-mach.mod.o
make -C /lib/modules/5.12.10-arch1-1/build M=/home/bluu/Desktop/darling/src/external/lkm modules
make[5]: Entering directory '/home/bluu/Desktop/darling/src/external/lkm'
make[5]: *** /lib/modules/5.12.10-arch1-1/build: No such file or directory.  Stop.
make[5]: Leaving directory '/home/bluu/Desktop/darling/src/external/lkm'
make[4]: *** [Makefile:615: default] Error 2
make[4]: Leaving directory '/home/bluu/Desktop/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:71: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:53812: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:53819: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:18577: lkm] Error 2

**Comment by notbluu** [comment]
Okay, nevermind. At least this time around I was a dumbass and forgot to install my headers. Build works 100% now.
