### ISSUE TITLE
Fix Ubuntu (15.10) build instructions

### ISSUE THREAD

**Issue by iHateInventNames** [darlinghq/darling#95]
no liblcms-dev

**Comment by iHateInventNames** [comment]
also gnustep-make is in repository

**Comment by iHateInventNames** [comment]
maybe possible to use sudo apt-get install gnustep-devel

**Comment by faissaloo** [comment]
I second this, getting it work on ubuntu is a pain.

**Comment by LubosD** [comment]
All the development is happening in the darling-libsystem branch (master is no longer updated), where the build instructions are going to be very different. Hence it doesn't make sense updating the guide. This is therefore a won't fix. Thank you for your understanding.

darling-libsystem will be merged into master once it is considered good enough (it doesn't yet support 32-bit apps).
