### ISSUE TITLE
darling depends on libc6 (>= 2.32)

### ISSUE THREAD

**Issue by arnoldcui** [darlinghq/darling#951]
While install deb package on ubuntu20.04,it give an error
![Screenshot from 2021-03-26 18-04-45](https://user-images.githubusercontent.com/40977489/112615710-cb5e7500-8e5d-11eb-9e5b-c593046d0c40.png)

Seems ubuntu20.04 didn't has libc6 >= v2.32

**Library**
libc6 

**Test Application**
darling_0.1.20210224.testing_amd64.deb

**Steps To Reproduce**
sudo dpkg -i darling_0.1.20210224.testing_amd64.deb

**System Information**
ubuntu20.04

| Software | Version |
| --- | --- |
| Darling | Git Commit Hash |

**Comment by LubosD** [comment]
It says in the description:

> **Ubuntu 20.10** packages provided. May work on 20.04 but is not tested.

So it's not supported on Ubuntu 20.04.
