### ISSUE TITLE
Failed to install on Ubuntu 21.04

### ISSUE THREAD

**Issue by Manasx100** [darlinghq/darling#953]
installing from.deb failed i tried to install dkms first but it failed tried other package failed to.
![Ekrano nuotrauka iš 2021-03-28 13-01-08](https://user-images.githubusercontent.com/80171692/112748638-b56bc400-8fc5-11eb-980d-1fd68e5a3e31.png)
![Ekrano nuotrauka iš 2021-03-28 13-00-43](https://user-images.githubusercontent.com/80171692/112748639-b6045a80-8fc5-11eb-945a-ea95f234ae84.png)
![Ekrano nuotrauka iš 2021-03-28 13-00-32](https://user-images.githubusercontent.com/80171692/112748640-b69cf100-8fc5-11eb-8a71-9ef58cef3b5c.png)

Sorry for Lithuanian language in the photos

**Comment by JCWasmx86** [comment]
A daemon called `aptd` is running in the background. Wait until it ends, or kill it yourself. Then try again to install darling

**Comment by Manasx100** [comment]
JCWasmx86 i will try this

**Comment by ahyattdev** [comment]
Like others have said, APT is running in the background.

**Comment by Manasx100** [comment]
all apps broked daily build

**Comment by JCWasmx86** [comment]
>seems like darling-dkms is doing something failed tp install other app

Could you please try to install it from the commandline and paste the output?
