### ISSUE TITLE
prefix attribute must be followed by an interface or protocol (solved)

### ISSUE THREAD

**Issue by agavrel** [darlinghq/darling#955]
I had this error while building darling

The fix was to remove from .mm files:
```
__attribute__((objc_nonlazy_class))
```

with, from within `darling/src/external/objc4/runtime`:
```
sed -i.bak '/__attribute__((objc_nonlazy_class))/d' *.mm
```

**Comment by facekapow** [comment]
See #964; you're probably using an old version of Clang
