### ISSUE TITLE
Ubuntu 21.04 building issue .deb install failed

### ISSUE THREAD

**Issue by Manasx100** [darlinghq/darling#957]
Darling mach not builds normally also .deb instal failed LOG bellow
[LOG.zip](https://github.com/darlinghq/darling/files/6398316/LOG.zip)

**Comment by JCWasmx86** [comment]
The same error was here: https://github.com/darlinghq/darling/issues/933

**Comment by Manasx100** [comment]
Probably it is a issue with the kernel.

**Comment by facekapow** [comment]
Closing as a duplicate of #933
