### ISSUE TITLE
darling-swift cannot be cloned due to account data limit

### ISSUE THREAD

**Issue by crazyquark** [darlinghq/darling#959]
**Build Log**
What is the build error?
```
Cloning into 'darling-swift'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 61 (delta 3), reused 61 (delta 3), pack-reused 0
Receiving objects: 100% (61/61), 9.99 KiB | 2.00 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Downloading libswiftAVFoundation.dylib (130 KB)
Error downloading object: libswiftAVFoundation.dylib (06aa9a4): Smudge error: Error downloading libswiftAVFoundation.dylib (06aa9a4164514f7f0339c086089861320b980bc3c1a727d7395fcf8447fb5fe7): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /home/[redacted]/Desktop/Workspace/darling-swift/.git/lfs/logs/20210505T120017.191802115.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: libswiftAVFoundation.dylib: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

**System Information**
What system are you building with?
Manjaro kernel 5.12

**Comment by ahmubashshir** [comment]
It happened to me too.
```
EndeavourOS
Linux 5.4.115-152-tkg-bmq x86_64
```

**Comment by LubosD** [comment]
Yes, that's how it is, unfortunately. Limits for free OSS projects are very low.

**Comment by LubosD** [comment]
But I'll see if I can configure LFS to host these files outside of GitHub.

**Comment by facekapow** [comment]
This should actually already be fixed on latest master. After cloning the latest master, however, you'll need to run a post-checkout script: `./tools/post-checkout.sh`. I updated the build instructions but they're not updating on the website for some reason.

**Comment by LubosD** [comment]
> This should actually already be fixed on latest master. After cloning the latest master, however, you'll need to run a post-checkout script: `./tools/post-checkout.sh`. I updated the build instructions but they're not updating on the website for some reason.

This should be fixed, wrong permissions on the server.
I'm struggling a little to find a simple git-lfs implementation that allows for anonymous downloads :-/
