### ISSUE TITLE
deb packages and apt launchpad

### ISSUE THREAD

**Issue by iHateInventNames** [darlinghq/darling#96]

**Comment by LubosD** [comment]
Not planned.

**Comment by iHateInventNames** [comment]
But it would make life easier. Why not put this at bountysource.com?

**Comment by LubosD** [comment]
For Ubuntu users, maybe. I don't use Ubuntu and there are many other distributions. Anyone is free to provide this stuff on his own.

**Comment by iHateInventNames** [comment]
There is already. It would be really nice to make it official. Is it
possible?
15 нояб. 2015 г. 15:24 пользователь "Luboš Doležel" <
notifications@github.com> написал:
