### ISSUE TITLE
Using `-O2` for the LKM causes incorrect behavior

### ISSUE THREAD

**Issue by facekapow** [darlinghq/darling#967]
**Expected Result**
The kernel module should produce the same behavior regardless of optimization flags used.

**Actual Result**
Compiling with `-O1`, all applications and APIs behave as expected, but with `-O2`, syslogd crashes repeatedly because the kernel reports that the notification port is invalid (which is certainly not the case in the userspace side of things), and libdispatch knows this is wrong.

**Steps To Reproduce**
1. Compile the kernel module normally.
2. Upon entering a `darling shell`, run `launchctl list` and see that `syslogd` has exited with status `-4` (for SIGILL, meaning libdispatch aborted).

To reproduce the expected behavior, repeat the steps above but compile the LKM with `-O1`--if using DKMS, you can do this by adding `EXTRA_CFLAGS='-O1'` to the `MAKE[0]` option--and note that `syslogd` will not crash at all.

**``dmesg`` Output**
```
# nothing useful
# (no difference between -O1 and -O2 logs)
```

**System Information**
What system are you using?

| Software | Version |
| --- | --- |
| Linux Kernel | 5.8.0-53-generic |
| Darling | 35534fcaa312b184145c95a543cf86c8b08d4e70 |

**Comment by TheBrokenRail** [comment]
This also causes ``python`` to hang.

**Comment by facekapow** [comment]
The real issue was that we weren't properly setting the notification port for the mach_msg_overwrite trap arguments. For some reason, this issue only manifested itself when compiling with `-O2`. That's just incredibly weird and should never have worked even with `-O1` 🤷‍♂️.
