### ISSUE TITLE
Darling's Build Of Python Hangs

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#969]
**Expected Result**
I run ``python`` and it opens up the REPL prompt.

**Actual Result**
It hangs no matter what arguments I give it.

``xtrace``:
```
Darling [~]$ xtrace /usr/bin/python
xtrace: failed to dlsym(/usr/lib/darling/xtrace-mig/libnotify_xtrace_mig.dylib, "xtrace_mig_subsystem"): dlsym(0x7ffff8131dd8, xtrace_mig_subsystem): symbol not found
[183] getuid() -> 1000
[183] mach_msg_trap(0x7FFFFFDFAAA8, MACH_SEND_MSG|MACH_RCV_MSG, 188, 108, port 1543, 0, port 0)
[183]         {remote = copy send 1799, local = make send-once 1543, id = 404}, 164 bytes of inline data
[183]         job::look_up2(copy send 1799, "com.apple.system.notification_center", u, [u, u, u, u, u, u, u, u, u, u, u, u, u, u, u, u], u)
^C
[183]     thread_self_trap() -> port right 775
```

**Steps To Reproduce**
Run ``python``

**System Information**
Ubuntu 20.04

| Software | Version |
| --- | --- |
| Linux Kernel | ``5.8.0-50-generic`` |
| Darling | ``35534fcaa312b184145c95a543cf86c8b08d4e70`` |

**Comment by facekapow** [comment]
Yep, I'm pretty sure this is a side-effect of #967; when syslogd crashes, any app that tries to log to it fails to do so and hangs, waiting for another syslogd instance to be spawned (but unfortunately, they always crash, so apps wait forever).

**Comment by TheBrokenRail** [comment]
Should I close this and just add a comment to #967?

**Comment by facekapow** [comment]
Yeah, that would be better since it's the root cause (this is just a side-effect).

**Comment by TheBrokenRail** [comment]
OK.
