### ISSUE TITLE
Building on Debian 10

### ISSUE THREAD

**Issue by JJTech0130** [darlinghq/darling#979]
**Build Log**
What is the build error?
Same as https://github.com/darlinghq/darling/issues/964, https://github.com/darlinghq/darling/issues/939 and possibly others:
```
/home/jjtech/darling/src/external/objc4/runtime/NSObject.mm:2000:2: error: prefix attribute must be followed by an
      interface or protocol
@implementation NSObject
 ^
```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 6.0.1-10 |
| CMake | 3.13.4 |
| Linux Kernel | 5.10.16.3-microsoft-standard-WSL2+ |
| Darling | 4fd969bf1e6bc8fcd1830229394f35676246e827 |

Your build instructions for Debian 10 include `clang-6.0` as a build dependency, while previously stating that Darling will not build without Clang 9 or higher. `clang-11` appears to be available on Debian 10 (at least the WSL version) so it appears to be a documentation issue.

**Comment by HinTak** [comment]
clang too old. I think the doc mentions that clang 10+(?) is required...

**Comment by JJTech0130** [comment]
I know. But the *build instructions* specifically install clang-6.0

**Comment by HinTak** [comment]
You can check when that line was written at https://github.com/darlinghq/darling-docs - likely very old... And you can create pull / edit / update to the docs there yourself too, btw. If you are simply complaining about the doc being out of date, filing and fixing it over there may be more appropriate... (yes, you can just click the edit button on the top right to create a pull there..)

**Comment by HinTak** [comment]
Disclaimer: I am just another user (and not a happy one at that...).

**Comment by JJTech0130** [comment]
Yah, is there any reason Clang 11 wouldn't work? I'm building now but it's going to take awhile

**Comment by JJTech0130** [comment]
https://github.com/darlinghq/darling-docs/pull/25

**Comment by HinTak** [comment]
There were some problems with Clang 12, but has since been fixed: https://github.com/darlinghq/darling/issues/856

**Comment by JJTech0130** [comment]
https://github.com/darlinghq/darling/pull/980

**Comment by JJTech0130** [comment]
I'm going to close this issue, I've added all of the pull req. necessary to fix it.
