### ISSUE TITLE
curl fails with "Segmentation fault: 11"

### ISSUE THREAD

**Issue by JCWasmx86** [darlinghq/darling#992]
**Expected Result**
curl runs

**Actual Result**
`Segmentation fault: 11`

**Steps To Reproduce**
Just run curl, output:
```
Darling [~]$ curl
Segmentation fault: 11
```

**System Information**

| Software | Version |
| --- | --- |
| Linux Kernel | 5.10.0-8-amd64 |
| Darling | e03a33d7f |
| OS | Debian Sid |
| clang | 11.0.1-2 |

**Other information**

Attempts to debug with lldb yield this results:
```
user@host:~/Downloads/lldb$ darling shell
Setting up a new Darling prefix at /home/user/.darling
Bootstrapping the container with launchd...

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Darling [/Volumes/SystemRoot/home/user/Downloads/lldb]$ ./lldb curl
(lldb) target create "curl"
Current executable set to 'curl' (x86_64).
(lldb) run
error: process exited with status -1 (debugserver died with an exit status of 0x00000000)
(lldb) 
```

I'm not sure, but it seems like it crashes before curl is really loaded

**Comment by facekapow** [comment]
Hmm, not sure what's going on here. I tried this myself on Arch Linux (kernel version 5.13.4) and got:

```
darling-arch% darling shell 
Bootstrapping the container with launchd...

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Darling [/Volumes/SystemRoot/home/dtest/Downloads]$ curl
curl: try 'curl --help' or 'curl --manual' for more information
Darling [/Volumes/SystemRoot/home/dtest/Downloads]$ cd
Darling [~]$ curl
curl: try 'curl --help' or 'curl --manual' for more information
Darling [~]$
```

Could you try again with the latest commit?

**Comment by JCWasmx86** [comment]
I tested it again:
  e03a33d7f fails
  48c199cfb works

**Comment by facekapow** [comment]
Alright then, I'll close this since it's gone with the latest commit to master.

**Comment by JCWasmx86** [comment]
Sorry, but I have to reopen this.

I have built two darlings. One (Release build with `tools/debian/make-deb`) installed in system, one as debug build (Built with `cmake -DCMAKE_BUILD_TYPE=Debug`).

Both are at 9393db2c6

If I run:
```
rm -r ~/.darling
darling shell # Built with tools/debian/make-deb (Uploaded to https://github.com/JCWasmx86/unofficial_darling)
[darling]$ curl
=>Segmentation fault: 11
```
, it crashes.

If I run:
```
rm -r ~/.darling
./darling shell # Debug build
[darling]$ curl
=>curl: try 'curl --help' or 'curl --manual' for more information
```
, it works.


I don't know, what other information I can provide.

**Comment by JCWasmx86** [comment]
I've now built it on Fedora 34: It just works! No idea why, probably my environment is messed up or some undefined behavior/weird cornercase/...
