### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by alicera** [darlinghq/darling#996]
**Build Log**
make -j4

```
Put the build log here!
```
ld: warning: direct access in function '__ZN3WTF13LockAlgorithmIhLh64ELh128ENS_14EmptyLockHooksIhEEE8lockSlowERNS_6AtomicIhEE' from file 'CMakeFiles/JavaScriptCore.dir/runtime/JSCell.cpp.o' to global weak symbol '__ZN3WTF22ScopedLambdaRefFunctorIFbvEZNS_10ParkingLot14compareAndParkIhhEENS2_10ParkResultEPKNS_6AtomicIT_EET0_EUlvE_E12implFunctionEPv' from file '../WTF/libWTF.a(Lock.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

**Comment by LubosD** [comment]
What? This is not a build error.

**Comment by alicera** [comment]
How can I do ？
I run again.


[ 90%] Building CXX object src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/AUGraph.cpp.o
In file included from /work/Videos/work/darling/src/CoreAudio/AudioToolbox/AudioConverter.cpp:21:
/work/Videos/work/darling/src/CoreAudio/AudioToolbox/AudioConverterImpl.h:9:10: fatal error: 'libavresample/avresample.h' file not found
In file included from /work/Videos/work/darling/src/CoreAudio/AudioToolbox/AudioConverterImpl.cpp:20:
/work/Videos/work/darling/src/CoreAudio/AudioToolbox/AudioConverterImpl.h:9:10: fatal error: #include <libavresample/avresample.h>
'libavresample/avresample.h' file not found         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <libavresample/avresample.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/build.make:76: src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/AudioConverter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/build.make:89: src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/AudioConverterImpl.cpp.o] Error 1
[ 90%] Built target ruby_stringio
[ 90%] Built target ruby_ripper
[ 90%] Built target pyobjc_CoreGraphics_extra_module_py27
[ 90%] Built target ruby_readline
Scanning dependencies of target ruby_sizeof
Scanning dependencies of target ruby_cparse
make[1]: *** [CMakeFiles/Makefile2:25596: src/CoreAudio/AudioToolbox/CMakeFiles/AudioToolbox.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...

**Comment by facekapow** [comment]
This means you don't have libavresample installed. You need to install it, per our build instructions.
