### ISSUE TITLE
location

### ISSUE THREAD

**Issue by alicera** [darlinghq/darling#999]
**Framework**
I put the .zip in /Application. Where is the response as location in host

**Comment by facekapow** [comment]
By default, the Darling prefix is in `$HOME/.darling`. So in your case, the file would be in `$HOME/.darling/Applications/<name-of-your-zipfile>.zip`.

**Comment by bugaevc** [comment]
Meta note: @alicera, I see you have created a bunch of issue reports just to ask us a few questions. [We have Discord for that now!](https://discord.gg/XRD3mQA) So please use Discord for support & questions (like asking what to do about `'libavresample/avresample.h' file not found`, or where do the files go), and leave the GitHub issues for actual issue reports for when there's an actual bug in Darling.
